#!/usr/bin/env node
/**
 * Session 25: 50 VWL/zuordnung-Fragen.
 * Zuordnung hat keine Sub-IDs → 0 Teilerklärungen, nur überarbeitete Musterlösungen.
 * Qualitätsregeln: 2–4 Sätze, ~60–80 Wörter, neutrale 3. Person, Schweizer Hochdeutsch, Plain-Text.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'fragen-updates.jsonl')
const STATE = path.join(__dirname, 'state.json')

const updates = [
  { id: '609b458b-cdcb-4198-ad63-28a3be9e48ae', fachbereich: 'VWL', musterlosung: `Der Gütermarkt-Ansatz bekämpft Arbeitslosigkeit indirekt: Höhere Nachfrage nach Gütern soll zusätzliche Beschäftigung auslösen. Dazu zählen Stärkung der Wettbewerbskraft, erhöhte Standortattraktivität und staatliche Beschäftigungsprogramme. Der Arbeitsmarkt-Ansatz greift dagegen direkt ein, etwa mit Kurzarbeit, Bildungs- und Weiterbildungspolitik oder Flexibilisierung des Arbeitsmarktes. Die Schweiz kombiniert beide Strategien; schwergewichtig setzt sie auf Rahmenbedingungen statt auf staatliche Jobschaffung.`, teilerklaerungen: [] },
  { id: '61e20aee-2c00-48cb-8939-800f6e446ec2', fachbereich: 'VWL', musterlosung: `Die Nachfrage wird durch Einkommen, Präferenzen sowie Preise verwandter Güter (Substitute, Komplemente) bestimmt; sie betrifft die Kaufentscheidung der Konsumenten. Das Angebot hängt von den Produktionsbedingungen ab, also von Produktionskosten, technologischem Fortschritt und Inputpreisen wie Rohstoffen oder Löhnen. Änderungen dieser Faktoren verschieben die jeweilige Kurve. Der Preis des betrachteten Guts bewirkt dagegen nur eine Bewegung entlang der Kurve, keine Verschiebung.`, teilerklaerungen: [] },
  { id: '6218b181-6748-4975-9207-8d6ae193e94a', fachbereich: 'VWL', musterlosung: `Bei der Finanzierung am Kapitalmarkt gibt der Staat Obligationen aus. Das treibt die Zinsen nach oben und kann private Investitionen verdrängen (Crowding-out); die Geldmenge bleibt unverändert. Bei der Monetisierung durch die Nationalbank wird faktisch neues Geld geschaffen: Die Geldmenge wächst, Zinsen sinken kurzfristig, langfristig steigt das Inflationsrisiko. In der Schweiz ist dies durch die Unabhängigkeit der SNB stark begrenzt.`, teilerklaerungen: [] },
  { id: '6269e455-1a1c-4f65-ad4c-4097ffee2dce', fachbereich: 'VWL', musterlosung: `Die Nachfragekurve verschiebt sich nach rechts, wenn das Einkommen bei einem normalen Gut steigt, Präferenzen zunehmen, die Bevölkerung wächst oder der Preis eines Substituts steigt. Sie verschiebt sich nach links bei gegenteiligen Entwicklungen: günstigere Substitute, teurere Komplemente oder negative Informationen über das Gut. Zu unterscheiden ist immer zwischen einer Kurvenverschiebung (durch externe Faktoren) und einer Bewegung entlang der Kurve (durch den eigenen Preis).`, teilerklaerungen: [] },
  { id: '6501d6e6-02f1-4e61-a329-7a5cc0d919d9', fachbereich: 'VWL', musterlosung: `Marktformen unterscheiden sich nach der Anzahl Anbieter. Ein Monopol hat genau einen Anbieter, zum Beispiel einen lokalen Wasserversorger. Ein Oligopol umfasst wenige grosse Anbieter wie die Schweizer Mobilfunkbranche. Monopolistische Konkurrenz und vollkommene Konkurrenz zählen beide viele Anbieter; erstere differenziert über Produktmerkmale (Restaurants), letztere bietet homogene Güter an (Weizenmarkt). Mit steigender Anbieterzahl sinkt die Marktmacht der einzelnen Unternehmen.`, teilerklaerungen: [] },
  { id: '67f1c924-a619-4edb-a38b-594765f861da', fachbereich: 'VWL', musterlosung: `Auf dem Arbeitsmarkt bieten Arbeitnehmende ihre Arbeitskraft an; dazu gehören alle Erwerbspersonen und Stellensuchenden. Die Arbeitsnachfrage geht von Unternehmen und öffentlichen Arbeitgebern aus, die Personal rekrutieren. Der Arbeitsmarkt gilt als «umgekehrter Markt»: Haushalte sind hier die Anbietenden, nicht wie sonst üblich die Konsumierenden. Der Lohn ist der Preis, der Angebot und Nachfrage an Arbeit ausgleicht.`, teilerklaerungen: [] },
  { id: '6b2b4e3c-d70c-4322-868f-99e29de6ee8f', fachbereich: 'VWL', musterlosung: `Adverse Selektion betrifft die Zusammensetzung des Versichertenkollektivs vor Vertragsabschluss: Hohe Risiken schliessen sich besonders häufig ab, niedrige Risiken verzichten oder kündigen. Moral Hazard betrifft das Verhalten nach Vertragsabschluss: Versicherte werden unvorsichtiger, weil sie die Kosten nicht mehr selber tragen. Die Unterscheidung ist zentral, denn beide Probleme verlangen unterschiedliche Gegenmassnahmen; sie gehören zu den Kernkonzepten der Versicherungsökonomie.`, teilerklaerungen: [] },
  { id: '6c3e9edf-9b37-43ce-b5e7-20fdabbfbd53', fachbereich: 'VWL', musterlosung: `Direkte Steuern berücksichtigen persönliche Merkmale wie Einkommen oder Vermögen und werden direkt beim Pflichtigen erhoben. Indirekte Steuern belasten Transaktionen, etwa die Mehrwertsteuer oder Zölle auf Importe, und werden über den Preis weitergegeben. Gebühren sind dagegen Entgelte für konkrete Staatsleistungen wie Pass oder Kehrichtentsorgung. Sie folgen dem Äquivalenzprinzip, während Steuern voraussetzungslos erhoben werden.`, teilerklaerungen: [] },
  { id: '6d7fc2e2-cbcc-4cb4-bcaf-7f4bb9521eee', fachbereich: 'VWL', musterlosung: `Die Volkswirtschaftslehre unterscheidet traditionell vier Produktionsfaktoren. Arbeit umfasst körperliche und geistige Tätigkeit, zum Beispiel den Lohn einer Verkäuferin. Boden steht für Standort sowie natürliche Ressourcen wie Rohstoffe. Kapital bezeichnet Sach- und Geldkapital, also Maschinen, Anlagen und Finanzmittel für Investitionen. Wissen umfasst Humankapital, Patente und Know-how und gilt heute als zentraler Wachstumsfaktor; jede Produktion kombiniert alle vier.`, teilerklaerungen: [] },
  { id: '73b39070-70a9-4497-9531-18b1e5db1620', fachbereich: 'VWL', musterlosung: `Die Bedürfnispyramide ordnet Motive hierarchisch. Körperliche Grundbedürfnisse dominieren bei Hunger oder Obdachlosigkeit und gehen Schutz und Wärme voraus. Sicherheitsbedürfnisse prägen den Wunsch nach Lebensversicherung oder unbefristetem Vertrag. Soziale Bedürfnisse zeigen sich im Anpassen des Kleidungsstils, um dazuzugehören. Selbstverwirklichung steht an der Spitze und treibt Start-up-Gründungen oder das Teilen von Erfolgen; die Einordnung verlangt, die dominierende Motivation der Situation zu erkennen.`, teilerklaerungen: [] },
  { id: '75a4e56b-9689-40f3-8072-743b9e62eb29', fachbereich: 'VWL', musterlosung: `Die Elefantengrafik zeigt das globale Einkommenswachstum zwischen 1988 und 2008. Der Rücken steigt stark an: Die aufstrebende Mittelschicht in China und Indien legte massiv zu. Der Knick am Rüssel markiert die stagnierende westliche untere Mittelschicht. Die Rüsselspitze schiesst nach oben: Die reichsten ein Prozent der Weltbevölkerung verzeichneten enorme Zuwächse. Die Grafik visualisiert damit Gewinner und Verlierer der Globalisierung.`, teilerklaerungen: [] },
  { id: '81c328a1-a9dd-4327-8504-41743b4fc54f', fachbereich: 'VWL', musterlosung: `Befürwortende Argumente für ein bedingungsloses Grundeinkommen betonen Entbürokratisierung, Freiheit für Pflege, Ehrenamt oder Weiterbildung sowie Entstigmatisierung der Empfangenden. Gegnerinnen und Gegner warnen vor massiven Kosten, sinkender Erwerbsmotivation und fehlender Finanzierbarkeit. Die Schweizer Volksinitiative wurde 2016 mit rund 77 Prozent Nein-Stimmen deutlich abgelehnt. Durch die Debatte um Automatisierung gewinnt das Thema international wieder an Bedeutung.`, teilerklaerungen: [] },
  { id: '883d69e2-eb7f-4d66-a10c-a53a265152a7', fachbereich: 'VWL', musterlosung: `Gegen Moral Hazard wirken Instrumente, welche die Eigenverantwortung stärken: Selbstbehalt und Bonus-Malus-System verringern Anreize zu riskantem Verhalten. Gegen Adverse Selektion helfen Massnahmen, die das Risikokollektiv stabil halten. Risikoklassifizierung mit gestaffelten Prämien macht die Kalkulation tragfähig; ein Obligatorium wie in der Krankenversicherung zwingt auch gute Risiken zur Teilnahme und verhindert so die Negativauslese guter Versicherter.`, teilerklaerungen: [] },
  { id: '88b2e9b5-6e92-4e75-af27-1e7cfe8506ee', fachbereich: 'VWL', musterlosung: `Die Leistungsgerechtigkeit verteilt nach Produktivität: Wer mehr leistet, soll mehr verdienen; Marktlöhne gelten als gerechte Entlohnung. Die Bedarfsgerechtigkeit sichert jedem Menschen unabhängig von der Leistungsfähigkeit ein angemessenes Einkommen; staatliche Grundsicherung ist das typische Instrument. Beide Prinzipien verkörpern den Zielkonflikt zwischen Effizienz und Verteilungsgerechtigkeit. Moderne Sozialsysteme kombinieren sie, setzen aber unterschiedliche Gewichtungen und lösen so diese Spannung unterschiedlich auf.`, teilerklaerungen: [] },
  { id: '8911fa76-9e1c-4369-a1a4-2d523bbeecf1', fachbereich: 'VWL', musterlosung: `Moral Hazard tritt nach Vertragsabschluss auf: Vollkaskoversicherte fahren unvorsichtiger, systemrelevante Banken gehen höhere Risiken ein, weil sie auf Rettung zählen, und festangestellte Personen strengen sich manchmal weniger an. Adverse Selektion tritt vor Vertragsabschluss auf: Kranke schliessen Krankenversicherungen häufiger ab, und auf Gebrauchtwagenmärkten werden vor allem minderwertige Autos angeboten. Das zeitliche Kriterium hilft bei der Einordnung: MH verändert das Verhalten, AS die Zusammensetzung.`, teilerklaerungen: [] },
  { id: '8bbbba8f-161c-4861-bc8a-23c8236f74ba', fachbereich: 'VWL', musterlosung: `Green Growth geht davon aus, dass technologischer Fortschritt und Internalisierung externer Effekte Wachstum und Umweltschutz vereinen. Beyond Growth (OECD) will das BIP durch Wohlfahrts- und Nachhaltigkeitsindikatoren ergänzen und fordert eine aktive Industriepolitik. Degrowth betrachtet Wachstum selbst als Problem und verlangt die bewusste Schrumpfung der Wirtschaft, Suffizienz statt Effizienz. Die drei Positionen unterscheiden sich grundlegend in der Einschätzung der Rolle des Staates.`, teilerklaerungen: [] },
  { id: '8cfe5acd-729b-434e-aece-6393bcd515d1', fachbereich: 'VWL', musterlosung: `Der Fiskalzweck finanziert die Staatsaufgaben; Einkommens- und Mehrwertsteuer liefern den grössten Teil der Einnahmen. Der Umverteilungszweck gleicht Einkommens- und Vermögensunterschiede aus; die Erbschaftssteuer ist ein typisches Beispiel. Der Lenkungszweck verteuert gezielt unerwünschtes Verhalten, etwa durch die Alkoholsteuer oder die CO₂-Abgabe. Die meisten Steuern erfüllen mehrere Zwecke gleichzeitig, sind aber einem Hauptzweck zugeordnet, der ihre Einführung begründete.`, teilerklaerungen: [] },
  { id: '8ee2d822-26c9-41ad-b895-55bc1f46ec08', fachbereich: 'VWL', musterlosung: `Das Umlageverfahren funktioniert als Generationenvertrag: Die Beiträge der Erwerbstätigen finanzieren direkt die laufenden Renten. Die AHV ist das Hauptbeispiel; sie hängt stark von der demografischen Entwicklung ab. Das Kapitaldeckungsverfahren beruht auf individuellem Ansparen mit Zinserträgen und finanziert die berufliche Vorsorge (Pensionskasse). Es reagiert empfindlich auf die Entwicklung der Finanzmärkte; anhaltend tiefe Zinsen schmälern die Rendite über Jahre und belasten die Vorsorgewerke.`, teilerklaerungen: [] },
  { id: '8f02f682-dca2-4515-aa69-677cb585c3d9', fachbereich: 'VWL', musterlosung: `Im einfachen Wirtschaftskreislauf stellen Haushalte den Unternehmen Produktionsfaktoren zur Verfügung, vor allem Arbeit und Kapital, und bezahlen für gekaufte Güter. Die Unternehmen liefern Güter und Dienstleistungen an die Haushalte und zahlen Faktorentgelte wie Löhne und Zinsen. Güter und Geld zirkulieren dabei in entgegengesetzter Richtung. Das Modell abstrahiert vom Staat, den Banken und dem Ausland und eignet sich deshalb nur zur ersten Übersicht.`, teilerklaerungen: [] },
  { id: '902825ad-8593-43ad-ba33-12d45c676987', fachbereich: 'VWL', musterlosung: `Die Neue Politische Ökonomie erklärt das Wachstum der Staatsausgaben durch eigeninteressierte Akteure: Beamte maximieren ihr Budget, Parlamentarier finanzieren Klientelinteressen und suchen Macht sowie Prestige über hohe Budgets. Zunehmende Staatsaufgaben ergänzen diese Erklärung durch sachliche Ausweitungen in Sozial-, Bildungs-, Umwelt-, Gesundheits- und Infrastrukturpolitik. Beide Ansätze wirken kumulativ und erklären den Anstieg der Staatsquote in praktisch allen Industrieländern seit 1945.`, teilerklaerungen: [] },
  { id: '9606e3c9-9c5f-4191-a1c5-1c369d70e653', fachbereich: 'VWL', musterlosung: `Die AHV als 1. Säule finanziert sich durch einkommensabhängige Lohnbeiträge, ergänzt durch Bundesbeiträge und einen MWST-Anteil; die Verwaltungskosten sind tief. Die berufliche Vorsorge als 2. Säule arbeitet mit individuellen Sparkonten und mindestens paritätischen Beiträgen von Arbeitgebenden und Arbeitnehmenden. Die obligatorische Krankenversicherung erhebt einheitliche Kopfprämien pro Region und Kasse; Prämienverbilligungen gleichen die fehlende Einkommensabhängigkeit sozialpolitisch aus.`, teilerklaerungen: [] },
  { id: '9676373e-c534-4126-84db-159c495c6e01', fachbereich: 'VWL', musterlosung: `Direkte Steuern treffen Einkommen und Vermögen und berücksichtigen die wirtschaftliche Leistungsfähigkeit — dazu zählen Einkommens-, Vermögens- und die direkte Bundessteuer. Indirekte Steuern belasten den Konsum unabhängig vom persönlichen Einkommen; Mehrwertsteuer, Mineralöl- und Tabaksteuer sind typische Beispiele. Nirgendwo in Europa ist der Anteil der direkten Steuern so hoch wie in der Schweiz; das stärkt die Umverteilungswirkung des Steuersystems.`, teilerklaerungen: [] },
  { id: '9c32e208-554c-4445-9d20-74224e3178de', fachbereich: 'VWL', musterlosung: `Die Schweiz (rund 28 Prozent) und die USA (rund 27 Prozent) gehören zu den Ländern mit tiefer Fiskalquote; der Staatsanteil bleibt vergleichsweise gering. Skandinavische Wohlfahrtsstaaten wie Schweden (rund 43 Prozent) und Dänemark (rund 46 Prozent) weisen hohe Fiskalquoten auf, ebenso Frankreich (rund 45 Prozent). Hohe Fiskalquoten finanzieren umfassende Sozialsysteme, reduzieren aber den verfügbaren privaten Konsum.`, teilerklaerungen: [] },
  { id: 'a205db4d-ce9f-4e48-8f53-6b5bb3d3b23e', fachbereich: 'VWL', musterlosung: `Konsumgüter dienen direkt der Bedürfnisbefriedigung, etwa Smartphone, Schulbuch oder Kleidung. Investitionsgüter werden zur Produktion weiterer Güter eingesetzt, zum Beispiel Friteuse im Restaurant, Lastwagen für den Gütertransport oder Fabrikgebäude. Freie Güter sind von der Natur gratis und ausreichend verfügbar, klassisch Luft zum Atmen und Sonnenlicht. Mit zunehmender Knappheit oder Verschmutzung können freie Güter allerdings zu knappen Wirtschaftsgütern werden.`, teilerklaerungen: [] },
  { id: 'a23551f3-2fa3-4184-b477-9b9f8c47589e', fachbereich: 'VWL', musterlosung: `Die AHV zahlt Altersrenten ab dem gesetzlichen Rentenalter. Die IV unterstützt Personen mit dauerhafter Erwerbsunfähigkeit nach Krankheit oder Unfall. Die Erwerbsersatzordnung (EO) gleicht den Erwerbsausfall bei Militär-, Zivildienst oder Mutterschaft aus. Die Arbeitslosenversicherung zahlt Taggelder nach betriebsbedingter Kündigung, und die obligatorische Krankenversicherung übernimmt Arzt- und Behandlungskosten. Franchise und Selbstbehalt verbleiben beim Versicherten.`, teilerklaerungen: [] },
  { id: 'a96697f9-2f23-4bb1-9383-c49afaf74536', fachbereich: 'VWL', musterlosung: `Transparenz-Instrumente zielen auf das Bankgeheimnis: Der Automatische Informationsaustausch (AIA) zwischen Staaten und die schwarzen Listen der EU erhöhen den Informationsfluss über Konten und Steuerpflichtige. Instrumente gegen Gewinnverschiebung zielen auf die Besteuerung am Ort der Wertschöpfung: Das OECD-BEPS-Projekt und die globale Mindeststeuer von 15 Prozent begrenzen aggressive Steueroptimierung multinationaler Konzerne. Beide Stossrichtungen wirken komplementär.`, teilerklaerungen: [] },
  { id: 'a9e38b08-259a-4429-b3fd-59f6fa3742a0', fachbereich: 'VWL', musterlosung: `Die Angebotskurve verschiebt sich nach rechts, wenn die Produktionskosten sinken: Neue Technologien oder Subventionen erlauben günstigere Herstellung. Sie verschiebt sich nach links, wenn die Kosten steigen — etwa durch teurere Rohstoffe, Produktionssteuern oder Lohnerhöhungen in der Branche. Entscheidend ist die Unterscheidung zwischen einer Verschiebung der Kurve (durch Kostenfaktoren) und einer Bewegung entlang der Kurve (durch den Preis des betrachteten Guts).`, teilerklaerungen: [] },
  { id: 'ade43564-a8ee-447a-8691-b05644076564', fachbereich: 'VWL', musterlosung: `Negative externe Effekte entstehen, wenn Dritte Kosten tragen, die im Marktpreis nicht abgebildet sind — zum Beispiel Flussverschmutzung, Fluglärm oder CO₂-Emissionen des Autoverkehrs. Der Markt produziert dann zu viel dieses Guts. Positive externe Effekte bringen Dritten einen Nutzen, der den Anbietenden nicht vergütet wird — Impfungen schützen auch Ungeimpfte, Bildung steigert die allgemeine Produktivität, schöne Gärten erfreuen Nachbarn. Hier produziert der Markt zu wenig.`, teilerklaerungen: [] },
  { id: 'afa6d4bc-de62-45e1-b880-fd479b1fc326', fachbereich: 'VWL', musterlosung: `Wirtschaftswachstum bringt zahlreiche Vorteile: bessere Bedürfnisbefriedigung, sinkende Arbeitslosigkeit, erleichterte Sozialpolitik und die Option auf mehr Freizeit bei gleichem Einkommen. Als Nachteile gelten Umweltverschmutzung und Ressourcenausbeutung, weil steigende Produktion in der Regel mehr Materialeinsatz erfordert. Die zentrale Herausforderung der Wirtschaftspolitik besteht darin, Wachstum stärker von der Umweltbelastung zu entkoppeln, zum Beispiel durch Ressourceneffizienz und Kreislaufwirtschaft.`, teilerklaerungen: [] },
  { id: 'b67e6022-4e0f-4476-82e6-e8d7cf98aee1', fachbereich: 'VWL', musterlosung: `Libertarians (neo-liberale Positionen) lehnen Umverteilung als Freiheitseinschränkung ab und sehen Staatseingriffe als Wohlfahrtsminderung. Liberals wie John Rawls kombinieren Markt und Staat: Ungleichheiten sind gerechtfertigt, wenn sie den Nutzen des Schwächsten maximieren (Differenzprinzip). Collectivists (sozialistische Positionen) verstehen den Mehrwert als Ausbeutung der Arbeiterschaft und fordern die Verstaatlichung der Produktionsmittel. Die drei Positionen markieren die Bandbreite moderner Gerechtigkeitsdebatten.`, teilerklaerungen: [] },
  { id: 'b847efe6-aede-459f-9d92-a576bd24d0c6', fachbereich: 'VWL', musterlosung: `Staatliche Regulierung steuert die Nutzung einer Allmende direkt, etwa über Fischereilizenzen oder Fahrverbote in der Innenstadt. Selbstorganisation setzt auf gemeinsame Regeln der Betroffenen, wie Schweizer Alpgenossenschaften oder gemeinsame Bewässerungspläne. Privatisierung weist Eigentums- oder Nutzungsrechte zu und etabliert Märkte, beispielsweise Emissionshandel. In der Praxis werden oft Mischformen eingesetzt; Elinor Ostrom zeigte, dass Selbstorganisation unter klaren Rahmenbedingungen sehr gut funktionieren kann.`, teilerklaerungen: [] },
  { id: 'baaf9df8-f8fc-4869-b4ad-a5b7d287faeb', fachbereich: 'VWL', musterlosung: `Anreize wirken oft weniger eindeutig als geplant. Kehrichtsackgebühren reduzieren zwar den Abfall, lösen aber auch wilde Deponien aus. Die historische Kobra-Prämie in Indien führte dazu, dass Menschen Kobras gezielt züchteten. Alkoholrationierungen förderten Schmuggel und Schwarzbrennereien. Gelungene Beispiele sind Nudges wie Fussabdrücke auf Strassen und die Organspende-Widerspruchslösung. Eisenhut warnt davor, Menschen als simple Reiz-Reaktions-Maschinen zu verstehen.`, teilerklaerungen: [] },
  { id: 'c384336f-e2b7-436e-9d87-6d7fdb5d8b2f', fachbereich: 'VWL', musterlosung: `Friktionelle Arbeitslosigkeit entsteht durch Suchprozesse und saisonale Schwankungen, etwa beim Stellenwechsel oder bei Skilehrerinnen im Sommer. Konjunkturelle Arbeitslosigkeit folgt aus Nachfragerückgang in Rezessionen: Unternehmen entlassen oder bauen Stellen ab. Strukturelle Arbeitslosigkeit resultiert aus langfristigen Umwälzungen wie Digitalisierung, Automatisierung oder Branchenwandel; Fabrikarbeitende, die durch Roboter ersetzt werden, oder Druckereien, die schliessen müssen, sind typische Beispiele.`, teilerklaerungen: [] },
  { id: 'c4d0859f-1ed2-42c6-8f33-aa6fc41772a7', fachbereich: 'VWL', musterlosung: `Der Homo oeconomicus ist ein vereinfachtes Modell: Er handelt rational, maximiert seinen Nutzen, wägt Kosten und Nutzen ab und reagiert auf Anreize. Nicht zum Modell gehören karikierende Eigenschaften wie Allwissenheit, reiner Altruismus, reines Bauchgefühl oder das Ignorieren des Eigeninteresses. Eigennützig bedeutet nicht egoistisch — soziale Ziele können Teil des Nutzens sein. Die Verhaltensökonomie zeigt zwar systematische Abweichungen, das Modell bleibt aber nützlich.`, teilerklaerungen: [] },
  { id: 'c9371217-d761-46a7-b4a3-d37d9a68b008', fachbereich: 'VWL', musterlosung: `Absolute Armut bedeutet, dass das physische Existenzminimum nicht gesichert ist: Hunger, mangelnde Gesundheitsversorgung und kein sauberes Wasser. Sie betrifft weltweit rund 700 Millionen Menschen, vor allem in Entwicklungsländern. Relative Armut wird am gesellschaftlichen Wohlstand gemessen, typischerweise bei einem Einkommen unter 60 Prozent des Medianeinkommens. In Industrieländern wie der Schweiz ist dies die praktisch relevante Armutsdefinition für die Sozialpolitik.`, teilerklaerungen: [] },
  { id: 'c9df5e1a-e88f-40d3-ab6f-3bfd0c7fa750', fachbereich: 'VWL', musterlosung: `Die Pommes-Produktion (nach Eisenhut) illustriert die vier Produktionsfaktoren. Arbeit liefern der Koch und das Servierpersonal. Natürliche Ressourcen sind Kartoffeln vom Feld und Erdöl zur Energiegewinnung. Realkapital umfasst Friteuse und Restaurantgebäude. Wissen besteht aus der Ausbildung des Kochs sowie aus Rezepten und Know-how. Jede Produktion kombiniert alle vier Faktoren; fehlt einer, kann nicht produziert werden.`, teilerklaerungen: [] },
  { id: 'cae065f3-1055-4931-b8ab-1d64cc1bd8e8', fachbereich: 'VWL', musterlosung: `Die Volkswirtschaftliche Gesamtrechnung erfasst nur monetäre Markttransaktionen. Eine offiziell angestellte Putzkraft, Fremdbetreuung in der Krippe, Restaurantbesuche und Garagenreparaturen fliessen ins BIP ein. Eigenleistungen wie Selbstkochen, die eigene Kinderbetreuung oder das eigene Putzen der Wohnung bleiben unberücksichtigt, ebenso wie nicht angemeldete Schwarzarbeit. Dieselbe Leistung wird also nur erfasst, sobald sie über den Markt abgewickelt wird — ein bekannter Schwachpunkt des BIP.`, teilerklaerungen: [] },
  { id: 'cc401550-bd35-46d9-b41e-62c8a9bf4c43', fachbereich: 'VWL', musterlosung: `Der grösste Posten der Bundesausgaben ist die soziale Wohlfahrt mit rund 22 Milliarden Franken (2018); sie umfasst vor allem AHV und IV. Mit je rund 10 Milliarden Franken folgen Finanzen und Steuern sowie Verkehr. Bildung (rund 8 Milliarden) und Landesverteidigung (rund 6 Milliarden) schliessen die wichtigsten Posten ab. Die Dominanz der Sozialausgaben spiegelt den Ausbau des Sozialstaats seit 1945.`, teilerklaerungen: [] },
  { id: 'd0818471-e4ff-4a4b-8381-21ca27f8b028', fachbereich: 'VWL', musterlosung: `Historisch dominierte zuerst die Laissez-faire-Marktwirtschaft des 19. Jahrhunderts, in welcher der Staat als Nachtwächter auftrat und nur für Recht, Verteidigung und Infrastruktur sorgte. Als Reaktion auf Monopolbildungen entstand die neoliberale Ordnung mit aktiver Wettbewerbspolitik. Nach 1945 etablierte sich schliesslich die soziale Marktwirtschaft mit umfangreichen Verteilungsaufgaben und Arbeitsmarktpolitik. Die Schweiz und Deutschland gelten als typische Vertreter dieses dritten Modells.`, teilerklaerungen: [] },
  { id: 'd3eb5881-6f75-4115-9689-cbb071a06e64', fachbereich: 'VWL', musterlosung: `Gebote und Verbote sind direkte Regulierungen wie Schadstoff-Grenzwerte oder das FCKW-Verbot; sie wirken verbindlich, lassen aber keine Flexibilität zu. Lenkungsabgaben setzen Preisanreize, etwa die CO₂-Abgabe oder der Klimarappen auf Benzin; die Einnahmen werden meist rückverteilt. Umweltzertifikate legen eine Gesamtmenge fest (Cap) und lassen Unternehmen untereinander handeln; das EU-Emissionshandelssystem ETS ist das prominenteste Beispiel dieser marktbasierten Steuerung.`, teilerklaerungen: [] },
  { id: 'd75693e3-56f1-46b3-bce4-6e130b2e0c12', fachbereich: 'VWL', musterlosung: `Der Produktionsansatz summiert die Wertschöpfung aller Unternehmen, also Produktionswert abzüglich Vorleistungen. Der Einkommensansatz addiert alle Einkommen wie Löhne, Gewinne und Zinsen; der Lohn einer Lehrerin gehört hierhin. Der Verwendungsansatz folgt der Formel C + I + G + NX, wobei Uhrenexporte als Nettoexport erfasst werden. Alle drei Ansätze ergeben definitionsgemäss dasselbe BIP, betrachten es aber aus unterschiedlichen Perspektiven.`, teilerklaerungen: [] },
  { id: 'db4c61fa-2c98-4517-8798-4969c054339f', fachbereich: 'VWL', musterlosung: `Die Beveridge-Kurve stellt offene Stellen und Arbeitslose gegeneinander dar. Hochkonjunktur liegt links oben: Es gibt mehr offene Stellen als Arbeitslose, Unternehmen finden kaum Personal — ein Stellenüberhang. Rezession liegt rechts unten: Viele Arbeitslose treffen auf wenige offene Stellen, Unternehmen reagieren mit Entlassungen. Die Kurve veranschaulicht den grundlegenden Zielkonflikt der Arbeitsmarktpolitik und hilft, konjunkturelle Phasen einzuordnen.`, teilerklaerungen: [] },
  { id: 'dca030b7-052b-451f-95ac-84005c70e9e8', fachbereich: 'VWL', musterlosung: `Gebote und Verbote sind direkte staatliche Regulierungen mit verbindlichen Vorgaben: Schadstoff-Grenzwerte, das FCKW-Verbot oder die Umweltverträglichkeitsprüfung. Marktbasierte Instrumente nutzen dagegen Preismechanismen, zum Beispiel CO₂-Lenkungsabgaben, handelbare Emissionszertifikate oder gezielte Besteuerung belastender Aktivitäten. Der marktbasierte Weg gilt ökonomisch als effizienter, weil Unternehmen selbst die kostengünstigste Vermeidungsstrategie wählen, politisch ist er aber oft schwerer durchsetzbar.`, teilerklaerungen: [] },
  { id: 'dce2df8e-60a8-48fe-905e-99e60f5fd181', fachbereich: 'VWL', musterlosung: `Umverteilung korrigiert Einkommensunterschiede nachträglich, etwa durch progressive Besteuerung, Sozialhilfe oder AHV-Renten. Sie wirkt schnell, kann aber Anreize dämpfen und bekämpft nur Symptome. Ursachenbekämpfung setzt an den Wurzeln an: Frühförderung für bildungsferne Familien, kostenloser Bildungszugang und Stipendien stärken Chancengleichheit und Humankapital langfristig. Moderne Sozialpolitik kombiniert beide Strategien, verlagert den Akzent aber zunehmend auf Prävention und Investition in Bildung.`, teilerklaerungen: [] },
  { id: 'e24cf16c-148e-43e0-b4e7-839968172dce', fachbereich: 'VWL', musterlosung: `Haushaltsdisziplin bedeutet Sparen durch Ausgabenkürzungen oder Steuererhöhungen; sie wirkt direkt, bremst aber kurzfristig die Konjunktur. Wirtschaftswachstum senkt die Schuldenquote relativ, wenn das BIP schneller wächst als die Schulden; Strukturreformen unterstützen diesen Effekt. Inflation reduziert den realen Wert der Schulden, belastet jedoch Gläubiger und Sparende. Alle drei Strategien bergen Nebenwirkungen und werden deshalb meist kombiniert eingesetzt, um Stabilität und Wachstum zu sichern.`, teilerklaerungen: [] },
  { id: 'e33b0731-eb65-41c1-ac36-40e09821d6d6', fachbereich: 'VWL', musterlosung: `Verbrauchsgüter werden beim Konsum aufgebraucht und gehen unter; dazu gehören Sandwich, Mineralwasser oder Benzin. Gebrauchsgüter können über längere Zeit wiederholt genutzt werden, zum Beispiel Velo, Winterjacke oder Spielkonsole. Die Unterscheidung ist für die Haushaltsplanung wichtig: Gebrauchsgüter verursachen einmalige Anschaffungskosten mit anteiliger Nutzungsdauer, Verbrauchsgüter regelmässige laufende Ausgaben. Die Grenze ist bei manchen Gütern fliessend, etwa bei Möbeln oder Elektronik.`, teilerklaerungen: [] },
  { id: 'e645bbc6-952e-4098-9b09-31164661ea46', fachbereich: 'VWL', musterlosung: `Zielharmonie liegt vor, wenn das Erreichen eines Ziels ein anderes fördert — Wirtschaftswachstum unterstützt Vollbeschäftigung, und Bildungsinvestitionen begünstigen Wachstum und sozialen Ausgleich gleichzeitig. Zielkonkurrenz bedeutet, dass sich Ziele gegenseitig behindern: Mehr Wachstum kann die Umwelt belasten, und Preisstabilität konkurriert kurzfristig mit Vollbeschäftigung. Das klassische Bild «Butter und Kanonen» illustriert den Zielkonflikt zwischen Konsumproduktion und Verteidigungsausgaben.`, teilerklaerungen: [] },
  { id: 'e7c11811-6b64-4585-a518-cda104a51740', fachbereich: 'VWL', musterlosung: `Investive Schulden für Infrastruktur oder Bildung gelten als gerechtfertigt, weil sie zukünftige Erträge oder Nutzen für die Gesellschaft schaffen. Auch temporäre Defizite zur Konjunkturstabilisierung in Rezessionen sind volkswirtschaftlich sinnvoll. Problematisch sind dagegen Schulden für den laufenden Konsum, für Personalausgaben oder ein dauerhaftes Leben über den Verhältnissen. Die Schweizer Schuldenbremse trennt deshalb konsequent zwischen strukturellen und konjunkturellen Defiziten und zwingt zum Ausgleich über den Zyklus.`, teilerklaerungen: [] },
  { id: 'ebd8037a-82b0-484d-8900-96ff267bb3b4', fachbereich: 'VWL', musterlosung: `Rivale Güter werden durch Konsum aufgebraucht oder blockieren andere Nutzende: ein Stück Pizza, ein Parkplatz in der Innenstadt oder Wasser aus einer begrenzten Quelle sind nur einmal nutzbar. Nicht-rivale Güter stehen gleichzeitig vielen Menschen zur Verfügung, ohne dass die Qualität für Einzelne leidet — ein Radiosignal, eine staufreie Brücke oder ein Feuerwerk. Die Rivalität bestimmt mit, ob Märkte effizient funktionieren.`, teilerklaerungen: [] },
  { id: 'einr-zu-emojis', fachbereich: 'VWL', musterlosung: `Die Emojis dieser Einführungsfrage symbolisieren bekannte Schweizer Leitmotive. Der Doktorhut 🎓 steht für Bildung, die Berge 🏔️ für die alpine Landschaft, der Käse 🧀 für die Milchwirtschaft und die Uhr 🕐 für die Präzisionsindustrie. Die Frage vermittelt kein Fachwissen, sondern zeigt die Bedienung: Jedes Emoji wird über das Dropdown-Menü rechts dem passenden Begriff zugeordnet. Sie dient der Einführung in das Antwortformat.`, teilerklaerungen: [] },
]

async function main() {
  const stateRaw = await fs.readFile(STATE, 'utf8')
  const state = JSON.parse(stateRaw)
  state.fragen = state.fragen || {}

  const outLines = []
  let done = 0
  const now = new Date().toISOString()

  for (const u of updates) {
    const existing = state.fragen[u.id]
    if (existing && existing.status === 'done') {
      console.warn(`skip already done: ${u.id}`)
      continue
    }
    outLines.push(JSON.stringify(u))
    state.fragen[u.id] = {
      status: 'done',
      zeitpunkt: now,
      teile: u.teilerklaerungen.length,
    }
    done++
  }

  state.verarbeitet = (state.verarbeitet || 0) + done
  state.letzteSession = now

  await fs.appendFile(OUT, outLines.join('\n') + (outLines.length ? '\n' : ''), 'utf8')
  await fs.writeFile(STATE, JSON.stringify(state, null, 2), 'utf8')

  console.log(`Session 25: ${done} verarbeitet, total ${state.verarbeitet}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
