#!/usr/bin/env node
/**
 * Session 21: 50 VWL/richtigfalsch-Fragen.
 * Erste Hälfte des 100er-Batches nach Fachbereich → Typ → ID.
 * Keine Teilerklärungen (aussagen haben keine IDs in der DB).
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'fragen-updates.jsonl')
const STATE = path.join(__dirname, 'state.json')

const updates = [
  { id: '53080d6e-8732-449e-9eda-016dd8380724', fachbereich: 'VWL', musterlosung: 'Richtig. Bei vollkommener Konkurrenz treffen viele kleine Anbieter und Nachfrager auf homogene Güter. Kein einzelner Marktteilnehmer hat Marktmacht — alle müssen den gegebenen Marktpreis akzeptieren. Wer über dem Marktpreis anbietet, verkauft nichts; wer darunter anbietet, verzichtet auf Gewinn. Diese Preisnehmer-Eigenschaft ist ein zentrales Merkmal des Modells der vollkommenen Konkurrenz.', teilerklaerungen: [] },
  { id: '56086529-ffbc-4921-af7f-719757eebc90', fachbereich: 'VWL', musterlosung: 'Richtig. Über 70 Prozent der Beschäftigten in der Schweiz arbeiten im tertiären Sektor — Banken, Versicherungen, Handel, Bildung, Gesundheit, IT. Der sekundäre Sektor (Industrie) beschäftigt rund 25 Prozent, der primäre (Landwirtschaft) nur noch etwa 3 Prozent. Die Schweiz hat den typischen Strukturwandel einer Industrie- zur Dienstleistungsgesellschaft vollzogen.', teilerklaerungen: [] },
  { id: '56addc34-d25d-4122-b62f-8b60d76b96c8', fachbereich: 'VWL', musterlosung: 'Falsch. Preisdifferenzierung kann die Wohlfahrt sogar erhöhen, wenn dadurch mehr Konsumenten bedient werden als bei einem Einheitspreis. Bei vollständiger Preisdifferenzierung — jede Person zahlt ihre maximale Zahlungsbereitschaft — entfällt sogar der Wohlfahrtsverlust des Monopols. Allerdings geht die gesamte Konsumentenrente an den Produzenten; die Verteilungswirkung ist also problematisch, nicht die Effizienz.', teilerklaerungen: [] },
  { id: '5a3fd65c-7ead-4b50-a2c6-ff73be4921b9', fachbereich: 'VWL', musterlosung: 'Richtig. Die Wertschöpfung entspricht dem neu geschaffenen Wert auf einer Produktionsstufe. Sie ergibt sich, indem vom Produktionswert die zugekauften Vorleistungen abgezogen werden. Nur so wird vermieden, dass Leistungen mehrfach gezählt werden. Die Summe aller Wertschöpfungen ergibt das BIP einer Volkswirtschaft — das ist die Grundidee des Produktionsansatzes.', teilerklaerungen: [] },
  { id: '5b9b0550-a902-4fa6-9bd1-260bf9666ce7', fachbereich: 'VWL', musterlosung: 'Richtig. Eine Kopfsteuer (Pauschalsteuer, Lump-Sum Tax) verzerrt keine wirtschaftlichen Entscheidungen, weil sie unabhängig von Einkommen, Konsum oder Verhalten anfällt. Es gibt keinen Ausweicheffekt und keinen Wohlfahrtsverlust. Sie ist aber regressiv und damit politisch kaum durchsetzbar. In der ökonomischen Theorie dient sie als Referenzpunkt für verzerrungsfreie Besteuerung.', teilerklaerungen: [] },
  { id: '5ba970d2-f55f-4ab2-8a44-dbdffc32abf7', fachbereich: 'VWL', musterlosung: 'Falsch. Knappheit ist nicht dasselbe wie Seltenheit. Knappheit entsteht durch das Verhältnis zwischen Bedürfnissen und verfügbaren Mitteln — wir wollen mehr, als vorhanden ist. Auch ein häufig vorhandenes Gut kann knapp sein, wenn die Nachfrage das Angebot übersteigt. Umgekehrt sind seltene Güter ohne Nachfrage nicht knapp. Das Verhältnis macht den Unterschied.', teilerklaerungen: [] },
  { id: '5bfda75a-0c45-4308-82cf-406f523b9d2c', fachbereich: 'VWL', musterlosung: 'Richtig. Ein Gini-Koeffizient von 0 entspricht der 45-Grad-Linie in der Lorenzkurven-Darstellung — der perfekten Gleichverteilung. Jeder Prozentanteil der Bevölkerung erhält genau denselben Prozentanteil des Gesamteinkommens. Ein Wert von 1 entspräche vollständiger Ungleichverteilung, bei der eine Person das gesamte Einkommen bezieht. Reale Gesellschaften liegen dazwischen; die Schweiz bei etwa 0.33.', teilerklaerungen: [] },
  { id: '5e7b0466-aa43-4fbe-ab01-c57f00349c33', fachbereich: 'VWL', musterlosung: 'Falsch — das Gegenteil ist der Fall. Bei positiven externen Effekten liegt der gesellschaftliche Nutzen über dem privaten Nutzen. Da Konsumenten und Produzenten nur den privaten Nutzen berücksichtigen, wird das Gut in zu geringer Menge bereitgestellt. Bildung, Impfungen oder Forschung werden deshalb staatlich gefördert oder subventioniert, um die Unterproduktion zu korrigieren.', teilerklaerungen: [] },
  { id: '5eff0ceb-2b1e-4d47-8805-2f17408d9487', fachbereich: 'VWL', musterlosung: 'Richtig. Das Kapitaldeckungsverfahren beruht auf der Anlage von Beiträgen am Finanzmarkt. Börsencrashs und Finanzkrisen können Pensionskassenvermögen erheblich schmälern. Das ist ein zentrales Risiko dieses Verfahrens. Das Umlageverfahren der AHV ist hingegen weitgehend unabhängig von Finanzmarktentwicklungen — dafür reagiert es empfindlich auf demografischen Wandel.', teilerklaerungen: [] },
  { id: '5f472cef-26a6-49e6-acc2-b637bd168c73', fachbereich: 'VWL', musterlosung: 'Richtig. Die globale Mindeststeuer der OECD (Pillar 2) setzt dem internationalen Steuerwettbewerb eine Untergrenze von 15 Prozent. Damit soll verhindert werden, dass multinationale Konzerne ihre Gewinne in Tiefsteuerländer verschieben. Betroffen sind auch einige Schweizer Kantone, die Unternehmensgewinne bisher unter 15 Prozent besteuerten. Die Schweiz hat die Regelung via Verfassungsänderung umgesetzt.', teilerklaerungen: [] },
  { id: '619b0e21-4a2d-48e9-b283-885b765ca457', fachbereich: 'VWL', musterlosung: 'Falsch. Die Klassiker lehnen aktive staatliche Konjunkturpolitik ab. Sie vertrauen auf die Selbstheilungskräfte des Marktes — flexible Preise, Löhne und Zinsen sorgen für automatische Anpassung. Staatliche Eingriffe würden diesen Prozess stören und verzögern. Die aktive Konjunkturpolitik gegen Rezessionen ist vielmehr ein Kerngedanke des Keynesianismus, der in den 1930er-Jahren als Gegenentwurf entstand.', teilerklaerungen: [] },
  { id: '6412d814-c336-43c1-a2f0-0de7deae52a6', fachbereich: 'VWL', musterlosung: 'Richtig. Eine steile (unelastische) Nachfragekurve zeigt, dass Konsumenten kaum auf Preiserhöhungen reagieren — Substitute fehlen oder das Gut ist lebensnotwendig (etwa Insulin, Benzin). Die Produzenten können die Steuer deshalb fast vollständig über höhere Preise weitergeben. Allgemein gilt: Die Marktseite mit der unelastischeren Kurve trägt den grösseren Teil der Steuer.', teilerklaerungen: [] },
  { id: '66c162ae-e08c-4393-84af-af471fee0b28', fachbereich: 'VWL', musterlosung: 'Richtig. In einer Liquiditätsfalle sind die Zinsen bereits bei oder nahe null, weitere Zinssenkungen sind unmöglich oder wirkungslos. Haushalte und Unternehmen horten Geld statt es auszugeben oder zu investieren. Die Geldpolitik verliert ihre Wirkung. Keynes empfahl für diese Situation, dass die Fiskalpolitik die Rolle der Konjunktursteuerung übernehmen muss — über höhere Staatsausgaben.', teilerklaerungen: [] },
  { id: '66cc1540-b8b2-4eaf-ba15-b2172ecf9ed0', fachbereich: 'VWL', musterlosung: 'Richtig. Die Volkswirtschaftslehre und die Betriebswirtschaftslehre gehören zu den Sozialwissenschaften — zusammen mit Soziologie, Politikwissenschaft und Rechtswissenschaft. Sie untersuchen menschliches Verhalten und gesellschaftliche Strukturen. Damit zählen sie zu den Geisteswissenschaften im weiteren Sinn und nicht zu den Naturwissenschaften, auch wenn sie quantitative Methoden nutzen.', teilerklaerungen: [] },
  { id: '67328681-dd04-4280-8431-1578cf0222c3', fachbereich: 'VWL', musterlosung: 'Falsch. Dem Bund verbleibt nur rund ein Drittel der Einnahmen für eigene Zwecke wie Verwaltung, Landesverteidigung oder internationale Beziehungen. Zwei Drittel fliessen als Übertragungen an Dritte — hauptsächlich in Form von Subventionen an Sozialversicherungen, Kantone, Bildung und Verkehr. Die Hauptaufgabe des Bundeshaushalts liegt also in der Umverteilung, nicht im Eigenverbrauch.', teilerklaerungen: [] },
  { id: '6788661f-6e49-4444-a12a-07903abd6a2f', fachbereich: 'VWL', musterlosung: 'Falsch. Gerade weil der Materialwert (rund 40 Rappen) weit unter dem Nennwert (100 Franken) liegt, handelt es sich um Papiergeld — nicht um Warengeld. Warengeld hätte einen materiellen Eigenwert in Höhe des Nennwerts, etwa eine Goldmünze. Beim Papiergeld beruht der Wert dagegen auf dem Vertrauen in die herausgebende Institution und die allgemeine Akzeptanz.', teilerklaerungen: [] },
  { id: '69a03e8e-1a20-4c9c-b225-d9d1f5f698f0', fachbereich: 'VWL', musterlosung: 'Falsch. Eigennutz ist nicht dasselbe wie Egoismus. Der Homo oeconomicus orientiert sich an seinen eigenen Interessen — diese können aber Vertrauen, Solidarität und Gerechtigkeit einschliessen. Eisenhut schreibt: «Die Menschen sind — von Ausnahmen abgesehen — weder Heilige noch Verbrecher.» Wer anderen hilft, weil ihm dies Freude macht, handelt ebenfalls eigennützig im ökonomischen Sinn.', teilerklaerungen: [] },
  { id: '6b6d7f73-d929-46b4-910c-e9bd59f53cc8', fachbereich: 'VWL', musterlosung: 'Falsch. Das Unternehmen handelt nach dem Minimumprinzip — das Ergebnis (1\'000 Hemden) ist vorgegeben, der Aufwand (Kosten) soll minimiert werden. Beim Maximumprinzip wäre die Logik umgekehrt: Mit einem gegebenen Budget möglichst viele Hemden produzieren. Beide Varianten gehören zum ökonomischen Prinzip und zeigen, dass es je nach Ausgangslage unterschiedliche Optimierungsrichtungen gibt.', teilerklaerungen: [] },
  { id: '6bcbcb8e-d9e0-47d3-9207-1de2519fcdb8', fachbereich: 'VWL', musterlosung: 'Richtig. Das Drei-Säulen-Modell der Nachhaltigkeit umfasst die ökologische Nachhaltigkeit (Umwelt schützen), die ökonomische Nachhaltigkeit (wirtschaftliche Leistungsfähigkeit erhalten) und die soziale Nachhaltigkeit (Gerechtigkeit, Teilhabe, Bildung). Alle drei Dimensionen müssen gleichzeitig berücksichtigt werden — einseitige Betrachtung einzelner Säulen führt zu Zielkonflikten. Die UN-Agenda 2030 folgt diesem Modell.', teilerklaerungen: [] },
  { id: '6cdf3807-593a-414e-a3fb-f0efbd29bf80', fachbereich: 'VWL', musterlosung: 'Falsch. Werden Arbeitszeitverkürzungen nicht kostenneutral umgesetzt, steigen die Lohnstückkosten, die Wettbewerbsfähigkeit sinkt und Arbeitsplätze gehen verloren. Das Arbeitsvolumen ist kein feststehender Kuchen, der einfach umverteilt werden könnte (Lump-of-Labor-Fallacy). Empirisch haben Länder mit hoher Arbeitszeit oft tiefere Arbeitslosenquoten. Die Massnahme ist also weder einfach noch risikolos.', teilerklaerungen: [] },
  { id: '6ddec675-7798-4165-a21e-cae40b47728c', fachbereich: 'VWL', musterlosung: 'Richtig. Die politische Konjunkturtheorie geht davon aus, dass Regierungen ein Interesse haben, vor Wahlen die Wirtschaft zu stimulieren — etwa über höhere Staatsausgaben oder Steuersenkungen — um wiedergewählt zu werden. Nach der Wahl wird dann gespart, was die Konjunktur dämpft. Die Theorie unterstellt, dass Wählerinnen und Wähler ein kurzes Gedächtnis haben und kurzfristige Effekte stark gewichten.', teilerklaerungen: [] },
  { id: '6e2c036c-548a-41bc-9ed4-800aa9336539', fachbereich: 'VWL', musterlosung: 'Richtig. Die Elefantengrafik zeigt prozentuale Einkommensveränderungen 1988 bis 2008 weltweit. Eine 60-Prozent-Steigerung eines Tageseinkommens von 2\'000 US-Dollar ist absolut viel grösser als 60 Prozent von 2 US-Dollar. Gerechnet in absoluten Beträgen kamen fast die Hälfte des globalen Wohlstandsgewinns den reichsten 5 Prozent zugute. Die globalen Gewinner sind damit die westlichen Spitzenverdiener.', teilerklaerungen: [] },
  { id: '6f0b8ae8-d753-4e90-a40e-e04d3529d0c2', fachbereich: 'VWL', musterlosung: 'Falsch. Inflation bezeichnet einen kontinuierlichen Anstieg des allgemeinen Preisniveaus über einen längeren Zeitraum. Verteuert sich nur ein einzelnes Gut wie Benzin, handelt es sich um eine relative Preisveränderung — nicht um Inflation. Das BFS misst die Teuerung über den Landesindex der Konsumentenpreise (LIK), der einen breiten Warenkorb abdeckt und Einzelpreisveränderungen ausgleicht.', teilerklaerungen: [] },
  { id: '6f795fbd-7751-4ce6-93c7-5c4fa9a645e5', fachbereich: 'VWL', musterlosung: 'Richtig. Steigende Preise machen die Produktion rentabler. Bestehende Anbieter weiten ihre Menge aus, und neue Anbieter treten in den Markt ein — sie können nun ihre Grenzkosten decken und Gewinn erzielen. Deshalb verläuft die Angebotskurve typischerweise steigend. Die Stärke der Reaktion hängt von der Preiselastizität des Angebots ab, die wiederum von Produktionsflexibilität und Zeithorizont bestimmt wird.', teilerklaerungen: [] },
  { id: '6fe5cfb4-e078-45b9-a326-f2dd579d9546', fachbereich: 'VWL', musterlosung: 'Falsch. Die Steuerinzidenz zeigt, wer die Steuer wirtschaftlich tatsächlich trägt — nicht wer sie formal an den Staat abliefert. Der formale Steuerschuldner und der tatsächliche wirtschaftliche Träger können stark voneinander abweichen. Die Inzidenz hängt von den Elastizitäten von Angebot und Nachfrage ab, nicht von der gesetzlichen Regelung. Die unelastischere Marktseite trägt den grösseren Teil.', teilerklaerungen: [] },
  { id: '76ee6a7e-2ed1-4583-afd4-af2799813e16', fachbereich: 'VWL', musterlosung: 'Richtig. Garantien signalisieren Qualität — ein Anbieter minderwertiger Ware würde keine Garantie geben (Signaling). Zertifikate wie Bio-Label oder Prüfsiegel reduzieren die Informationsasymmetrie durch unabhängige Prüfung. Auch Probezeiten im Arbeitsmarkt, Ratings und Online-Bewertungen dienen diesem Zweck. Private Lösungen ergänzen oder ersetzen damit staatliche Regulierung, wo Informationsasymmetrien den Markt zu lähmen drohen.', teilerklaerungen: [] },
  { id: '786b683f-4df7-4f98-9624-996b91451f47', fachbereich: 'VWL', musterlosung: 'Richtig. In Hochkonjunkturphasen ist die Zahl der Arbeitslosen klein, die Zahl der offenen Stellen dagegen hoch. Der entsprechende Punkt auf der Beveridge-Kurve liegt links oberhalb der Winkelhalbierenden — ein Stellenüberhang. In Rezessionen liegt der Punkt rechts unten mit vielen Arbeitslosen und wenigen offenen Stellen. Die Bewegung entlang der Kurve bildet den Konjunkturverlauf ab.', teilerklaerungen: [] },
  { id: '79836fbb-1635-472b-8822-4e03bcc849af', fachbereich: 'VWL', musterlosung: 'Richtig. Im Spiel BOB bleibt X zwischen den Runden erhalten, während andere nicht eingesetzte Buchstaben zurückgegeben werden müssen. Damit lässt sich X über mehrere Runden hinweg sparen — es erfüllt die Wertaufbewahrungsfunktion des Geldes. Gleichzeitig dient X als Tauschmittel im Spielverlauf und als Recheneinheit (1 X = 1 Siegpunkt). Das Spiel illustriert die drei klassischen Geldfunktionen.', teilerklaerungen: [] },
  { id: '7d2cb964-b923-4c45-b464-4cb324dfe9a2', fachbereich: 'VWL', musterlosung: 'Richtig. Während bei vollkommener Konkurrenz der Preis den Grenzkosten entspricht, setzt ein Monopolist den Preis über die Grenzkosten. Durch Mengenbeschränkung hebt er den Marktpreis und maximiert seinen Gewinn. Das geht zulasten der Konsumenten und der Gesamtwohlfahrt — es entsteht ein Wohlfahrtsverlust (Deadweight Loss). Deshalb wird die Bildung von Monopolen oft durch Wettbewerbsrecht eingeschränkt.', teilerklaerungen: [] },
  { id: '7f290314-6a26-4e53-9e90-f65ffdbbf8e9', fachbereich: 'VWL', musterlosung: 'Richtig. Von den gesamten inländischen Schulden (ohne Finanzsektor) entfallen rund 47 Prozent auf private Haushalte — vor allem Hypotheken. Rund 35 Prozent halten Unternehmen, nur etwa 18 Prozent der Bund, die Kantone und Gemeinden zusammen. Die Schweiz hat damit eine vergleichsweise tiefe Staatsverschuldung, aber eine der höchsten Privatverschuldungsquoten weltweit, getrieben durch den Immobilienmarkt.', teilerklaerungen: [] },
  { id: '7f8ab48e-748d-4a3c-bc4e-1da3b1203892', fachbereich: 'VWL', musterlosung: 'Falsch. Negative Nettoexporte bedeuten nur, dass diese Komponente einen negativen Beitrag zum BIP liefert. Das BIP kann trotzdem steigen, wenn Konsum, Investitionen oder Staatsausgaben stärker wachsen als der Handelsbilanzsaldo sinkt. Der Nettoexport ist nur eine von vier Komponenten der Verwendungsrechnung. Zwingend ist der Zusammenhang nicht.', teilerklaerungen: [] },
  { id: '7ffc04c1-0f74-4593-ad0f-6441f6b80b6a', fachbereich: 'VWL', musterlosung: 'Richtig. Herbert Simon prägte 1957 den Begriff der «bounded rationality» — begrenzte Rationalität. Menschen können nicht alle relevanten Informationen sammeln und verarbeiten; die Welt ist zu komplex. Sie nutzen stattdessen Faustregeln, Erfahrungswerte und vereinfachende Heuristiken. Simon erhielt für seine Arbeiten 1978 den Wirtschafts-Nobelpreis. Sein Ansatz bereitete den Weg für die moderne Verhaltensökonomie.', teilerklaerungen: [] },
  { id: '80065324-aaf8-40a5-a7ae-189c71222ed5', fachbereich: 'VWL', musterlosung: 'Richtig. Bei Schäden mit hoher Eintrittswahrscheinlichkeit und kleiner Schadenssumme ist die Prämie im Verhältnis zum Risiko hoch — die Versicherung lohnt sich ökonomisch kaum. Ersparnisse bieten in solchen Fällen eine flexible Alternative und decken zudem andere Risiken ab. Bei grossen, existenzbedrohenden Schäden wie Feuer oder Krankheit reichen Ersparnisse hingegen nicht — hier ist die Risikogemeinschaft einer Versicherung überlegen.', teilerklaerungen: [] },
  { id: '8194ae87-40c7-4b7e-8171-fcae2f03eb62', fachbereich: 'VWL', musterlosung: 'Richtig. Die CO₂-Abgabe verteuert klimaschädliches Verhalten und soll damit den Ausstoss von Treibhausgasen reduzieren — ein klassischer Lenkungszweck. Zusätzlich generiert sie Einnahmen, die teilweise an Bevölkerung und Wirtschaft rückverteilt werden. Dominierend ist aber die Lenkungswirkung, nicht der Fiskalzweck. Die Abgabe folgt dem Verursacherprinzip und setzt am Preis an, nicht am Verbot.', teilerklaerungen: [] },
  { id: '8340b5ff-4503-4442-93b8-becf0b54703d', fachbereich: 'VWL', musterlosung: 'Falsch. Eine Frankenaufwertung wirkt dämpfend auf das Preisniveau, nicht inflationär. Importe werden billiger (direkter Effekt), Schweizer Exportgüter für Ausländer teurer — die Exportnachfrage und damit die Konjunktur werden gedämpft (indirekter Effekt). Beide Mechanismen senken das Preisniveau. Die SNB muss deshalb bei anhaltender Aufwertung gelegentlich am Devisenmarkt intervenieren, um Deflationstendenzen zu verhindern.', teilerklaerungen: [] },
  { id: '8369fc17-f2f3-4d1e-b0a3-db3b56134055', fachbereich: 'VWL', musterlosung: 'Richtig. Die drei Ansätze betrachten denselben Sachverhalt aus drei Perspektiven — Produktion, Verteilung und Verwendung. Was produziert wird, fliesst als Einkommen zu und wird verwendet. Alle drei Ansätze müssen definitionsgemäss dasselbe Resultat ergeben. In der Praxis gibt es kleine statistische Differenzen, die aber als Ex-post-Korrekturen behandelt werden. Die ex-ante-Identität ist theoretisch zwingend.', teilerklaerungen: [] },
  { id: '837eb087-06d2-421e-9abb-e13edf197cd8', fachbereich: 'VWL', musterlosung: 'Richtig. Angebotsökonomen setzen wie die Klassiker auf die Selbstheilungskräfte des Marktes. Kurzfristige Konjunkturmassnahmen haben ihrer Ansicht nach keine nachhaltige Wirkung und verlangsamen notwendige Anpassungen. Stattdessen sollen gute Rahmenbedingungen — tiefe Steuern, flexible Arbeitsmärkte, Deregulierung — langfristig für Wachstum und Beschäftigung sorgen. Diese Sicht dominierte in den 1980er-Jahren unter Reagan und Thatcher.', teilerklaerungen: [] },
  { id: '845b0517-06be-40a3-bd18-110c6e4c2b8b', fachbereich: 'VWL', musterlosung: 'Falsch. Der Bäckermeister nutzt mehrere Produktionsfaktoren gleichzeitig. Seine körperliche Tätigkeit ist Arbeit, seine langjährige Erfahrung und Ausbildung zählen als Wissen oder Humankapital. Der Backofen ist Realkapital, Mehl und Wasser sind natürliche Ressourcen. Die moderne VWL unterscheidet vier Produktionsfaktoren — Arbeit allein wäre eine grobe Vereinfachung der realen Produktionsprozesse.', teilerklaerungen: [] },
  { id: '84e08247-ca6c-4360-9b6e-d2aeca6e5e49', fachbereich: 'VWL', musterlosung: 'Falsch. Die Mehrwertsteuer ist eine indirekte Steuer. Sie wird auf Markttransaktionen erhoben, unabhängig von den persönlichen Merkmalen der Käuferin oder des Käufers. Alle zahlen denselben Steuersatz auf ein bestimmtes Produkt — unabhängig vom Einkommen. Direkte Steuern wie Einkommens- und Vermögenssteuer berücksichtigen hingegen persönliche Verhältnisse und sind bei verschiedenen Personen unterschiedlich hoch.', teilerklaerungen: [] },
  { id: '873a2e07-6507-4dc9-aa93-6048b57fdb5b', fachbereich: 'VWL', musterlosung: 'Falsch. Elinor Ostrom zeigte gerade das Gegenteil. Lokale Gemeinschaften können Allmenderessourcen unter bestimmten Bedingungen selbst erfolgreich verwalten — ohne Privatisierung oder Verstaatlichung. Entscheidend sind klare Regeln, gegenseitige Überwachung, abgestufte Sanktionen und Beteiligung der Nutzer an den Entscheidungen. Für diese Erkenntnisse erhielt sie 2009 den Wirtschafts-Nobelpreis, als erste Frau überhaupt.', teilerklaerungen: [] },
  { id: '882d3f15-bdca-4def-9f5b-d90c7e4cdd1f', fachbereich: 'VWL', musterlosung: 'Richtig. Länder wie die Schweiz, Schweden und Grossbritannien haben ihr reales BIP gesteigert und gleichzeitig die territorialen CO₂-Emissionen pro Kopf gesenkt. Die Entkopplung ist damit nachweisbar. Ein Teil der Emissionen wurde allerdings ins Ausland verlagert — importierte Güter werden den Produktionsländern zugerechnet. Bei konsumbasierter Betrachtung ist die Bilanz deutlich weniger eindeutig.', teilerklaerungen: [] },
  { id: '899b9f18-0b2c-4bf5-b7aa-f3247d39e663', fachbereich: 'VWL', musterlosung: 'Richtig. Die Zentralbank legt das Geldangebot fest — unabhängig vom Zinssatz und der Kaufkraft. Deshalb verläuft die Geldangebotskurve im Geldmarktdiagramm senkrecht (vertikal). Die Geldnachfragekurve ist hingegen fallend, weil höhere Zinsen die Opportunitätskosten der Geldhaltung erhöhen. Der Gleichgewichtszins ergibt sich am Schnittpunkt — er ist der zentrale Steuerungshebel konventioneller Geldpolitik.', teilerklaerungen: [] },
  { id: '8b33c2a3-faa2-402a-a2a3-234207a2581e', fachbereich: 'VWL', musterlosung: 'Richtig. Nach Robert Nozicks naturrechtlichem Liberalismus haben Individuen ein natürliches Recht auf die durch ihre Arbeit erworbenen Erträge. Die Hauptaufgabe des Staates beschränkt sich auf den Schutz der Eigentumsrechte — ein Minimalstaat. Besteuerung wird in dieser Sicht als Eingriff in dieses Eigentumsrecht betrachtet und moralisch mit Diebstahl gleichgesetzt. Die Position ist eine extreme Variante des Liberalismus.', teilerklaerungen: [] },
  { id: '8bc21c06-8e70-4f74-9a51-c8e6441d9352', fachbereich: 'VWL', musterlosung: 'Falsch. Das BIP pro Kopf misst den materiellen Wohlstand, nicht die Lebensqualität. Es ignoriert Umweltschäden, Einkommensverteilung, Gesundheit, Bildung, Freizeit und soziale Beziehungen. Mehr Autounfälle oder höherer Medikamentenverbrauch erhöhen das BIP, senken aber die Lebensqualität. Alternative Indikatoren wie der Human Development Index oder der Better Life Index versuchen, diese Dimensionen abzubilden.', teilerklaerungen: [] },
  { id: '8d617287-4fbf-47e7-8667-a20307a42cf1', fachbereich: 'VWL', musterlosung: 'Richtig. Das BIP misst nur die Wertschöpfung jeder Produktionsstufe, nicht den gesamten Umsatz. Würden alle Verkaufswerte addiert, wären zugekaufte Vorleistungen mehrfach enthalten — das BIP wäre künstlich aufgebläht. Durch den Abzug der Vorleistungen bleibt nur der neu geschaffene Wert. Diese Bereinigung ist zentral für die Vergleichbarkeit und Aussagekraft des BIP.', teilerklaerungen: [] },
  { id: '90244c59-9ef9-4cbc-b4b4-59016c86db1e', fachbereich: 'VWL', musterlosung: 'Richtig. Das Beyond-Growth-Modell der OECD steht zwischen Green Growth und Degrowth. Es lehnt reines BIP-Wachstum als oberstes Ziel ab und fordert neue Indikatoren und wirtschaftspolitische Ziele — Nachhaltigkeit, Wohlbefinden, Gerechtigkeit und Resilienz. Ein bewusstes Schrumpfen der Wirtschaft wird nicht angestrebt. Stattdessen soll die Wirtschaft neu ausgerichtet werden, um mehrere Ziele gleichzeitig zu verfolgen.', teilerklaerungen: [] },
  { id: '93be6254-5174-492d-9e44-8b35c75bf986', fachbereich: 'VWL', musterlosung: 'Richtig. Auf der 45-Grad-Linie entspricht die Zahl der offenen Stellen genau der Zahl der Arbeitslosen. Diese Punkte bilden die gleichgewichtige oder Sockelarbeitslosigkeit ab — hier gibt es für jeden Arbeitslosen theoretisch eine offene Stelle. Die Arbeitslosigkeit ist friktionell und strukturell, nicht konjunkturell. Durch Arbeitsmarktreformen oder Qualifizierung kann die Sockelarbeitslosigkeit langfristig gesenkt werden.', teilerklaerungen: [] },
  { id: '94a534f8-ca25-4dd5-ae24-eb8732be3cc6', fachbereich: 'VWL', musterlosung: 'Falsch. Die Fiskalquote der Schweiz liegt bei rund 28 Prozent des BIP und damit deutlich unter dem OECD-Durchschnitt von etwa 35 Prozent. Die Schweiz hat im internationalen Vergleich eine tiefe Steuerbelastung. Gründe sind der schlanke Staatsapparat, föderale Aufgabenteilung und private Finanzierung wesentlicher Bereiche wie Gesundheits- und Altersvorsorge. Länder wie Frankreich oder Schweden liegen bei über 45 Prozent.', teilerklaerungen: [] },
  { id: '956f98d3-4756-4a77-81ce-d9ac69e3b534', fachbereich: 'VWL', musterlosung: 'Richtig. Die Recheneinheitsfunktion erlaubt es, den Wert unterschiedlichster Güter in einer gemeinsamen Einheit auszudrücken. Statt unzählige Tauschverhältnisse zu kennen — wie viele Brote ein Haarschnitt wert ist, wie viele Haarschnitte ein Kinoticket — genügt der Preis jedes Gutes in Franken. Diese Vereinheitlichung reduziert die Informationskosten im Wirtschaftsverkehr drastisch und ermöglicht effiziente Preissignale.', teilerklaerungen: [] },
  { id: '97808bd2-bc0b-42cc-8cb7-d669f61ece17', fachbereich: 'VWL', musterlosung: 'Falsch. In einer modernen arbeitsteiligen Wirtschaft produzieren wir fast nichts von dem, was wir täglich konsumieren, selbst. Eisenhut regt zum Nachdenken an: Wie viele Güter stellen wir selber her? Fast alles wird von spezialisierten Unternehmen produziert und über Märkte getauscht. Wir sind eingebunden in ein dichtes Netz der Arbeitsteilung und Spezialisierung — das erhöht die Produktivität enorm.', teilerklaerungen: [] },
]

async function main() {
  const stateRaw = await fs.readFile(STATE, 'utf8')
  const state = JSON.parse(stateRaw)

  const outLines = []
  let done = 0
  let skip = 0
  const skipped = []
  const now = new Date().toISOString()

  for (const u of updates) {
    const existing = state.fragen[u.id]
    if (existing && existing.status === 'done') {
      console.warn(`skip already done: ${u.id}`)
      continue
    }
    outLines.push(JSON.stringify(u))
    state.fragen[u.id] = {
      status: 'done',
      zeitpunkt: now,
      teile: u.teilerklaerungen.length,
    }
    done++
  }

  await fs.appendFile(OUT, outLines.join('\n') + '\n', 'utf8')
  state.verarbeitet = Object.values(state.fragen).filter((x) => x.status === 'done').length
  state.letzteSession = now
  await fs.writeFile(STATE, JSON.stringify(state, null, 2), 'utf8')

  console.log(`Session 21 done.`)
  console.log(`  Verarbeitet diese Session: ${done + skip} (done=${done}, skip=${skip})`)
  console.log(`  Total: ${state.verarbeitet}/${state.totalFragen} (${((state.verarbeitet / state.totalFragen) * 100).toFixed(1)}%)`)
  if (skipped.length) console.log(`  Skip-Fragen: ${skipped.join(', ')}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
