#!/usr/bin/env node
/**
 * Session 22: 50 VWL/richtigfalsch-Fragen.
 * Erste Hälfte des Batches nach Fachbereich → Typ → ID.
 * Keine Teilerklärungen (aussagen haben keine IDs in der DB).
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'fragen-updates.jsonl')
const STATE = path.join(__dirname, 'state.json')

const updates = [
  { id: '990784f5-62e0-4931-8e98-6f5c85526878', fachbereich: 'VWL', musterlosung: 'Falsch. Modernes Wirtschaftswachstum bedeutet zunehmend «immer besser» statt nur «immer mehr» — effizientere Geräte, höhere Qualität und sparsamere Technologien lassen die Wertschöpfung pro Einheit steigen. Das BIP misst die Wertschöpfung, also den Wert der Güter, nicht die produzierte Menge. Qualitative Verbesserungen tragen somit genauso zum Wachstum bei wie reine Mengenausweitung.', teilerklaerungen: [] },
  { id: '9a668b91-c207-4460-a289-c175db6f3868', fachbereich: 'VWL', musterlosung: 'Richtig. Das Krankenversicherungsgesetz (KVG) schreibt für die Grundversicherung ein einheitliches Leistungspaket vor. Jede Kasse setzt deshalb pro Region und Altersgruppe eine einheitliche Kopfprämie an, unabhängig von Einkommen oder Gesundheitszustand. Personen in bescheidenen wirtschaftlichen Verhältnissen erhalten von den Kantonen Prämienverbilligungen, um die soziale Last abzufedern.', teilerklaerungen: [] },
  { id: '9da9ba94-823b-4d15-bf25-01f2e01f7b33', fachbereich: 'VWL', musterlosung: 'Richtig. Wird nur die Hälfte entnommen, regeneriert sich der Bestand durch die Verdopplung wieder vollständig — der Ertrag bleibt über viele Runden konstant hoch. Wird mehr als die Hälfte gefischt, schrumpft der Bestand und der nachhaltig mögliche Ertrag sinkt. Das Spiel illustriert die Allmendeproblematik: Individuelle Kurzfrist-Rationalität führt ohne Kooperation zur Überfischung.', teilerklaerungen: [] },
  { id: '9de34444-fc2e-4fbe-baf8-96dc5d2b4a1b', fachbereich: 'VWL', musterlosung: 'Richtig. Nimmt der Staat grosse Mengen Kapital am Finanzmarkt auf, konkurriert er mit privaten Investoren um begrenztes Sparvolumen. Da der Staat als sicherer Schuldner gilt, fliessen die Mittel bevorzugt zu ihm, wodurch Zinsen steigen und private Investitionen verdrängt werden. Dieser Crowding-out-Effekt gilt als ein zentrales Argument gegen dauerhafte Staatsverschuldung.', teilerklaerungen: [] },
  { id: '9e651728-00be-4329-8578-32019a9bccec', fachbereich: 'VWL', musterlosung: 'Falsch. Buchgeld ist eine Forderung gegenüber der kontoführenden Geschäftsbank, nicht gegenüber der Zentralbank. Bei einer Bankpleite ist das Guthaben nur über die Einlagensicherung bis 100\'000 Franken geschützt. Bargeld hingegen ist eine direkte Forderung an die SNB und damit insolvenzfest. Sicherheit und Ausfallrisiko hängen entscheidend davon ab, wer der Schuldner ist.', teilerklaerungen: [] },
  { id: '9f97fc39-90da-410f-8322-75197704e632', fachbereich: 'VWL', musterlosung: 'Richtig. Einkommens-, Vermögens-, Mehrwert- und Gewinnsteuer dienen primär dem Fiskalzweck: Sie finanzieren die Staatsaufgaben. Neben dem Fiskalzweck gibt es den Lenkungszweck (etwa die CO₂-Abgabe) und den Umverteilungszweck (progressive Tarife). Bei den fiskalisch ergiebigsten Schweizer Steuern überwiegt jedoch eindeutig die Einnahmefunktion — Lenkung und Umverteilung sind Nebenzwecke.', teilerklaerungen: [] },
  { id: 'a1d3a7b6-de85-4b15-8af5-620a320b0da2', fachbereich: 'VWL', musterlosung: 'Falsch. Pareto-Effizienz trifft keine Aussage über Gerechtigkeit — sie verlangt nur, dass niemand mehr besser gestellt werden kann, ohne einen anderen schlechter zu stellen. Auch eine Verteilung, bei der eine Person alles und alle anderen nichts besitzen, kann pareto-effizient sein. Effizienz ist ein Kriterium für Verschwendungsfreiheit, Gerechtigkeit dagegen ein normativer Verteilungsmassstab.', teilerklaerungen: [] },
  { id: 'a256b3f9-c005-4875-a1c8-017b7ef076d9', fachbereich: 'VWL', musterlosung: 'Richtig. Direkte Steuern wie die Einkommens- und Vermögenssteuer knüpfen an persönlichen Merkmalen der steuerpflichtigen Person an: Einkommen, Vermögen, Familienstand oder Abzüge. Deshalb fällt die Steuerschuld bei verschiedenen Personen mit gleichen Bruttoeinkünften unterschiedlich aus. Indirekte Steuern wie die Mehrwertsteuer sind dagegen anonym und unabhängig von der persönlichen Situation des Zahlers.', teilerklaerungen: [] },
  { id: 'a4274b38-8c2a-410e-8299-fb31059b2992', fachbereich: 'VWL', musterlosung: 'Richtig. Wer sich spezialisiert, produziert nur wenige Güter und muss alles andere durch Tausch beschaffen. Arbeitsteilung und Tausch sind deshalb zwei Seiten derselben Medaille: Ohne Tauschbereitschaft wäre Spezialisierung wirtschaftlich sinnlos. Geld erleichtert den Tausch, weil es die doppelte Koinzidenz der Bedürfnisse überwindet und damit die Produktivitätsgewinne der Arbeitsteilung erst nutzbar macht.', teilerklaerungen: [] },
  { id: 'a43cc1cf-e232-4fe0-bf17-014862e03303', fachbereich: 'VWL', musterlosung: 'Richtig. Kreditkarten, Debitkarten und mobile Zahlungsdienste wie Twint sind Zahlungsinstrumente, nicht Geld. Sie übertragen Buchgeld von einem Konto auf ein anderes, schaffen aber selbst kein neues Geld. Geld im engeren Sinn ist Bargeld (Notenbankgeld) und Buchgeld (Bankguthaben); Karten sind lediglich der technische Kanal, über den Buchgeld bewegt wird.', teilerklaerungen: [] },
  { id: 'a4d131de-75ea-4556-9465-046e3eb32325', fachbereich: 'VWL', musterlosung: 'Falsch. In der volkswirtschaftlichen Systematik sind nur Arbeit, Boden und Realkapital Produktionsfaktoren. Geld ist lediglich ein Tauschmittel, mit dem diese Faktoren beschafft werden — Maschinen kaufen oder Löhne zahlen. Der Begriff «Realkapital» betont bewusst die Abgrenzung zum Geldkapital: Produktionsfaktor ist nicht das Bankguthaben, sondern das dafür erworbene Sachkapital.', teilerklaerungen: [] },
  { id: 'a5665b17-8463-400d-b896-55e6863fd652', fachbereich: 'VWL', musterlosung: 'Richtig. Die sechs Ziele des magischen Sechsecks stehen teilweise in Konflikt zueinander: Wirtschaftswachstum kann die Umweltqualität beeinträchtigen, Preisstabilität und Vollbeschäftigung sind kurzfristig nicht immer gleichzeitig erreichbar. «Magisch» heisst deshalb: Eine gleichzeitige, vollständige Erfüllung aller sechs Ziele ist schwierig bis unmöglich. Wirtschaftspolitik muss zwischen Zielen abwägen und Prioritäten setzen.', teilerklaerungen: [] },
  { id: 'a778be1d-2274-4ed7-925c-3018ba43b143', fachbereich: 'VWL', musterlosung: 'Richtig. Die Schuldenbremse verbietet Defizite nicht generell, sondern verlangt einen Ausgleich über den Konjunkturzyklus hinweg. In Rezessionen sind Defizite sogar erwünscht, weil sinkende Einnahmen und steigende Transferleistungen als automatische Stabilisatoren wirken. Im Aufschwung entstehen entsprechend Überschüsse, die die Defizite ausgleichen. Damit wird prozyklische Finanzpolitik vermieden.', teilerklaerungen: [] },
  { id: 'a78ea807-fccc-4ebb-aebf-ada8086f2c32', fachbereich: 'VWL', musterlosung: 'Falsch. Eine Arbeitslosenquote von null Prozent ist in einer dynamischen Marktwirtschaft weder realistisch noch erstrebenswert. Friktionelle Arbeitslosigkeit ist unvermeidbar und sogar nützlich: Sie zeigt, dass Personen zwischen Stellen wechseln und der Strukturwandel funktioniert. Das Ziel heisst deshalb Vollbeschäftigung — eine tiefe, aber positive Quote, in der Schweiz traditionell um 2 bis 3 Prozent.', teilerklaerungen: [] },
  { id: 'a7a1eeed-1ba4-4985-937b-7690a06fb080', fachbereich: 'VWL', musterlosung: 'Richtig. Nach den Zahlen des BFS entfallen auf die Berufliche Vorsorge rund 39 Prozent, auf die AHV (inklusive Ergänzungsleistungen) rund 25 Prozent und auf die Krankenversicherung rund 17 Prozent der Sozialversicherungseinnahmen — zusammen etwa 81 Prozent. Diese drei Zweige bilden damit das Rückgrat des schweizerischen Sozialversicherungssystems. Die übrigen Zweige (IV, ALV, UV, EO, FamZG) teilen sich die restlichen 19 Prozent.', teilerklaerungen: [] },
  { id: 'a829eb54-3b99-4875-89ba-716e28f6a5ed', fachbereich: 'VWL', musterlosung: 'Falsch. Der Utilitarismus zielt nicht auf Gleichverteilung, sondern auf die Maximierung der gesellschaftlichen Wohlfahrt (Nutzensumme). Aus der Annahme abnehmenden Grenznutzens folgt, dass Umverteilung zu Ärmeren die Nutzensumme erhöhen kann — aber die optimale Verteilung ist dort erreicht, wo die Grenznutzen aller gleich sind, nicht dort, wo alle gleich viel besitzen.', teilerklaerungen: [] },
  { id: 'aa5c6a22-ed3e-4c7b-aced-80de11f461ad', fachbereich: 'VWL', musterlosung: 'Falsch. Die Modern Monetary Theory argumentiert gegenteilig zum Monetarismus: Ein Staat mit eigener Währung könne sich praktisch unbegrenzt verschulden und die Geldmenge ausweiten; die einzige Grenze sei die Inflation. Der Monetarismus hingegen warnt vor einer unkontrollierten Geldmengenausweitung und sieht die Geldmengensteuerung als zentrales Instrument der Preisstabilität. Die beiden Ansätze sind weitgehend unvereinbar.', teilerklaerungen: [] },
  { id: 'aa843ca1-d6ed-4a01-a21d-10a7a2b3a3b8', fachbereich: 'VWL', musterlosung: 'Richtig. Rund 59 Prozent der Bundesausgaben fliessen als Subventionen und Transferzahlungen an Dritte. Davon entfallen etwa 45 Prozent auf die soziale Wohlfahrt, 17 Prozent auf Bildung und Forschung und 15 Prozent auf den Verkehr. Der Bund ist damit weit überwiegend eine Umverteilungsinstanz; der Eigenverbrauch für Verwaltung, Landesverteidigung und Diplomatie ist relativ klein.', teilerklaerungen: [] },
  { id: 'aacbd9b3-68b0-4376-8b0f-336132d21111', fachbereich: 'VWL', musterlosung: 'Falsch. Auch die Schweiz erfüllt die dritte Richtlinie nicht: Die Staatsausgaben sind in den letzten Jahrzehnten stärker gewachsen als das BIP — ein Muster, das Wagners Gesetz beschreibt. Zunehmende Aufgaben im Sozial- und Bildungsbereich sowie demografisch bedingte Mehrausgaben treiben die Staatsquote. Die Regel gilt damit eher als Idealbild denn als eingehaltene Praxis.', teilerklaerungen: [] },
  { id: 'ab7caae7-2875-4203-bc18-c1c192eb3d8c', fachbereich: 'VWL', musterlosung: 'Richtig. Personalausgaben und Renten sind indexgebunden und lassen sich kurzfristig nicht kürzen. Einige Ausgabenkategorien steigen in Rezessionen sogar — insbesondere Arbeitslosenentschädigungen. Gleichzeitig brechen die Einnahmen aus Einkommens- und Gewinnsteuern ein. Dieser Schereneffekt zwischen rigiden Ausgaben und sinkenden Einnahmen verstärkt konjunkturelle Defizite automatisch und wirkt als Stabilisator.', teilerklaerungen: [] },
  { id: 'ac014d71-3714-4899-bc7b-066f92f8fc9d', fachbereich: 'VWL', musterlosung: 'Falsch. Luft ist zwar in vielen Situationen ein freies Gut, nicht aber immer. Saubere Luft in stark verschmutzten Städten wird zum knappen, wirtschaftlichen Gut — etwa wenn Luftfilter nachgefragt werden. Auch Atemluft unter Wasser ist knapp und wird in Tauchflaschen bereitgestellt. Ob ein Gut frei oder wirtschaftlich ist, hängt vom Verhältnis zwischen Nachfrage und Verfügbarkeit ab.', teilerklaerungen: [] },
  { id: 'acb53421-6724-46c5-b93c-5b7a9c2075e1', fachbereich: 'VWL', musterlosung: 'Richtig. Die doppelte Koinzidenz der Bedürfnisse («double coincidence of wants») ist das Kernproblem der reinen Tauschwirtschaft: Beide Tauschpartner müssen gleichzeitig genau das besitzen, was der andere braucht. Das macht Tausch aufwändig und begrenzt die Arbeitsteilung. Geld löst dieses Problem, weil es als allgemein akzeptiertes Zwischentauschmittel die Suche nach passenden Tauschpartnern überflüssig macht.', teilerklaerungen: [] },
  { id: 'af72a1bc-c8c5-40ed-bc3d-6e90d319bc27', fachbereich: 'VWL', musterlosung: 'Richtig. Seit September 2014 werden in der Schweiz illegale Aktivitäten wie Drogenhandel und Prostitution geschätzt und ins BIP einbezogen. Hintergrund ist eine Anpassung an das europäische Volkswirtschaftliche Gesamtrechnungssystem (ESVG 2010). Ziel ist die internationale Vergleichbarkeit des BIP — das Ergebnis hat den Wert des Schweizer BIP um weniger als ein Prozent erhöht.', teilerklaerungen: [] },
  { id: 'b0de05cf-4469-4cb4-8700-e91ea89820f5', fachbereich: 'VWL', musterlosung: 'Falsch. Ein Anstieg des nominalen BIP kann allein auf Inflation zurückzuführen sein: Die produzierte Gütermenge bleibt gleich, nur die Preise steigen. Erst das reale BIP, das die Preisveränderung herausrechnet, zeigt echtes Wirtschaftswachstum. Für Wohlstandsvergleiche über die Zeit ist deshalb immer das reale BIP massgebend, nicht das nominale.', teilerklaerungen: [] },
  { id: 'b2550e9d-a28b-4eb8-a407-f2699420f5bf', fachbereich: 'VWL', musterlosung: 'Falsch. Ökonomische Prognosen sind schwierig, weil die Wirkungsketten vielschichtig und die Einflussfaktoren kaum vollständig erfassbar sind. Menschen reagieren zudem unvorhersehbar auf Anreize, und Erwartungen wirken auf das prognostizierte Ergebnis zurück. Deshalb veröffentlichen SECO, KOF und SNB Prognosen stets mit Unsicherheitsbändern und revidieren sie regelmässig. Die VWL arbeitet mit Wahrscheinlichkeiten, nicht mit Gewissheiten.', teilerklaerungen: [] },
  { id: 'b48d246e-2e22-40d8-81cf-89240b5409d4', fachbereich: 'VWL', musterlosung: 'Falsch. Das Gefangenendilemma entsteht gerade, weil alle Beteiligten rational und eigennützig handeln. Nicht-Kooperation ist die dominante Strategie — sie liefert unabhängig vom Verhalten des anderen das bessere individuelle Ergebnis. Individuelle Rationalität führt dabei zu kollektiver Irrationalität. Das Problem liegt in der Struktur der Situation, nicht in Denkfehlern oder Irrationalität der Akteure.', teilerklaerungen: [] },
  { id: 'b58ea26d-e0e7-41e4-a4cd-c5860c9fed86', fachbereich: 'VWL', musterlosung: 'Richtig. In der Schweiz — wie in den meisten Ländern — ist die Vermögensverteilung deutlich schiefer als die Einkommensverteilung. Das reichste Prozent hält einen überproportionalen Anteil am Gesamtvermögen. Ursachen sind Erbschaften, Kapitaleinkommen und die kumulative Wirkung des Zinseszinses. Einkommen kann jeder verdienen; Vermögen aufzubauen braucht Zeit, Ersparnisse und häufig Vererbung.', teilerklaerungen: [] },
  { id: 'b6f82d7f-9f0e-48ea-9ae3-0c39d25e728c', fachbereich: 'VWL', musterlosung: 'Richtig. In der Hochkonjunktur werden Arbeit und Kapital überdurchschnittlich stark ausgelastet, Überstunden und zusätzliche Schichten sind üblich. Die tatsächliche Wirtschaftsleistung liegt damit über dem Produktionspotenzial bei Normalauslastung. Typische Begleiterscheinungen sind steigende Preise und sinkende Arbeitslosigkeit. Auf den Boom folgt früher oder später ein Abschwung, weil die Überhitzung nicht dauerhaft tragbar ist.', teilerklaerungen: [] },
  { id: 'b7f2fd27-fa95-46ed-b02b-beb3c5035d5c', fachbereich: 'VWL', musterlosung: 'Richtig. Die Kreditrückzahlung ist der umgekehrte Vorgang zur Geldschöpfung: Das bei der Kreditvergabe als Buchgeld geschaffene Guthaben verschwindet bei der Tilgung wieder aus der Geldmenge. Geldschöpfung und Geldvernichtung sind damit zwei Seiten desselben Prozesses. Weil Banken laufend neue Kredite vergeben und alte zurückerhalten, ist die Geldmenge eine dynamische Grösse.', teilerklaerungen: [] },
  { id: 'ba78d395-ba03-425e-ae6b-191950f184e7', fachbereich: 'VWL', musterlosung: 'Richtig. Güter sind nicht naturgegeben klassifiziert, sondern hängen von Institutionen und Technik ab. Fischbestände können durch Fangquoten und Lizenzen aus dem Allmendegut zum Klubgut werden. Eine frei zugängliche Strasse kann zur Mautstrasse werden. Rivalität im Konsum und Ausschliessbarkeit sind also steuerbare Eigenschaften, nicht unveränderliche Merkmale.', teilerklaerungen: [] },
  { id: 'bb73d3ed-0938-4c50-a221-11d63d3a50c0', fachbereich: 'VWL', musterlosung: 'Falsch. Ein Markt ist der Ort des freiwilligen Tauschs zwischen Angebot und Nachfrage — er kann auch virtuell sein, etwa als Online-Marktplatz oder elektronische Börse. Entscheidend ist das Aufeinandertreffen von Kauf- und Verkaufswünschen sowie die Preisbildung daraus. Die räumliche Dimension ist zweitrangig: Ebay, SIX und Devisenmärkte sind Märkte ohne physischen Ort.', teilerklaerungen: [] },
  { id: 'bcbd1813-cb04-4295-9e83-0968cd95b157', fachbereich: 'VWL', musterlosung: 'Falsch. Bei asymmetrischer Information weiss der Versicherte mehr über sein eigenes Risiko als die Versicherung — zum Beispiel kennt der Autofahrer seinen Fahrstil besser als sein Versicherer. Dieses Ungleichgewicht ist die Ursache sowohl für adverse Selektion (schlechte Risiken versichern sich überproportional) als auch für Moral Hazard (Verhaltensänderung nach Vertragsabschluss).', teilerklaerungen: [] },
  { id: 'bf1df2b0-98a5-4258-9f71-d549d7a383ec', fachbereich: 'VWL', musterlosung: 'Richtig. Konjunkturelle Defizite wirken als automatische Stabilisatoren: In der Rezession stützen sinkende Steuereinnahmen und steigende Transferleistungen die gesamtwirtschaftliche Nachfrage. Im Aufschwung verschwinden die Defizite dank wieder steigender Einkommen und Gewinne. Problematisch sind dagegen strukturelle Defizite, weil sie unabhängig von der Konjunktur bestehen und die Staatsverschuldung dauerhaft erhöhen.', teilerklaerungen: [] },
  { id: 'bf3597e8-f4c5-48b8-bca6-d5ea88c7c998', fachbereich: 'VWL', musterlosung: 'Richtig. Bei Quellensteuern wird die Steuer direkt beim Schuldner der steuerpflichtigen Leistung abgezogen, bevor die Zahlung den Empfänger erreicht. Ein bekanntes Beispiel ist die Verrechnungssteuer von 35 Prozent auf Kapitalerträge, die von der Bank einbehalten und an die ESTV abgeliefert wird. Das Verfahren sichert die Steuererhebung und erschwert Steuerhinterziehung.', teilerklaerungen: [] },
  { id: 'bf856a12-2932-4b8c-9a8d-d8781fb52cad', fachbereich: 'VWL', musterlosung: 'Richtig. Der Automatische Informationsaustausch wurde 2014 von der OECD lanciert und umfasst inzwischen über 100 Staaten. Teilnehmende Finanzinstitute melden Salden, Zinsen und Dividenden ausländischer Kundinnen und Kunden an die Steuerbehörden der Heimatstaaten. Das Bankgeheimnis im grenzüberschreitenden Kontext ist damit faktisch aufgehoben, Steuerhinterziehung über ausländische Konten deutlich erschwert.', teilerklaerungen: [] },
  { id: 'c360c6eb-2274-40ae-a8ef-35e5b3d090cb', fachbereich: 'VWL', musterlosung: 'Falsch. Arbeitskräftewanderungen sind fester Bestandteil einer offenen Marktwirtschaft und können Wohlstand erhöhen. Sind Zuwanderer Komplemente — also mit ergänzenden Qualifikationen —, steigern sie die Produktivität und die Löhne der Einheimischen. Nur wenn sie Substitute mit gleichen Qualifikationen sind, entsteht Konkurrenz auf dem Arbeitsmarkt. Pauschale Konkurrenzbehauptungen verkennen diese ökonomische Differenzierung.', teilerklaerungen: [] },
  { id: 'c51ea536-119b-414e-8644-926d7541c245', fachbereich: 'VWL', musterlosung: 'Richtig. Strenger Kündigungsschutz kann Unternehmen bei Neueinstellungen vorsichtig machen, weil Entlassungen später schwierig und teuer werden. Im Insider-Outsider-Modell profitieren die bereits Beschäftigten, während Arbeitslose schlechtere Einstellungschancen haben. Das ist ein klassisches Beispiel für Staatsversagen durch unbeabsichtigte Nebenwirkungen: Gut gemeinte Schutzregeln erschweren den Arbeitsmarktzugang.', teilerklaerungen: [] },
  { id: 'c6f13c2c-9382-45fd-b2dc-3510637bbfb4', fachbereich: 'VWL', musterlosung: 'Richtig. Der Schweizer Nominallohnindex ist seit seiner Einführung kein einziges Jahr gesunken. Dieser Befund bestätigt die Theorie der nach unten starren Nominallöhne: Arbeitgeber kürzen Nominallöhne sehr selten, weil Widerstand und Demotivation der Belegschaft hoch wären. Reallohnkürzungen entstehen deshalb meist indirekt über Inflation, nicht über offene Lohnreduktionen.', teilerklaerungen: [] },
  { id: 'c7560e3d-c169-4f15-8490-61633be91435', fachbereich: 'VWL', musterlosung: 'Falsch. Kehrichtsackgebühren reduzieren zwar die Anzahl Säcke, haben aber typische Nebenwirkungen: Die Säcke werden stärker gestopft, es entstehen wilde Deponien, und Abfall wird in Nachbargemeinden gebracht. Menschen reagieren auf Anreize oft kreativ, nicht nur im erwünschten Sinn. Eine Politik muss deshalb mögliche Ausweichreaktionen mitdenken, wenn sie über Preise steuert.', teilerklaerungen: [] },
  { id: 'c78be264-e432-4934-a0cd-c0e99e300e7a', fachbereich: 'VWL', musterlosung: 'Falsch. Staatsversagen bedeutet nicht, dass Staatseingriffe generell zu unterlassen sind. Der Begriff beschreibt nur, dass staatliche Eingriffe ebenfalls Kosten und Risiken haben können. Bei echtem Marktversagen kann ein gut gestalteter Eingriff die Wohlfahrt erhöhen. Die relevante Frage lautet immer: Ist das Ergebnis mit Eingriff besser als ohne? — nicht: Soll der Staat sich raushalten?', teilerklaerungen: [] },
  { id: 'c791f638-59ff-45b4-8423-c4fe4dc6ebd8', fachbereich: 'VWL', musterlosung: 'Richtig. Ob eine Steuer formal beim Anbieter oder beim Nachfrager erhoben wird, ist für die tatsächliche Lastverteilung unerheblich. Entscheidend sind die Preiselastizitäten von Angebot und Nachfrage. Die weniger elastische Marktseite trägt den grösseren Teil der Steuer, weil sie weniger ausweichen kann. Dieses Prinzip ist als Äquivalenz der Steuerinzidenz bekannt.', teilerklaerungen: [] },
  { id: 'c7d83d4e-a074-467b-bbd5-ac5e2082e236', fachbereich: 'VWL', musterlosung: 'Richtig. Im Januar 2015 führte die SNB auf Sichtguthaben einen Negativzins von minus 0.75 Prozent ein. Ziel war, Frankenanlagen unattraktiver zu machen und den Aufwertungsdruck nach der Aufhebung des Euro-Mindestkurses zu dämpfen. Der Negativzins übertrug sich auf Geld- und Kapitalmarktzinsen und gilt als Kernstück der unkonventionellen Geldpolitik der SNB bis 2022.', teilerklaerungen: [] },
  { id: 'c891e88e-c3f2-485e-acf1-a32b3e9fb1bf', fachbereich: 'VWL', musterlosung: 'Richtig. Im Spiel BOB kommt X in keinem der zu bildenden Wörter vor und ist deshalb zum Wortbilden wertlos. Gerade dadurch eignet es sich als Tauschmittel: Alle akzeptieren es, weil niemand es selbst direkt verbraucht. X ist zudem haltbar, knapp und einheitlich — Eigenschaften, die auch reales Geld auszeichnen. Das Spiel illustriert die drei Geldfunktionen.', teilerklaerungen: [] },
  { id: 'c9cc1424-6bc4-42b9-9262-9d0d8e44b428', fachbereich: 'VWL', musterlosung: 'Richtig. Warengeld wie Goldmünzen hat einen intrinsischen Materialwert und behält so auch ausserhalb seiner Geldfunktion einen Nutzen. Papiergeld dagegen ist fast wertlos — eine 100-Franken-Note kostet in der Herstellung wenige Rappen. Sein Wert beruht allein auf dem Vertrauen in die Notenbank und die Akzeptanz im Wirtschaftskreislauf. Vertrauen ist deshalb bei Papiergeld konstitutiv.', teilerklaerungen: [] },
  { id: 'ca7cd5db-b886-41a5-a541-b771a28d7be3', fachbereich: 'VWL', musterlosung: 'Falsch. Japan und die Schweiz zählen zu den wohlhabendsten Volkswirtschaften der Welt, obwohl sie kaum über natürliche Ressourcen verfügen. Entscheidend für ein hohes BIP pro Kopf sind Humankapital, Forschung und Entwicklung, technischer Fortschritt sowie stabile Institutionen und Rechtssicherheit. Ressourcenreichtum kann sogar schaden, wenn er zu Rentenökonomien und Korruption führt («Ressourcenfluch»).', teilerklaerungen: [] },
  { id: 'cfffb667-a65f-44fb-acd7-9f8fc6d55a41', fachbereich: 'VWL', musterlosung: 'Falsch. Maslow beschreibt zwar eine hierarchische Ordnung der Bedürfnisse, in der Praxis streben Menschen aber nach gleichzeitiger Erfüllung aus verschiedenen Ebenen. Selbstverwirklichung und Anerkennung werden gesucht, obwohl Grundbedürfnisse nicht vollständig abgedeckt sind. Die strikte Stufenabfolge ist empirisch nicht haltbar und dient eher als heuristisches Ordnungsschema denn als Verhaltensgesetz.', teilerklaerungen: [] },
  { id: 'd083733c-290c-4bb7-a992-a06d421ab880', fachbereich: 'VWL', musterlosung: 'Falsch. Beim Emissionshandel legt der Staat nur die Gesamtmenge an Emissionsrechten fest («Cap»). Der Preis pro Zertifikat bildet sich anschliessend auf einem Markt durch Angebot und Nachfrage. Sind Vermeidungskosten hoch, steigt der Preis; sind sie tief, fällt er. Das System verbindet damit eine mengenmässige Obergrenze mit marktgetriebener Preisfindung — Cap-and-Trade statt staatlicher Preisfestsetzung.', teilerklaerungen: [] },
  { id: 'd24cdf37-be34-4262-b3ef-8c50b2d0fb90', fachbereich: 'VWL', musterlosung: 'Richtig. Kurzarbeit überbrückt vorübergehende Nachfragerückgänge, ohne dass Unternehmen Personal entlassen müssen. Die Arbeitslosenversicherung übernimmt rund 80 Prozent des Verdienstausfalls für die ausgefallenen Stunden. So bleiben die Arbeitsverhältnisse bestehen, und die Unternehmen müssen bei der Erholung keine neuen Fachkräfte suchen. Das Instrument hat sich besonders in der Finanzkrise und während der Pandemie bewährt.', teilerklaerungen: [] },
  { id: 'd3cba471-2475-4c9d-99cc-4e39817786e3', fachbereich: 'VWL', musterlosung: 'Falsch. Das Crowding-out-Argument hat für die Schweiz nur geringe praktische Relevanz. Der private Sektor weist einen chronischen Sparüberschuss auf, am Kapitalmarkt steht mehr Geld zur Verfügung als inländisch nachgefragt wird. Staatliche Kreditaufnahme verdrängt deshalb keine privaten Investitionen in nennenswertem Ausmass. In anderen Ländern, etwa den USA, ist die Situation umgekehrt.', teilerklaerungen: [] },
  { id: 'd3dceda1-e29f-4306-98b6-e176daa39be1', fachbereich: 'VWL', musterlosung: 'Richtig. Normen und Standards dienen oft dem Konsumentenschutz, können aber gleichzeitig als Marktzutrittsbarriere wirken. Kleinere oder ausländische Anbieter können die Anforderungen nicht immer erfüllen, wodurch die Auswahl sinkt und die Preise steigen. Die Regulierung schützt damit etablierte Anbieter vor Wettbewerb. Gut gestaltete Normen berücksichtigen deshalb ihren Einfluss auf den Marktzugang mit.', teilerklaerungen: [] },
]

async function main() {
  const stateRaw = await fs.readFile(STATE, 'utf8')
  const state = JSON.parse(stateRaw)

  const outLines = []
  let done = 0
  let skip = 0
  const skipped = []
  const now = new Date().toISOString()

  for (const u of updates) {
    const existing = state.fragen[u.id]
    if (existing && existing.status === 'done') {
      console.warn(`skip already done: ${u.id}`)
      continue
    }
    outLines.push(JSON.stringify(u))
    state.fragen[u.id] = {
      status: 'done',
      zeitpunkt: now,
      teile: u.teilerklaerungen.length,
    }
    done++
  }

  await fs.appendFile(OUT, outLines.join('\n') + '\n', 'utf8')
  state.verarbeitet = Object.values(state.fragen).filter((x) => x.status === 'done').length
  state.letzteSession = now
  await fs.writeFile(STATE, JSON.stringify(state, null, 2), 'utf8')

  console.log(`Session 22 done.`)
  console.log(`  Verarbeitet diese Session: ${done + skip} (done=${done}, skip=${skip})`)
  console.log(`  Total: ${state.verarbeitet}/${state.totalFragen} (${((state.verarbeitet / state.totalFragen) * 100).toFixed(1)}%)`)
  if (skipped.length) console.log(`  Skip-Fragen: ${skipped.join(', ')}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
