#!/usr/bin/env node
/**
 * Session 23: 50 VWL-Fragen (38 richtigfalsch + 12 sortierung).
 * richtigfalsch: aussagen ohne IDs in der DB → keine Teilerklärungen.
 * sortierung: keine Sub-Array-IDs → keine Teilerklärungen.
 * Nur überarbeitete Musterlösungen nach Qualitätsregeln (2–4 Sätze, 60–80 Wörter, neutrale 3. Person, Schweizer Hochdeutsch).
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'fragen-updates.jsonl')
const STATE = path.join(__dirname, 'state.json')

const updates = [
  // ----- 38 VWL / richtigfalsch -----
  { id: 'd4175c07-efb9-477f-bea5-71a698b112a1', fachbereich: 'VWL', musterlosung: 'Richtig. Ein natürliches Monopol entsteht durch sinkende Durchschnittskosten: Hohe Fixkosten und tiefe Grenzkosten machen es effizienter, wenn nur ein Anbieter den gesamten Markt bedient. Typische Beispiele sind Stromnetze, Eisenbahninfrastruktur und Wasserversorgung. Mehrere parallele Netze wären volkswirtschaftlich eine Verschwendung. Weil in dieser Konstellation kein Wettbewerb spielt, reguliert der Staat die Preise, um Monopolmissbrauch zu verhindern.', teilerklaerungen: [] },
  { id: 'd41d3f62-3636-4ce3-821e-3f891c85da3b', fachbereich: 'VWL', musterlosung: 'Falsch. Stellensuchende ist der weitere Begriff und umfasst auch Personen, die nicht sofort vermittelbar sind oder an Beschäftigungsprogrammen, Umschulungen oder Zwischenverdiensten teilnehmen. Als Arbeitslose gelten hingegen nur jene Stellensuchenden, die sofort zur Vermittlung bereitstehen. Die Arbeitslosenquote des SECO bezieht sich deshalb auf die engere Gruppe und liegt tiefer als die Stellensuchendenquote.', teilerklaerungen: [] },
  { id: 'd579211a-ad74-480e-8fe6-d32353661a54', fachbereich: 'VWL', musterlosung: 'Richtig. Forschung von James Heckman zeigt, dass rund die Hälfte der späteren Einkommensunterschiede vor dem 18. Lebensjahr geprägt wird. Investitionen in Frühförderung wirken deshalb besonders hebelwirksam: Sie erhöhen Humankapital und Chancen, statt später Symptome bekämpfen zu müssen. Umverteilung im Erwachsenenalter ist teurer und weniger wirksam. Frühe Bildungsinvestitionen gelten daher als effizientestes Mittel gegen Ungleichheit.', teilerklaerungen: [] },
  { id: 'd7bffb26-bebc-40bc-9411-5ac657cee7ae', fachbereich: 'VWL', musterlosung: 'Richtig. Ohne Wettbewerbsdruck und ohne die Möglichkeit des Konkurses fehlen in staatlichen Unternehmen zentrale Anreize zur Effizienzsteigerung. Verluste können oft durch Zuschüsse gedeckt werden. Allerdings gibt es Ausnahmen, etwa gut geführte öffentliche Betriebe oder Bereiche mit natürlichen Monopolen, in denen staatliche Trägerschaft sinnvoller ist als private Anbieter. Die Tendenz zu tieferer Effizienz bleibt aber bestehen.', teilerklaerungen: [] },
  { id: 'd8d88df1-fae0-42d1-b757-9fe9a11234bb', fachbereich: 'VWL', musterlosung: 'Falsch. Zwar zahlen alle denselben Prozentsatz, die relative Belastung fällt jedoch sehr unterschiedlich aus. Bei 20 Prozent Steuer auf 40\'000 Franken Einkommen bleibt weniger Spielraum für den Lebensunterhalt als bei 20 Prozent auf 400\'000 Franken. Das Prinzip der wirtschaftlichen Leistungsfähigkeit verlangt deshalb einen progressiven Tarif, bei dem höhere Einkommen mit steigendem Prozentsatz belastet werden.', teilerklaerungen: [] },
  { id: 'd9b5c107-e51d-487c-973e-ac395abe6fee', fachbereich: 'VWL', musterlosung: 'Falsch. Strukturelle und konjunkturelle Arbeitslosigkeit hängen eng zusammen. In einer Rezession werden Betriebe mit veralteten Geschäftsmodellen schneller aus dem Markt gedrängt, die strukturelle Komponente tritt offen zutage. Umgekehrt kann eine gute Konjunktur Strukturprobleme überdecken und strukturelle Arbeitslosigkeit lindern. Die saubere Trennung der beiden Komponenten ist deshalb eine analytische Abstraktion, keine empirische Realität.', teilerklaerungen: [] },
  { id: 'd9e99080-ac65-4366-91c7-e3e69ad82d02', fachbereich: 'VWL', musterlosung: 'Richtig. Ohne Obligatorium würden viele Menschen Risiken wie Alter, Krankheit oder Arbeitslosigkeit unterschätzen oder sich die Absicherung nicht leisten können. Informationsasymmetrien und adverse Selektion würden zudem dazu führen, dass primär schlechte Risiken sich versichern, was tragfähige Beiträge verunmöglicht. Der Staat korrigiert dieses Marktversagen durch obligatorische Sozialversicherungen und sichert so den kollektiven Schutz.', teilerklaerungen: [] },
  { id: 'dbce6f06-5291-4959-ac16-dd87c4f8994b', fachbereich: 'VWL', musterlosung: 'Richtig. Im erweiterten Wirtschaftskreislauf gelangen Zahlungen für Importe von den inländischen Haushalten und Unternehmen ans Ausland. Umgekehrt fliessen Exporteinnahmen aus dem Ausland zu inländischen Unternehmen. Der Saldo dieser Ströme zeigt sich in der Handelsbilanz. Ein Importüberschuss bedeutet, dass Kaufkraft netto ins Ausland abfliesst; ein Exportüberschuss erhöht die inländische Wertschöpfung.', teilerklaerungen: [] },
  { id: 'df41ac46-5574-4907-a83d-adf917498603', fachbereich: 'VWL', musterlosung: 'Richtig. In der klassischen Theorie gleichen flexible Löhne Angebot und Nachfrage auf dem Arbeitsmarkt aus. Bei Arbeitslosigkeit sinken die Löhne, Arbeit wird billiger und Unternehmen stellen mehr Personal ein. Im Gleichgewicht bleibt nur freiwillige Arbeitslosigkeit. Die Annahme vollständig flexibler Löhne ist jedoch empirisch problematisch: Gesamtarbeitsverträge, Mindestlöhne und Lohnrigiditäten verhindern den raschen Ausgleich in der Realität.', teilerklaerungen: [] },
  { id: 'e0e47a5c-0687-4709-913b-7e21d97712c0', fachbereich: 'VWL', musterlosung: 'Richtig. Ein steigendes reales BIP bedeutet mehr Transaktionen in der Volkswirtschaft: mehr Einkäufe, Löhne und Zahlungen. Für jede Transaktion wird Geld benötigt, weshalb die Transaktionskasse wächst. Die Geldnachfragekurve verschiebt sich bei zunehmender realer Wirtschaftsleistung nach rechts. Die SNB berücksichtigt dies bei der Geldmengensteuerung, damit Preisstabilität gewahrt bleibt und keine Knappheit entsteht.', teilerklaerungen: [] },
  { id: 'e10bb9e6-c9dd-4742-b08f-d60f4b0b9eca', fachbereich: 'VWL', musterlosung: 'Richtig. Die Schuldenbremse wurde 2001 vom Volk mit rund 85 Prozent Ja-Stimmen angenommen und ist seit 2003 in Kraft. Sie ist in Art. 126 der Bundesverfassung verankert und bindet Bundesrat und Parlament. Ausgaben und Einnahmen müssen über den Konjunkturzyklus im Gleichgewicht stehen. Seit der Einführung ist die Schuldenquote des Bundes deutlich gesunken.', teilerklaerungen: [] },
  { id: 'e30c54f5-fbb9-4301-8afe-559af8736c06', fachbereich: 'VWL', musterlosung: 'Falsch. Nudging schränkt die Wahlfreiheit formal nicht ein, wirft aber ethische Fragen auf: Wer legt fest, welches Verhalten das «richtige» ist? Ist eine subtile Verhaltenslenkung durch den Staat legitim? Kritiker sprechen von «libertärem Paternalismus» und warnen vor einer wertgebundenen Einflussnahme. Auch sanfte Steuerung ist nicht wertfrei, weshalb Nudging in der Demokratie transparent und begründet sein muss.', teilerklaerungen: [] },
  { id: 'e3621ead-9fb2-4333-a2fc-624b9dcb2f42', fachbereich: 'VWL', musterlosung: 'Richtig. Der Bundeshaushalt gilt als «Transferhaushalt», weil rund zwei Drittel der Mittel als Übertragungen an Kantone, Sozialwerke oder Private weitergereicht werden. Nur etwa ein Drittel verbleibt für Eigenaufgaben wie Verwaltung, Landesverteidigung und Hochschulen. Rund 59 Prozent der Gesamtausgaben sind Subventionen, die grösstenteils in die soziale Wohlfahrt fliessen. Der Bund steuert damit weniger direkt, als es die Ausgabensumme suggeriert.', teilerklaerungen: [] },
  { id: 'e4633f9e-c78d-427b-af8a-f0936b99f6ed', fachbereich: 'VWL', musterlosung: 'Richtig. Friktionelle Arbeitslosigkeit entsteht durch Stellenwechsel, Berufseinstiege oder saisonale Schwankungen und ist kurzfristiger Natur. Sie löst sich in der Regel von selbst auf, sobald eine passende Stelle gefunden ist. Ein gewisses Mass an Friktion ist sogar erwünscht, weil es einen funktionierenden Strukturwandel anzeigt. Wirtschaftspolitisch problematisch sind dagegen strukturelle und konjunkturelle Arbeitslosigkeit.', teilerklaerungen: [] },
  { id: 'e5dde3dc-abba-4b03-8c91-b8dd29cda952', fachbereich: 'VWL', musterlosung: 'Falsch. Bei Komplementärgütern gilt das Gegenteil: Steigt der Preis des einen Gutes, sinkt die Nachfrage nach dem anderen. Teureres Benzin verteuert den Betrieb eines SUV, weshalb die Nachfragekurve nach SUV sich nach links verschiebt. Komplementärgüter werden gemeinsam konsumiert — Auto und Treibstoff, Drucker und Patronen, Smartphone und Netzabonnement. Die Preisänderung wirkt deshalb über die Gesamtkosten auf das verwandte Gut.', teilerklaerungen: [] },
  { id: 'ec123fdd-1051-4354-adcb-92191326fc4d', fachbereich: 'VWL', musterlosung: 'Falsch. Das BIP erfasst nur marktliche Wertschöpfung und zieht Umweltschäden nicht ab. Paradoxerweise erhöht die Beseitigung von Schäden — etwa durch Reparaturen oder Sanierungen — das BIP sogar, weil dabei bezahlte Arbeit entsteht. Externe Kosten wie Luftverschmutzung oder Klimafolgen bleiben unberücksichtigt. Deshalb ergänzen viele Länder das BIP durch Indikatoren zu Nachhaltigkeit und Ressourcenverbrauch.', teilerklaerungen: [] },
  { id: 'ec1f96a7-dbae-4add-bb03-847ec5ec76f9', fachbereich: 'VWL', musterlosung: 'Falsch. Qualitatives Wachstum durch bessere Technologie, höhere Effizienz und mehr Dienstleistungen ist mit Nachhaltigkeit durchaus vereinbar. Nicht Wachstum an sich ist das Problem, sondern dessen Ressourcen- und Emissionsintensität. Das Konzept der Entkopplung beschreibt genau diesen Ansatz: mehr Wertschöpfung bei geringerem Ressourceneinsatz. Ob eine vollständige absolute Entkopplung in grossem Massstab möglich ist, bleibt umstritten.', teilerklaerungen: [] },
  { id: 'f0b3470b-8ade-46da-a5b6-82331330d2fd', fachbereich: 'VWL', musterlosung: 'Falsch. Die Nachfragekurve zeigt die Zahlungsbereitschaft und damit den Grenznutzen der Konsumentinnen und Konsumenten — nicht deren Grenzkosten. Konsumenten haben keine Produktionskosten; Grenzkosten sind ein Begriff der Angebotsseite. Die Angebotskurve hingegen bildet die Grenzkosten der Produzenten ab. Die Verwechslung beider Kurven ist ein häufiger Denkfehler im Mikroökonomie-Einstieg.', teilerklaerungen: [] },
  { id: 'f0efe9ea-f92b-46af-a470-f9632774050d', fachbereich: 'VWL', musterlosung: 'Richtig. Erste Formen von Papiergeld entstanden im China des 7. Jahrhunderts, setzten sich zunächst aber nicht dauerhaft durch. Erst unter der Song-Dynastie ab dem 11. Jahrhundert wurde Papiergeld regelmässig verwendet. In Europa tauchten die ersten regulären Banknoten erst im 17. Jahrhundert auf, ausgegeben von schwedischen und englischen Banken. Die chinesische Priorität ist heute historisch unbestritten.', teilerklaerungen: [] },
  { id: 'f1959069-c6ba-4453-8739-542445c55250', fachbereich: 'VWL', musterlosung: 'Falsch. Adolf Wagner formulierte, dass die Staatsausgaben überproportional zum Wirtschaftswachstum steigen — also schneller als die Wirtschaft wächst. Begründet wird dies mit zunehmenden staatlichen Aufgaben in Infrastruktur, Sozialem, Bildung und Verwaltung im Zuge der wirtschaftlichen Entwicklung. Das empirische Muster in den meisten Industrienationen bestätigt das Gesetz, auch wenn die Steigung sich über Zeit verändert.', teilerklaerungen: [] },
  { id: 'f1c29bee-0eb9-46bd-a89c-c92b237d485e', fachbereich: 'VWL', musterlosung: 'Richtig. In der Rezession sollen laut Keynes die Staatsausgaben erhöht und Steuern gesenkt werden, um die Nachfrage zu stützen — auch um den Preis eines Budgetdefizits. In der Hochkonjunktur werden diese Defizite durch Überschüsse wieder abgebaut. Dieses Prinzip der antizyklischen Fiskalpolitik ist bis heute Kern keynesianischer Konjunktursteuerung und beeinflusst auch die Schweizer Schuldenbremse.', teilerklaerungen: [] },
  { id: 'f1ef67c3-74ef-4301-b453-ff3b97f03198', fachbereich: 'VWL', musterlosung: 'Falsch. Knappheit ist relativ und nicht absolut. Mit steigendem Wohlstand entstehen neue und anspruchsvollere Bedürfnisse: grössere Wohnungen, mehr Reisen, bessere Gesundheitsversorgung. Eisenhut weist darauf hin, dass Bedürfnisse grundsätzlich unbegrenzt sind und mit den Möglichkeiten mitwachsen. Das Knappheitsproblem verschiebt sich dadurch, es verschwindet nicht. Ökonomisches Handeln bleibt deshalb auch in reichen Gesellschaften notwendig.', teilerklaerungen: [] },
  { id: 'f23df027-3ead-4e2f-9617-171942d6eea6', fachbereich: 'VWL', musterlosung: 'Richtig. Green Growth vertraut auf Kostenwahrheit durch Internalisierung externer Effekte: Wer die Umwelt belastet, soll den wahren Preis zahlen. Über Marktanreize wie die CO₂-Abgabe, Zertifikatehandel und Innovation werden Produktion und Konsum ökologisch gelenkt. Der Staat setzt Rahmenbedingungen, überlässt die konkrete Umsetzung aber dem Markt. Damit grenzt sich Green Growth klar von ordnungspolitischen Planwirtschaftsansätzen ab.', teilerklaerungen: [] },
  { id: 'f384846c-ae88-40e3-baf2-3f68362da5a5', fachbereich: 'VWL', musterlosung: 'Falsch. Die Schweiz hat eine der tiefsten Schuldenquoten weltweit, klar unter der Maastricht-Grenze von 60 Prozent des BIP. Länder wie Japan weisen Werte über 230 Prozent, Italien über 130 Prozent und die USA über 100 Prozent aus. Gründe für die tiefe Quote sind Schuldenbremse, Haushaltsdisziplin und eine breite Steuerbasis. International gilt die Schweiz deshalb als Musterland solider Staatsfinanzen.', teilerklaerungen: [] },
  { id: 'f434b515-a6ad-4d82-ae1c-0f2f1273e3ee', fachbereich: 'VWL', musterlosung: 'Falsch. Lenkungsabgaben zielen auf Verhaltensänderung und nicht auf zusätzliche Staatseinnahmen. Die Einnahmen werden vollumfänglich an die Bevölkerung rückverteilt, etwa über tiefere Krankenkassenprämien. Wer sich umweltfreundlich verhält, erhält am Ende mehr zurück, als eingezahlt wurde. Dadurch entsteht ein fiskalisch neutrales Anreizsystem, das Konsum und Produktion ökologisch lenkt, ohne die Staatsquote zu erhöhen.', teilerklaerungen: [] },
  { id: 'f4e42615-10d9-4c1b-936b-fb552e4f6709', fachbereich: 'VWL', musterlosung: 'Richtig. Zu Beginn des Spiels bilden die Teilnehmenden Wörter allein mit ihren eigenen Buchstaben — das entspricht der Autarkie. Danach beginnt der Tausch: Zwei Spielende geben sich gegenseitig Buchstaben, ohne Zwischenmedium (Tauschwirtschaft). Schliesslich etabliert sich der Buchstabe X als allgemein akzeptiertes Tauschmittel — die Geldwirtschaft ist entstanden. BOB illustriert so die historische Entstehung von Geld im Kleinen.', teilerklaerungen: [] },
  { id: 'f7249fd8-8124-4e18-9f1c-c4b7ca4d6e47', fachbereich: 'VWL', musterlosung: 'Falsch. Die OECD-Mindeststeuer von 15 Prozent betrifft nur grosse multinationale Konzerne mit über 750 Millionen Euro Umsatz und nur die Gewinnbesteuerung. Der innerschweizerische Steuerwettbewerb zwischen Kantonen umfasst hingegen Einkommens-, Vermögens- und KMU-Steuern. Diese Bereiche bleiben von der Mindeststeuer unberührt. Der Steuerwettbewerb auf kantonaler Ebene geht also weiter, auch wenn sein Spielraum bei Grosskonzernen kleiner geworden ist.', teilerklaerungen: [] },
  { id: 'f72c28bb-ee99-4b4e-91ee-2d4f5da07f36', fachbereich: 'VWL', musterlosung: 'Richtig. Wenn der Staat Defizite direkt bei der Nationalbank finanziert, wird frisches Zentralbankgeld geschaffen — die Geldmenge wächst. Das nennt man Monetisierung der Staatsschuld. Im Unterschied dazu verschiebt die Finanzierung am Kapitalmarkt nur bestehende Ersparnisse. Die Monetisierung birgt langfristig Inflationsgefahren, wenn die Geldmenge schneller wächst als das reale BIP. Deshalb ist sie der SNB in der Schweiz gesetzlich untersagt.', teilerklaerungen: [] },
  { id: 'f8ecfbba-afc0-4c8a-bbcf-46d3515b31af', fachbereich: 'VWL', musterlosung: 'Falsch. Die Laffer-Kurve zeigt, dass Steuersatz und Steuereinnahmen nur bis zu einem Scheitelpunkt gemeinsam steigen. Jenseits dieses Punkts überwiegen Anreizeffekte wie Arbeitsvermeidung, Steuerflucht und Schwarzarbeit, weshalb die Bemessungsgrundlage schrumpft. Die Einnahmen sinken trotz höherem Steuersatz. Wo der Scheitelpunkt genau liegt, ist empirisch umstritten und variiert zwischen Volkswirtschaften und Steuerarten.', teilerklaerungen: [] },
  { id: 'f93dd931-3d48-468c-8267-9a0ce9d07e89', fachbereich: 'VWL', musterlosung: 'Richtig. Bei abnehmendem Grenznutzen des Einkommens bringt ein zusätzlicher Franken einer ärmeren Person mehr Nutzen als einer reichen. Eine moderate Umverteilung erhöht deshalb die gesellschaftliche Nutzensumme. Der Utilitarismus unterstützt Umverteilung aus Effizienzgründen, nicht aus Gerechtigkeitserwägungen. Allerdings muss der Nutzengewinn gegen negative Anreizeffekte der Umverteilung auf Arbeitsangebot und Sparen abgewogen werden.', teilerklaerungen: [] },
  { id: 'f96c66a5-64f6-420e-89c6-a774616ddc25', fachbereich: 'VWL', musterlosung: 'Richtig. Branchen mit hoher Arbeitsproduktivität wie Pharma, Versicherungen oder Finanzdienstleistungen zahlen deutlich höhere Löhne als produktivitätsschwächere Branchen wie das Gastgewerbe. Höhere Wertschöpfung pro Arbeitsstunde lässt höhere Löhne zu, ohne die Wettbewerbsfähigkeit zu gefährden. Weitere Faktoren wie Qualifikationsanforderungen, gewerkschaftliche Stärke und Arbeitsmarktbedingungen spielen mit, die Produktivität bleibt jedoch ein zentraler Erklärungsfaktor.', teilerklaerungen: [] },
  { id: 'fa1d2e83-2406-4f5b-90d1-e58063c4f2a7', fachbereich: 'VWL', musterlosung: 'Richtig. In modernen Volkswirtschaften ist die Herausgabe von Noten und Münzen ein staatliches Monopol. In der Schweiz darf nur die Schweizerische Nationalbank Banknoten emittieren; Münzen werden von der Swissmint im Auftrag des Bundes geprägt. Das Monopol ermöglicht eine Geldmengensteuerung zur Preisstabilität und sichert das Vertrauen in die Währung. Buchgeld hingegen schaffen die Geschäftsbanken durch Kreditvergabe.', teilerklaerungen: [] },
  { id: 'fa60f8c0-417a-42fa-9c05-c171e5e115b7', fachbereich: 'VWL', musterlosung: 'Falsch. Lenkungsabgaben sollen nicht Einnahmen schaffen, sondern Verhalten lenken — weg von umweltschädlichen hin zu umweltfreundlichen Alternativen. Die Einnahmen werden vollumfänglich an die Wirtschaftssubjekte rückverteilt, etwa über tiefere Krankenkassenprämien. Fiskalisch sind Lenkungsabgaben neutral konstruiert. Wer umweltfreundlich handelt, erhält am Ende sogar mehr zurück, als eingezahlt wurde.', teilerklaerungen: [] },
  { id: 'fb0fb727-15bd-40fc-a6fd-0dc4958270f9', fachbereich: 'VWL', musterlosung: 'Richtig. Im Marktgleichgewicht schneiden sich Angebots- und Nachfragekurve. Die zum Gleichgewichtspreis angebotene Menge entspricht exakt der nachgefragten — der Markt ist geräumt. Unter dem Gleichgewichtspreis entsteht ein Nachfrageüberschuss (Knappheit), darüber ein Angebotsüberschuss. Der Preismechanismus treibt den Markt in Richtung Gleichgewicht, solange keine Eingriffe oder Marktmachtverzerrungen vorliegen.', teilerklaerungen: [] },
  { id: 'fb531de1-1536-44d5-bd85-2c8121221b30', fachbereich: 'VWL', musterlosung: 'Richtig. Der reduzierte Mehrwertsteuersatz von 2.6 Prozent auf Güter des täglichen Bedarfs wie Lebensmittel, Medikamente und Bücher entlastet relativ gesehen Personen mit tieferem Einkommen stärker. Weil diese einen grösseren Anteil ihres Einkommens für Grundbedürfnisse ausgeben, trägt die geringere Belastung zur sozialen Gerechtigkeit bei. Die MwSt gilt zwar als regressiv, der reduzierte Satz mildert diesen Effekt gezielt ab.', teilerklaerungen: [] },
  { id: 'fc48d723-b0a7-4241-90b8-e3301c5c98ca', fachbereich: 'VWL', musterlosung: 'Falsch. Die Verrechnungssteuer ist eine indirekte Steuer und wirkt als Sicherungssteuer auf Kapitalerträgen wie Dividenden und Zinsen. Sie wird an der Quelle mit 35 Prozent abgezogen und bei korrekter Deklaration in der Steuererklärung zurückerstattet. Ziel ist nicht die Einnahmenerzielung, sondern die lückenlose Erfassung steuerpflichtiger Erträge. Wer deklariert, erhält die Verrechnungssteuer vollständig zurück.', teilerklaerungen: [] },
  { id: 'fc5bca72-068d-4c4b-b027-c21aa450c2ec', fachbereich: 'VWL', musterlosung: 'Richtig. Bei völlig unelastischem Angebot reagiert die angebotene Menge nicht auf den Preis — die Steuer verursacht deshalb keine Mengenveränderung und keine Wohlfahrtsverluste. Die gesamte Steuerlast trägt der Anbieter, der konsumierte Bedarf wird weiterhin voll bedient. Dieser Fall ist theoretisch lehrreich, in der Praxis aber selten: Bodenwerte oder bestehende Gebäude kommen ihm am nächsten, weshalb Bodensteuern als besonders effizient gelten.', teilerklaerungen: [] },
  { id: 'fcfc00ce-fe2f-47be-aa7b-831c97010c9b', fachbereich: 'VWL', musterlosung: 'Richtig. Die Einführung der Schuldenbremse per Volksabstimmung zeigt, dass direkte Demokratien langfristige Interessen berücksichtigen können. Stimmberechtigte haben erkannt, dass kurzfristiges Schuldenmachen langfristig hohe Kosten verursacht und den Handlungsspielraum künftiger Generationen einengt. Anders als in repräsentativen Demokratien, wo Wahlzyklen kurzfristiges Verhalten begünstigen können, fördert die Volksabstimmung nachhaltige Finanzpolitik.', teilerklaerungen: [] },

  // ----- 12 VWL / sortierung -----
  { id: '0ee6975d-750f-4f30-950d-7ce98e8e9b0f', fachbereich: 'VWL', musterlosung: 'Leistungsgerechtigkeit erfordert kaum staatliche Umverteilung, weil der Markt Leistung über Löhne und Preise direkt belohnt. Chancengerechtigkeit verlangt moderate Eingriffe — etwa kostenlose Bildung, Stipendien oder Frühförderung —, um gleiche Startbedingungen zu schaffen. Bedarfsgerechtigkeit geht am weitesten: Der Staat transferiert aktiv Ressourcen von Bessergestellten zu Bedürftigen. In der Schweiz werden alle drei Prinzipien kombiniert.', teilerklaerungen: [] },
  { id: '1dfa54d8-476a-4be7-a521-7bcae09d4601', fachbereich: 'VWL', musterlosung: 'Die Schuldenbremse wirkt antizyklisch: Zunächst wird der konjunkturbereinigte Einnahmenplafond ermittelt, dann als Ausgabenobergrenze festgelegt. In Rezessionen erlaubt der Konjunkturfaktor höhere Ausgaben, in Boomphasen erzwingt er Zurückhaltung. Überschüsse und Defizite gleichen sich über den Zyklus hinweg aus. Seit Einführung 2003 hat das Instrument die Schuldenquote des Bundes deutlich reduziert und die Haushaltsdisziplin gestärkt.', teilerklaerungen: [] },
  { id: '355dc318-ac4b-48df-9ff4-65545510b3df', fachbereich: 'VWL', musterlosung: 'Das SECO zählt ausschliesslich beim RAV registrierte, sofort vermittelbare Arbeitslose. Personen in Beschäftigungsprogrammen werden oft nicht als arbeitslos gezählt, je nach Programmtyp. Ausgesteuerte und entmutigte Personen tauchen in der offiziellen Statistik gar nicht auf und gehören zur versteckten Arbeitslosigkeit. Die ILO-Arbeitslosenquote des BFS erfasst einen breiteren Personenkreis und liegt deshalb regelmässig über der SECO-Quote.', teilerklaerungen: [] },
  { id: '39077299-0e5a-4717-a99b-8993ede221b6', fachbereich: 'VWL', musterlosung: 'Kapital und Technologie sind unmittelbare Wachstumstreiber: Mehr Maschinen und bessere Verfahren erhöhen die Produktivität direkt. Bildung wirkt eine Ebene tiefer, sie ermöglicht Innovation und effiziente Kapitalnutzung. Institutionen sind die fundamentalste Ebene: Eigentumsrechte, Rechtssicherheit und funktionierende Märkte schaffen die Rahmenbedingungen, unter denen Kapital, Technologie und Bildung überhaupt gedeihen. Länder mit schwachen Institutionen wachsen trotz Ressourcen kaum nachhaltig.', teilerklaerungen: [] },
  { id: '3bfa90f1-ec77-4ff9-9eb3-7d918a87416c', fachbereich: 'VWL', musterlosung: 'Traditionell stehen Preisstabilität und Vollbeschäftigung im Zentrum der Schweizer Wirtschaftspolitik. Wachstum und aussenwirtschaftliches Gleichgewicht folgen als klassische Zielgrössen. Ausgewogene Einkommens- und Vermögensverteilung sowie Nachhaltigkeit wurden historisch erst später als gleichwertige Ziele anerkannt. Alle sechs Ziele stehen in Wechselbeziehungen und teilweise im Konflikt — daher «magisch»: Die gleichzeitige Erfüllung aller Ziele ist kaum möglich.', teilerklaerungen: [] },
  { id: '47d96bd1-5e5b-45cf-9de3-a0c97ff0acd0', fachbereich: 'VWL', musterlosung: 'Die vollkommene Konkurrenz bietet den stärksten Wettbewerb: Viele Anbieter, homogene Güter, volle Transparenz, kein Marktmacht-Einzelner. Die monopolistische Konkurrenz hat ebenfalls viele Anbieter, doch Produktdifferenzierung schafft begrenzte Preissetzungsspielräume. Im Oligopol dominieren wenige grosse Anbieter, die Preise und Mengen stark beeinflussen können — etwa der Schweizer Mobilfunk. Das Monopol kennt keinen Wettbewerb; ein einziger Anbieter kontrolliert den Markt.', teilerklaerungen: [] },
  { id: '5016223f-a81d-410a-acb8-5c5778d01583', fachbereich: 'VWL', musterlosung: 'Die Schweiz kennt ein dreistufiges Steuersystem mit parallelen Hoheiten. Der Bund erhebt die direkte Bundessteuer und die Mehrwertsteuer. Die Kantone erheben eigene Einkommens- und Vermögenssteuern mit unterschiedlichen Tarifen — daraus ergibt sich der innerkantonale Steuerwettbewerb. Die Gemeinden schlagen als Steuerfuss einen Prozentsatz auf die Kantonssteuer auf. Diese föderale Dreigliedrigkeit ist international weitgehend einzigartig.', teilerklaerungen: [] },
  { id: '50660fa7-9576-4de4-9383-5774b6c810d6', fachbereich: 'VWL', musterlosung: 'Private Güter mit Rivalität und Ausschliessbarkeit werden effizient vom Markt bereitgestellt. Klubgüter können privat angeboten werden, weil der Zugang kontrolliert werden kann — etwa Kinos oder Pay-TV. Allmendegüter wie Fischbestände erfordern staatliche Regulierung, um Übernutzung zu verhindern. Rein öffentliche Güter wie Landesverteidigung kann der Markt wegen Trittbrettfahrer-Problem nicht bereitstellen, hier ist der Staat unverzichtbar.', teilerklaerungen: [] },
  { id: '532adede-3708-431f-87ba-d2ef051b8c06', fachbereich: 'VWL', musterlosung: 'Die Schweiz durchlief den klassischen Strukturwandel. In der Agrargesellschaft vor 1800 dominierten Landwirtschaft und Handwerk. Die Industrialisierung des 19. Jahrhunderts verschob Arbeitskräfte in den sekundären Sektor — Maschinenbau, Textil, Chemie. Ab etwa 1970 wurde der tertiäre Sektor dominant; heute arbeiten über 75 Prozent im Dienstleistungsbereich, der primäre Sektor beschäftigt nur noch rund 3 Prozent der Erwerbstätigen.', teilerklaerungen: [] },
  { id: '5eec88c6-3832-4254-94f2-21ca9f0dc573', fachbereich: 'VWL', musterlosung: 'Die Arbeitslosenversicherung folgt einem klaren Ablauf. Zuerst meldet sich die arbeitslose Person beim RAV an und wird in einem Beratungsgespräch eingestuft. Dann wird ein individueller Vermittlungs- und Wiedereinstiegsplan erstellt. Während des Taggeldbezugs müssen Arbeitsbemühungen monatlich nachgewiesen werden. Die Bezugsdauer ist zeitlich begrenzt. Nach Ausschöpfung der Taggelder folgt die Aussteuerung; bei anhaltender Not übernimmt die Sozialhilfe.', teilerklaerungen: [] },
  { id: '659ec1a3-e7aa-4534-bd16-ee0cd04cf9e2', fachbereich: 'VWL', musterlosung: 'Konjunkturprogramme wirken kurzfristig — Monate bis wenige Jahre. Steuersenkungen zeigen mittelfristig Wirkung, weil sie Investitions- und Arbeitsanreize verändern. Infrastrukturprojekte haben eine mittelfristige Bauphase, entfalten aber über Jahrzehnte Nutzen für Produktivität und Mobilität. Bildungs- und Forschungsausgaben wirken am langfristigsten: Erträge zeigen sich erst nach vielen Jahren, sind jedoch für nachhaltiges Wachstum zentral.', teilerklaerungen: [] },
  { id: '7ca37063-6a3b-4e7a-9ca0-4ad09e410715', fachbereich: 'VWL', musterlosung: 'Zunächst wird das nominale BIP zu laufenden Preisen ermittelt. Anschliessend wird ein Basisjahr festgelegt, an dessen Preisen die Veränderung gemessen wird. Der BIP-Deflator drückt die durchschnittliche Preisveränderung gegenüber dem Basisjahr aus. Das nominale BIP wird durch den Deflator bereinigt; das Ergebnis ist das reale BIP. So lässt sich unterscheiden, ob Wachstum auf höhere Mengen oder nur auf höhere Preise zurückgeht.', teilerklaerungen: [] },
]

async function main() {
  const stateRaw = await fs.readFile(STATE, 'utf8')
  const state = JSON.parse(stateRaw)

  const outLines = []
  let done = 0
  const now = new Date().toISOString()

  for (const u of updates) {
    const existing = state.fragen[u.id]
    if (existing && existing.status === 'done') {
      console.warn(`skip already done: ${u.id}`)
      continue
    }
    outLines.push(JSON.stringify(u))
    state.fragen[u.id] = {
      status: 'done',
      zeitpunkt: now,
      teile: u.teilerklaerungen.length,
    }
    done++
  }

  state.verarbeitet = (state.verarbeitet || 0) + done
  state.letzteSession = now

  await fs.appendFile(OUT, outLines.join('\n') + (outLines.length ? '\n' : ''), 'utf8')
  await fs.writeFile(STATE, JSON.stringify(state, null, 2), 'utf8')

  console.log(`Session 23: ${done} verarbeitet, total ${state.verarbeitet}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
