#!/usr/bin/env node
/**
 * Session 9: 100 Fragen (58 Recht/richtigfalsch + 25 Recht/sortierung
 * + 3 Recht/visualisierung + 2 VWL/audio + 12 VWL/berechnung).
 *
 * RF-Aussagen ohne ID → teilerklaerungen = [] (Spec-Konvention, analog S7+S8).
 * Ausnahmen: einr-rf-toolfunktionen + ueb-rf-toolfunktionen haben IDs 1..4
 *   → feld='aussagen', id='1'..'4', text.
 * Sortierung/Visualisierung/Audio/Berechnung: keine Sub-Struktur → [].
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'fragen-updates.jsonl')
const STATE = path.join(__dirname, 'state.json')

const updates = [
  // ========== Recht / richtigfalsch (58) ==========
  { id: 'a4f32aca-fdac-450a-860f-44a95b225cce', fachbereich: 'Recht', musterlosung: 'Richtig. Ein befristeter Arbeitsvertrag endet ohne Kündigung automatisch mit Ablauf der vereinbarten Zeit. Diese Form der Beendigung ist in OR 334 geregelt und unterscheidet sich vom unbefristeten Vertrag, der grundsätzlich einer ordentlichen Kündigung bedarf. Eine stillschweigende Fortsetzung nach Ablauf macht den Vertrag allerdings unbefristet.', teilerklaerungen: [] },
  { id: 'a5ca5c65-3ec2-4349-ae51-32b1bc6e5cdf', fachbereich: 'Recht', musterlosung: 'Falsch. Das Eigentumsrecht gilt nur innerhalb der Schranken der Rechtsordnung. Der Eigentümer muss insbesondere auf die Interessen seiner Nachbarn Rücksicht nehmen und darf keine übermässigen Immissionen verursachen. Tägliches Grillieren auf dem Balkon kann gegen das Nachbarrecht verstossen und ist damit unzulässig.', teilerklaerungen: [] },
  { id: 'a6ceda15-8cc8-4955-894a-b29094f0ad06', fachbereich: 'Recht', musterlosung: 'Richtig. Grunddienstbarkeiten sind nicht an eine bestimmte Person, sondern an das herrschende und belastete Grundstück gebunden. Wer ein belastetes Grundstück erwirbt, übernimmt die Dienstbarkeit automatisch und muss sie dulden. Eine Löschung ist nur mit Einwilligung des Berechtigten möglich — in der Regel gegen Entschädigung.', teilerklaerungen: [] },
  { id: 'a6d1f66d-c401-423a-8a05-f8345f35d269', fachbereich: 'Recht', musterlosung: 'Falsch. Obligatorische Rechte wirken nur zwischen den Personen, die in einem Schuldverhältnis zueinander stehen — deshalb spricht man von relativen Rechten. Nur die dinglichen Rechte (Sachenrechte wie Eigentum) wirken gegenüber jedermann und sind damit absolute Rechte. Obligatorische und dingliche Wirkung dürfen nicht verwechselt werden.', teilerklaerungen: [] },
  { id: 'a7a62055-0894-480f-99e3-9ae7cbe5bcad', fachbereich: 'Recht', musterlosung: 'Falsch. Grundrechte können nach Art. 36 BV unter bestimmten Voraussetzungen eingeschränkt werden: gesetzliche Grundlage, öffentliches Interesse und Verhältnismässigkeit müssen kumulativ vorliegen. Unantastbar ist lediglich der Kerngehalt — z.B. das Folterverbot als Kerngehalt der persönlichen Freiheit. Ausserhalb des Kerngehalts sind Einschränkungen also sehr wohl zulässig.', teilerklaerungen: [] },
  { id: 'aa36e23b-2fd8-4d85-a2b6-bbb1a0c3cff9', fachbereich: 'Recht', musterlosung: 'Falsch. Die Urteilsfähigkeit ist relativ — sie hängt vom konkreten Geschäft ab. Eine Person kann urteilsfähig sein, um eine CD zu kaufen, aber urteilsunfähig für ein kompliziertes Finanzgeschäft. Entscheidend ist die Fähigkeit, vernunftgemäss zu handeln, bezogen auf die jeweilige Handlung und deren Tragweite.', teilerklaerungen: [] },
  { id: 'aa5bb763-a655-4553-9b5d-3e16bb9116ed', fachbereich: 'Recht', musterlosung: 'Richtig. Ein Gesamtarbeitsvertrag (GAV) wird zwischen Arbeitnehmerverbänden (Gewerkschaften) und Arbeitgeberverbänden oder einzelnen Arbeitgebern abgeschlossen. Er regelt kollektive Arbeitsbedingungen — Mindestlöhne, Arbeitszeiten, Ferien — für ganze Branchen. GAV-Bestimmungen gehen dem Einzelvertrag vor, soweit dieser nicht günstiger ist.', teilerklaerungen: [] },
  { id: 'aca43f21-ba53-4e78-96ad-fe4aca9b182b', fachbereich: 'Recht', musterlosung: 'Falsch. Die Abgrenzung zwischen Recht und Sitte kann fliessend sein. Eine Verabredung zum Sonntagsspaziergang schafft keine Rechtspflicht. Eine Abmachung, gemeinsam in die Ferien zu fahren und die Kosten zu teilen, kann hingegen als rechtlich relevante Vereinbarung gelten. Die Übergänge sind oft Auslegungssache im Einzelfall.', teilerklaerungen: [] },
  { id: 'ae348afc-b5b9-4d14-ba27-cb3dcde4a49a', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 266m und 266n muss die Kündigung einer Familienwohnung beiden Ehegatten bzw. eingetragenen Partnern separat zugestellt werden — auch wenn nur einer Mietpartei ist. Der Schutz der Familienwohnung ist zwingendes Recht und soll den nicht unterzeichnenden Partner vor einseitigem Wohnungsverlust schützen.', teilerklaerungen: [] },
  { id: 'b18425ee-9ee5-4406-ad23-a5b5af1de4f4', fachbereich: 'Recht', musterlosung: 'Falsch. Der Grundsatz der Rechtskraft gilt nicht ausnahmslos. Unter bestimmten Voraussetzungen kann ein rechtskräftiger Entscheid mit einem Revisionsgesuch angefochten werden — etwa wenn neue erhebliche Tatsachen oder Beweismittel auftauchen, die bei zumutbarer Sorgfalt nicht bekannt sein konnten. Die Revision ist ein ausserordentliches Rechtsmittel mit strengen Voraussetzungen.', teilerklaerungen: [] },
  { id: 'b18a31e1-81b8-4f46-be07-070813ced5f7', fachbereich: 'Recht', musterlosung: 'Richtig. Die Verjährungsfrist bemisst sich nach Art. 97 StGB an der gesetzlich angedrohten Höchststrafe, nicht am konkreten Urteil. Ist ein Delikt mit maximal drei Jahren Freiheitsstrafe bedroht, beträgt die Verjährungsfrist zehn Jahre — unabhängig davon, ob das Gericht nur sechs Monate ausspricht. Die Abstraktion schützt vor Zirkelschlüssen bei der Strafzumessung.', teilerklaerungen: [] },
  { id: 'b227ed4f-e75d-4434-bf33-f33ef19d22c1', fachbereich: 'Recht', musterlosung: 'Richtig. Die Verjährung wird nach OR 135 unterbrochen, wenn der Schuldner die Schuld anerkennt — etwa durch eine Abschlagszahlung oder eine schriftliche Bestätigung. Auch Betreibung oder Klageerhebung durch den Gläubiger lösen eine Unterbrechung aus. Nach der Unterbrechung beginnt die Verjährungsfrist von Neuem zu laufen.', teilerklaerungen: [] },
  { id: 'b28763ee-7442-4046-8461-59b7fa19556d', fachbereich: 'Recht', musterlosung: 'Richtig. Art. 7 BV lautet: «Die Würde des Menschen ist zu achten und zu schützen.» Die Menschenwürde steht bewusst am Anfang des Grundrechtskatalogs und bildet die Basis aller weiteren Grundrechte. Sie schützt den unverfügbaren Kern der menschlichen Existenz und ist ein absolutes Grundrecht.', teilerklaerungen: [] },
  { id: 'b387fc38-cd94-4f55-9513-5fad11a62765', fachbereich: 'Recht', musterlosung: 'Richtig. Im Zivilprozess gilt — von Ausnahmen abgesehen — die Verhandlungsmaxime. Das Gericht klärt den Sachverhalt nicht von Amtes wegen, sondern die Parteien müssen die für sie wesentlichen Tatsachen behaupten (Behauptungslast) und beweisen (Beweislast). Wer nicht behauptet oder beweist, unterliegt in Bezug auf diese Tatsache.', teilerklaerungen: [] },
  { id: 'b4e66d3b-64ff-4e20-884d-c50dea746ad5', fachbereich: 'Recht', musterlosung: 'Falsch. Urteilsfähigkeit ist nach Art. 16 ZGB die Fähigkeit, vernunftgemäss zu handeln, und nicht an ein bestimmtes Alter gebunden. Kinder können bei Alltagsgeschäften durchaus urteilsfähig sein. Mit 18 Jahren erreicht man die Volljährigkeit und damit die volle Handlungsfähigkeit — Urteilsfähigkeit und Mündigkeit sind jedoch strikt zu unterscheiden.', teilerklaerungen: [] },
  { id: 'b559ef8c-c337-4d09-8a10-532b3c8fdd0c', fachbereich: 'Recht', musterlosung: 'Richtig. Die Prüfung nach Art. 36 BV beginnt mit der Frage, ob überhaupt ein Grundrecht betroffen ist. Nur wenn ein Schutzbereich eröffnet ist, sind die weiteren Voraussetzungen (gesetzliche Grundlage, öffentliches Interesse, Verhältnismässigkeit, Kerngehalt) zu prüfen. Fehlt ein Grundrechtseingriff, erübrigt sich die Rechtfertigungsprüfung.', teilerklaerungen: [] },
  { id: 'b67011fe-e9d0-4e0c-8cb5-d56f81062be2', fachbereich: 'Recht', musterlosung: 'Richtig. Nach dem Jugendstrafgesetz (JStG 25) ist Freiheitsentzug für Jugendliche erst ab 15 Jahren möglich. Die Einrichtung ist pädagogisch ausgerichtet und verbindet Elemente von Familie, Schule, Arbeitsort und Gefängnis. Der Vollzug orientiert sich primär am Erziehungs- und Resozialisierungsgedanken.', teilerklaerungen: [] },
  { id: 'b6e9ef28-958b-4580-a16e-a6a0bfd8b6d4', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 37 StGB kann gemeinnützige Arbeit nur mit Zustimmung des Täters angeordnet werden — eine Arbeit gegen den Willen wäre mit der Verfassung und dem Zwangsarbeitsverbot unvereinbar. Sie beträgt bei Vergehen höchstens 720 Stunden, bei Übertretungen höchstens 360 Stunden. Der Staat kann sie also nicht einseitig aufzwingen.', teilerklaerungen: [] },
  { id: 'b809b1ee-c58c-400a-b8a6-be521b4b1765', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 10 Abs. 1 ZPO ist grundsätzlich das Gericht am Wohnsitz der beklagten Partei örtlich zuständig. Von dieser Grundregel gibt es zahlreiche Ausnahmen — etwa bei Streitigkeiten über Grundstücke (Lageort) oder bei Konsumentenverträgen (Wohnsitz der Konsumentin). Die Wahl des Gerichtsstands ist in manchen Fällen möglich.', teilerklaerungen: [] },
  { id: 'b8481ba7-17e1-4c31-8169-b364b4c09cc8', fachbereich: 'Recht', musterlosung: 'Richtig. Ohne Antrittsprotokoll gerät der Mieter in Beweisnot. Werden bei der Wohnungsabgabe Mängel festgestellt, kann er nicht belegen, dass diese bereits beim Einzug vorhanden waren. Der Vermieter wird in der Regel davon ausgehen, dass der Mieter die Schäden verursacht hat — deshalb ist ein sorgfältiges Protokoll essenziell.', teilerklaerungen: [] },
  { id: 'ba13d890-85a9-4e80-a09d-199c19c8a0bf', fachbereich: 'Recht', musterlosung: 'Richtig. Urkunden — schriftliche Dokumente wie Verträge, Quittungen, Briefe oder E-Mails — sind eines der fünf anerkannten Beweismittel im Zivilprozess. Sie haben oft hohe Beweiskraft, weil sie Inhalt und Zeitpunkt einer Vereinbarung schriftlich dokumentieren. Neben Urkunden sind auch Zeugen, Parteiaussagen, Gutachten und Augenschein zugelassen.', teilerklaerungen: [] },
  { id: 'bcedc2cc-8eb7-4572-82ef-d396154d522e', fachbereich: 'Recht', musterlosung: 'Richtig. Art. 30 AEMR bestimmt, dass keine Norm der Erklärung so ausgelegt werden darf, dass sie Handlungen gegen die in ihr verkündeten Rechte legitimiert. Damit wird kulturellen Relativierungsversuchen zur Aushöhlung der Menschenrechte ein Riegel vorgeschoben. Die Debatte über Universalität versus Kulturrelativismus hält in der Praxis dennoch an.', teilerklaerungen: [] },
  { id: 'be1adc91-bee7-4e05-84d7-e5e30924033d', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 11 bedürfen Verträge nur dann einer besonderen Form, wenn das Gesetz sie vorschreibt — grundsätzlich gilt Formfreiheit. Die meisten Verträge können mündlich oder sogar konkludent geschlossen werden. Ausnahmen bilden Sonderbereiche wie Grundstückkauf (öffentliche Beurkundung) oder Arbeitsvermittlungsvertrag (Schriftlichkeit).', teilerklaerungen: [] },
  { id: 'c13a400a-8231-486d-9104-c6c295890fc1', fachbereich: 'Recht', musterlosung: 'Richtig. Die Verfallklausel (lex commissoria) ist nach Art. 894 ZGB nichtig. Der Gläubiger darf sich die Pfandsache nicht einfach aneignen, wenn der Schuldner nicht rechtzeitig zahlt. Stattdessen muss er den Weg über die Betreibung auf Pfandverwertung beschreiten — dies schützt den Schuldner vor unverhältnismässigen Werteinbussen.', teilerklaerungen: [] },
  { id: 'c153e488-f279-42c8-b3d6-a44cb1943273', fachbereich: 'Recht', musterlosung: 'Richtig. Das Arbeitsgesetz (ArG) gilt grundsätzlich für alle Betriebe in der Schweiz. Ausnahmen bestehen für bestimmte Gruppen wie staatliche Verwaltungen, landwirtschaftliche Betriebe, leitende Angestellte sowie wissenschaftliche oder künstlerische Tätigkeiten. Für diese gelten spezielle Regelungen oder personenbezogene Ausnahmen.', teilerklaerungen: [] },
  { id: 'c2893daa-ef8e-4880-b80f-3ca92f2af959', fachbereich: 'Recht', musterlosung: 'Falsch. Die Konventionalstrafe ist keine Schadenersatzzahlung, sondern ein vorab vereinbartes Geldversprechen für den Fall der Nichterfüllung, Schlechterfüllung oder Verspätung (OR 160 ff.). Der Gläubiger muss den konkreten Schaden nicht beweisen. Schadenersatz hingegen setzt Nachweis eines effektiven Schadens voraus — die beiden Institute sind klar zu trennen.', teilerklaerungen: [] },
  { id: 'ca69c31f-158b-40eb-967e-2a0fc1675493', fachbereich: 'Recht', musterlosung: 'Richtig. Nach dem Arbeitsgesetz (ArG 12 und 13) darf Überzeit pro Jahr höchstens 170 Stunden betragen (in bestimmten Branchen 140 Stunden). Die Kompensation erfolgt entweder durch gleichwertige Freizeit oder durch einen Lohnzuschlag von mindestens 25%. Die Grenzwerte sind zwingend und dienen dem Gesundheitsschutz.', teilerklaerungen: [] },
  { id: 'cd053db4-edf2-4b08-855d-8e686545eea2', fachbereich: 'Recht', musterlosung: 'Falsch. Nach Art. 641a ZGB sind Tiere ausdrücklich keine Sachen. Die auf Sachen anwendbaren Vorschriften finden jedoch entsprechende Anwendung, soweit keine abweichenden Regelungen bestehen. Diese Sonderstellung trägt dem Empfinden Rechnung, dass Tiere lebende, leidensfähige Wesen sind — rechtliche Folgen zeigen sich etwa im Sachenrecht und im Schadenersatzrecht.', teilerklaerungen: [] },
  { id: 'd0ae68b8-995d-450f-b2a2-f4f8fafbed35', fachbereich: 'Recht', musterlosung: 'Falsch. Eine verjährte Forderung besteht weiter, der Schuldner kann ihre Erfüllung aber verweigern (Einrede der Verjährung). Das Gericht berücksichtigt die Verjährung nicht von Amtes wegen. Eine freiwillig bezahlte verjährte Schuld ist keine ungerechtfertigte Bereicherung und kann nicht zurückgefordert werden — die Schuld existiert rechtlich also fort.', teilerklaerungen: [] },
  { id: 'd4fb07d5-bfd6-4f28-9c90-74a66c721299', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 16 können die Parteien freiwillig eine strengere Form vereinbaren als das Gesetz vorschreibt — die sogenannte gewillkürte Form. Wird etwa für einen mündlich gültigen Vertrag Schriftlichkeit vereinbart, ist die schriftliche Form Gültigkeitsvoraussetzung. Verletzung der gewillkürten Form führt zur Nichtigkeit des Geschäfts.', teilerklaerungen: [] },
  { id: 'd7e0b513-4f96-48de-b1e7-1ef06c5a6849', fachbereich: 'Recht', musterlosung: 'Richtig. Die Spezialprävention wirkt auf den konkreten Täter und umfasst drei Aspekte: individuelle Abschreckung vor erneuten Straftaten, Resozialisierung zur Wiedereingliederung in die Gesellschaft sowie die Sicherung der Allgemeinheit durch Schutz vor dem Täter. Die Generalprävention hingegen zielt auf die Allgemeinheit als abschreckendes Signal.', teilerklaerungen: [] },
  { id: 'd8b012c4-89cb-4e14-91a1-e8fa91d2fc40', fachbereich: 'Recht', musterlosung: 'Falsch. Der Mediator hat keine Entscheidungsgewalt — er ist ein neutraler Dritter, der die Parteien bei der Suche nach einer einvernehmlichen Lösung unterstützt. Bindend wird das Ergebnis nur, wenn beide Parteien eine Vereinbarung unterzeichnen. Ein Schiedsrichter hingegen fällt ein verbindliches Urteil — die beiden Verfahren sind klar zu unterscheiden.', teilerklaerungen: [] },
  { id: 'da3c4d6c-324e-400c-82d1-4308283d4153', fachbereich: 'Recht', musterlosung: 'Falsch. Die Privilegierung auf noch vorhandene Bereicherung gilt nur für den gutgläubig Bereicherten. Der bösgläubig Bereicherte — also wer den Mangel des Rechtsgrundes kannte oder kennen musste — muss den gesamten erhaltenen Betrag rückerstatten, unabhängig davon, was er noch davon besitzt. Die Gutgläubigkeit ist für den Umfang der Rückgabepflicht entscheidend.', teilerklaerungen: [] },
  { id: 'de9178ad-8c23-438d-b656-99cce1feec48', fachbereich: 'Recht', musterlosung: 'Falsch. Willensmängel wie Irrtum, Täuschung oder Furchterregung führen nach OR 23 ff. zur Anfechtbarkeit, nicht zur Nichtigkeit. Der Vertrag bleibt zunächst gültig, die geschädigte Partei kann ihn aber innerhalb eines Jahres einseitig unverbindlich erklären. Nichtigkeit tritt nur bei schwersten Mängeln wie widerrechtlichem oder sittenwidrigem Inhalt ein.', teilerklaerungen: [] },
  { id: 'e102223f-442d-458a-9b39-c378dea26555', fachbereich: 'Recht', musterlosung: 'Richtig. Art. 101 StGB listet bestimmte besonders schwere Straftaten auf, die unverjährbar sind — etwa Völkermord, Verbrechen gegen die Menschlichkeit oder sexueller Missbrauch von Kindern unter 12 Jahren. Der Grundsatz der Verjährung nach Art. 97 StGB wird hier also durchbrochen. Die Unverjährbarkeit unterstreicht die besondere Schwere dieser Delikte.', teilerklaerungen: [] },
  { id: 'e1420d57-bb83-4a33-84dc-ec24476bd44b', fachbereich: 'Recht', musterlosung: 'Richtig. Ein Gerichtsentscheid erlangt Rechtskraft, wenn er nicht mehr mit ordentlichen Rechtsmitteln angefochten werden kann. Dies ist der Fall, wenn die Rechtsmittelfrist ungenutzt verstreicht oder die letzte Instanz entschieden hat. Eine ausserordentliche Revision bleibt unter engen Voraussetzungen möglich — die ordentliche Rechtskraft ist damit grundsätzlich abgeschlossen.', teilerklaerungen: [] },
  { id: 'e2bcb885-a69d-4a56-848b-87e814a28244', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 321 muss der Arbeitnehmer die Arbeit persönlich verrichten — die persönliche Arbeitspflicht ist ein Kernmerkmal des Arbeitsvertrags. Eine Übertragung auf Dritte ist wegen der vertrauensbasierten Beziehung grundsätzlich nicht zulässig. Der Arbeitsvertrag unterscheidet sich damit vom Werkvertrag, bei dem nur ein Ergebnis geschuldet ist.', teilerklaerungen: [] },
  { id: 'e415928d-914e-487c-b7ad-b2f8a5df89ed', fachbereich: 'Recht', musterlosung: 'Falsch. In die ganzheitliche Kosten-Nutzen-Rechnung fliessen viele Aspekte ein: Rückfallrisiko und damit verbundene Folgekosten, Aufwand der Strafverfolgung, Leid der Opfer sowie positive Beiträge durch resozialisierte Täter. Eine kostengünstige, aber wenig wirksame Strafe kann langfristig teurer sein als eine aufwendigere Massnahme mit besserer Wiedereingliederung.', teilerklaerungen: [] },
  { id: 'e7a92797-bab2-470f-bae5-a7084ca8f937', fachbereich: 'Recht', musterlosung: 'Richtig. Im öffentlichen Recht sind die Normen zwingend — sie können nicht durch Parteivereinbarung abgeändert werden. Wird ein Straftäter erwischt, muss er die Konsequenzen tragen, unabhängig von seinem Einverständnis. Im Privatrecht hingegen ist vieles dispositiv: Die Parteien können oft abweichende Vereinbarungen treffen, solange zwingende Normen gewahrt bleiben.', teilerklaerungen: [] },
  { id: 'e7bae092-d2a7-434b-b6a9-d4dac0e936d7', fachbereich: 'Recht', musterlosung: 'Falsch. Beim Gesamteigentum hat der einzelne Gesamteigentümer keinen Anteil, über den er allein verfügen kann. Verfügungen über die Sache bedürfen eines einstimmigen Beschlusses aller Gesamteigentümer. Von einem rechnerischen Anteil kann nur als Anwartschaft auf das Liquidationsergebnis bei Auflösung der Gesamthandschaft gesprochen werden — nicht als verfügbares Recht.', teilerklaerungen: [] },
  { id: 'e8797022-b4e2-472d-a526-4880875fc6e0', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 42 StGB können Freiheitsstrafen unter 24 Monaten, Geldstrafen und gemeinnützige Arbeit bedingt ausgesprochen werden. Bussen hingegen sind immer unbedingt. Eine bedingte Strafe kann mit einer unbedingten Geldstrafe oder Busse kombiniert werden — etwa als spürbarer Denkzettel neben der aufgeschobenen Hauptstrafe.', teilerklaerungen: [] },
  { id: 'eb552ac2-ea03-4fcf-9914-b37555af88b3', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 81 und 83 StGB ist die inhaftierte Person zur Arbeit verpflichtet und erhält dafür ein leistungsabhängiges Entgelt. Ein Teil steht zur freien Verfügung, ein anderer wird als Rücklage für die Zeit nach der Entlassung gebildet. Die Arbeitspflicht dient Disziplin, Resozialisierung und Vorbereitung auf ein straffreies Leben.', teilerklaerungen: [] },
  { id: 'eb5ba368-5498-4ac4-b9f8-b8a8e22dcd21', fachbereich: 'Recht', musterlosung: 'Richtig. Das Legalitätsprinzip «nulla poena sine lege» ist ein zentraler Grundsatz des Strafrechts: Eine Person darf nur bestraft werden, wenn ihr Verhalten zum Tatzeitpunkt ausdrücklich unter Strafe stand. Der Grundsatz schützt vor willkürlicher Strafverfolgung und Rückwirkungen. Er ist in Art. 1 StGB und auf Verfassungsebene verankert.', teilerklaerungen: [] },
  { id: 'ec511799-3c2d-4824-8657-ffa6d7765ab5', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 12 StGB ist für eine Bestrafung mindestens Fahrlässigkeit erforderlich. Bei reinem Zufall, wo dem Täter kein Vorwurf gemacht werden kann, bleibt er straffrei. Weder Wissen und Wollen (Vorsatz) noch eine Sorgfaltspflichtverletzung (Fahrlässigkeit) liegen dann vor — die subjektive Seite der Tat fehlt vollständig.', teilerklaerungen: [] },
  { id: 'ed7b3cb5-9921-4274-9fc3-bd8028030e0f', fachbereich: 'Recht', musterlosung: 'Richtig. Das Bundesgericht mit Sitz in Lausanne (Sozialversicherungs- und Strafabteilungen in Luzern) ist das oberste Gericht der Schweiz. Es entscheidet als letzte Instanz über Beschwerden in Zivilsachen, Strafsachen und öffentlich-rechtlichen Angelegenheiten. Es prüft nur noch Rechtsfragen und greift nicht in die Sachverhaltsfeststellung ein.', teilerklaerungen: [] },
  { id: 'edb6daf9-6dbe-4178-afe2-b509907a41c5', fachbereich: 'Recht', musterlosung: 'Richtig. Das Arbeitsrecht enthält viele zwingende Vorschriften zum Schutz des Arbeitnehmers als strukturell schwächerem Vertragspartner. Abweichungen zulasten des Arbeitnehmers sind nichtig, zugunsten sind günstigere Regelungen erlaubt. Diese einseitige Zwingendnatur ist charakteristisch für Schutzgesetze und dient dem Ausgleich der Machtasymmetrie.', teilerklaerungen: [] },
  // RF mit IDs → Teilerklärungen
  { id: 'einr-rf-toolfunktionen', fachbereich: 'Recht', musterlosung: 'Aussage 1 ist richtig: Die Navigation zwischen Fragen ist frei in beide Richtungen möglich. Aussage 2 ist richtig: ExamLab speichert Antworten automatisch alle 30 Sekunden. Aussage 3 ist falsch: Die Reihenfolge der Bearbeitung kann frei gewählt werden. Aussage 4 ist richtig: Der Dark Mode ist in den Einstellungen verfügbar.', teilerklaerungen: [
    { feld: 'aussagen', id: '1', text: 'Richtig: Mit den Pfeil-Buttons oder der Seitenleiste lässt sich jederzeit vor- und zurücknavigieren.' },
    { feld: 'aussagen', id: '2', text: 'Richtig: Die AutoSave-Funktion sichert Antworten alle 30 Sekunden automatisch im Hintergrund.' },
    { feld: 'aussagen', id: '3', text: 'Falsch: Die Bearbeitungsreihenfolge ist frei wählbar, eine Pflichtabfolge besteht nicht.' },
    { feld: 'aussagen', id: '4', text: 'Richtig: Der Dark Mode ist als Farbschema-Option in den Einstellungen aktivierbar.' },
  ] },
  { id: 'f145a6fa-b225-4dd0-acc0-0e450d2cf0ad', fachbereich: 'Recht', musterlosung: 'Falsch. Beim Kauf einer beweglichen Sache spielt die Bezahlung für den Eigentumsübergang keine Rolle. Der Käufer wird nach Art. 714 ZGB Eigentümer, sobald er Besitzer geworden ist — unabhängig davon, ob bar oder auf Rechnung gekauft wird. Bei Zahlungsausfall bleibt dem Verkäufer nur der Weg über die Betreibung.', teilerklaerungen: [] },
  { id: 'f31efc6a-4ef4-47bd-983d-cb4676f2f700', fachbereich: 'Recht', musterlosung: 'Richtig. Art. 28 ZGB stellt den Grundsatz auf, dass jede Verletzung der Persönlichkeit widerrechtlich ist. Die Widerrechtlichkeit entfällt jedoch bei einem Rechtfertigungsgrund: Einwilligung des Verletzten, überwiegendes privates oder öffentliches Interesse oder gesetzliche Erlaubnis. Erst die Interessenabwägung entscheidet im Einzelfall über die Zulässigkeit.', teilerklaerungen: [] },
  { id: 'f544498e-67dd-43c5-9c16-5b0946fbe0bb', fachbereich: 'Recht', musterlosung: 'Falsch. Wurde ein GAV allgemeinverbindlich erklärt, bindet er alle Arbeitgeber und Arbeitnehmer der betreffenden Branche oder Region — unabhängig von der Verbandsmitgliedschaft. Diese Allgemeinverbindlicherklärung (AVE) schützt die Branchenstandards vor Unterbietung durch Aussenseiter. Ohne AVE bindet der GAV nur Mitglieder der abschliessenden Verbände.', teilerklaerungen: [] },
  { id: 'f8725af6-5c1d-44b4-8c89-a6cc8e75c8f5', fachbereich: 'Recht', musterlosung: 'Falsch. Ordnungsbussen werden nicht ins Strafregister eingetragen. Im vereinfachten Ordnungsbussenverfahren kann die Polizei bei geringfügigen Übertretungen vor Ort eine Busse bis CHF 300 erheben. Der Betroffene kann die vereinfachte Erledigung ablehnen und ein ordentliches Verfahren verlangen — nur dann könnte ein Eintrag resultieren.', teilerklaerungen: [] },
  { id: 'f938e4a3-f960-4f02-a003-454f0806e570', fachbereich: 'Recht', musterlosung: 'Falsch. Der Arbeitgeber trägt gestützt auf OR 324a zwar die Lohnfortzahlung bei unverschuldetem Unfall, die Heilungskosten werden jedoch durch die obligatorische Unfallversicherung (UVG) gedeckt. Der Arbeitgeber hat darüber hinaus die Pflicht, sichere Arbeitsbedingungen zu gewährleisten und Schutzvorschriften einzuhalten. Eine unbegrenzte Kostenübernahme besteht nicht.', teilerklaerungen: [] },
  { id: 'fba7fb69-95b8-4482-8927-c94984551b76', fachbereich: 'Recht', musterlosung: 'Richtig. Offizialdelikte werden von Amtes wegen durch die Strafverfolgungsbehörden verfolgt — unabhängig davon, ob das Opfer eine Bestrafung wünscht. Die meisten Straftatbestände sind Offizialdelikte. Antragsdelikte sind die Ausnahme: Sie werden nur auf Strafantrag des Verletzten verfolgt. Die Einordnung ergibt sich aus dem jeweiligen Tatbestand.', teilerklaerungen: [] },
  { id: 'fc9cc741-d822-4e6a-9a1e-77b5959549f4', fachbereich: 'Recht', musterlosung: 'Richtig. Das Bundesgericht wies den Vorwurf der Diskriminierung zurück: Die Wegweisung erfolgte nicht wegen personenspezifischer Merkmale wie Rasse, Geschlecht, Sprache oder Lebensweise, sondern allein wegen des konkreten Verhaltens. Erheblicher Alkoholkonsum, Lärm und grosse Unordnung hatten Passanten belästigt. Damit waren die sachlichen Voraussetzungen für die polizeiliche Wegweisung erfüllt.', teilerklaerungen: [] },
  { id: 'fcc2f521-53d7-421b-bfe8-61132e416526', fachbereich: 'Recht', musterlosung: 'Falsch. Die aktuelle Meinung der Bevölkerung ist kein legitimes öffentliches Interesse. Zulässig sind Polizeigüter wie öffentliche Sicherheit und Ordnung, Gesundheit, Sittlichkeit und Ruhe sowie soziale oder ökologische Werte. Grundrechte schützen gerade auch Minderheiten vor der «Tyrannei der Mehrheit» — blosse Mehrheitsmeinungen rechtfertigen keinen Grundrechtseingriff.', teilerklaerungen: [] },
  { id: 'fe53a0d9-c0ee-4046-9852-cba22e7f51e1', fachbereich: 'Recht', musterlosung: 'Falsch. Nach OR 141 Abs. 1 kann auf die Einrede der Verjährung im Voraus nicht verzichtet werden — ein solcher Verzicht wäre unwirksam. Verspricht ein Schuldner trotzdem, die Einrede nicht zu erheben und macht sie später geltend, kann ihm Rechtsmissbrauch nach Art. 2 Abs. 2 ZGB entgegengehalten werden.', teilerklaerungen: [] },
  { id: 'fff4294a-fe7d-4e84-a594-e8f5387b58c8', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 67 verjährt der Bereicherungsanspruch in drei Jahren seit Kenntnis vom Anspruch (relative Verjährung) und spätestens nach zehn Jahren ab Entstehung (absolute Verjährung). Die doppelte Fristsetzung schützt einerseits den Gläubiger, der Zeit zur Kenntnisnahme braucht, und andererseits den Schuldner vor zeitlich unbegrenzter Haftung.', teilerklaerungen: [] },
  { id: 'ueb-rf-toolfunktionen', fachbereich: 'Recht', musterlosung: 'Aussage 1 ist richtig: Die Navigation zwischen Fragen ist frei in beide Richtungen möglich. Aussage 2 ist richtig: ExamLab speichert Antworten automatisch alle 30 Sekunden. Aussage 3 ist falsch: Die Reihenfolge der Bearbeitung kann frei gewählt werden. Aussage 4 ist richtig: Der Dark Mode ist in den Einstellungen verfügbar.', teilerklaerungen: [
    { feld: 'aussagen', id: '1', text: 'Richtig: Mit den Pfeil-Buttons oder der Seitenleiste lässt sich jederzeit vor- und zurücknavigieren.' },
    { feld: 'aussagen', id: '2', text: 'Richtig: Die AutoSave-Funktion sichert Antworten alle 30 Sekunden automatisch im Hintergrund.' },
    { feld: 'aussagen', id: '3', text: 'Falsch: Die Bearbeitungsreihenfolge ist frei wählbar, eine Pflichtabfolge besteht nicht.' },
    { feld: 'aussagen', id: '4', text: 'Richtig: Der Dark Mode ist als Farbschema-Option in den Einstellungen aktivierbar.' },
  ] },

  // ========== Recht / sortierung (25) ==========
  { id: '00d6a5e6-50c2-4fe4-9fea-30d263476174', fachbereich: 'Recht', musterlosung: 'Die Beweisführung im Zivilprozess folgt einer festen Abfolge: Zuerst wird geklärt, wer die Beweislast trägt — nach Art. 8 ZGB muss beweisen, wer ein Recht geltend macht. Dann werden Beweismittel eingereicht. Das Gericht würdigt sie frei, ohne starre gesetzliche Beweisregeln. Am Ende steht fest, ob die Tatsache bewiesen ist; bei Beweislosigkeit verliert die beweisbelastete Partei.', teilerklaerungen: [] },
  { id: '04679e23-eb85-4bc2-9ee9-8a622748ddc9', fachbereich: 'Recht', musterlosung: 'Die gesetzlichen Kündigungsfristen nach OR 335c staffeln sich nach Dienstjahren: In der Probezeit beträgt die Frist 7 Tage, im 1. Dienstjahr 1 Monat, vom 2. bis 9. Dienstjahr 2 Monate, ab dem 10. Dienstjahr 3 Monate. Die Kündigung erfolgt jeweils auf Ende eines Monats. GAV und Einzelverträge können längere Fristen vorsehen — kürzere nur in der Probezeit.', teilerklaerungen: [] },
  { id: '04ed4ec7-33d1-4c7f-9217-5edbe199210a', fachbereich: 'Recht', musterlosung: 'Die Strenge der Vollzugsformen steigt schrittweise: Der bedingte Vollzug nach Art. 42 StGB ist die mildeste Form — keine Inhaftierung bei Bewährung. Der teilbedingte Vollzug nach Art. 43 StGB kombiniert Strafe und Bewährung. Der unbedingte Vollzug bedeutet tatsächlichen Freiheitsentzug. Die Verwahrung nach Art. 64 StGB ist die schärfste Massnahme — sie ist zeitlich unbefristet und kann lebenslänglich dauern.', teilerklaerungen: [] },
  { id: '1233d2e1-fe84-4ce5-a8ba-885083dce691', fachbereich: 'Recht', musterlosung: 'Das Drei-Sphären-Modell stuft den Persönlichkeitsschutz ab: Die Gemeinsphäre betrifft das öffentliche Auftreten und ist am schwächsten geschützt — Berichterstattung ist oft zulässig. Die Privatsphäre umfasst den persönlichen Lebensbereich und ist stärker geschützt. Die Intimsphäre geniesst den absolut stärksten Schutz; Eingriffe sind nur in Ausnahmefällen und unter strengen Voraussetzungen gerechtfertigt.', teilerklaerungen: [] },
  { id: '1f8732e1-4189-43a0-869e-929602cabdf4', fachbereich: 'Recht', musterlosung: 'Die dreistufige Deliktsprüfung ist das Fundament des Strafrechts: Zuerst prüft man, ob ein Tatbestand erfüllt ist — etwa «wer einen Menschen tötet» nach Art. 111 StGB. Danach wird geprüft, ob ein Rechtfertigungsgrund vorliegt, etwa Notwehr nach Art. 15 StGB. Zuletzt folgt die Schuldprüfung (Schuldfähigkeit, Vorsatz/Fahrlässigkeit). Nur wenn alle drei Stufen bejaht werden, ist die Tat strafbar.', teilerklaerungen: [] },
  { id: '294d7fc7-351d-498a-9da6-9d49a8a2fe7b', fachbereich: 'Recht', musterlosung: 'Der Stufenbau der Rechtsordnung folgt dem Legalitätsprinzip: Die Bundesverfassung steht zuoberst und bildet die Grundlage für alles weitere Recht. Gesetze werden vom Parlament erlassen und konkretisieren die Verfassung. Verordnungen werden vom Bundesrat erlassen und regeln die Details. Weisungen sind behördeninterne Anweisungen ohne direkte Bindungswirkung für Bürger.', teilerklaerungen: [] },
  { id: '3c899948-3ca9-49a2-bf3c-12752276752c', fachbereich: 'Recht', musterlosung: 'Die Mieterrechte bei Mängeln sind nach Eskalationsstufe geordnet: Zuerst muss der Mieter den Mangel schriftlich anzeigen und eine angemessene Frist setzen. Bleibt der Vermieter untätig, kann eine Mietzinsreduktion verlangt werden. Nächste Stufe ist die Ersatzvornahme — der Mieter lässt den Mangel selbst beheben. Die fristlose Kündigung ist das letzte Mittel, nur bei schweren Mängeln zulässig.', teilerklaerungen: [] },
  { id: '4318eb88-0647-49ba-93b4-64122fc67cd5', fachbereich: 'Recht', musterlosung: 'Das Strafgesetzbuch unterscheidet drei Deliktsarten nach Schwere: Übertretungen sind mit Busse bedroht (Art. 103 StGB). Vergehen sind mit Freiheitsstrafe bis 3 Jahre oder Geldstrafe bedroht (Art. 10 Abs. 3 StGB). Verbrechen sind mit Freiheitsstrafe über 3 Jahren bedroht (Art. 10 Abs. 2 StGB). Die Einteilung wirkt sich auf Verjährung, Zuständigkeit und bedingten Vollzug aus.', teilerklaerungen: [] },
  { id: '439f6f58-420f-45b3-9434-4028c757154e', fachbereich: 'Recht', musterlosung: 'Bei einer missbräuchlichen Kündigung muss der Arbeitnehmer zuerst schriftlich Einspruch erheben — vor Ende der Kündigungsfrist. Anschliessend wird eine gütliche Einigung versucht. Scheitert diese, folgt ein obligatorisches Schlichtungsverfahren. Erst danach kann beim Arbeitsgericht geklagt werden — innerhalb von 180 Tagen nach Beendigung des Arbeitsverhältnisses. Die Einhaltung dieser Reihenfolge ist Prozessvoraussetzung.', teilerklaerungen: [] },
  { id: '4a044807-7978-42fd-a8e8-fa14798a3f5d', fachbereich: 'Recht', musterlosung: 'Das OR kennt gestaffelte Verjährungsfristen: 1 Jahr für Gewährleistungsansprüche beim Kauf (OR 210), 2 Jahre für Forderungen aus täglichem Verkehr wie Handwerkerrechnungen, 5 Jahre für periodische Leistungen wie Miete und Zinsen, und 10 Jahre als allgemeine Frist für vertragliche Forderungen (OR 127). Die Verjährung kann durch Schuldanerkennung oder Betreibung unterbrochen werden.', teilerklaerungen: [] },
  { id: '5fa50fba-1bd5-4e6d-9270-c9a1b3837250', fachbereich: 'Recht', musterlosung: 'Im Arbeitsrecht gilt eine klare Normenhierarchie: Die Bundesverfassung steht zuoberst und garantiert die arbeitsbezogenen Grundrechte. Danach folgen die Bundesgesetze — OR für den Arbeitsvertrag, ArG für den Arbeitsschutz. GAV-Bestimmungen gehen dem Einzelvertrag vor, dürfen aber nicht gegen zwingendes Gesetzesrecht verstossen. Der Einzelvertrag darf nur zugunsten des Arbeitnehmers vom GAV abweichen.', teilerklaerungen: [] },
  { id: '7172b2b3-25e0-4c8a-bafa-e61aa5c4e461', fachbereich: 'Recht', musterlosung: 'Die Schweizer Rechtsordnung entwickelte sich schrittweise: 1848 entstand der moderne Bundesstaat mit der ersten Bundesverfassung. 1874 wurde sie totalrevidiert und brachte mehr direkte Demokratie. 1912 trat das ZGB in Kraft und vereinheitlichte das zuvor kantonale Zivilrecht. 1999 wurde die aktuelle BV verabschiedet (in Kraft 2000) — primär als Nachführung ohne grosse inhaltliche Änderungen.', teilerklaerungen: [] },
  { id: '75a64ef3-07fa-4fb5-a35d-3f687cf77056', fachbereich: 'Recht', musterlosung: 'Die Prüfung nach Art. 36 BV folgt einer festen Reihenfolge: (1) Besteht eine gesetzliche Grundlage? (2) Liegt ein öffentliches Interesse vor? (3) Ist der Eingriff verhältnismässig (geeignet, erforderlich, zumutbar)? (4) Wird der Kerngehalt gewahrt? Fehlt eine Voraussetzung, ist die Einschränkung verfassungswidrig. Das Folterverbot ist ein klassischer absoluter Kerngehalt.', teilerklaerungen: [] },
  { id: '75fe2311-1849-4cc4-bf87-63317c0ce976', fachbereich: 'Recht', musterlosung: 'Vor jedem Zivilprozess muss grundsätzlich ein Schlichtungsversuch stattfinden (Ausnahmen z.B. bei hohem Streitwert). Scheitert die Schlichtung, wird beim erstinstanzlichen Gericht Klage erhoben. Gegen das Urteil ist die Berufung beim Obergericht möglich. Das Bundesgericht ist die letzte Instanz — es prüft nur noch Rechtsfragen, nicht den Sachverhalt. Der Instanzenzug sichert gerichtliche Kontrolle.', teilerklaerungen: [] },
  { id: '791ba5e6-4148-45b4-8e5b-33cd4af1d8d9', fachbereich: 'Recht', musterlosung: 'Beim Grundstückkauf ist der Vertrag formgebunden: Er muss öffentlich beurkundet werden (OR 216). Nach Vertragsabschluss folgt die Anmeldung beim Grundbuchamt. Das Eigentum geht nach Art. 656 ZGB erst mit dem konstitutiven Grundbucheintrag über — nicht schon mit Vertragsabschluss. Dies unterscheidet sich von beweglichen Sachen, bei denen das Eigentum mit der Besitzübergabe übergeht.', teilerklaerungen: [] },
  { id: '8628fa88-273a-4c9f-9b8e-19d39080e74e', fachbereich: 'Recht', musterlosung: 'Ein Vertrag entsteht nach OR 1 ff. durch Antrag und Annahme. Die Parteien müssen sich über alle wesentlichen Punkte einig sein (Konsens). Zusätzlich müssen die Gültigkeitsvoraussetzungen erfüllt sein: Handlungsfähigkeit nach Art. 12 ff. ZGB, allfällige Formvorschriften nach OR 11 ff. und zulässiger Inhalt nach OR 19/20. Erst bei Erfüllung aller Voraussetzungen ist der Vertrag gültig zustande gekommen.', teilerklaerungen: [] },
  { id: '88236de8-2912-442b-a3ea-368bffb9e8c0', fachbereich: 'Recht', musterlosung: 'Der internationale Menschenrechtsschutz entwickelte sich nach dem Zweiten Weltkrieg: Die AEMR von 1948 war die erste universelle Erklärung — rechtlich nicht bindend, aber mit grosser Autorität. Die EMRK von 1950 schuf verbindlichen regionalen Schutz mit dem EGMR. Die UNO-Pakte von 1966 machten Menschenrechte völkerrechtlich verbindlich. Die aktuelle Schweizer BV von 1999 enthält einen modernen Grundrechtskatalog.', teilerklaerungen: [] },
  { id: '8dc234fb-ce9f-4077-92b5-dac4c7dc1030', fachbereich: 'Recht', musterlosung: 'Die Handlungsfähigkeit ist abgestuft: Handlungsunfähige können gar keine gültigen Rechtsgeschäfte tätigen. Beschränkt Handlungsunfähige — meist Kinder — können nur Geschäfte vornehmen, die ihnen ausschliesslich Vorteile bringen, etwa ein Geschenk annehmen. Beschränkt Handlungsfähige dürfen zudem über ihr Taschengeld oder ihren Lohn frei verfügen. Volle Handlungsfähigkeit setzt Volljährigkeit (18) und Urteilsfähigkeit voraus.', teilerklaerungen: [] },
  { id: 'ad2f62f3-1faf-465b-ad5c-0bde1f4738b0', fachbereich: 'Recht', musterlosung: 'Eine wirksame Kündigung erfordert die Einhaltung der Kündigungsfrist (3 Monate für Wohnungen nach OR 266c) und das amtliche Formular. Bei Familienwohnungen muss der Ehepartner zustimmen (OR 266n). Nach Zustellung kann der Mieter die Kündigung anfechten (Missbrauchsprüfung) oder eine Erstreckung beantragen (OR 272 ff.). Die Formvorschriften sind zwingend; ein Verstoss führt zur Ungültigkeit.', teilerklaerungen: [] },
  { id: 'b7fec22f-42da-48e2-9e92-dad8bc3e21c5', fachbereich: 'Recht', musterlosung: 'Streitbeilegungsformen reichen von informell bis hochformalisiert: Die direkte Verhandlung ist die einfachste und formloseste Form. Die Mediation ist freiwillig und konsensorientiert. Die Schlichtung ist in der Schweiz vor Zivilklagen obligatorisch. Schiedsgerichte werden vertraglich vereinbart und fällen bindende Entscheide — oft im internationalen Handel. Das staatliche Gericht ist die formellste und letzte Option.', teilerklaerungen: [] },
  { id: 'c64f01e5-a29a-407d-8af8-4a08d7a9df9b', fachbereich: 'Recht', musterlosung: 'Die Rechtsanwendung folgt einem festen Schema: Zuerst wird der Sachverhalt geklärt — was genau ist geschehen? Danach sucht man die passende Rechtsnorm. Im dritten Schritt erfolgt die Subsumtion — die Tatbestandsmerkmale werden einzeln geprüft und mit dem Sachverhalt abgeglichen. Zuletzt bestimmt man die Rechtsfolge. Dieses Vorgehen heisst auch «juristischer Syllogismus».', teilerklaerungen: [] },
  { id: 'c7db7648-28c7-492e-b9c8-f6b18ffd89f5', fachbereich: 'Recht', musterlosung: 'Art. 1 ZGB legt die Anwendungsreihenfolge der Rechtsquellen fest: Zuerst ist das geschriebene Gesetz anzuwenden — nach Wortlaut und Sinn. Fehlt eine Bestimmung, greift der Richter auf Gewohnheitsrecht zurück. Erst wenn auch dieses fehlt, entscheidet der Richter nach der Regel, die er als Gesetzgeber aufstellen würde. Dabei folgt er bewährter Lehre und Überlieferung.', teilerklaerungen: [] },
  { id: 'ceb1e22d-cf9b-4c7e-8c8c-3e2fd6bddfbd', fachbereich: 'Recht', musterlosung: 'Beim Schuldnerverzug muss der Gläubiger systematisch vorgehen: Die Leistung muss fällig sein. Dann muss gemahnt werden — ausser bei einem vereinbarten Verfalltag, bei dem der Verzug automatisch eintritt. Danach setzt der Gläubiger eine Nachfrist. Nach deren Ablauf hat er drei Wahlmöglichkeiten: weiterhin Erfüllung verlangen, Schadenersatz wegen Nichterfüllung fordern oder vom Vertrag zurücktreten.', teilerklaerungen: [] },
  { id: 'd6a5a615-3300-47f6-a25d-6ace516a4bf6', fachbereich: 'Recht', musterlosung: 'Die dinglichen Rechte staffeln sich nach Umfang: Eigentum ist nach Art. 641 ZGB das umfassendste Recht — der Eigentümer kann mit der Sache im Rahmen des Gesetzes tun, was er will. Die Nutzniessung gibt das Recht auf Nutzung und Erträge, nicht aber auf Veräusserung. Das Wohnrecht ist enger — es umfasst nur das Wohnen. Grunddienstbarkeiten sind am eingeschränktesten, etwa ein Durchgangsrecht.', teilerklaerungen: [] },
  { id: 'fbb38480-d08a-4fe6-a883-651ce53fdb91', fachbereich: 'Recht', musterlosung: 'Das Strafverfahren beginnt mit dem Vorverfahren: Die Polizei ermittelt, die Staatsanwaltschaft untersucht. Bei ausreichender Beweislage wird Anklage erhoben. Es folgt die Hauptverhandlung mit Beweisaufnahme und Plädoyers. Das Gericht fällt ein Urteil. Gegen das Urteil ist die Berufung beim kantonalen Obergericht oder die Beschwerde beim Bundesgericht möglich. Die einzelnen Phasen sind strukturell getrennt.', teilerklaerungen: [] },

  // ========== Recht / visualisierung (3) ==========
  { id: 'b056aca9-6dae-4b61-b976-e4f0b00bd54e', fachbereich: 'Recht', musterlosung: 'Die Normenhierarchie wird als Pyramide gezeichnet: An der Spitze die Bundesverfassung, darunter die Bundesgesetze (OR, ZGB, StGB), dann die Verordnungen des Bundesrates und der Departemente, zuunterst allfällige Weisungen und Gewohnheitsrecht. Das Prinzip «lex superior derogat legi inferiori» bedeutet: Höherrangiges Recht geht niederrangigem vor. Widerspricht eine Verordnung dem Gesetz, gilt das Gesetz.', teilerklaerungen: [] },
  { id: 'c1a1003d-ede6-4227-89c5-0bd69ef5c170', fachbereich: 'Recht', musterlosung: 'Ein Vertrag nach OR 1 kommt durch übereinstimmende gegenseitige Willenserklärung zustande. Partei A macht einen Antrag (Offerte), Partei B erklärt die Annahme (Akzept). Stimmen beide Willenserklärungen überein — Konsens —, ist der Vertrag geschlossen. Nach OR 11 bedürfen Verträge nur dann einer besonderen Form, wenn das Gesetz sie vorschreibt. Grundsätzlich gilt Formfreiheit.', teilerklaerungen: [] },
  { id: 'einr-vis-smiley', fachbereich: 'Recht', musterlosung: 'Gefordert ist ein erkennbarer Smiley, gezeichnet mit mindestens zwei verschiedenen Werkzeugen der Zeichenfläche — etwa Kreis für das Gesicht und Stift für die Augen, oder Linie und Text. Die Aufgabe ist eine Werkzeug-Exploration: Die Bewertung achtet auf die Erkennbarkeit des Smileys und den Einsatz unterschiedlicher Werkzeuge. Farbvariationen sind ausdrücklich erwünscht.', teilerklaerungen: [] },

  // ========== VWL / audio (2) ==========
  { id: 'einr-audio-vorstellen', fachbereich: 'VWL', musterlosung: 'Freie Audio-Antwort mit drei inhaltlichen Pflichtelementen: Name, Lieblingsfach und ein Fun Fact über sich selbst. Die Aufnahme darf maximal 60 Sekunden dauern. Die Bewertung berücksichtigt Verständlichkeit der Sprache, Vollständigkeit der drei Inhaltsbausteine sowie Sprachqualität insgesamt. Die Aufgabe dient zugleich als Funktionstest der Audio-Aufnahme.', teilerklaerungen: [] },
  { id: 'ueb-audio-vorstellen', fachbereich: 'VWL', musterlosung: 'Freie Audio-Antwort mit drei inhaltlichen Pflichtelementen: Name, Lieblingsfach und ein Fun Fact über sich selbst. Die maximale Aufnahmezeit beträgt 60 Sekunden. Bewertet werden Verständlichkeit der Sprache und die Vollständigkeit der Inhalte. Die Aufgabe dient dem Kennenlernen der Audio-Aufnahme-Funktion und ist inhaltlich offen.', teilerklaerungen: [] },

  // ========== VWL / berechnung (12) ==========
  { id: '016082fa-b52b-4672-8005-efc93794b673', fachbereich: 'VWL', musterlosung: 'Die 70er-Regel besagt: Verdopplungszeit ≈ 70 / Wachstumsrate. Bei einer jährlichen Wachstumsrate des BIP pro Kopf von 2% ergibt sich 70 / 2 = 35 Jahre. Das BIP pro Kopf verdoppelt sich somit in rund 35 Jahren. Die Regel basiert auf der logarithmischen Näherung für Zinseszins-Wachstum und eignet sich für schnelle Abschätzungen.', teilerklaerungen: [] },
  { id: '1aa14f9f-4e6d-43cd-b262-97ad178aea19', fachbereich: 'VWL', musterlosung: 'Land X verdoppelt sein BIP pro Kopf alle 70/5 = 14 Jahre, Land Y alle 70/1 = 70 Jahre. Nach 28 Jahren hat Land X zweimal verdoppelt: 20\'000 → 40\'000 → 80\'000. Land Y wächst in 28 Jahren nur auf rund 79\'000. Die Konvergenz zeigt: Hohe Wachstumsraten ärmerer Länder können den Abstand zu reichen Ländern deutlich verringern.', teilerklaerungen: [] },
  { id: '1ab482de-1c04-405d-b522-60b9817efd60', fachbereich: 'VWL', musterlosung: 'Der AHV-Gesamtbeitrag beträgt 8.7% von CHF 6\'000 = CHF 522. Die Arbeitnehmerin trägt die Hälfte: 4.35% von CHF 6\'000 = CHF 261. Der Arbeitgeber trägt ebenfalls CHF 261. Die paritätische Finanzierung ist typisch für die schweizerische Sozialversicherung — beide Parteien zahlen hälftig den obligatorischen AHV-Beitrag.', teilerklaerungen: [] },
  { id: '5408f591-f525-4dcd-948e-da531532dc70', fachbereich: 'VWL', musterlosung: 'Die Anzahl der Tauschverhältnisse berechnet sich mit der Formel n × (n − 1) / 2. Bei 5 Gütern: 5 × 4 / 2 = 10 Tauschverhältnisse. Mit einer gemeinsamen Recheneinheit genügen hingegen 5 absolute Preise. Bei 100 Gütern wären es 4\'950 Tauschverhältnisse statt 100 Preise — dies verdeutlicht den enormen Nutzen der Recheneinheitsfunktion des Geldes.', teilerklaerungen: [] },
  { id: '5cfb8b98-3ec4-4690-90c5-4a3ac140066d', fachbereich: 'VWL', musterlosung: 'Die Fiskalquote berechnet sich als Steuereinnahmen geteilt durch BIP in Prozent: 224 Mrd. / 800 Mrd. × 100 = 28%. Diese Quote misst den Anteil der Steuereinnahmen an der Wirtschaftsleistung. Die Schweiz weist mit rund 28% eine international tiefe Fiskalquote auf — im Vergleich zu Schweden (ca. 43%) oder Deutschland (ca. 38%) deutlich niedriger.', teilerklaerungen: [] },
  { id: '5ff583f5-eec9-4c07-a1a6-9242cf8fe23d', fachbereich: 'VWL', musterlosung: 'Das BIP pro Einwohner setzt sich aus Arbeitseinsatz und Produktivität zusammen: (1 + 0.25) × (1 − 0.07) = 1.25 × 0.93 = 1.1625, also rund +16%. Trotz gesunkenem Arbeitseinsatz ist das BIP pro Einwohner gestiegen. Der gesamte Wohlstandszuwachs von 2000 bis 2018 stammt aus der Produktivitätssteigerung — nicht aus mehr Arbeit.', teilerklaerungen: [] },
  { id: '7243f5a1-afb5-4011-be22-2e99b2adfb8f', fachbereich: 'VWL', musterlosung: 'Das S80/S20-Verhältnis ist der Quotient aus Einkommensanteil der reichsten 20% und Einkommensanteil der ärmsten 20%: 45% / 5% = 9. Die reichsten 20% verdienen neunmal so viel wie die ärmsten 20%. Je höher der Wert, desto ungleicher die Verteilung. Das Verhältnis ist ein verbreiteter Indikator zur Messung von Einkommensungleichheit.', teilerklaerungen: [] },
  { id: '76a29072-5e2d-42ec-a777-718df8f7f8a2', fachbereich: 'VWL', musterlosung: 'Der Durchschnittssteuersatz ist der Quotient aus Steuerbetrag und steuerbarem Einkommen in Prozent: 12\'000 / 80\'000 × 100 = 15%. Diese Person liefert im Durchschnitt 15 Rappen pro verdienten Franken als Einkommenssteuer ab. Der Durchschnittssteuersatz ist vom Grenzsteuersatz zu unterscheiden: Letzterer bezeichnet die Belastung des nächsten zusätzlichen Einkommensfrankens.', teilerklaerungen: [] },
  { id: '852a5688-a336-4c20-a196-48b00ba58424', fachbereich: 'VWL', musterlosung: 'Nach der 70er-Regel ergibt sich: 70 / 6.5 ≈ 10.8 Jahre. Bei einer jährlichen Wachstumsrate von 6.5% verdoppelt sich das BIP pro Kopf in knapp 11 Jahren. Dies erklärt den rasanten Wohlstandszuwachs Chinas zwischen 2012 und 2019 — hohe Wachstumsraten führen bei Zinseszins-Logik zu enormen langfristigen Effekten.', teilerklaerungen: [] },
  { id: '8a8ee0d6-1b4e-490b-bf45-71acd98e57c2', fachbereich: 'VWL', musterlosung: 'Die Staatsausgaben ergeben sich aus Staatsquote × BIP = 35% × 600 Mrd. = CHF 210 Mrd. Die Staatseinnahmen ergeben sich aus Fiskalquote × BIP = 30% × 600 Mrd. = CHF 180 Mrd. Die Fiskalquote umfasst alle Zwangsabgaben — Steuern und Sozialversicherungsbeiträge. Das Haushaltsdefizit beträgt somit 210 − 180 = CHF 30 Mrd.', teilerklaerungen: [] },
  { id: '90bb37f5-4c9e-4833-b172-188b9b417779', fachbereich: 'VWL', musterlosung: 'Die Preiselastizität der Nachfrage ist der Quotient aus prozentualer Mengenänderung und prozentualer Preisänderung: 4% / 10% = 0.4. Da der Wert kleiner als 1 ist, ist die Nachfrage unelastisch. Benzin hat wenige Substitute — Konsumenten reduzieren den Verbrauch bei Preiserhöhungen nur geringfügig. Unelastische Nachfrage ist typisch für Grundbedürfnisse ohne nahe Ersatzprodukte.', teilerklaerungen: [] },
  { id: '95d7cc6b-a1c1-41fd-a061-6f083cb7082c', fachbereich: 'VWL', musterlosung: 'Der Nettoexport ist Exporte minus Importe: 250 − 200 = CHF 50 Mrd. Das BIP nach Verwendungsansatz ergibt sich aus Konsum + Investitionen + Staatsausgaben + Nettoexport: 400 + 150 + 100 + 50 = CHF 700 Mrd. Die Formel BIP = C + I + G + NX ist die klassische Zerlegung der Endverwendung einer Volkswirtschaft.', teilerklaerungen: [] },
]

// === Runner ===
async function main() {
  const lines = updates.map(u => JSON.stringify(u)).join('\n') + '\n'
  await fs.appendFile(OUT, lines)

  const state = JSON.parse(await fs.readFile(STATE, 'utf8'))
  const now = new Date().toISOString()
  for (const u of updates) {
    state.fragen[u.id] = { status: 'done', zeitpunkt: now, teile: u.teilerklaerungen.length }
  }
  state.verarbeitet += updates.length
  state.letzteSession = now
  await fs.writeFile(STATE, JSON.stringify(state, null, 2))

  const withTeile = updates.filter(u => u.teilerklaerungen.length > 0).length
  console.log(`Session 9: ${updates.length} Fragen appended (${withTeile} mit Teilerklärungen, ${updates.length - withTeile} ohne).`)
  console.log(`Total verarbeitet: ${state.verarbeitet} / ${state.totalFragen}`)
}

main().catch(err => { console.error(err); process.exit(1) })
