#!/usr/bin/env node
/**
 * Session 10: 100 VWL-Fragen
 * Verteilung: 12 berechnung + 11 bildbeschriftung + 11 dragdrop_bild + 4 formel + 62 freitext
 *
 * Teilerklärungen nur für bildbeschriftung (beschriftungen) + dragdrop_bild (zielzonen).
 * Berechnung/formel/freitext: keine Sub-Struktur → [].
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'fragen-updates.jsonl')
const STATE = path.join(__dirname, 'state.json')

const updates = [
  // ========== VWL / berechnung (12) — keine Sub-Struktur ==========
  { id: 'a7552026-712a-4ab1-98c4-465e68ab65de', fachbereich: 'VWL', musterlosung: 'Die Soziallastquote ergibt sich aus Sozialversicherungseinnahmen dividiert durch das BIP: 182 / 670 × 100 ≈ 27.2%. Von jedem erwirtschafteten Franken fliessen also rund 27 Rappen in die soziale Sicherheit. Die Kennzahl misst, wie stark eine Volkswirtschaft durch Sozialabgaben belastet ist, und ermöglicht internationale Vergleiche.', teilerklaerungen: [] },
  { id: 'a7fbf370-5cc9-424c-905c-c6ed1a4fc2a8', fachbereich: 'VWL', musterlosung: 'Land A investiert 500 × 0.15 = 75 Mrd. CHF, Land B 200 × 0.40 = 80 Mrd. CHF. Obwohl Land B ein deutlich kleineres BIP hat, ist sein absoluter Investitionsbetrag höher. Eine hohe Investitionsquote ist ein zentraler Treiber für rasches Wachstum — so lässt sich der Aufholprozess von Ländern wie China erklären.', teilerklaerungen: [] },
  { id: 'c258f7ec-3b74-470f-9b82-07ecfc4515be', fachbereich: 'VWL', musterlosung: 'Land A: 60\'000 × 0.85 = 51\'000 USD (das hohe Preisniveau reduziert die Kaufkraft). Land B: 25\'000 × 1.6 = 40\'000 USD (tiefes Preisniveau erhöht die Kaufkraft). Die nominale Differenz von 35\'000 USD schrumpft nach PPP-Bereinigung auf 11\'000 USD. PPP-Faktoren machen Wohlstandsvergleiche zwischen Ländern aussagekräftiger.', teilerklaerungen: [] },
  { id: 'd9814aaa-ddcb-46f3-aaaf-84669cddcd9d', fachbereich: 'VWL', musterlosung: 'Die Verrechnungssteuer beträgt 35% von CHF 2\'000 = CHF 700. Die Anlegerin erhält somit CHF 1\'300 ausbezahlt. Bei korrekter Deklaration in der Steuererklärung kann sie die CHF 700 vollständig zurückfordern — die Verrechnungssteuer dient primär als Sicherungssteuer gegen Steuerhinterziehung, nicht als endgültige Belastung.', teilerklaerungen: [] },
  { id: 'dba4a081-d54f-498d-99d2-8b4184670a9c', fachbereich: 'VWL', musterlosung: 'Ohne Reduktion: 1\'000 × 120 = CHF 120\'000 Abgabe. Mit Reduktion: 800 × 120 = CHF 96\'000 Abgabe + 200 × 100 = CHF 20\'000 Vermeidungskosten = CHF 116\'000. Die Einsparung beträgt CHF 4\'000. Die Reduktion lohnt sich, weil die Vermeidungskosten pro Tonne (CHF 100) unter der Abgabe (CHF 120) liegen — genau dieser Anreiz ist gewollt.', teilerklaerungen: [] },
  { id: 'e25c8109-eb20-483b-ad63-20150738a8bd', fachbereich: 'VWL', musterlosung: 'Erwerbspersonen: 5 Mio. × 0.70 = 3.5 Mio. Arbeitsstunden: 3.5 Mio. × 1\'600 = 5\'600 Mio. Stunden. BIP: 5\'600 Mio. × CHF 80 = CHF 448 Mrd. BIP pro Kopf: 448 Mrd. / 5 Mio. = CHF 89\'600. Die Formel zeigt: Wohlstand ergibt sich aus Arbeitseinsatz und Produktivität — beide Grössen sind Stellhebel für wirtschaftspolitische Massnahmen.', teilerklaerungen: [] },
  { id: 'e2656896-0b08-44bf-aef4-6817bc2ad46a', fachbereich: 'VWL', musterlosung: 'Steuereinnahmen: CHF 2 × 90 = CHF 180. Konsumenten zahlen CHF 11 statt CHF 10, tragen also 1 Franken = 50% der Steuerlast. Produzenten erhalten CHF 9 statt CHF 10, tragen ebenfalls 50%. In diesem Beispiel teilen sich beide Seiten die Last gleich — die tatsächliche Aufteilung hängt von den Elastizitäten ab, nicht vom gesetzlichen Steuerschuldner.', teilerklaerungen: [] },
  { id: 'f2c89e0c-a422-4512-9e20-178b25a37c3a', fachbereich: 'VWL', musterlosung: 'Bei proportionalem Anstieg wäre der Reallohn 25\'000 × 2 = USD 50\'000. Tatsächlich liegt er bei USD 27\'000, die Lücke beträgt USD 23\'000. Diese Differenz floss in Kapitalerträge, Managergehälter und Unternehmensgewinne. Seit den 1970er-Jahren entkoppelt sich der Medianlohn in den USA von der Produktivität — ein Kernelement der Debatte um wachsende Ungleichheit.', teilerklaerungen: [] },
  { id: 'f41dad37-031c-444e-9b0f-7d9d5d90faac', fachbereich: 'VWL', musterlosung: '5 / 1.8 ≈ 2.8 Planeten. Würde die gesamte Weltbevölkerung wie in der Schweiz konsumieren, bräuchte es fast drei Erden, um den ökologischen Fussabdruck nachhaltig zu decken. Die Zahl illustriert, dass der Schweizer Lebensstil global nicht verallgemeinerbar ist — der Global Footprint Network berechnet diese Quote jährlich.', teilerklaerungen: [] },
  { id: 'faa191e4-e49d-4af0-82db-befa06273808', fachbereich: 'VWL', musterlosung: 'Reales BIP = nominales BIP / Preisindex × 100 = 800 / 105 × 100 ≈ CHF 761.9 Mrd. Die Inflation beträgt 105 − 100 = 5%. Das reale BIP eliminiert den Preiseffekt und zeigt die tatsächliche Mengenentwicklung der Produktion. Nur reale Grössen erlauben aussagekräftige Wachstumsvergleiche über die Zeit.', teilerklaerungen: [] },
  { id: 'fb9d20e0-daba-4ee6-9ed1-769d91b83c10', fachbereich: 'VWL', musterlosung: 'Die Preiselastizität des Angebots ist der Quotient aus Mengenänderung und Preisänderung. Umgeformt: Mengenänderung = 0.3 × 20% = 6%. Bei einem Preisanstieg um 20% erhöht sich das Weizenangebot also um 6%. Da der Wert unter 1 liegt, ist das Angebot unelastisch — typisch für Agrargüter mit saisonalen Produktionszyklen und begrenzten Anbauflächen.', teilerklaerungen: [] },
  { id: 'fe86e0d5-bc94-4981-8107-4c9af7ca9fc9', fachbereich: 'VWL', musterlosung: '1 Kuchen kostet 20 Kilo Salz, 1 Apfel 1 Kilo Salz. Somit entspricht 1 Kuchen = 20 / 1 = 20 Äpfeln. Die gemeinsame Recheneinheit Salz erlaubt einen einfachen Vergleich aller Preise. Dies ist die Recheneinheitsfunktion des Geldes — ohne sie müssten für n Güter n × (n−1) / 2 Tauschverhältnisse gemerkt werden.', teilerklaerungen: [] },

  // ========== VWL / bildbeschriftung (11) — mit Teilerklärungen pro Label ==========
  { id: '110d7200-0a81-4c32-8a24-7e3bad5d7110', fachbereich: 'VWL', musterlosung: 'Der Konjunkturzyklus beschreibt die Schwankungen des BIP um das langfristige Wachstumspotenzial. Auf den Aufschwung folgt die Hochkonjunktur mit positiver Outputlücke, dann Abschwung und Rezession mit negativer Outputlücke. Die Trendlinie zeigt das Produktionspotenzial — die langfristige Wachstumskapazität der Volkswirtschaft.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: 'Die Trendlinie zeigt das langfristige Produktionspotenzial — die nachhaltige Wachstumskapazität ohne Überhitzung oder Unterauslastung.' },
    { feld: 'beschriftungen', id: 'l2', text: 'Im Aufschwung steigt das BIP zurück Richtung Trend, Investitionen und Beschäftigung nehmen zu.' },
    { feld: 'beschriftungen', id: 'l3', text: 'In der Hochkonjunktur (Boom) liegt das BIP über dem Trend, es entsteht eine positive Outputlücke mit Inflationsdruck.' },
    { feld: 'beschriftungen', id: 'l4', text: 'Im Abschwung fällt das BIP zum Trend zurück, Aufträge und Gewinne gehen zurück.' },
    { feld: 'beschriftungen', id: 'l5', text: 'In der Rezession liegt das BIP unter dem Trend — negative Outputlücke mit steigender Arbeitslosigkeit.' },
  ] },
  { id: '15831779-78ba-4a59-9856-3da27542b640', fachbereich: 'VWL', musterlosung: 'Die Geldmengenaggregate sind ineinander geschachtelt und nach abnehmender Liquidität geordnet. M0 ist die monetäre Basis (Notenbankgeld), M1 das unmittelbar verfügbare Transaktionsgeld, M2 ergänzt Spareinlagen, M3 zusätzlich Termineinlagen. Die SNB steuert primär M0 und beobachtet M1–M3 als Indikatoren der Geldschöpfung im Bankensystem.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: 'M0 umfasst Notenbankgeld: Bargeld im Umlauf plus Giroguthaben der Banken bei der SNB.' },
    { feld: 'beschriftungen', id: 'l2', text: 'M1 ist das Transaktionsgeld: Bargeld plus Sichteinlagen der Haushalte und Unternehmen.' },
    { feld: 'beschriftungen', id: 'l3', text: 'M2 erweitert M1 um Spareinlagen — weniger liquide, aber jederzeit verfügbar.' },
    { feld: 'beschriftungen', id: 'l4', text: 'M3 umfasst M2 plus Termineinlagen mit fester Laufzeit, das breiteste Geldmengenaggregat.' },
  ] },
  { id: '1aaf27e4-137d-4cd5-9e68-c362a3ce99be', fachbereich: 'VWL', musterlosung: 'Die Bedürfnispyramide nach Maslow (1943) ordnet Bedürfnisse hierarchisch: Erst wenn tiefere Stufen befriedigt sind, werden höhere aktiv. Grundbedürfnisse und Sicherheit bilden die Basis, darauf folgen soziale Bedürfnisse, Wertschätzung und an der Spitze Selbstverwirklichung. Das Modell ist eine didaktische Vereinfachung — in der Praxis können mehrere Stufen parallel wirken.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: 'Grundbedürfnisse sind physiologisch: Nahrung, Wasser, Schlaf, Wärme — die biologische Basis des Überlebens.' },
    { feld: 'beschriftungen', id: 'l2', text: 'Sicherheitsbedürfnisse umfassen Schutz vor Gefahren: Wohnung, Gesundheit, Arbeitsplatz, Versicherungen.' },
    { feld: 'beschriftungen', id: 'l3', text: 'Soziale Bedürfnisse betreffen Zugehörigkeit: Familie, Freundschaft, Partnerschaft.' },
    { feld: 'beschriftungen', id: 'l4', text: 'Wertschätzung bedeutet Anerkennung durch andere und Selbstachtung — Status, Erfolg, Respekt.' },
    { feld: 'beschriftungen', id: 'l5', text: 'Selbstverwirklichung ist persönliches Wachstum, Kreativität und das Ausschöpfen des eigenen Potenzials.' },
  ] },
  { id: '2b6f3529-c274-4268-9d20-34f36ce2f825', fachbereich: 'VWL', musterlosung: 'Die Schweiz kennt ein dreistufiges Steuersystem: Bund, Kantone und Gemeinden erheben je eigene Steuern. Der Bund erhebt direkte Bundessteuer und MWST, die Kantone Einkommens- und Vermögenssteuer mit eigenen Steuerfüssen, die Gemeinden einen Zuschlag auf die Kantonssteuer. Diese föderale Struktur erzeugt Steuerwettbewerb zwischen Kantonen.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: 'Die Bundesebene ist die oberste Stufe und erhebt gesamtschweizerische Steuern.' },
    { feld: 'beschriftungen', id: 'l2', text: 'Direkte Bundessteuer (auf Einkommen) und MWST sind die wichtigsten Bundessteuern.' },
    { feld: 'beschriftungen', id: 'l3', text: 'Die Kantonsebene erhebt autonom Steuern nach eigenen Tarifen und Steuerfüssen.' },
    { feld: 'beschriftungen', id: 'l4', text: 'Einkommens- und Vermögenssteuer sind die zentralen kantonalen Steuerarten und Hauptquelle des Steuerwettbewerbs.' },
    { feld: 'beschriftungen', id: 'l5', text: 'Die Gemeindeebene ist die unterste Stufe — sie schöpft lokale Steuern ab.' },
    { feld: 'beschriftungen', id: 'l6', text: 'Der Gemeindesteuerzuschlag wird prozentual auf die Kantonssteuer aufgeschlagen und finanziert Gemeindeaufgaben.' },
  ] },
  { id: '566e588b-d5d5-48ed-a8d8-537718bdc89d', fachbereich: 'VWL', musterlosung: 'Das BIP nach Verwendungsseite zerlegt die Endverwendung aller Güter und Dienstleistungen einer Volkswirtschaft. Die Formel lautet Y = C + I + G + NX: privater Konsum (ca. 52%), Investitionen (ca. 25%), staatlicher Konsum (ca. 12%) und Nettoexporte (ca. 11% in der Schweiz). Diese Perspektive zeigt, wer die produzierten Güter schlussendlich nachfragt.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: 'Privater Konsum (C) ist der grösste BIP-Bestandteil — Haushaltsausgaben für Güter und Dienstleistungen.' },
    { feld: 'beschriftungen', id: 'l2', text: 'Staatlicher Konsum (G) umfasst Ausgaben des Staates für Verwaltung, Bildung, Sicherheit.' },
    { feld: 'beschriftungen', id: 'l3', text: 'Investitionen (I) sind Ausgaben für Produktionsanlagen, Maschinen, Bauten und Lagerhaltung.' },
    { feld: 'beschriftungen', id: 'l4', text: 'Nettoexporte (NX) sind Exporte minus Importe — ein Überschuss erhöht das inländische BIP.' },
    { feld: 'beschriftungen', id: 'l5', text: 'Y = C + I + G + NX ist die klassische Zerlegung des BIP von der Verwendungsseite.' },
  ] },
  { id: '7e0035ba-a3f4-4fa2-89e7-af1d93a98250', fachbereich: 'VWL', musterlosung: 'Die Schweizer Schuldenbremse (seit 2003) verpflichtet den Bund, Ausgaben und Einnahmen über den Konjunkturzyklus auszugleichen. Der Konjunkturfaktor k korrigiert den Ausgabenplafond: im Boom (k < 1) Pflicht zu Überschüssen, in der Rezession (k > 1) sind Defizite erlaubt. Das Ausgleichskonto überwacht die Einhaltung über die Jahre.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: 'Der Konjunkturfaktor k bildet die Konjunkturlage ab und steuert den zulässigen Ausgabenrahmen.' },
    { feld: 'beschriftungen', id: 'l2', text: 'Der Ausgabenplafond ergibt sich aus den geschätzten Einnahmen multipliziert mit k.' },
    { feld: 'beschriftungen', id: 'l3', text: 'Im Boom (k kleiner 1) müssen Überschüsse erwirtschaftet werden, um spätere Defizite zu kompensieren.' },
    { feld: 'beschriftungen', id: 'l4', text: 'In der Rezession (k grösser 1) dürfen Defizite gefahren werden, um die Wirtschaft zu stützen.' },
    { feld: 'beschriftungen', id: 'l5', text: 'Das Ausgleichskonto bucht Abweichungen und erzwingt langfristig eine ausgeglichene Bilanz.' },
  ] },
  { id: '98b6e25b-8f59-468a-9a31-835d9884350c', fachbereich: 'VWL', musterlosung: 'Das Gefangenendilemma zeigt: Beide Spieler haben individuell die dominante Strategie, zu gestehen, obwohl das kollektive Optimum (beidseitiges Schweigen, je 1 Jahr) besser wäre. Das Nash-Gleichgewicht liegt bei «beide gestehen» (je 5 Jahre). Das Dilemma illustriert, warum rationales Eigeninteresse zu kollektiv schlechten Ergebnissen führen kann — zentral für Klima- und Kartellprobleme.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: 'Beide gestehen: 5/5 Jahre — Nash-Gleichgewicht, aber nicht pareto-optimal.' },
    { feld: 'beschriftungen', id: 'l2', text: 'A gesteht, B schweigt: A kommt frei (0 Jahre), B erhält die volle Strafe (10 Jahre).' },
    { feld: 'beschriftungen', id: 'l3', text: 'A schweigt, B gesteht: umgekehrte Situation — B wird belohnt, A bestraft.' },
    { feld: 'beschriftungen', id: 'l4', text: 'Beide schweigen: 1/1 Jahr — kollektiv bestes Ergebnis, aber instabil ohne Bindung.' },
    { feld: 'beschriftungen', id: 'l5', text: 'Die Zeile zeigt die Strategien von Spieler A: gestehen oder schweigen.' },
    { feld: 'beschriftungen', id: 'l6', text: 'Die Spalte zeigt die Strategien von Spieler B: gestehen oder schweigen.' },
  ] },
  { id: 'a84331c3-24f1-4b4b-a6bf-263a04a5a277', fachbereich: 'VWL', musterlosung: 'Das Drei-Ebenen-Modell des Wachstums unterscheidet unmittelbare, tiefere und fundamentale Ursachen. Ebene 1 sind die Produktionsfaktoren Arbeit und Kapital. Ebene 2 steigert deren Produktivität durch Technologie, Humankapital und Infrastruktur. Ebene 3 bestimmt über Institutionen, Geographie und Kultur, ob überhaupt investiert und innoviert wird — die fundamentale Basis für Wachstum.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: 'Ebene 1 fasst die unmittelbaren Ursachen zusammen: Was geht direkt ins Produktionsergebnis ein?' },
    { feld: 'beschriftungen', id: 'l2', text: 'Arbeit und Kapital sind die klassischen Produktionsfaktoren der unmittelbaren Ebene.' },
    { feld: 'beschriftungen', id: 'l3', text: 'Ebene 2 umfasst die tieferen Ursachen, die die Produktivität der Faktoren erhöhen.' },
    { feld: 'beschriftungen', id: 'l4', text: 'Technologie, Bildung und Infrastruktur steigern den Output pro Faktoreinheit.' },
    { feld: 'beschriftungen', id: 'l5', text: 'Ebene 3 sind die fundamentalen Ursachen — der Rahmen, in dem gewirtschaftet wird.' },
    { feld: 'beschriftungen', id: 'l6', text: 'Institutionen, Geographie und Kultur bestimmen Investitions- und Innovationsanreize.' },
  ] },
  { id: 'ce5e82eb-757b-45da-ba8d-2a374d298598', fachbereich: 'VWL', musterlosung: 'Das Marktdiagramm zeigt die Interaktion von Angebot und Nachfrage: Die Angebotskurve steigt (höhere Preise = mehr Angebot), die Nachfragekurve fällt (höhere Preise = weniger Nachfrage). Im Schnittpunkt liegt das Gleichgewicht mit Gleichgewichtspreis und -menge. Die Konsumentenrente ist der Nutzenüberschuss der Konsumenten über dem tatsächlich bezahlten Preis.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: 'Die Angebotskurve (S für Supply) steigt: Bei höheren Preisen wollen Anbieter mehr produzieren.' },
    { feld: 'beschriftungen', id: 'l2', text: 'Die Nachfragekurve (D für Demand) fällt: Bei höheren Preisen wird weniger nachgefragt.' },
    { feld: 'beschriftungen', id: 'l3', text: 'Der Gleichgewichtspunkt ist der Schnittpunkt der Kurven — hier räumt sich der Markt.' },
    { feld: 'beschriftungen', id: 'l4', text: 'Der Preis (P) steht auf der y-Achse — Franken pro Mengeneinheit.' },
    { feld: 'beschriftungen', id: 'l5', text: 'Die Menge (Q für Quantity) steht auf der x-Achse — Stück oder Einheiten pro Zeit.' },
    { feld: 'beschriftungen', id: 'l6', text: 'Die Konsumentenrente ist das Dreieck zwischen Nachfragekurve und Gleichgewichtspreis — Nutzenüberschuss.' },
  ] },
  { id: 'ddcd029a-5c20-4f48-a89d-9bf284d48379', fachbereich: 'VWL', musterlosung: 'Die Schweizer Altersvorsorge basiert auf drei Säulen: Die 1. Säule (AHV/IV) sichert im Umlageverfahren die Existenz. Die 2. Säule (BVG) sichert im Kapitaldeckungsverfahren den gewohnten Lebensstandard (zusammen mit Säule 1 ca. 60% des Lohns). Die 3. Säule ist die private, freiwillige Vorsorge — 3a ist gebunden und steuerbegünstigt, 3b frei.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: '1. Säule: AHV und IV sind staatliche Sozialversicherungen im Umlageverfahren.' },
    { feld: 'beschriftungen', id: 'l2', text: 'Ziel der 1. Säule ist die Existenzsicherung — das Überleben im Alter oder bei Invalidität.' },
    { feld: 'beschriftungen', id: 'l3', text: '2. Säule: BVG ist die berufliche Vorsorge im Kapitaldeckungsverfahren (Pensionskasse).' },
    { feld: 'beschriftungen', id: 'l4', text: 'Die 2. Säule soll zusammen mit der AHV den gewohnten Lebensstandard sichern.' },
    { feld: 'beschriftungen', id: 'l5', text: '3. Säule: Private, freiwillige Vorsorge zur individuellen Ergänzung der staatlichen Leistungen.' },
    { feld: 'beschriftungen', id: 'l6', text: 'Säule 3a ist gebunden und steuerlich begünstigt, Säule 3b ist frei.' },
  ] },
  { id: 'fa6b659a-3dfb-44b3-a9f6-bf90282c65e7', fachbereich: 'VWL', musterlosung: 'Der Arbeitsmarkt im Modell: Das Arbeitsangebot (Ls) der Haushalte steigt mit dem Lohn, die Arbeitsnachfrage (Ld) der Unternehmen fällt. Im Gleichgewicht stimmen Menge und Lohn überein. Liegt der effektive Lohn über dem Gleichgewicht — etwa durch einen Mindestlohn — entsteht ein Überschuss an Arbeitsangebot: klassisches Modell für unfreiwillige Arbeitslosigkeit.', teilerklaerungen: [
    { feld: 'beschriftungen', id: 'l1', text: 'Das Arbeitsangebot (Ls) kommt von den Haushalten: Je höher der Lohn, desto mehr Arbeit wird angeboten.' },
    { feld: 'beschriftungen', id: 'l2', text: 'Die Arbeitsnachfrage (Ld) kommt von den Unternehmen: Je höher der Lohn, desto weniger Arbeitskräfte werden eingestellt.' },
    { feld: 'beschriftungen', id: 'l3', text: 'Der Gleichgewichtslohn räumt den Markt — alle, die zu diesem Lohn arbeiten wollen, finden eine Stelle.' },
    { feld: 'beschriftungen', id: 'l4', text: 'Ein Mindestlohn über dem Gleichgewicht erzeugt Lohnrigidität und verhindert die Marktanpassung.' },
    { feld: 'beschriftungen', id: 'l5', text: 'Die Arbeitslosigkeit ist die Differenz zwischen Angebot und Nachfrage beim zu hohen Lohn.' },
    { feld: 'beschriftungen', id: 'l6', text: 'Die Gleichgewichtsmenge zeigt die Beschäftigung im ungestörten Markt — ohne Mindestlohn-Überschuss.' },
  ] },

  // ========== VWL / dragdrop_bild (11) — mit Teilerklärungen pro Zielzone ==========
  { id: '0d02246f-40f4-4314-bb90-ba9f24b1642b', fachbereich: 'VWL', musterlosung: 'Die drei Geldarten unterscheiden sich nach Trägermedium und Entstehung. Warengeld hat einen inneren Stoffwert (Gold, Salz, Muscheln). Kreditgeld entsteht durch Bankenschöpfung und existiert nur als Buchgeld auf Konten. Digitales Geld umfasst Kryptowährungen wie Bitcoin, mobile Zahlsysteme wie TWINT sowie potenzielle Zentralbank-Digitalwährungen (CBDC).', teilerklaerungen: [
    { feld: 'zielzonen', id: 'waren', text: 'Warengeld hat einen inneren Wert. Goldmünzen sind ein klassisches Beispiel — der Metallwert deckt den Nominalwert.' },
    { feld: 'zielzonen', id: 'kredit', text: 'Kreditgeld entsteht durch Bankbuchungen. Eine Lohnüberweisung aufs Bankkonto ist reines Buchgeld ohne physischen Träger.' },
    { feld: 'zielzonen', id: 'digital', text: 'Bitcoin ist digitales Geld ohne staatlichen Emittenten — dezentral auf Blockchain-Basis.' },
  ] },
  { id: '338d8a29-245d-446c-98e7-8c0e57c831cd', fachbereich: 'VWL', musterlosung: 'Die Schweiz kennt ein dreistufiges Steuersystem. Der Bund erhebt MWST, direkte Bundessteuer und Verrechnungssteuer. Die Kantone heben Einkommens- und Vermögenssteuer (eigene Steuerfüsse erzeugen Steuerwettbewerb) sowie die Motorfahrzeugsteuer ein. Die Gemeinden erheben einen Zuschlag auf die Kantonssteuer plus Liegenschaftssteuer und diverse lokale Abgaben.', teilerklaerungen: [
    { feld: 'zielzonen', id: 'bund', text: 'Die Mehrwertsteuer (MWST) ist die wichtigste Bundessteuer und belastet den Konsum einheitlich.' },
    { feld: 'zielzonen', id: 'kanton', text: 'Die Einkommenssteuer mit kantonalem Tarif ist Hauptquelle des Steuerwettbewerbs zwischen Kantonen.' },
    { feld: 'zielzonen', id: 'gemeinde', text: 'Der Gemeindesteuerfuss ist ein prozentualer Zuschlag auf die Kantonssteuer und finanziert Gemeindeaufgaben.' },
  ] },
  { id: '5e97bcf8-b82d-4956-b155-b13a7c7934d8', fachbereich: 'VWL', musterlosung: 'Maslows Bedürfnispyramide ordnet Bedürfnisse hierarchisch. Zuerst Grundbedürfnisse (Nahrung, Kleidung), dann Sicherheit (Versicherung, Arbeitsplatz), soziale Bedürfnisse (Freundschaft, Familie), Wertschätzung (Erfolg, Anerkennung) und zuletzt Selbstverwirklichung (Kreativität, persönliches Wachstum). Höhere Bedürfnisse werden erst aktiv, wenn tiefere gedeckt sind.', teilerklaerungen: [
    { feld: 'zielzonen', id: 'grund', text: 'Nahrung und Wasser sind biologische Grundbedürfnisse — die Basis des Überlebens.' },
    { feld: 'zielzonen', id: 'sicherheit', text: 'Die Krankenversicherung sichert vor finanziellen Gesundheitsrisiken und gehört zur Stufe Sicherheit.' },
    { feld: 'zielzonen', id: 'sozial', text: 'Freundschaft und Liebe erfüllen das Bedürfnis nach Zugehörigkeit und sozialer Bindung.' },
    { feld: 'zielzonen', id: 'wertschaetzung', text: 'Beruflicher Erfolg verleiht Status und Anerkennung — typisches Wertschätzungsbedürfnis.' },
    { feld: 'zielzonen', id: 'selbst', text: 'Kreative Entfaltung ist Ausdruck von Selbstverwirklichung — dem Ausschöpfen des eigenen Potenzials.' },
  ] },
  { id: '7b9c1673-2a2d-4de1-ab2e-ea8ac69802a0', fachbereich: 'VWL', musterlosung: 'Der Homo oeconomicus ist das klassische Modell des rationalen, eigeninteressierten Nutzenmaximierers mit vollständiger Information. Behavioral Economics ergänzt das Bild: Menschen sind nur begrenzt rational, gewichten Verluste stärker als Gewinne, nutzen Heuristiken und haben soziale Präferenzen. Beide Modelle erklären unterschiedliche Aspekte realen Entscheidungsverhaltens.', teilerklaerungen: [
    { feld: 'zielzonen', id: 'homo', text: 'Vollständige Information ist eine Kernannahme des Homo oeconomicus — alle relevanten Daten sind verfügbar und verarbeitbar.' },
    { feld: 'zielzonen', id: 'behavioral', text: 'Begrenzte Rationalität ist das Kernprinzip der Behavioral Economics — Menschen nutzen Heuristiken statt vollständiger Optimierung.' },
  ] },
  { id: '93632995-dbd1-4e76-9b9d-4cb3e5bff68e', fachbereich: 'VWL', musterlosung: 'Das BIP kann auf drei Arten berechnet werden, die alle zum gleichen Ergebnis führen. Die Entstehungsseite misst die Wertschöpfung der Wirtschaftssektoren. Die Verwendungsseite zerlegt nach Nachfragekomponenten (Y = C + I + G + NX). Die Verteilungsseite summiert Löhne, Gewinne und Vermögenseinkommen. Diese Dreifach-Rechnung dient auch der statistischen Qualitätssicherung.', teilerklaerungen: [
    { feld: 'zielzonen', id: 'entstehung', text: 'Die Wertschöpfung der Branchen ist die Kernrechnung der Entstehungsseite — Umsatz minus Vorleistungen pro Sektor.' },
    { feld: 'zielzonen', id: 'verwendung', text: 'Der private Konsum (C) ist die grösste Komponente der Verwendungsseite — Haushaltsausgaben für Konsumgüter.' },
    { feld: 'zielzonen', id: 'verteilung', text: 'Arbeitnehmerentgelt ist der grösste Posten der Verteilungsseite — Löhne und Gehälter aller Erwerbstätigen.' },
  ] },
  { id: '9a25b2fd-740f-4ba1-89f2-a55a2f3c04a2', fachbereich: 'VWL', musterlosung: 'Das Drei-Ebenen-Modell des Wachstums unterscheidet unmittelbare, tiefere und fundamentale Ursachen. Ebene 1 sind Arbeit und Kapital als direkte Produktionsfaktoren. Ebene 2 erhöht deren Produktivität durch Technologie, Bildung und Infrastruktur. Ebene 3 bildet mit Institutionen, Geographie und Handelsoffenheit den Rahmen, der überhaupt Investitionen und Innovationen ermöglicht.', teilerklaerungen: [
    { feld: 'zielzonen', id: 'ebene1', text: 'Die Zunahme des Kapitalstocks ist ein unmittelbarer Wachstumsfaktor — mehr Maschinen ergeben mehr Output.' },
    { feld: 'zielzonen', id: 'ebene2', text: 'Technologischer Fortschritt gehört zur tieferen Ebene — er erhöht die Produktivität pro Arbeits- und Kapitaleinheit.' },
    { feld: 'zielzonen', id: 'ebene3', text: 'Eigentumsrechte und Rechtsstaat sind fundamentale Institutionen — ohne sie bleiben Investitionen aus.' },
  ] },
  { id: 'aca40cb9-3eb0-480f-bc29-667fb3c44697', fachbereich: 'VWL', musterlosung: 'Die Fiskalpolitik kennt zwei Ausrichtungen. Expansive Politik in der Rezession erhöht Staatsausgaben und senkt Steuern, um die Nachfrage zu stimulieren. Restriktive Politik in Überhitzung oder zum Schuldenabbau kürzt Ausgaben und erhöht Steuern, um die Nachfrage zu bremsen. Die Schweizer Schuldenbremse zwingt zu antizyklischem Verhalten über den Konjunkturzyklus.', teilerklaerungen: [
    { feld: 'zielzonen', id: 'expansiv', text: 'Die Erhöhung der Staatsausgaben stimuliert die Nachfrage und ist das klassische expansive Instrument in Rezessionen.' },
    { feld: 'zielzonen', id: 'restriktiv', text: 'Die Kürzung der Staatsausgaben bremst die Nachfrage und wirkt der Überhitzung oder zu hoher Verschuldung entgegen.' },
  ] },
  { id: 'c3ff19bd-0dc7-4e1c-bdf6-00b3ab4dfbb7', fachbereich: 'VWL', musterlosung: 'Arbeitslosigkeit lässt sich nach Ursachen typisieren. Friktionelle Arbeitslosigkeit entsteht beim normalen Stellenwechsel und ist kurzfristig. Strukturelle Arbeitslosigkeit kommt von einem Mismatch zwischen Qualifikation und Nachfrage. Konjunkturelle Arbeitslosigkeit entsteht durch Nachfrageeinbrüche in der Rezession und lässt sich durch Konjunkturpolitik bekämpfen.', teilerklaerungen: [
    { feld: 'zielzonen', id: 'friktionell', text: 'Stellenwechsel mit Suchphase ist friktionelle Arbeitslosigkeit — kurz und in jeder Volkswirtschaft vorhanden.' },
    { feld: 'zielzonen', id: 'strukturell', text: 'Ein Mismatch von Qualifikationen ist klassisch strukturell — Angebot und Nachfrage an Arbeitskräften passen nicht zusammen.' },
    { feld: 'zielzonen', id: 'konjunkturell', text: 'Nachfragerückgang in der Rezession verursacht konjunkturelle Arbeitslosigkeit — reversibel mit dem Aufschwung.' },
  ] },
  { id: 'dd047d77-c25d-4492-85f7-5962327a702f', fachbereich: 'VWL', musterlosung: 'Verschiebungen der Nachfragekurve werden durch Einkommen, Präferenzen, Bevölkerungszahl und Substitutpreise ausgelöst. Verschiebungen der Angebotskurve gehen auf Technologie, Inputpreise, neue Anbieter oder Regulierung zurück. Wichtig: Bewegungen entlang einer Kurve (Preisänderung) sind keine Verschiebungen — nur andere Faktoren verschieben die ganze Kurve.', teilerklaerungen: [
    { feld: 'zielzonen', id: 'nachfrage', text: 'Eine Einkommensveränderung verschiebt die Nachfragekurve — bei Einkommenswachstum steigt die Nachfrage nach normalen Gütern.' },
    { feld: 'zielzonen', id: 'angebot', text: 'Technologischer Fortschritt senkt die Produktionskosten und verschiebt die Angebotskurve nach rechts.' },
  ] },
  { id: 'e98b7656-24fb-47f4-a58c-df6bf87f01da', fachbereich: 'VWL', musterlosung: 'Die Schweizer Sozialversicherungen sind in drei Säulen gegliedert. Säule 1 (AHV, IV, EO) arbeitet im Umlageverfahren und sichert die Existenz. Säule 2 (BVG, UVG) arbeitet im Kapitaldeckungsverfahren und sichert den Lebensstandard. Säule 3 ist die private Vorsorge — 3a gebunden und steuerbegünstigt, 3b frei. Alle drei Säulen zusammen bilden das schweizerische Altersvorsorgesystem.', teilerklaerungen: [
    { feld: 'zielzonen', id: 'saule1', text: 'Die AHV (Alters- und Hinterlassenenvorsorge) ist das staatliche Kernstück der 1. Säule im Umlageverfahren.' },
    { feld: 'zielzonen', id: 'saule2', text: 'Die Pensionskasse (BVG) bildet die berufliche Vorsorge — das Kapital wird individuell angespart und verzinst.' },
    { feld: 'zielzonen', id: 'saule3', text: 'Die gebundene Vorsorge (Säule 3a) ist privat und steuerbegünstigt — Einzahlungen reduzieren das steuerbare Einkommen.' },
  ] },
  { id: 'fd388c42-4c77-4e7f-b981-adc6dae381f9', fachbereich: 'VWL', musterlosung: 'Jede Konjunkturphase hat typische Merkmale. Im Aufschwung steigen Investitionen und die Arbeitslosigkeit sinkt. Im Boom herrscht Vollbeschäftigung bei steigendem Preisniveau. Im Abschwung gehen Aufträge und Gewinne zurück. In der Rezession ist die Arbeitslosigkeit hoch und die Kapazitäten sind unterausgelastet. Die Abfolge bildet den Konjunkturzyklus.', teilerklaerungen: [
    { feld: 'zielzonen', id: 'aufschwung', text: 'Steigende Investitionen sind ein Frühindikator des Aufschwungs — Unternehmen erwarten wachsende Nachfrage.' },
    { feld: 'zielzonen', id: 'boom', text: 'Vollbeschäftigung kennzeichnet den Boom — die Wirtschaft arbeitet über dem Produktionspotenzial mit Inflationsdruck.' },
    { feld: 'zielzonen', id: 'abschwung', text: 'Rückläufige Aufträge sind ein typisches Abschwungs-Merkmal — die Auftragsbücher der Unternehmen leeren sich.' },
    { feld: 'zielzonen', id: 'rezession', text: 'Hohe Arbeitslosigkeit und unterausgelastete Kapazitäten sind Rezessions-Kernmerkmale — negative Outputlücke.' },
  ] },

  // ========== VWL / formel (4) — keine Sub-Struktur ==========
  { id: '980b79f8-65b2-4533-b376-116bb2e5b9e3', fachbereich: 'VWL', musterlosung: 'Reales BIP = nominales BIP / Preisindex × 100. Die Formel eliminiert Preiseffekte und zeigt die tatsächliche Mengenentwicklung. Nur das reale BIP erlaubt einen aussagekräftigen Vergleich der Wirtschaftsleistung über die Zeit. Steigt das nominale BIP um 5% und der Preisindex ebenfalls um 5%, ist das reale Wachstum null — der gemessene Anstieg war reine Inflation.', teilerklaerungen: [] },
  { id: 'ecc63037-421d-4b7b-ae7a-e1fdc61fff52', fachbereich: 'VWL', musterlosung: 'BIP-Wachstumsrate = (BIP_t − BIP_{t−1}) / BIP_{t−1} × 100. Die Formel gibt die prozentuale Veränderung des realen BIP gegenüber dem Vorjahr. Eine negative Wachstumsrate über zwei aufeinanderfolgende Quartale gilt als technische Rezession. Für langfristige Vergleiche werden meist Jahres-Wachstumsraten verwendet.', teilerklaerungen: [] },
  { id: 'einr-formel-pythagoras', fachbereich: 'VWL', musterlosung: 'a² + b² = c². Der Satz des Pythagoras beschreibt den Zusammenhang zwischen den Seitenlängen eines rechtwinkligen Dreiecks: Die Summe der Quadrate der beiden Katheten a und b entspricht dem Quadrat der Hypotenuse c. Die Formel ist eine der fundamentalen Gleichungen der euklidischen Geometrie.', teilerklaerungen: [] },
  { id: 'ueb-formel-pythagoras', fachbereich: 'VWL', musterlosung: 'a² + b² = c². Der Satz des Pythagoras verbindet die drei Seiten eines rechtwinkligen Dreiecks: Die Quadrate der Katheten a und b addieren sich zum Quadrat der Hypotenuse c. Die Übungsaufgabe prüft den korrekten Umgang mit dem Formel-Editor (Hochzahlen via ^-Symbol oder x²-Button).', teilerklaerungen: [] },

  // ========== VWL / freitext (62) — keine Sub-Struktur ==========
  { id: '0113b6e4-49e2-461f-a688-71b6dc4c8f12', fachbereich: 'VWL', musterlosung: 'Mismatch-Arbeitslosigkeit erklärt das Paradox: Offene Stellen und Arbeitslose existieren gleichzeitig, passen aber nicht zusammen. Gründe sind qualifikatorische Diskrepanzen (Fachkräftemangel bei IT, Pflege), regionale Unterschiede oder technologischer Wandel. Grafisch zeigt sich dies als Aussenverschiebung der Beveridge-Kurve — bei gleichem Offenstellenniveau steigt die Arbeitslosigkeit.', teilerklaerungen: [] },
  { id: '013ea8d0-27be-4337-a38a-10b8000d0ded', fachbereich: 'VWL', musterlosung: 'Ein konjunkturelles Defizit verschwindet mit dem Aufschwung und kompensiert sich über den Zyklus. Ein strukturelles Defizit besteht auch bei normaler Auslastung und akkumuliert Schulden. Beispiel: Dauerhafte Rentenlücken durch demografischen Wandel sind strukturell — ohne Reform wächst die Verschuldung kontinuierlich. Strukturelle Defizite erfordern Ausgaben- oder Einnahmenreformen, nicht nur Konjunkturerholung.', teilerklaerungen: [] },
  { id: '0556c314-703d-4809-8941-f900973f0454', fachbereich: 'VWL', musterlosung: 'Erzwungene Umverteilung erfolgt per Gesetz (Steuern, Sozialbeiträge), freiwillige durch private Spenden. Der Unterschied ist das Trittbrettfahrerproblem: Weil Armutslinderung ein öffentliches Gut ist (alle profitieren), unterlässt jeder Einzelne seinen Beitrag, wenn andere zahlen. Das gesellschaftlich optimale Niveau wird nur erreicht, wenn der Staat Beiträge erzwingt — eine klassische Begründung für Umverteilungsstaat.', teilerklaerungen: [] },
  { id: '066982f0-0111-4339-9409-5d1f32c8de3e', fachbereich: 'VWL', musterlosung: 'Einkommensabhängige Prämien würden Geringverdiener entlasten und höhere Einkommen belasten — mehr Solidarität, aber weniger Kostenanreiz für Versicherte. Leistungskürzungen senken die Prämien direkt, gefährden aber den gleichen Zugang zur Grundversorgung. Beide Ansätze berühren den Zielkonflikt zwischen Effizienz, Solidarität und Qualität und scheitern politisch oft an den divergierenden Interessen der Akteure.', teilerklaerungen: [] },
  { id: '074d2bd7-780e-479c-bd69-806b31367e6f', fachbereich: 'VWL', musterlosung: 'Beispiele: (1) Landesverteidigung — keine Rivalität (Schutz aller gleichzeitig), kein Ausschluss. (2) Leuchtturm — Signalnutzung durch ein Schiff mindert Nutzen anderer nicht. (3) Öffentlicher Park — Freiflächenerlebnis für alle, Ausschluss nicht praktikabel. Diese Güter würden im Markt unterversorgt, da kein individueller Anreiz zur Finanzierung besteht (Trittbrettfahrerproblem).', teilerklaerungen: [] },
  { id: '0b8249ec-b1fa-459c-8c4a-29ccda8689bb', fachbereich: 'VWL', musterlosung: 'Ein Höchstpreis unter dem Gleichgewicht verhindert die Markträumung: Die Nachfrage steigt, das Angebot sinkt, es entsteht ein permanenter Nachfrageüberschuss (Wohnungsmangel). Kurzfristig profitieren Mieter, die eine Wohnung haben. Langfristig investieren Vermieter weniger, die Qualität leidet, Schwarzmärkte entstehen, und die Wohnungssuche wird zum Wartelistenproblem — Beispiel Stockholm oder New York.', teilerklaerungen: [] },
  { id: '0b92f7b8-f49b-41c3-bf62-b01bdfaccbf2', fachbereich: 'VWL', musterlosung: 'Wachstum ist kein Selbstzweck, sondern Mittel zur Finanzierung steigender Ansprüche. Ohne Wachstum müsste bei einer Umverteilung jemand anderem etwas weggenommen werden — mit Wachstum kann das Einkommen aller steigen. Wachstum finanziert auch Sozialwerke, Infrastruktur und Umweltmassnahmen. Kritiker gewichten allerdings ökologische Grenzen und plädieren für qualitatives statt quantitatives Wachstum.', teilerklaerungen: [] },
  { id: '0ce31b1a-e7a1-4bdf-8bda-3730ef9d4c70', fachbereich: 'VWL', musterlosung: 'Die offizielle Fiskalquote umfasst Steuern und Sozialbeiträge. Die erweiterte Fiskalquote bezieht obligatorische Krankenkassenprämien und weitere Zwangsabgaben mit ein — in der Schweiz ein wesentlicher Unterschied, da die KK-Prämien statistisch nicht als Staatseinnahme, wirtschaftlich aber als Zwangsabgabe wirken. Der Unterschied ist relevant für internationale Vergleiche und die effektive Belastungsquote der Haushalte.', teilerklaerungen: [] },
  { id: '113383c7-06b5-47c9-a091-36181ceebf12', fachbereich: 'VWL', musterlosung: 'Die Lenkungsabgabe setzt den Preis fix (z.B. CHF 120/t CO₂), die Menge passt sich an (Preislösung). Der Emissionshandel setzt die Gesamtmenge fix (Cap), der Preis bildet sich am Markt (Mengenlösung). Beide internalisieren externe Kosten und sind theoretisch gleich effizient. Die Wahl hängt davon ab, was politisch wichtiger ist: Budgetsicherheit über Einnahmen oder Mengensicherheit für Klimaziele.', teilerklaerungen: [] },
  { id: '11edcb1c-c294-4270-9f89-64e2fa36931a', fachbereich: 'VWL', musterlosung: 'Die Debatte ist kein reines «Entweder-oder», weil beide Elemente gebraucht werden. Reines Sparen verschärft die Rezession und senkt die Steuereinnahmen (Austeritätsfalle). Reine Schuldenfinanzierung löst strukturelle Probleme nicht. Die erfolgreichsten Krisenbewältigungen kombinieren kurzfristige Konjunkturhilfen mit langfristigen Strukturreformen (Rentensystem, Arbeitsmarkt, Bildung) — Deutschland nach 2004 ist ein oft zitiertes Beispiel.', teilerklaerungen: [] },
  { id: '1284e4da-dcfe-4155-bfd1-c84b0989a69d', fachbereich: 'VWL', musterlosung: 'Liegt der Preis über dem Gleichgewicht, entsteht ein Angebotsüberschuss: Anbieter senken den Preis, um Ware loszuwerden. Liegt der Preis darunter, entsteht ein Nachfrageüberschuss: Konsumenten bieten mehr, der Preis steigt. Beide Ungleichgewichte treiben den Preis zum Schnittpunkt. In der Realität brauchen diese Anpassungen Zeit, und Marktunvollkommenheiten können den Prozess stören.', teilerklaerungen: [] },
  { id: '134aa0f7-af1a-4dfd-a430-138db5369301', fachbereich: 'VWL', musterlosung: 'Im Radsport hat jeder Fahrer die dominante Strategie zu dopen: Mit Doping gewinnt man, ohne verliert man gegen dopende Konkurrenten. Das Gleichgewicht liegt bei «alle dopen», obwohl «niemand dopt» für alle besser wäre. Eisenhut beschreibt das als «absurd und rational» — absurd, weil alle gesundheitlich schlechter fahren; rational, weil individuell jede andere Strategie noch schlechter ist.', teilerklaerungen: [] },
  { id: '164d1336-af7c-40f8-8c77-cf12b8eb74af', fachbereich: 'VWL', musterlosung: 'Im Tagebuch sind indirekte Steuern (MWST auf Einkauf, Benzinsteuer, Billettabgaben) und Gebühren (Abwasser, Radio/TV) überproportional vertreten — sie durchziehen den Alltag. Das föderale System (Gemeinde/Kanton/Bund) wird sichtbar. Insgesamt zeigt das Tagebuch: Steuerbelastung ist mehr als die Einkommenssteuer; viele kleine Abgaben summieren sich und werden oft nicht wahrgenommen.', teilerklaerungen: [] },
  { id: '17f69aca-c2fb-4ec2-9a75-cea05b24a2d0', fachbereich: 'VWL', musterlosung: 'Absolute Armut bedeutet fehlende Existenzsicherung (Nahrung, Obdach) — weltweit via Weltbank-Schwelle (2.15 USD/Tag). Relative Armut ist Ungleichheit im Ländervergleich: Armutsgefährdet gilt, wer unter 60% des Medianeinkommens lebt. Subjektive Armut beruht auf Selbsteinschätzung. In der Schweiz garantiert die Bundesverfassung nur den Schutz vor absoluter Armut — relative und subjektive Armut sind politische Kategorien.', teilerklaerungen: [] },
  { id: '19db1a0e-14bc-47df-8ae7-8e15781538b8', fachbereich: 'VWL', musterlosung: 'Maximumprinzip (Input fix): Ich habe CHF 50 für den Einkauf und will damit so viel wie möglich herausholen. Minimumprinzip (Output fix): Ich muss eine Prüfung bestehen und will dafür möglichst wenig Zeit investieren. Entscheidend ist die Fix-Grösse: fix ist der Input (Budget, Zeit) oder der Output (Ziel, Ergebnis). Beide Prinzipien sind Ausprägungen des ökonomischen Prinzips der Effizienz.', teilerklaerungen: [] },
  { id: '1beb5897-811a-49ea-99f2-f26771ad493e', fachbereich: 'VWL', musterlosung: 'Wirtschaften ist notwendig, weil Bedürfnisse unbegrenzt, Mittel aber knapp sind. Knappheit zwingt zum Abwägen: Wer alles gleichzeitig will, muss entscheiden, wofür Zeit, Geld und Ressourcen eingesetzt werden. Im Schlaraffenland wäre Wirtschaften überflüssig. In der Realität ist es der rationale Umgang mit der Differenz zwischen Wünschen und Möglichkeiten — das Kernthema der VWL.', teilerklaerungen: [] },
  { id: '1cda79b3-e5dd-4671-8076-8a9d7e9c93f8', fachbereich: 'VWL', musterlosung: 'Hohe Fluktuation kann strukturelle Arbeitslosigkeit reduzieren: Schneller Jobwechsel verhindert lange Arbeitslosigkeitsperioden, Matching zwischen Anforderung und Qualifikation geschieht rascher. Der Schweizer Arbeitsmarkt ist ein «Hochleistungsarbeitsmarkt» mit kurzen Arbeitslosigkeitsdauern (Langzeitarbeitslose ca. 16%). Die Kehrseite: hohe Anforderungen an Mobilität und Anpassungsfähigkeit der Arbeitnehmenden.', teilerklaerungen: [] },
  { id: '1dc602a3-212a-430a-93aa-8ad58322cb65', fachbereich: 'VWL', musterlosung: 'Kreditfinanzierung ist politisch attraktiv, weil die Lasten verschoben werden: Wählerinnen und Wähler profitieren heute von Ausgaben, die Rückzahlung belastet künftige Generationen (Generationenkonflikt). Steuererhöhungen sind unpopulär und politisch kostspielig. Diese Asymmetrie erklärt, warum viele Demokratien zu steigender Verschuldung neigen — ein zentrales Argument der Public-Choice-Theorie für institutionelle Schuldenbremsen.', teilerklaerungen: [] },
  { id: '351b207a-2f22-4121-a91a-35a43d22a1a1', fachbereich: 'VWL', musterlosung: '(a) E-Auto-Markt: Technologieschub senkt Produktionskosten, Angebotskurve verschiebt sich nach rechts, Preis sinkt, Menge steigt. (b) Benzin-Markt: E-Autos sind Substitute, Nachfrage nach Benzin sinkt (Nachfragekurve nach links), Preis und Menge fallen. Das zeigt Spillover-Effekte: Veränderungen in einem Markt wirken über Substitutionsbeziehungen auf andere Märkte.', teilerklaerungen: [] },
  { id: '35464f80-3603-4ef8-9724-bbe175b3c9be', fachbereich: 'VWL', musterlosung: 'Das BIP misst die Wertschöpfung, nicht den Gesamtumsatz — sonst würde dieselbe Leistung mehrfach gezählt. Beispiel Brotkette: Bauer (Umsatz 30) + Bäcker (100 − 30 Vorleistungen = 70) + Händler (120 − 100 = 20) = Wertschöpfung 120 = Endproduktpreis. Ohne Abzug der Vorleistungen wäre das BIP im Beispiel fälschlich 250 (30 + 100 + 120). Vorleistungsabzug verhindert Doppelzählung.', teilerklaerungen: [] },
  { id: '3cc4011a-b77d-44a8-9086-17737ffe3b49', fachbereich: 'VWL', musterlosung: 'Stigmatisierung führt dazu, dass Berechtigte Sozialhilfe nicht beziehen (hohe Nichtbezugsquote, ca. 25% in der Schweiz). Folgen: verdeckte Armut, gesundheitliche Belastung, verpasste Reintegration. Lösungsansätze: automatische Auszahlung via negative Einkommenssteuer, Grundeinkommen oder aktive Ansprache Berechtigter. Die Stigmatisierung schwächt den Zweck des Systems und ist ein bekanntes sozialpolitisches Problem vieler Länder.', teilerklaerungen: [] },
  { id: '3d3c87b8-291d-479e-89b7-2475ca980f3c', fachbereich: 'VWL', musterlosung: 'Degrowth fordert gezielte Schrumpfung in Industrieländern, um planetare Grenzen einzuhalten. Realismus: Schwer, weil Wachstum Sozialwerke finanziert und Arbeitslosigkeit bei Schrumpfung droht. Wünschbarkeit: Umstritten — Befürworter betonen Nachhaltigkeit und Lebensqualität, Kritiker warnen vor Wohlstandsverlust. Eine differenzierte Beurteilung trennt qualitatives Wachstum (Dienstleistungen, Kreislaufwirtschaft) von quantitativer Ressourcenschonung.', teilerklaerungen: [] },
  { id: '420e7e2e-7db2-46fc-88e4-f6c1f757f9db', fachbereich: 'VWL', musterlosung: 'Umlageverfahren (AHV) finanziert laufende Renten aus laufenden Beiträgen — solidarisch, aber demografieanfällig. Kapitaldeckung (BV) spart individuelles Kapital an — demografierobust, aber anfällig für Finanzmarktrisiken. «Besser» hängt vom Kriterium ab: Solidarität spricht für Umlage, Eigenverantwortung für Kapitaldeckung. Die Schweizer Drei-Säulen-Mischung diversifiziert beide Risiken und ist international anerkannt.', teilerklaerungen: [] },
  { id: '422aa02e-18ff-4794-9583-b314a2ceba52', fachbereich: 'VWL', musterlosung: 'Die Elefantengrafik zeigt global: Gewinner des Wachstums seit 1988 sind asiatische Mittelschicht und globales Top-1%, Verlierer die westliche Mittelschicht. Die Produktivitäts-Lohn-Schere zeigt dasselbe für einzelne Länder: Kapitalbesitzer und Hochqualifizierte profitieren überproportional. Gemeinsame Ursache ist die Globalisierung — dieselben Mechanismen erzeugen global und national wachsende Ungleichheit.', teilerklaerungen: [] },
  { id: '45148128-60e8-4130-b122-96dce5464e97', fachbereich: 'VWL', musterlosung: 'Grundlagenforschung ist ein öffentliches Gut: Ergebnisse sind nicht ausschliessbar (Publikation frei zugänglich) und nicht rival. Privat wäre sie unterversorgt, weil keine Firma die Erträge exklusiv abschöpfen kann. Deshalb ist staatliche Finanzierung ökonomisch begründet — ETH, Hochschulen und SNF sind Beispiele. Angewandte Forschung kann hingegen über Patente privat organisiert werden.', teilerklaerungen: [] },
  { id: '489314d9-4f91-4869-a476-51960028ea16', fachbereich: 'VWL', musterlosung: 'Kaufentscheid Tablet: Der Homo oeconomicus sammelt vollständige Information, listet Alternativen, berechnet Preis-Leistung und Opportunitätskosten und wählt den Nutzen-maximierenden Kauf. In der Realität sind Markenpräferenz, Gruppendruck und Zeitdruck wirksam. Das Modell vereinfacht stark, erfasst aber das Durchschnittsverhalten oft erstaunlich gut und dient als nützlicher Benchmark.', teilerklaerungen: [] },
  { id: '4b89eccd-ad22-4663-82e3-e082c0afec6d', fachbereich: 'VWL', musterlosung: 'Vorteile: Schutz strategischer Branchen, Förderung junger Industrien (Infant-Industry-Argument), politischer Druckmittel, Arbeitsplatzerhalt. Nachteile: Höhere Konsumentenpreise, geringere Produktvielfalt, Wohlfahrtsverlust durch Effizienzverzerrung, Gegenmassnahmen der Handelspartner. Die theoretische Ökonomie spricht meist gegen Zölle; die politische Praxis folgt oft anderen Kriterien (Wahlkreise, Industrielobbys).', teilerklaerungen: [] },
  { id: '509664a4-9313-4989-a004-3b1ca60bc7f8', fachbereich: 'VWL', musterlosung: 'Pro: Das BIP ist international vergleichbar, quantifizierbar und eng mit Beschäftigung und Steueraufkommen korreliert. Contra: Es ignoriert Verteilung, Umwelt, unbezahlte Arbeit, Gesundheit und Lebenszufriedenheit. Alternativindikatoren (HDI, GPI, Bruttonationalglück) versuchen diese Lücken zu schliessen, sind aber weniger einheitlich. Das BIP bleibt der Standard, muss aber um Zusatzindikatoren ergänzt werden.', teilerklaerungen: [] },
  { id: '5925de60-da28-47b4-b117-87f2f44ad4f0', fachbereich: 'VWL', musterlosung: 'Die Aussage ist pragmatisch: Nicht jeder Marktfehler rechtfertigt einen Staatseingriff, weil auch der Staat versagen kann (Bürokratie, Regulierungsfehler, Politikversagen). Das Kriterium fordert Abwägung: Eingreifen nur, wenn das zu erwartende Staatsversagen geringer ist als der Gewinn durch Marktverbesserung. Die Aussage ist sinnvoll, aber schwer operationalisierbar — beide Versagen sind selten exakt quantifizierbar.', teilerklaerungen: [] },
  { id: '5b04af11-d6c5-49c7-bb79-d4f3b8ec6e66', fachbereich: 'VWL', musterlosung: 'CO₂-Abgabe (Preislösung): Preis fix, Menge variabel, Vorteil Planbarkeit für Unternehmen, Nachteil Mengenunsicherheit. Emissionshandel (Mengenlösung): Cap fix, Preis variabel, Vorteil Zielsicherheit, Nachteil Preisvolatilität. Beide internalisieren externe Kosten. In der Praxis kombinieren Schweiz und EU beide Instrumente — Abgabe für diffuse Quellen, Handel für Grossemittenten.', teilerklaerungen: [] },
  { id: '5ba8b420-8f51-4076-bd53-9ec9de7226b4', fachbereich: 'VWL', musterlosung: 'Der Wohlfahrtsverlust ist bei elastischer Nachfrage grösser: Je stärker die Menge auf die steuerbedingte Preisänderung reagiert, desto mehr Tauschgewinne entgehen. Die Fläche des Wohlfahrtsverlust-Dreiecks hängt vom Mengenrückgang ab. Effiziente Steuern setzen deshalb an unelastischen Gütern an (Tabak, Benzin) — das ist der Kern der Ramsey-Regel der Optimalsteuertheorie.', teilerklaerungen: [] },
  { id: '5bbe1fff-a09a-489e-8263-219db8d88eb8', fachbereich: 'VWL', musterlosung: 'Roslings Kernbotschaft: Wohlstandsgewinn in Entwicklungsländern ist moralisch geboten, aber energieintensiv. Lösungsansätze: (1) Umstieg auf erneuerbare Energien (Solar, Wind, Wasserkraft), (2) drastische Effizienzsteigerung in Industrieländern, (3) Technologietransfer, (4) internationale Klimakooperation. Ohne technischen Fortschritt ist das Dilemma unlösbar — mit Fortschritt ist Entwicklung bei sinkendem Pro-Kopf-Verbrauch denkbar.', teilerklaerungen: [] },
  { id: '5c6afe26-79a5-45f9-93e9-954b726dfa47', fachbereich: 'VWL', musterlosung: 'Gut gemeinte Regulierungen erzeugen unbeabsichtigte Folgen: Hoher Kündigungsschutz erschwert Neueinstellungen (Unternehmen scheuen Risiko), Mindestlöhne können Geringqualifizierte aus dem Markt drängen, grosszügige Arbeitslosenunterstützung verlängert die Suchphase. Das Prinzip «gut gemeint ist nicht gleich gut gemacht» warnt vor einseitigen Eingriffen — stattdessen braucht es eine Abwägung zwischen Schutz und Flexibilität.', teilerklaerungen: [] },
  { id: '5d2b5b80-44ae-4c0d-aef5-d66ac30dafff', fachbereich: 'VWL', musterlosung: 'Der Monopolist setzt Preis und Menge so, dass Grenzerlös = Grenzkosten — das liegt unter der effizienten Menge (Grenzerlös < Preis). Durch Mengenverknappung steigt der Preis, der Monopolist maximiert seinen Gewinn. Im Vergleich zur vollkommenen Konkurrenz entsteht ein Wohlfahrtsverlust — das Dreieck aus entgangenen Tauschgewinnen zwischen Monopolmenge und Gleichgewichtsmenge. Deshalb greifen Kartellbehörden bei Marktmacht ein.', teilerklaerungen: [] },
  { id: '5ec285ed-4f31-4c04-82a8-333ddc070e9d', fachbereich: 'VWL', musterlosung: 'Die MWST ist nominal einheitlich, aber regressiv, weil Geringverdienende einen grösseren Anteil ihres Einkommens konsumieren (geringere Sparquote). Der reduzierte Satz auf Lebensmittel mildert das Problem, löst es aber nicht: Alle profitieren, auch Reiche. Zielgenauer wären Bedarfstransfers. Der reduzierte Satz ist politisch populär, aber steuerpolitisch ineffizient — Einnahmeverluste stehen geringer sozialer Wirkung gegenüber.', teilerklaerungen: [] },
  { id: '5f6ccaaf-b752-474c-996b-85d9b763e80d', fachbereich: 'VWL', musterlosung: 'Sparen (S), Steuern (T) und Importe (M) sind Abflüsse — sie nehmen Geld aus dem Kreislauf. Die Zuflüsse sind Investitionen (I, von Ersparnissen finanziert), Staatsausgaben (G, aus Steuern finanziert) und Exporte (X, ersetzen Importe). Im Gleichgewicht gilt S + T + M = I + G + X. Diese Gleichung ist eine Umformung der Verwendungsgleichung Y = C + I + G + (X − M).', teilerklaerungen: [] },
  { id: '60807bbb-c7ce-4914-9488-59ee6f6930ef', fachbereich: 'VWL', musterlosung: 'Saubere Luft ist weitgehend nicht-rival: Der Atemzug des einen mindert die Luft des anderen kaum. Sie ist auch nicht-ausschliessbar: Man kann niemanden vom Atmen lokaler Luft ausschliessen. Damit erfüllt sie die Kriterien eines öffentlichen Gutes. Luftverschmutzung ist entsprechend ein klassisches Beispiel negativer externer Effekte, die private Märkte nicht lösen — deshalb braucht es staatliche Umweltregulierung.', teilerklaerungen: [] },
  { id: '613423be-2f53-483f-a537-15c282bc7d98', fachbereich: 'VWL', musterlosung: 'Kritikpunkte: Bankgeheimnis (AIA-relevant), tiefe Unternehmenssteuern, Pauschalbesteuerung und kantonale Sonderstatuten. Reformen der letzten Jahre: AIA-Einführung (Bankgeheimnis bei Auslandbeziehungen aufgehoben), STAF-Reform (Abschaffung der Sonderstatuten 2020), Umsetzung der OECD-Mindeststeuer (15%). Die Schweiz ist heute kein klassisches Steuerparadies mehr, behält aber im internationalen Vergleich tiefe Sätze.', teilerklaerungen: [] },
  { id: '650ad684-d597-4ea1-ba4e-a4a63dd89100', fachbereich: 'VWL', musterlosung: 'Klimaverhandlungen haben Dilemma-Struktur: Jedes Land profitiert individuell vom Nichtstun (Trittbrettfahrer), alle verlieren, wenn niemand handelt. Lösungsmechanismen der Spieltheorie: (1) wiederholte Spiele mit Reputation, (2) bindende Abkommen mit Sanktionen, (3) stufenweise Kooperation (Tit-for-Tat). Das Pariser Abkommen versucht dies mit Transparenz und politischem Druck — ohne formelle Sanktionen bleibt die Umsetzung jedoch fragil.', teilerklaerungen: [] },
  { id: '68018f6a-785f-40c9-b5b7-9ffb524c5009', fachbereich: 'VWL', musterlosung: 'Junge SP fordert Ausbau (Umverteilung, Solidarität, Armutsbekämpfung — collectivist/liberal). Jungfreisinnige halten den Sozialstaat grundsätzlich für nötig, plädieren aber für Eigenverantwortung und effizientere Mittel (liberal). Junge SVP warnt vor Umverteilungsexzessen und fordert Reduktion (libertär). Die Positionen widerspiegeln die drei klassischen Gerechtigkeitstheorien — zentral für die Schweizer Sozialpolitik-Debatte.', teilerklaerungen: [] },
  { id: '696d0ec3-2aa2-4384-a41e-e9352c779eff', fachbereich: 'VWL', musterlosung: 'Die soziale Marktwirtschaft kommt Rawls\' Liberalism am nächsten: Eigentumsrechte bleiben geschützt (liberales Element), aber Umverteilung ist gerechtfertigt, solange auch die Schwächsten profitieren (Differenzprinzip). Die Schweiz verbindet freien Markt mit gezielter Umverteilung via Progression, Sozialversicherungen und Bildungszugang. Weder Libertarianismus (Markt pur) noch Collectivism (reine Gleichheit) passen — der Kompromiss ist kennzeichnend.', teilerklaerungen: [] },
  { id: '6ec1796c-2099-4031-a850-0d92aef3abf4', fachbereich: 'VWL', musterlosung: 'Public Choice unterstellt Politikerinnen und Beamten Eigennutz: Stimmenmaximierung, Budgetmaximierung, Karriereplanung. Das führt zu steigenden Ausgaben, weil (a) Wählerinnen populäre Programme schätzen, (b) Verwaltungen an grösseren Budgets interessiert sind und (c) Gewinnkriterien wie in der Privatwirtschaft fehlen. Budgetgrösse wird selbst zum Erfolgsindikator — ein struktureller Trend Richtung Staatsexpansion.', teilerklaerungen: [] },
  { id: '6efbbd49-88ff-4c8f-b384-ea1aae4c933d', fachbereich: 'VWL', musterlosung: 'Der Begriff stammt von Thomas Carlyle (1849) und wird oft missverstanden. «Dismal» bezog sich auf Malthus\' düstere Bevölkerungsprognosen. Heute meint er: VWL zeigt, dass Knappheit existiert und Entscheidungen Trade-offs haben — keine angenehme Botschaft. Die Bezeichnung ist insofern berechtigt, als VWL unbequeme Wahrheiten formuliert. Sie ist aber auch ungerecht, da die VWL hilft, bessere Entscheidungen zu treffen.', teilerklaerungen: [] },
  { id: '73fa6fd9-9f80-4cca-91ed-6ac6bfaf7a60', fachbereich: 'VWL', musterlosung: 'Die Analogie passt strukturell: Atmosphäre als Allmende (nicht-ausschliessbar, rival bei CO₂-Aufnahme). Alle profitieren vom CO₂-Ausstoss, tragen aber Schäden gemeinsam. Unterschied zur lokalen Allmende: 195 Staaten mit divergierenden Interessen, keine zentrale Autorität. Elinor Ostroms Lösung via Selbstorganisation funktioniert lokal, global fast unmöglich. Die Analogie erklärt den Klimafluchtanreiz — aber unterschätzt die Komplexität globaler Kooperation.', teilerklaerungen: [] },
  { id: '744574c3-a30f-4bcd-9708-091016c6993c', fachbereich: 'VWL', musterlosung: 'Der Substitutionseffekt beschreibt das veränderte Tauschverhältnis: Wird Gut A teurer, lohnt Gut B als Ersatz relativ stärker, die Nachfrage nach A sinkt. Der Einkommenseffekt beschreibt die reduzierte Kaufkraft: Bei gleichem Nominaleinkommen kann weniger gekauft werden. Bei normalen Gütern wirken beide Effekte nachfragemindernd, bei inferioren Gütern kann der Einkommenseffekt dominieren (Giffen-Paradoxon).', teilerklaerungen: [] },
  { id: '75374c1f-ed93-4110-b519-90512c388fee', fachbereich: 'VWL', musterlosung: 'Beispiel Brot: (1) Boden (Weizenanbau, Standort der Bäckerei), (2) Arbeit (Bäcker, Lieferfahrer), (3) Kapital (Backofen, Lieferwagen, Ladenmiete), (4) Wissen/Unternehmertum (Rezepte, Betriebsorganisation). Ohne einen der vier Faktoren wäre Produktion unmöglich. Die Kombination entscheidet über Qualität und Produktivität — der Schlüssel zum «Wohlstandskuchen» eines Landes liegt in der verfügbaren Menge und Qualität aller Produktionsfaktoren.', teilerklaerungen: [] },
  { id: '773e40e3-8338-4a99-b3dd-492360b7cda9', fachbereich: 'VWL', musterlosung: 'Drei Probleme der Tauschwirtschaft: (1) Doppelte Koinzidenz der Wünsche — beide Seiten müssen das jeweils andere Gut wollen (Lösung: Tauschmittelfunktion). (2) Fehlende Recheneinheit — Preise sind schwer zu vergleichen (Lösung: Recheneinheitsfunktion). (3) Keine Wertaufbewahrung über Zeit — verderbliche Güter (Lösung: Wertaufbewahrungsfunktion). Geld senkt durch alle drei Funktionen die Transaktionskosten erheblich.', teilerklaerungen: [] },
  { id: '781f7195-bdcd-494c-be31-d67899c7cdcb', fachbereich: 'VWL', musterlosung: 'Das Essen ist nicht gratis, weil Opportunitätskosten entstehen: Die Zeit beim Nachtessen könnte für andere Aktivitäten (Lernen, Arbeit, Freizeit) verwendet werden. Dazu kommen Anfahrtszeit und möglicherweise soziale Verpflichtungen (Einladung erwidern). Eisenhut illustriert damit: Opportunitätskosten sind allgegenwärtig, auch wenn kein Geld fliesst — das ist ein Kernprinzip ökonomischen Denkens.', teilerklaerungen: [] },
  { id: '784e0602-b218-49f2-bb5c-fc3cc96bd38c', fachbereich: 'VWL', musterlosung: 'Der Generationenvertrag beruht darauf, dass die aktive Generation die Renten der älteren finanziert. Demografisch wird das immer schwieriger: Weniger Erwerbstätige pro Rentner, steigende Lebenserwartung, niedrige Geburtenraten. Bis 2035 droht der AHV ein Finanzierungsbedarf von ca. CHF 15 Mrd. Lösungen: höhere Beiträge, tiefere Renten, höheres Rentenalter oder alternative Finanzierung (MWST-Prozent). Der Vertrag hält, braucht aber strukturelle Anpassungen.', teilerklaerungen: [] },
  { id: '826ce8ac-bb97-4146-8ad6-0cec20b9f617', fachbereich: 'VWL', musterlosung: 'Die Regenerationsfunktion verdoppelt den Restbestand bis zum Maximum. Nachhaltig ist, was der Zuwachs pro Runde abschöpfen lässt: Bei 60 Fischen und Verdopplung ist der Zuwachs = 60. Geteilt durch 15 Spieler ergibt das 4 Fische pro Spieler pro Runde. Jede Entnahme darüber reduziert den Zuwachs langfristig — das ist die Tragödie der Allmende, übertragen auf Fischerei, Wälder und Klima.', teilerklaerungen: [] },
  { id: '85af9be1-57c9-49e4-bc42-09cd704f080f', fachbereich: 'VWL', musterlosung: 'BIP pro Einwohner = Arbeitseinsatz × Produktivität. In der Schweiz ist der Arbeitseinsatz (Erwerbsquote ca. 80%, Arbeitszeit hoch) bereits sehr hoch — zusätzliche Stunden sind kaum möglich. Daher ist die einzige nachhaltige Wohlstandsquelle Produktivitätswachstum: mehr Output pro Arbeitsstunde durch Technologie, Bildung und Infrastruktur. Eisenhut betont: Ohne Produktivitätsfortschritt stagniert der Wohlstand.', teilerklaerungen: [] },
  { id: '86ef0528-c48e-4946-b128-45ffa4716384', fachbereich: 'VWL', musterlosung: '(a) Mögliche Auslöser: Einkommensanstieg, geänderte Präferenzen (Trend), Bevölkerungswachstum, steigender Preis eines Substituts, sinkender Preis eines Komplements. (b) Bei unverändertem Angebot entsteht zunächst ein Nachfrageüberschuss, der Preis steigt, bis ein neues Gleichgewicht erreicht ist — Gleichgewichtspreis UND Gleichgewichtsmenge steigen. Der Preisanstieg dämpft die Nachfrage entlang der neuen Kurve.', teilerklaerungen: [] },
  { id: '8a4f9842-a6d7-4fcb-b2f7-d27b264adc24', fachbereich: 'VWL', musterlosung: 'Hinter dem Schleier des Nichtwissens wählen rationale Akteure Institutionen, die auch für die Schlechtestgestellten akzeptabel sind (Maximin-Prinzip). Das führt typischerweise zu einer sozialen Marktwirtschaft mit Grundrechten, Umverteilung und Chancengleichheit. Reine Planwirtschaft verkennt Anreize, reiner Libertarianismus die Absicherungsbedürfnisse. Die Schweizer Verfassung spiegelt diesen Rawls-Kompromiss in vielen Bereichen wider.', teilerklaerungen: [] },
  { id: '8ac1e9f2-b423-4664-a467-fa23e479eaf5', fachbereich: 'VWL', musterlosung: 'Vorteile: Schutz vor Lohndumping, Existenzsicherung, Kaufkraftstabilisierung. Nachteile: Geringqualifizierte könnten aus dem Markt fallen, Schwarzarbeit, Automatisierungsdruck, Wettbewerbsnachteil. Die Ablehnung der Initiative 2014 spiegelte diese Vorbehalte wider. Die Schweiz setzt auf GAV und kantonale Mindestlöhne (Neuenburg, Genf, Jura, Tessin, Basel-Stadt) — ein differenzierter Mittelweg zwischen Flexibilität und Schutz.', teilerklaerungen: [] },
  { id: '8e5c12f3-1ac4-48c5-9bef-0ddb4e0364ee', fachbereich: 'VWL', musterlosung: 'Der Karikaturvergleich trifft in drei Punkten: (1) Bewusste Vereinfachung ist methodisch legitim. (2) Wesentliche Merkmale werden pointiert. (3) Die Darstellung ist erkennbar, aber nicht realistisch. Er stösst an Grenzen, wenn Modelle als Realität behandelt werden — ihre blinden Flecken können dann zu Fehlprognosen führen (Finanzkrise 2008). Modelle sind Werkzeuge, keine Abbilder — so gelesen ist die Analogie treffend.', teilerklaerungen: [] },
  { id: '94a60762-14eb-4a9d-a3a1-33f87de5ac4a', fachbereich: 'VWL', musterlosung: 'Beispiel: Rolex-Uhr. Formal befriedigt sie das Grundbedürfnis Zeitmessung — dafür würde eine günstige Uhr reichen. Eigentlich befriedigt sie Wertschätzung (Stufe 4 bei Maslow): Anerkennung durch andere, Statusdemonstration, Zugehörigkeit zu einer Gruppe. Eisenhut nennt weitere Beispiele (Champagner, Van Gogh im Tresor) — Statussymbole zeigen, dass Güter oft mehrere Bedürfnisstufen gleichzeitig ansprechen.', teilerklaerungen: [] },
  { id: '98c0dd27-6d3e-4411-9ff2-9586a6754ec5', fachbereich: 'VWL', musterlosung: 'Die Corona-Defizite waren grösstenteils konjunkturell bzw. krisenbedingt: Einbruch der Wirtschaftsleistung, Kurzarbeit, Soforthilfe. Ohne Krise wäre das Budget ausgeglichen gewesen. Die Schweizer Schuldenbremse unterscheidet ordentlichen und ausserordentlichen Haushalt — Corona-Ausgaben gingen in den ausserordentlichen mit spezieller Tilgungsregel. Klassifikation: überwiegend konjunkturell, nicht strukturell — die Wirtschaft erholte sich, das Defizit war nicht dauerhaft.', teilerklaerungen: [] },
  { id: '9c25aec9-6ed3-421b-bbc1-26aeaa7531ef', fachbereich: 'VWL', musterlosung: 'Schwarzarbeit fliesst nicht vollständig in die offizielle BIP-Statistik (geschätzt ca. 7% in der Schweiz). Wird sie legalisiert, erscheint sie plötzlich im BIP — das gemessene BIP steigt, ohne dass die tatsächliche Wirtschaftsleistung gewachsen ist. Ähnlicher Effekt bei Legalisierung von Drogen oder Prostitution. Das zeigt: BIP misst das sichtbare Wertschöpfungsspektrum, nicht die gesamte ökonomische Aktivität.', teilerklaerungen: [] },
  { id: '9fcd9081-c6f7-404a-a7b6-c10c5f83488b', fachbereich: 'VWL', musterlosung: '(a) Die Elastizität 0.4 ist unelastisch, also tragen Konsumenten den grössten Teil der Steuerlast — Benzin hat kurzfristig kaum Substitute. (b) Mengenrückgang = 0.4 × 20% = 8%. Langfristig ist die Elastizität höher (Autokauf, Wohnort, ÖV-Wechsel), der Rückgang entsprechend grösser. Die Benzin-Steuer ist effizient (geringer Wohlfahrtsverlust), trifft aber sozial schwächere Haushalte härter (Regressivität).', teilerklaerungen: [] },
  { id: 'a34c63c1-7e59-4fd9-a2a4-30bc69aeb9e4', fachbereich: 'VWL', musterlosung: 'Die US-Luxussteuer auf Yachten sollte Reiche belasten, traf aber vor allem Werftarbeiter: Die Nachfrage war elastisch (Reiche kauften in der Karibik oder Europa), das Angebot unelastisch (Werftarbeiter konnten nicht kurzfristig den Beruf wechseln). Die Werften entliessen Personal, die Steuer wurde nach wenigen Jahren abgeschafft. Fazit: Elastizitäten bestimmen die tatsächliche Steuerinzidenz — nicht der gesetzliche Steuerschuldner.', teilerklaerungen: [] },
  { id: 'ade60530-514f-4b08-86ff-9a15b016243e', fachbereich: 'VWL', musterlosung: 'Schalteggers Aussage betont Generationengerechtigkeit: Heutige Staatsausgaben auf Pump werden morgen durch Steuern zurückbezahlt — von heute jungen Menschen. Kreditfinanzierung verschiebt die Last zeitlich ohne Gegenwert, wenn nicht produktiv investiert wird (Infrastruktur, Bildung). Die Schweizer Schuldenbremse gilt als Instrument, das langfristige Rationalität erzwingt. Die Aussage ist zutreffend — ein zentraler Pfeiler verantwortungsvoller Haushaltspolitik.', teilerklaerungen: [] },
  { id: 'aff6c3d2-3fb6-405c-adf1-7479855ea267', fachbereich: 'VWL', musterlosung: 'Vorteile «Mehr Markt»: tiefere Arbeitslosigkeit (USA, Schweiz vs. Südeuropa), schnelle Anpassung an Strukturwandel, leistungsorientierte Entlohnung. Nachteile: hohe Einkommensungleichheit, Unsicherheit, schwache Arbeitnehmerrechte, prekäre Arbeitsverhältnisse. Die ökonomische Beurteilung hängt von der Denkschule ab — klassisch liberal pro, keynesianisch eher kontra. Der Schweizer Mittelweg (flexibler Markt, starkes Sozialnetz) hat sich empirisch bewährt.', teilerklaerungen: [] },
]

// === Runner ===
async function main() {
  const lines = updates.map(u => JSON.stringify(u)).join('\n') + '\n'
  await fs.appendFile(OUT, lines)

  const state = JSON.parse(await fs.readFile(STATE, 'utf8'))
  const now = new Date().toISOString()
  for (const u of updates) {
    state.fragen[u.id] = { status: 'done', zeitpunkt: now, teile: u.teilerklaerungen.length }
  }
  state.verarbeitet += updates.length
  state.letzteSession = now
  await fs.writeFile(STATE, JSON.stringify(state, null, 2))

  const withTeile = updates.filter(u => u.teilerklaerungen.length > 0).length
  console.log(`Session 10: ${updates.length} Fragen appended (${withTeile} mit Teilerklärungen, ${updates.length - withTeile} ohne).`)
  console.log(`Total verarbeitet: ${state.verarbeitet} / ${state.totalFragen}`)
}

main().catch(err => { console.error(err); process.exit(1) })
