#!/usr/bin/env node
/**
 * Session 20: 50 VWL/richtigfalsch-Fragen.
 * Erste Hälfte des 100er-Batches nach Fachbereich → Typ → ID.
 * Keine Teilerklärungen (aussagen haben keine IDs in der DB).
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'fragen-updates.jsonl')
const STATE = path.join(__dirname, 'state.json')

const updates = [
  { id: '1768a96e-9129-48ac-a03c-2f6cf10b2469', fachbereich: 'VWL', musterlosung: 'Richtig. Um 1850 lag die Wochenarbeitszeit in Europa bei gut 80 Stunden (Sechs- bis Siebentagewoche), heute bei 35 bis 42 Stunden. Trotz dieser Halbierung ist der Wohlstand massiv gestiegen — dank Produktivitätsfortschritt durch Maschinen, Ausbildung und organisatorische Verbesserungen. Weniger Stunden ergeben heute mehr Output pro Kopf.', teilerklaerungen: [] },
  { id: '17d29ddb-acd6-49bd-8aed-18acc9d13ed3', fachbereich: 'VWL', musterlosung: 'Richtig. Friedman misstraute diskretionärer, fallweiser Geldpolitik wegen ihrer verzögerten und schwer dosierbaren Wirkung. Stattdessen schlug er eine Geldmengenregel vor: Die Notenbank soll die Geldmenge im Gleichschritt mit dem langfristigen Potenzialwachstum ausweiten — stetig und moderat. Damit vermeidet sie Fehlsteuerungen und macht Inflationserwartungen besser planbar.', teilerklaerungen: [] },
  { id: '1a55da7f-8c40-491b-be82-c9f2b8c492b0', fachbereich: 'VWL', musterlosung: 'Richtig. Die Verrechnungssteuer von 35 Prozent auf Kapitalerträge ist eine Sicherungssteuer. Sie soll erzwingen, dass Steuerpflichtige ihre Zinsen und Dividenden korrekt deklarieren. Wer die Erträge in der Steuererklärung ausweist, erhält die Verrechnungssteuer vollständig zurückerstattet. Nicht deklarierte Erträge führen hingegen zu einem definitiven Verlust.', teilerklaerungen: [] },
  { id: '1ae57e31-ab98-436b-9806-32d2b9dda29a', fachbereich: 'VWL', musterlosung: 'Richtig. Die neue Wachstumstheorie sieht Bildungsausgaben als Investition in Humankapital: Zeit und Geld werden eingesetzt, um später ein höheres Einkommen zu erzielen. Bildung erzeugt zudem positive externe Effekte für die ganze Volkswirtschaft — höhere Produktivität, Innovation und Anpassungsfähigkeit. Die Abgrenzung von blossem Konsum ist deshalb ökonomisch sinnvoll.', teilerklaerungen: [] },
  { id: '1c307857-a81f-4a40-a886-92c39c99e297', fachbereich: 'VWL', musterlosung: 'Richtig. Banken leben vom Zinsdifferenzgeschäft: Sie zahlen tiefere Zinsen auf Spareinlagen und verdienen mit höheren Zinsen bei der Kreditvergabe. Werden Giroguthaben bei der SNB negativ verzinst, Spargelder aber weiter positiv, drückt das auf die Marge. Die Weitergabe an Sparkunden ist politisch heikel und erfolgt erst spät — Gebührenerhöhungen federn das teilweise ab.', teilerklaerungen: [] },
  { id: '1cf7aa34-cb24-498d-9d27-826a90825edd', fachbereich: 'VWL', musterlosung: 'Richtig. Empirische Studien bestätigen diesen Zusammenhang. Offene Märkte fördern den Wettbewerb, erlauben Spezialisierung nach komparativen Vorteilen und erleichtern den Technologietransfer. Länder, die sich abschotten, verzichten auf Skalenerträge und Innovation. Die Schweiz als kleine offene Volkswirtschaft zeigt diese Logik exemplarisch.', teilerklaerungen: [] },
  { id: '1d0efcc5-7be9-4e88-859d-28ebcd09fb7d', fachbereich: 'VWL', musterlosung: 'Richtig. Höhere Sparzinsen bedeuten, dass Geld auf dem Sparkonto mehr erwirtschaftet. Bargeld oder Lohnkontostände verlieren dadurch relativ an Attraktivität — die Opportunitätskosten der Bargeldhaltung steigen. Das Publikum hält weniger Bargeld und mehr verzinsliche Einlagen. Diese Beziehung zwischen Zins und Geldnachfrage ist ein Kernelement der Geldtheorie.', teilerklaerungen: [] },
  { id: '1dad653d-f211-4a1b-a105-cd061b3e6264', fachbereich: 'VWL', musterlosung: 'Falsch. Der Arbeitseinsatz pro Einwohner ist in der Schweiz seit 2000 sogar um rund 7 Prozent zurückgegangen. Der Wohlstandszuwachs geht ausschliesslich auf das Produktivitätswachstum von rund 25 Prozent (2000 bis 2018) zurück. Mehr Output pro Stunde — nicht mehr Stunden — ist der Motor des höheren BIP pro Kopf.', teilerklaerungen: [] },
  { id: '1e07c6b3-7243-4551-859a-c414ab899285', fachbereich: 'VWL', musterlosung: 'Falsch. Die Verschuldung hat sich in den letzten Jahren auch in Schwellenländern wie China stark erhöht. Sie ist ein globales Phänomen, das Industrie-, Schwellen- und Entwicklungsländer gleichermassen betrifft. Unterschiede bestehen vor allem in Struktur (inländisch/fremdwährungsdenominiert) und Tragfähigkeit, nicht in der grundsätzlichen Existenz.', teilerklaerungen: [] },
  { id: '1e86bcd9-9a5e-4e75-9a53-3ea03e0d3c88', fachbereich: 'VWL', musterlosung: 'Richtig. Münzen werden von Swissmint — einer Einheit der Bundesverwaltung — hergestellt und an die SNB verkauft. Sie gelten deshalb als Verpflichtung des Bundes, nicht der Nationalbank. Zur Notenbankgeldmenge M0 zählen nur die Verpflichtungen der SNB: Banknoten und Giroguthaben der Banken bei der SNB. Münzen bleiben ausserhalb von M0.', teilerklaerungen: [] },
  { id: '1f414c35-c344-4ded-9938-692ac7497dec', fachbereich: 'VWL', musterlosung: 'Richtig. Bei elastischen Kurven reagieren Angebot und Nachfrage stark auf die Steuer: Die Mengenreduktion ist gross, viele potenzielle Transaktionen fallen weg. Damit entsteht ein grosser Wohlfahrtsverlust (Deadweight Loss). Bei unelastischen Kurven bleibt die Mengenreduktion gering, der Wohlfahrtsverlust ist deutlich kleiner — daher besteuert man bevorzugt unelastische Güter.', teilerklaerungen: [] },
  { id: '20e5d20e-22f5-43a5-b3dc-c3340567f76c', fachbereich: 'VWL', musterlosung: 'Richtig. Unternehmen beschäftigen Arbeitskräfte nicht um ihrer selbst willen, sondern zur Produktion von Gütern und Dienstleistungen. Sinkt die Nachfrage nach diesen Produkten, sinkt auch die Nachfrage nach Arbeit. Deshalb heisst sie «abgeleitete» Nachfrage — sie leitet sich aus der Gütermarktnachfrage ab und reagiert mit Verzögerung auf die Konjunktur.', teilerklaerungen: [] },
  { id: '2263f3f4-b0c7-4963-ab16-91467ef3149b', fachbereich: 'VWL', musterlosung: 'Richtig. Strassenbeleuchtung ist nicht-rival: Der Lichtgenuss einer Person schmälert den anderer nicht. Zudem ist sie nicht-ausschliessbar — niemand kann gezielt vom Licht abgehalten werden. Bei privater Organisation würden Trittbrettfahrer nicht zahlen, das Gut käme nicht zustande. Deshalb wird Strassenbeleuchtung kollektiv über Steuern finanziert.', teilerklaerungen: [] },
  { id: '23f4145f-64af-4ba9-9f4b-e62f49ad8ac7', fachbereich: 'VWL', musterlosung: 'Richtig. Jede Steuer verändert die relativen Preise und verzerrt damit die Signalfunktion des Preissystems. Die Mengen passen sich an, Knappheiten werden nicht mehr exakt abgebildet — ein Wohlfahrtsverlust ist die Regel. Die Staatstätigkeit kann die Wohlfahrt dennoch insgesamt erhöhen, wenn der Nutzen der Staatsausgaben den Verzerrungseffekt übersteigt.', teilerklaerungen: [] },
  { id: '25a6461e-00f6-45d9-acaf-72480868accf', fachbereich: 'VWL', musterlosung: 'Richtig. Die neoliberale Ordnung beschränkt den Staat auf Wettbewerbssicherung — etwa durch Kartellrecht. Die soziale Marktwirtschaft geht weiter und ergänzt diese Wettbewerbsordnung um Verteilungsaufgaben: Sozialversicherungen, Arbeitslosenversicherung und Sozialhilfe. Ziel ist Marktorientierung mit sozialer Absicherung, ohne den Leistungsanreiz zu zerstören.', teilerklaerungen: [] },
  { id: '2914949c-2bf8-4553-904f-8a54bfd27a47', fachbereich: 'VWL', musterlosung: 'Richtig. Psychologische Faktoren wirken als Verstärker im Konjunkturverlauf. In Phasen grosser Unsicherheit verschieben Konsumenten Käufe und Unternehmen Investitionen — ein einsetzender Abschwung wird dadurch tiefer. Umgekehrt verstärkt Optimismus in Aufschwüngen die Dynamik. Stimmungsindikatoren wie KOF oder Konsumentenvertrauen messen diese Effekte.', teilerklaerungen: [] },
  { id: '2983df03-f292-433a-be7f-a7f2b24c4743', fachbereich: 'VWL', musterlosung: 'Falsch. Die Corona-Krise war kein gewöhnlicher Konjunkturzyklus, sondern ein gleichzeitiger Angebots- und Nachfrageschock aus einer Gesundheitskrise und staatlichen Lockdowns. Die Massnahmen (Kurzarbeit, Überbrückungskredite, Härtefallhilfen) zielten auf die Überbrückung des Stillstands, nicht auf Nachfrageankurbelung. Klassische konjunkturpolitische Instrumente wären hier unzureichend gewesen.', teilerklaerungen: [] },
  { id: '2d047a1f-e317-4ad3-a8f4-1dc1adb39777', fachbereich: 'VWL', musterlosung: 'Falsch. Trotz hohen Wohlstands leben gemäss BFS rund 8 Prozent der Schweizer Bevölkerung in relativer Einkommensarmut. Hohe Lebenshaltungskosten — Mieten, Krankenkassenprämien, Nebenkosten — führen dazu, dass auch in der Schweiz Menschen am Existenzminimum leben. Absolute Armut ist selten, relative Armut aber real und messbar.', teilerklaerungen: [] },
  { id: '2eefea14-e10f-466c-8e5f-f9190236dfab', fachbereich: 'VWL', musterlosung: 'Richtig. Der Gini-Koeffizient misst die Einkommensungleichheit auf einer Skala von 0 bis 1. Ein Wert von 0 bedeutet vollständige Gleichverteilung — alle verdienen gleich viel. Ein Wert von 1 steht für maximale Ungleichheit — eine einzige Person bezieht das gesamte Einkommen. Reale Volkswirtschaften liegen dazwischen, die Schweiz bei etwa 0.33.', teilerklaerungen: [] },
  { id: '2f2e5736-f5fe-464b-a968-dfda7646674e', fachbereich: 'VWL', musterlosung: 'Richtig. Die Schweizer Staatsquote liegt bei rund 33 Prozent des BIP und damit deutlich unter dem OECD-Durchschnitt. Länder wie Frankreich oder Schweden erreichen Werte von 50 Prozent und mehr. Gründe sind ein schlanker Staatsapparat, föderale Aufgabenteilung und private Finanzierung von Gesundheits- und Vorsorgeleistungen.', teilerklaerungen: [] },
  { id: '310514e4-00e0-463a-ad35-38967cb9373d', fachbereich: 'VWL', musterlosung: 'Richtig. Die Lorenzkurve für Vermögen weicht deutlich stärker von der Gleichverteilung ab als jene für Einkommen. Im Kanton Bern etwa besitzen rund 209\'000 Personen gar kein Vermögen, während 770 Personen etwa 20 Prozent des Gesamtvermögens halten. Vermögen ist kumulativ und vererbbar — deshalb konzentrieren es sich stärker als laufende Einkommen.', teilerklaerungen: [] },
  { id: '3424f193-772c-4152-a8a8-598924d4c08f', fachbereich: 'VWL', musterlosung: 'Richtig. Die zweite Säule folgt dem Kapitaldeckungsverfahren: Arbeitgeber und Arbeitnehmer zahlen je zur Hälfte Beiträge auf ein individuelles Konto der Versicherten ein. Das angesparte Kapital wird verzinst und später als Rente oder Kapitalauszahlung ausbezahlt. Dies unterscheidet die 2. Säule klar von der AHV mit Umlageverfahren.', teilerklaerungen: [] },
  { id: '3460a953-e03b-4a29-8942-b80866c9c868', fachbereich: 'VWL', musterlosung: 'Richtig. Im Gleichgewicht bei vollkommener Konkurrenz wird solange produziert und konsumiert, bis die Zahlungsbereitschaft des Grenzkäufers den Grenzkosten des Grenzverkäufers entspricht. Konsumenten- und Produzentenrente sind zusammen maximal. Jede Abweichung vom Gleichgewicht — etwa durch Steuern, Monopol oder Preisregulierung — verkleinert die Gesamtrente.', teilerklaerungen: [] },
  { id: '35dad048-bd93-4219-9a26-e272577efd6f', fachbereich: 'VWL', musterlosung: 'Richtig. Das KOF-Konjunkturbarometer der Konjunkturforschungsstelle der ETH Zürich gilt als einer der wichtigsten Frühindikatoren der Schweizer Konjunktur. Es beruht auf Unternehmensumfragen und bildet zukünftige BIP-Entwicklungen früher ab als harte Daten. Entscheidungsträger in Politik, SNB und Wirtschaft beobachten den Index monatlich.', teilerklaerungen: [] },
  { id: '361f8968-7c90-4dc5-8fb1-695128731411', fachbereich: 'VWL', musterlosung: 'Falsch. Bei elastischer Nachfrage reagieren die Konsumenten stark auf Preiserhöhungen — Substitute sind verfügbar, Mengenrückgang ist gross. Versuchen Produzenten, die Steuer über den Preis weiterzugeben, bricht die Nachfrage ein. Den grösseren Teil der Steuerlast tragen deshalb die Produzenten. Die unelastischere Marktseite trägt die Steuer — hier sind das die Anbieter.', teilerklaerungen: [] },
  { id: '37e58979-62fa-4ae0-8008-841a7decb5a7', fachbereich: 'VWL', musterlosung: 'Richtig. Opportunitätskosten sind der entgangene Nutzen der besten nicht gewählten Alternative. Bei einem Manager mit hohem Stundenlohn kostet eine Stunde Freizeit den entsprechenden entgangenen Verdienst — nicht nur die Zeit selbst. Je höher der Zeitwert, desto teurer wird jede alternative Verwendung. Eisenhut nennt dies «Warum Manager gehetzt sind».', teilerklaerungen: [] },
  { id: '3a2970da-e28e-4d34-9df9-8c53116cc04c', fachbereich: 'VWL', musterlosung: 'Falsch. Modernes Papiergeld hat praktisch keinen materiellen Eigenwert — die Produktion einer 100er-Note kostet nur etwa 40 Rappen. Entscheidend ist nicht der Materialwert, sondern Vertrauen und allgemeine Akzeptanz. Solange alle Geld annehmen, funktioniert es als Zahlungs-, Wertaufbewahrungs- und Recheneinheitsmittel. Buchgeld hat gar keinen physischen Körper mehr.', teilerklaerungen: [] },
  { id: '3d9a0d27-e4ec-47ef-abc0-7edee291d501', fachbereich: 'VWL', musterlosung: 'Falsch. Die Sozialhilfe ist keine Sozialversicherung. Sie wird aus allgemeinen Steuermitteln finanziert — nicht durch Beiträge von Versicherten. Ihr Anspruch hängt vom konkreten Bedarf ab: Sie greift erst, wenn Erwerbseinkommen, Versicherungsleistungen und Vermögen ausgeschöpft sind. Die Sozialhilfe bildet das «letzte Netz» der sozialen Sicherung.', teilerklaerungen: [] },
  { id: '3db6ae0b-db5e-4032-a7fe-397fb6303ab8', fachbereich: 'VWL', musterlosung: 'Richtig. Die Schweiz hat ein sehr hohes Preisniveau. Beim PPP-Vergleich (Kaufkraftparitäten) wird berücksichtigt, dass derselbe Betrag in der Schweiz weniger kauft als in Ländern mit tieferen Preisen. Länder wie China oder Indien steigen in dieser Rangliste entsprechend auf, die Schweiz rutscht ab. Der Vergleich wird dadurch realitätsnäher als der reine Wechselkursvergleich.', teilerklaerungen: [] },
  { id: '3e326bf5-6d0d-4b84-92b3-9e09a3ee490f', fachbereich: 'VWL', musterlosung: 'Richtig. Die negative Einkommenssteuer mildert die Armutsfalle, weil Transfers mit steigendem Einkommen nur teilweise reduziert werden. Jeder zusätzlich verdiente Franken erhöht das verfügbare Einkommen, das Arbeiten lohnt sich stets. Bei klassischer Sozialhilfe kann hingegen ein zusätzlicher Lohnfranken den Transfer im Verhältnis eins zu eins senken — der Arbeitsanreiz verschwindet.', teilerklaerungen: [] },
  { id: '400ec63e-8122-4a0e-ba42-25e1cc03b9f5', fachbereich: 'VWL', musterlosung: 'Richtig. Beide Massnahmen verfolgen einen Lenkungszweck. Die Tabaksteuer verteuert unerwünschtes Verhalten (Rauchen), die Steuervergünstigung verbilligt erwünschtes Verhalten (Elektromobilität). Der Mechanismus ist identisch — einmal als Bestrafung über eine Lenkungsabgabe, einmal als Belohnung über einen Steuervorteil. Die Richtung der Anreizwirkung ist jedoch entgegengesetzt.', teilerklaerungen: [] },
  { id: '40f26bfb-6eb5-494d-9887-3a5663e8ed11', fachbereich: 'VWL', musterlosung: 'Falsch. Das ökonomische Prinzip gilt universell — überall dort, wo knappe Mittel auf unbegrenzte Bedürfnisse treffen. Auch im Alltag wird es angewendet: beim Einkaufen mit begrenztem Budget, bei der Einteilung knapper Freizeit oder bei der Wahl des Verkehrsmittels. Wirtschaften ist nicht auf «die Wirtschaft» beschränkt, sondern beginnt bei individuellen Entscheidungen.', teilerklaerungen: [] },
  { id: '431f69e2-a2ea-4395-8b8e-f7f1de07c13d', fachbereich: 'VWL', musterlosung: 'Falsch. Das Rezept funktioniert nicht immer — das Beispiel Luzern zeigt dies. Kantone mit Zentrumsfunktion haben strukturelle Nachteile wie Zentrumslasten und ländliche Gebiete. Diese lassen sich auch durch tiefe Steuern nur begrenzt kompensieren. Luzern musste trotz tiefster Unternehmenssteuern Sparpakete beschliessen und die Steuern für die Bevölkerung wieder erhöhen.', teilerklaerungen: [] },
  { id: '432cc54c-0420-403d-a0d0-812be861bc17', fachbereich: 'VWL', musterlosung: 'Richtig. Homogene Güter sind für die Nachfrager nicht unterscheidbar — etwa Weizen einer bestimmten Sorte oder Rohöl einer Qualität. Nur der Preis zählt als Entscheidungskriterium. Bei heterogenen (differenzierten) Gütern wie Smartphones oder Autos unterscheiden sich die Produkte in Qualität, Design, Marke oder Service — Preisunterschiede lassen sich damit rechtfertigen.', teilerklaerungen: [] },
  { id: '4444fda0-21fc-4ac3-8fd8-0a6c94691de1', fachbereich: 'VWL', musterlosung: 'Falsch — das Gegenteil trifft zu. Gewinnt ein Kanton an Ressourcenstärke, erhält er weniger NFA-Mittel, weil er weniger auf Ausgleich angewiesen ist. Genau das erlebte Luzern: Der Kanton baute Wirtschaftskraft auf, erhielt aber weniger NFA — was die Finanzlage zusätzlich belastete. Der NFA belohnt nicht Wirtschaftswachstum, sondern gleicht Ressourcen­schwäche aus.', teilerklaerungen: [] },
  { id: '451d8daa-1128-459e-adea-4d4c1e0ff2d9', fachbereich: 'VWL', musterlosung: 'Richtig. Der Wirtschaftskreislauf besteht aus zwei parallel laufenden Strömen in entgegengesetzter Richtung: Reale Ströme (Güter, Dienstleistungen, Produktionsfaktoren) und monetäre Ströme (Geld als Gegenleistung). Jeder Kauf verbindet beide — Geld wechselt zum Verkäufer, das Gut zum Käufer. Diese Gegenstromrelation ist die Grundlage aller Kreislaufdarstellungen.', teilerklaerungen: [] },
  { id: '46478572-ca9c-4619-875c-36bc8b91d4da', fachbereich: 'VWL', musterlosung: 'Richtig. Die meisten Steuern erfüllen mehrere Zwecke gleichzeitig. Die Tabaksteuer verfolgt einen Lenkungszweck (Rauchreduktion), generiert aber auch Fiskaleinnahmen. Die progressive Einkommenssteuer erfüllt einen Fiskalzweck und dient zugleich der Umverteilung. Welcher Zweck dominiert, hängt von Ausgestaltung und politischer Zielsetzung ab.', teilerklaerungen: [] },
  { id: '48368b77-e5dd-4699-bcfa-1c672bae897d', fachbereich: 'VWL', musterlosung: 'Richtig. Die Verhaltensökonomie untersucht, wie Menschen tatsächlich Entscheidungen treffen — im Gegensatz zum idealisierten Homo oeconomicus. Daniel Kahneman (Nobelpreis 2002) und Richard Thaler (Nobelpreis 2017) zeigten systematische Abweichungen vom rationalen Verhalten: Ankereffekte, Verlustaversion, Zeitinkonsistenz. Diese Erkenntnisse fliessen heute in Regulierung und Policy Design ein.', teilerklaerungen: [] },
  { id: '48773a7c-061a-45a4-a529-af4b95fe9d2d', fachbereich: 'VWL', musterlosung: 'Falsch — das BIP steigt sogar. Die Wiederaufbauarbeiten werden als Wertschöpfung erfasst und erhöhen das BIP. Die Zerstörung selbst — verlorenes Vermögen, zerstörte Gebäude — wird statistisch nicht erfasst. Das Beispiel zeigt eine wichtige Schwäche des BIP: Es misst Produktion, aber keine Bestandesveränderungen oder Wohlfahrtsverluste durch Katastrophen.', teilerklaerungen: [] },
  { id: '4903877a-1a1e-41b4-8ad2-86afc353a4c8', fachbereich: 'VWL', musterlosung: 'Richtig. Trotz berechtigter Kritik bleibt der Homo oeconomicus ein nützliches Modell — besonders für die Analyse von Unternehmen, die gewinnorientiert handeln. Für individuelles Konsumentenverhalten ergänzt die Verhaltensökonomie das Modell mit psychologischen Erkenntnissen. Die VWL erweitert ihr Menschenbild laufend, um realitätsnähere Prognosen zu ermöglichen.', teilerklaerungen: [] },
  { id: '4aa42082-74d4-4f84-9b73-76046672872d', fachbereich: 'VWL', musterlosung: 'Falsch. Wachsen reales BIP und Bevölkerung im gleichen Tempo, bleibt das BIP pro Kopf konstant — der einzelne Einwohner kann sich nicht mehr leisten als zuvor. Wohlstandszuwachs entsteht nur, wenn das BIP pro Kopf steigt — also wenn die Wirtschaftsleistung schneller wächst als die Bevölkerung. Reines Bevölkerungswachstum reicht nicht.', teilerklaerungen: [] },
  { id: '4aa82834-62fb-44b8-8af1-3030525c3437', fachbereich: 'VWL', musterlosung: 'Richtig. Die Schweiz hat im europäischen Vergleich einen besonders hohen Anteil direkter Steuern — also Einkommens- und Vermögenssteuern — an den gesamten Steuereinnahmen. Andere Länder finanzieren ihre Staatshaushalte stärker über indirekte Steuern wie Mehrwertsteuer, Energieabgaben oder Zölle. Die föderale Steuerhoheit der Kantone verstärkt diese Struktur.', teilerklaerungen: [] },
  { id: '4d32773c-f44a-421a-9531-928671dbc2e1', fachbereich: 'VWL', musterlosung: 'Richtig. Die Armutsfalle (auch «Schwelleneffekt» oder «poverty trap») entsteht, wenn bei Aufnahme einer Arbeit Sozialhilfe und Prämienverbilligungen entfallen. Das verfügbare Einkommen steigt nur minimal oder gar nicht — das Arbeiten lohnt sich kaum. Dies ist ein klassisches Beispiel für eine unbeabsichtigte Nebenwirkung wohlmeinender Sozialpolitik.', teilerklaerungen: [] },
  { id: '4df89dfd-2a63-438a-887d-89f528158df4', fachbereich: 'VWL', musterlosung: 'Richtig. Ökonomen gehen von der Annahme aus, dass menschliche Bedürfnisse grundsätzlich unbegrenzt sind. Sobald ein Bedürfnis befriedigt ist, entstehen neue Wünsche — ob nach besseren Gütern, neuen Erfahrungen oder gesellschaftlichem Ansehen. Diese Annahme ist zentral für das ökonomische Grundproblem: unbegrenzte Bedürfnisse treffen auf knappe Ressourcen.', teilerklaerungen: [] },
  { id: '4e073b1e-976d-4198-a506-68036c6bacc2', fachbereich: 'VWL', musterlosung: 'Falsch — PPP korrigieren gerade für Preisunterschiede zwischen Ländern, nicht für Wechselkursschwankungen. In einem Hochpreisland wie der Schweiz kauft derselbe USD-Betrag weniger als in einem Niedrigpreisland wie Indien. PPP rechnen auf gleiche Kaufkraft um und machen internationale Einkommensvergleiche realitätsnäher. Der Wechselkurs bildet die Kaufkraft oft nicht korrekt ab.', teilerklaerungen: [] },
  { id: '4e7d7a49-636c-4002-91cf-275626385207', fachbereich: 'VWL', musterlosung: 'Richtig. Ein öffentliches Gut weist zwei Merkmale auf. Nicht-Rivalität: Der Konsum durch eine Person beeinträchtigt den Konsum anderer nicht — etwa bei Strassenbeleuchtung. Nicht-Ausschliessbarkeit: Niemand kann vom Konsum ausgeschlossen werden — auch wer nicht zahlt, profitiert. Beide Eigenschaften führen zum Trittbrettfahrerproblem, weshalb der Staat öffentliche Güter bereitstellt.', teilerklaerungen: [] },
  { id: '5002b650-3e3f-4be3-b763-c3e70bdc856b', fachbereich: 'VWL', musterlosung: 'Falsch. Die Arbeitslosenquote ist ein Spätindikator. Der Arbeitsmarkt reagiert mit mehrmonatiger Verzögerung auf die Konjunktur — Unternehmen passen ihren Personalbestand erst an, wenn sich die Lage bereits geändert hat. Kurzarbeit und Einstellungsstopps dienen als Puffer. Frühindikatoren sind beispielsweise das KOF-Barometer oder Auftragseingänge der Industrie.', teilerklaerungen: [] },
  { id: '505faac2-6085-45a5-a269-12f8d47d6ae6', fachbereich: 'VWL', musterlosung: 'Richtig. Das Saysche Theorem besagt: Jede Produktion erzeugt in gleicher Höhe Einkommen, das wieder für den Kauf von Gütern verwendet wird. Nach klassischer Auffassung kann es deshalb keine dauerhafte Überproduktion geben — der Markt tendiert von selbst zum Gleichgewicht bei Vollbeschäftigung. Keynes stellte diese Sicht in den 1930er-Jahren grundsätzlich in Frage.', teilerklaerungen: [] },
  { id: '50884499-da80-4346-bb9e-e2867e2252ff', fachbereich: 'VWL', musterlosung: 'Richtig. Bei einem Steuersatz von 100 Prozent müssten Steuerpflichtige ihr gesamtes Einkommen abgeben. Jeder Anreiz zur Arbeit entfällt — niemand würde mehr produzieren, niemand würde Einkommen generieren. Die Steuerbemessungsgrundlage schrumpft auf null, und die Steuereinnahmen sind trotz des maximalen Satzes null. Das ist der obere Extrempunkt der Laffer-Kurve.', teilerklaerungen: [] },
  { id: '51c9cac4-7432-4af8-81b6-246d6478b8cc', fachbereich: 'VWL', musterlosung: 'Richtig. Öffentliche Leistungen wie Bildung, Gesundheit und Sicherheit gelten als einkommenselastisch. Mit steigendem Einkommen erwartet eine Gesellschaft mehr Qualität und Umfang vom Staat — mehr Schulen, mehr Gesundheitsversorgung, mehr soziale Absicherung. Dieser Zusammenhang ist als «Wagnersches Gesetz der wachsenden Staatsausgaben» bekannt.', teilerklaerungen: [] },
]

async function main() {
  const stateRaw = await fs.readFile(STATE, 'utf8')
  const state = JSON.parse(stateRaw)

  const outLines = []
  let done = 0
  let skip = 0
  const skipped = []
  const now = new Date().toISOString()

  for (const u of updates) {
    const existing = state.fragen[u.id]
    if (existing && existing.status === 'done') {
      continue
    }
    outLines.push(JSON.stringify(u))
    state.fragen[u.id] = { status: 'done', zeitpunkt: now, teile: u.teilerklaerungen.length }
    done++
  }

  state.verarbeitet = Object.values(state.fragen).filter(x => x.status === 'done').length
  state.letzteSession = now

  if (outLines.length > 0) {
    await fs.appendFile(OUT, outLines.join('\n') + '\n', 'utf8')
  }
  await fs.writeFile(STATE, JSON.stringify(state, null, 2), 'utf8')

  const total = state.verarbeitet
  const totalAll = state.totalFragen
  const pct = ((total / totalAll) * 100).toFixed(1)
  console.log(`Session 20 done.`)
  console.log(`  Verarbeitet diese Session: ${done + skip} (done=${done}, skip=${skip})`)
  console.log(`  Total: ${total}/${totalAll} (${pct}%)`)
  if (skipped.length > 0) console.log(`  Skip-Fragen: ${skipped.join(', ')}`)
  console.log(`  Verteilung: 50 VWL/richtigfalsch`)
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
