#!/usr/bin/env node
/**
 * Session 24: 50 VWL-Fragen (23 sortierung + 6 visualisierung + 21 zuordnung).
 * Alle Typen ohne Sub-Array-IDs → 0 Teilerklärungen, nur überarbeitete Musterlösungen.
 * Qualitätsregeln: 2–4 Sätze, ~60–80 Wörter, neutrale 3. Person, Schweizer Hochdeutsch, Plain-Text.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'fragen-updates.jsonl')
const STATE = path.join(__dirname, 'state.json')

const updates = [
  // ----- 23 VWL / sortierung -----
  { id: '846fb01f-3e57-46b6-9ca6-f00e2ce79dd0', fachbereich: 'VWL', musterlosung: `Progressive Tarife belasten hohe Einkommen überproportional und wirken stark umverteilend, etwa die Schweizer Einkommenssteuer. Proportionale Tarife belasten alle Einkommen mit demselben Prozentsatz und haben keine Umverteilungswirkung. Degressive Tarife belasten tiefe Einkommen relativ stärker und wirken sogar anti-umverteilend; indirekte Steuern wie die MWST haben tendenziell diesen Effekt. Die Reihenfolge richtet sich nach der Stärke der Umverteilung.`, teilerklaerungen: [] },
  { id: '856fa325-0f0f-4158-9dd8-d90a179d2556', fachbereich: 'VWL', musterlosung: `Das Drei-Säulen-System sichert die Schweizer Altersvorsorge gestaffelt ab. Die 1. Säule (AHV) garantiert das Existenzminimum und arbeitet im Umlageverfahren: Erwerbstätige finanzieren die Renten der heutigen Pensionierten. Die 2. Säule (BVG/Pensionskasse) ist obligatorisch für Arbeitnehmende und im Kapitaldeckungsverfahren organisiert. Die 3. Säule ist freiwillig und steuerlich begünstigt; Säule 3a ist gebunden, Säule 3b frei verfügbar.`, teilerklaerungen: [] },
  { id: '877fa3b0-aa66-433b-9164-d363e9547a28', fachbereich: 'VWL', musterlosung: `Der Wirtschaftskreislauf wird in Lehrbüchern stufenweise aufgebaut. Zuerst der einfache 2-Sektoren-Kreislauf zwischen Haushalten und Unternehmen, dann die Erweiterung um den Staat mit Steuern, Transfers und Staatskonsum. Anschliessend kommen die Banken hinzu (Kapitalmarkt mit Sparen und Investieren) und schliesslich das Ausland mit Exporten, Importen und Kapitalströmen. Jede Erweiterung macht das Modell realistischer, aber auch komplexer.`, teilerklaerungen: [] },
  { id: '90490a8d-3a5e-4d15-a0c7-ab94cc45b9c0', fachbereich: 'VWL', musterlosung: `Die Wirkungskette der expansiven Geldpolitik beginnt bei der SNB, die den Leitzins senkt. Dadurch werden Kredite günstiger, was Investitionen der Unternehmen und Konsum der Haushalte stimuliert. Die gesamtwirtschaftliche Nachfrage steigt, Produktion und Beschäftigung wachsen in der Folge. Dies entspricht dem keynesianischen Transmissionsmechanismus über den Zinskanal; er wirkt typischerweise erst mit einer Verzögerung von 6 bis 18 Monaten auf die Realwirtschaft.`, teilerklaerungen: [] },
  { id: '9c28c5f9-70d6-46cf-91f7-f800027d1556', fachbereich: 'VWL', musterlosung: `Adam Smith begründete 1776 mit «Wealth of Nations» die klassische Ökonomie und prägte das Bild der unsichtbaren Hand. Ab etwa 1870 formalisierte die Neoklassik das Modell des rationalen Akteurs mathematisch. Keynes kritisierte 1936 die Selbstheilungskräfte des Marktes und legitimierte staatliches Eingreifen. Ab etwa 1980 zeigt die Verhaltensökonomie systematische Abweichungen vom Homo Oeconomicus; Kahneman und Thaler erhielten dafür Nobelpreise.`, teilerklaerungen: [] },
  { id: 'ac84c49c-795d-4684-8822-bb3017f49d02', fachbereich: 'VWL', musterlosung: `Die Zinsbelastung wirkt sofort, jedes Budgetjahr fliessen Mittel an die Gläubiger. Crowding-out zeigt sich mittelfristig, wenn der Staat die Kreditnachfrage hochtreibt und private Investitionen verdrängt. Vertrauensverluste können relativ plötzlich eintreten und Staatsschuldenkrisen auslösen, wie 2010 in Griechenland. Generationenungerechtigkeit ist ein langfristiges Problem: Die heute aufgenommenen Schulden müssen künftige Steuerzahlende bedienen.`, teilerklaerungen: [] },
  { id: 'b2a978ac-9b0f-4710-bd47-5a4af9ae2289', fachbereich: 'VWL', musterlosung: `Maslow ordnet Bedürfnisse hierarchisch in fünf Stufen. Zuerst müssen physiologische Grundbedürfnisse wie Nahrung und Schlaf gedeckt sein, gefolgt von Sicherheitsbedürfnissen. Erst dann werden soziale Bedürfnisse, Wertschätzung und schliesslich Selbstverwirklichung relevant. Das Modell ist eine Vereinfachung — in der Realität können sich Stufen überschneiden, und höhere Bedürfnisse wirken auch ohne vollständige Befriedigung der unteren Stufen.`, teilerklaerungen: [] },
  { id: 'b3e79413-0413-46e7-858f-55c8d08d6cb2', fachbereich: 'VWL', musterlosung: `Die AHV wird im Umlageverfahren finanziert und ist deshalb stark vom Verhältnis der Beitragszahler zu den Rentenbeziehenden abhängig. Dieses Verhältnis verschlechtert sich seit Jahrzehnten: tiefere Geburtenraten, steigende Lebenserwartung und schliesslich die Pensionierung der Babyboomer-Generation belasten die Finanzierung kumulativ. Die Reform AHV 21 (in Kraft 2024) erhöhte das Frauenrentenalter auf 65 und passte den MWST-Satz leicht an.`, teilerklaerungen: [] },
  { id: 'b4e35a26-7077-485b-926a-5c9a6184c4dd', fachbereich: 'VWL', musterlosung: `Das BIP nach Verwendungsansatz folgt der Formel Y = C + I + G + NX. In der Schweiz dominiert der private Konsum mit über 50 Prozent, gefolgt von Investitionen mit etwa 25 bis 30 Prozent. Der Staatskonsum macht rund 10 bis 12 Prozent aus. Die Nettoexporte schwanken stark und tragen trotz starker Exportwirtschaft nur wenige Prozent bei, weil die Schweiz auch viel importiert.`, teilerklaerungen: [] },
  { id: 'bcee3e46-8a43-4d26-bfa5-28677fce1e86', fachbereich: 'VWL', musterlosung: `Die SNB unterscheidet vier Geldmengenaggregate, die immer breiter werden. M0 umfasst nur das Zentralbankgeld (Notenumlauf plus Sichteinlagen der Banken bei der SNB). M1 ergänzt jederzeit verfügbare Sichteinlagen. M2 nimmt zusätzlich Spareinlagen auf, die etwas weniger liquide sind. M3 schliesst auch Termineinlagen mit fester Laufzeit ein. Je breiter das Aggregat, desto geringer die Liquidität der enthaltenen Komponenten.`, teilerklaerungen: [] },
  { id: 'c16f9738-de20-4387-abd4-395ed0d11ead', fachbereich: 'VWL', musterlosung: `Friktionelle Arbeitslosigkeit dauert typischerweise wenige Tage bis Wochen und entsteht beim Stellenwechsel oder Berufseinstieg. Saisonale Arbeitslosigkeit umfasst einige Monate, etwa im Bauhandwerk oder Tourismus. Konjunkturelle Arbeitslosigkeit hält an, solange die Rezession dauert — Monate bis wenige Jahre. Strukturelle Arbeitslosigkeit ist oft langfristig, weil sie Umschulung oder Standortwechsel erfordert und ganze Branchen durch Technologiewandel oder Globalisierung treffen kann.`, teilerklaerungen: [] },
  { id: 'c5b55461-1b9c-470e-b5db-400a7bfc3f6d', fachbereich: 'VWL', musterlosung: `Der Konjunkturzyklus beginnt am Tiefpunkt, der Talsohle. Es folgt der Aufschwung mit steigender Produktion und sinkender Arbeitslosigkeit. Im Boom — der Hochkonjunktur — wird das Produktionspotenzial überschritten und die Inflation zieht oft an. Im anschliessenden Abschwung kühlt sich die Wirtschaft ab, und der Zyklus endet wieder an einer Talsohle, von wo er erneut beginnt.`, teilerklaerungen: [] },
  { id: 'cd2472cb-4b24-4415-93c1-2a12ae01693b', fachbereich: 'VWL', musterlosung: `Eigeninteresse ist die realistischste Annahme, denn Menschen handeln tatsächlich oft eigennützig. Nutzenmaximierung ist bereits stärker vereinfachend, weil die Verhaltensökonomie zahlreiche Heuristiken und systematische Verzerrungen aufzeigt. Stabile Präferenzen sind empirisch widerlegt: Gewohnheiten, Moden und Werbung verändern Vorlieben laufend. Die Annahme vollständiger Information ist am unrealistischsten, denn sie ist in der Realität praktisch nie gegeben.`, teilerklaerungen: [] },
  { id: 'de2f34d5-8dc8-48f4-9643-ee7319cfcc63', fachbereich: 'VWL', musterlosung: `Der Zinskanal des geldpolitischen Transmissionsmechanismus wirkt stufenweise. Zuerst senkt die SNB den Leitzins, dann reichen die Geschäftsbanken die tieferen Zinsen weiter. Kredite werden günstiger, Unternehmen investieren mehr und Haushalte konsumieren mehr. Die gesamtwirtschaftliche Nachfrage steigt, in der Folge wachsen BIP und Beschäftigung. Der gesamte Prozess dauert typischerweise 6 bis 18 Monate; dies wird als Time Lag bezeichnet.`, teilerklaerungen: [] },
  { id: 'e34669aa-ec33-470b-b0cf-9974f72635d6', fachbereich: 'VWL', musterlosung: `In der Agrargesellschaft war Boden der entscheidende Knappheitsfaktor; wer über Land verfügte, kontrollierte die Produktion. Mit der Industrialisierung gewann Kapital an Bedeutung — Maschinen, Fabriken und Infrastruktur. In der heutigen Wissensgesellschaft ist Humankapital der wichtigste Wachstumstreiber: Bildung, Forschung, Innovation und Datenkompetenz. Alle vier Faktoren bleiben relevant, aber ihre relative Bedeutung hat sich im Laufe der Geschichte deutlich verschoben.`, teilerklaerungen: [] },
  { id: 'e46e9c24-6663-4734-99ea-efb99d015eb8', fachbereich: 'VWL', musterlosung: `Die Instrumente lassen sich nach Eingriffstiefe ordnen. Private Verhandlungen nach Coase brauchen keinen staatlichen Eingriff, sondern setzen klar definierte Eigentumsrechte voraus. Transparenz- und Informationspflichten greifen leicht ein. Marktbasierte Instrumente wie Pigou-Steuern oder Emissionszertifikate setzen Preissignale, überlassen die Mengenentscheidung aber dem Markt. Direkte Verbote sind der stärkste Eingriff. Die Schweizer CO₂-Abgabe gilt als marktbasiertes Instrument mittlerer Eingriffstiefe.`, teilerklaerungen: [] },
  { id: 'e87f79a4-af3f-435e-8972-8306aaa9f1bc', fachbereich: 'VWL', musterlosung: `Die Schweiz weist dank Schuldenbremse eine der tiefsten Schuldenquoten weltweit aus, klar unter 30 Prozent des BIP. Deutschland liegt im EU-Mittelfeld nahe dem Maastricht-Kriterium von 60 Prozent. Die USA überschritten ihre Verschuldung seit Finanzkrise und COVID-19 deutlich die 100-Prozent-Marke. Japan hält mit über 230 Prozent die höchste Schuldenquote aller Industrieländer; sie wird allerdings grösstenteils im Inland gehalten.`, teilerklaerungen: [] },
  { id: 'eaf232a8-6310-47ed-a40a-236f3d5ac89f', fachbereich: 'VWL', musterlosung: `Die internationale Steuerkooperation hat sich schrittweise verschärft. Bilaterale Doppelbesteuerungsabkommen waren der Anfang. Nach dem UBS-Skandal von 2008 geriet das Schweizer Bankgeheimnis stark unter Druck und wurde abgebaut. Der automatische Informationsaustausch folgte: Über 100 Staaten tauschen heute Kontoinformationen aus. Den jüngsten Schritt bildet die globale OECD-Mindeststeuer von 15 Prozent für Grosskonzerne mit über 750 Millionen Euro Umsatz.`, teilerklaerungen: [] },
  { id: 'edd53887-5667-4e1a-b928-89938bb0f3ba', fachbereich: 'VWL', musterlosung: `Die Geldentwicklung verlief über Jahrtausende. Zuerst diente Warengeld als Tauschmittel, etwa Vieh, Salz oder Muscheln. Mit den ersten Münzen ab etwa 600 vor Christus entstand standardisiertes Metallgeld. Banknoten mit Golddeckung etablierten sich ab dem 17. Jahrhundert. Der Nixon-Schock von 1971 beendete den Goldstandard, und seither dominiert Fiat-Geld ohne intrinsischen Wert. Heute besteht in der Schweiz über 90 Prozent von M1 aus Buchgeld.`, teilerklaerungen: [] },
  { id: 'einr-sort-planeten', fachbereich: 'VWL', musterlosung: `Die Reihenfolge der Planeten von der Sonne aus gesehen lautet: Merkur, Venus, Erde, Mars, Jupiter, Saturn, Uranus und Neptun. Pluto wurde 2006 zum Zwergplaneten herabgestuft und gehört offiziell nicht mehr dazu. Diese Einführungsaufgabe dient dem Kennenlernen der Drag-and-Drop-Bedienung im Übungstool und hat keinen Bezug zum Volkswirtschaftsstoff.`, teilerklaerungen: [] },
  { id: 'f8adda7b-1a7b-498e-b024-a3589bb632e0', fachbereich: 'VWL', musterlosung: `Green Growth akzeptiert Wachstum grundsätzlich und fordert die Entkopplung von Ressourcenverbrauch durch Effizienz und technologischen Fortschritt — die moderateste Position. Beyond Growth relativiert das Wachstumsziel und betont alternative Wohlstandsmasse wie HDI oder Better Life Index. Degrowth fordert die aktive Schrumpfung der Wirtschaft in Industrieländern, weil unbegrenztes Wachstum mit planetaren Grenzen unvereinbar sei — die radikalste Position, die das Wirtschaftssystem grundlegend infrage stellt.`, teilerklaerungen: [] },
  { id: 'ueb-sort-planeten', fachbereich: 'VWL', musterlosung: `Die Reihenfolge der ersten fünf Planeten von der Sonne aus gesehen lautet: Merkur, Venus, Erde, Mars und Jupiter. Saturn, Uranus und Neptun folgen weiter aussen, gehören aber nicht zur Aufgabenstellung. Diese Übungsaufgabe dient dem Kennenlernen der Drag-and-Drop-Mechanik im Übungstool und hat keinen Bezug zum Volkswirtschaftsstoff.`, teilerklaerungen: [] },
  { id: 'ueb-sort-wochentage', fachbereich: 'VWL', musterlosung: `Die fünf Wochentage von Montag bis Freitag in chronologischer Reihenfolge lauten: Montag, Dienstag, Mittwoch, Donnerstag und Freitag. Das Wochenende mit Samstag und Sonntag ist hier nicht Teil der Aufgabe. Diese Übungsaufgabe dient ausschliesslich dem Kennenlernen der Drag-and-Drop-Mechanik im Übungstool und hat keinen Bezug zum Volkswirtschaftsstoff. Ähnliche Tutorial-Aufgaben stehen für Planeten und Emojis bereit.`, teilerklaerungen: [] },

  // ----- 6 VWL / visualisierung -----
  { id: '5afdac5b-5db1-4d35-8e65-52c51dfa0fb3', fachbereich: 'VWL', musterlosung: `Die Bedürfnispyramide nach Maslow (1943) ordnet menschliche Bedürfnisse hierarchisch in fünf Stufen, von unten nach oben. Zuerst die physiologischen Grundbedürfnisse, dann Sicherheit, soziale Bedürfnisse, Wertschätzung und an der Spitze die Selbstverwirklichung. Die unteren vier Stufen sind Defizitbedürfnisse — Mangel motiviert das Handeln. Die oberste Stufe gilt als Wachstumsbedürfnis und wird auch ohne Mangel angestrebt. Die Grenze verläuft zwischen Stufe 4 und 5.`, teilerklaerungen: [] },
  { id: 'ba2be9a3-fd17-4f4b-af8e-8beccfcb8af0', fachbereich: 'VWL', musterlosung: `Ein korrekter Konjunkturzyklus zeigt zwei vollständige Wellen rund um eine steigende Trendlinie, die das Produktionspotenzial darstellt. Die tatsächliche Wirtschaftsleistung schwankt um diesen Trend. Die vier Phasen sind Aufschwung (steigende Produktion), Hochkonjunktur (über dem Trend), Abschwung (rückläufige Produktion) und Rezession beziehungsweise Talsohle (unter dem Trend). Die Output-Lücke zwischen tatsächlichem BIP und Trend ist konjunkturpolitisch zentral.`, teilerklaerungen: [] },
  { id: 'd53f3d0f-b9d3-44fd-bb51-da6579be7d25', fachbereich: 'VWL', musterlosung: `Das Marktgleichgewicht entsteht im Schnittpunkt der fallenden Nachfragekurve und der steigenden Angebotskurve. Die x-Achse zeigt die Menge M, die y-Achse den Preis P. Beim Gleichgewichtspreis P* werden M* Einheiten getauscht, der Markt ist geräumt. Über dem Gleichgewichtspreis entsteht ein Angebotsüberschuss, darunter ein Nachfrageüberschuss; der Preismechanismus treibt den Markt zurück ins Gleichgewicht.`, teilerklaerungen: [] },
  { id: 'e367a37c-d8c4-4f2d-b9c9-4dc0bd191146', fachbereich: 'VWL', musterlosung: `Bei einem Mindestreservesatz von 10 Prozent beträgt der Geldschöpfungsmultiplikator 1 geteilt durch 0.1 gleich 10. Aus einer Einlage von 1'000 Franken kann theoretisch bis zu 10'000 Franken Buchgeld entstehen: Bank A behält 100 Franken Reserve und vergibt 900 als Kredit. Diese landen wieder als Einlage, woraus Bank B 90 reserviert und 810 weitergibt — und so weiter. In der Praxis ist der Multiplikator kleiner, weil Banken freiwillige Reserven halten.`, teilerklaerungen: [] },
  { id: 'ffac1ef6-e50f-49e5-8f51-0f98ab550abf', fachbereich: 'VWL', musterlosung: `Das BIP nach Verwendungsansatz folgt der Formel Y = C + I + G + NX. In der Schweiz entfallen rund 55 Prozent auf den privaten Konsum (C), etwa 25 Prozent auf Investitionen (I), rund 12 Prozent auf Staatsausgaben (G) und etwa 8 Prozent auf Nettoexporte (NX). Die Aufteilung zeigt, dass der private Konsum die wichtigste Nachfragekomponente ist. Die genauen Anteile schwanken jährlich, die Reihenfolge bleibt aber stabil.`, teilerklaerungen: [] },
  { id: 'ueb-vis-smiley', fachbereich: 'VWL', musterlosung: `Eine korrekte Lösung zeigt einen Smiley mit Gesichtsumriss als Kreis, zwei Augen und einem geschwungenen Mund. Mindestens zwei verschiedene Werkzeuge der Werkzeugleiste müssen verwendet werden — etwa Stift und Kreis oder Linie und Text. Auch verschiedene Farben sollen eingesetzt werden. Diese Einführungsaufgabe dient dem Kennenlernen der Zeichenwerkzeuge und hat keinen Bezug zum Volkswirtschaftsstoff.`, teilerklaerungen: [] },

  // ----- 21 VWL / zuordnung -----
  { id: '01f3f608-10dd-47d6-bf77-4553250f1d31', fachbereich: 'VWL', musterlosung: `Die Arbeitslosenquote des SECO erfasst nur Personen, die beim RAV registriert und sofort vermittelbar sind, und liegt deshalb tiefer. Die Erwerbslosenquote des BFS basiert auf der Stichprobenbefragung SAKE nach ILO-Definition und umfasst auch Ausgesteuerte und nicht beim RAV gemeldete Suchende. Die Erwerbslosenquote ist international vergleichbar und erscheint quartalsweise; die SECO-Quote wird monatlich publiziert. Beide Indikatoren haben unterschiedliche Verwendungszwecke.`, teilerklaerungen: [] },
  { id: '02debc50-a22a-4870-81f1-2aa5f3a1daca', fachbereich: 'VWL', musterlosung: `Für das Modell sprechen Verhaltensweisen mit klarer Kosten-Nutzen-Abwägung: Preisvergleich vor dem Kauf, Wahl des günstigsten Lieferanten, Studienwahl nach Berufsperspektiven. Gegen das Modell sprechen Impulskäufe, Doping wider besseres Wissen und anonyme Spenden. Bei den ersten beiden überwiegt kurzfristiger Affekt oder kurzfristiger Vorteil über langfristigen Schaden. Bei anonymen Spenden fehlt der Eigennutzen vollständig — es handelt sich um altruistisches Verhalten ohne Anerkennungseffekt.`, teilerklaerungen: [] },
  { id: '0dde482f-c51f-4e74-a582-4089bc7791df', fachbereich: 'VWL', musterlosung: `Private Güter sind rival und ausschliessbar — Konsum durch eine Person verhindert den Konsum durch andere, und Nicht-Zahler können ausgeschlossen werden (Brötchen). Öffentliche Güter sind nicht-rival und nicht-ausschliessbar (Landesverteidigung, Strassenbeleuchtung). Allmendegüter sind rival, aber nicht-ausschliessbar, was die Tragödie der Allmende verursacht (Fischbestände, Weideland, Trinkwasser aus Grundwasser). Klubgüter sind nicht-rival, aber ausschliessbar (Pay-TV, Kino). Die Klassifikation bestimmt, ob der Markt das Gut effizient bereitstellen kann.`, teilerklaerungen: [] },
  { id: '0ea9a1a2-9313-42e1-aa71-f23f47ee8a03', fachbereich: 'VWL', musterlosung: `Beim Gefangenendilemma wäre Kooperation für alle besser, individuelle Anreize verhindern sie jedoch. Doping im Sport, übermässige Werbung im Wettbewerb, Überfischung der Meere und Wettrüsten zwischen Staaten haben die identische Struktur: Jede Partei verbessert einzeln ihre Position, am Ende stehen alle schlechter da. Einkauf im Supermarkt und ein Sprintwettbewerb haben diese Struktur nicht — der eigene Nutzen hängt dort nicht von der Strategiewahl der anderen ab.`, teilerklaerungen: [] },
  { id: '12247739-3166-461c-b712-605f18ea2289', fachbereich: 'VWL', musterlosung: `Wachstum entsteht entweder durch mehr Arbeitsstunden oder durch höhere Produktivität pro Stunde. Mehr Stunden bringen Erhöhung des Pensionierungsalters, Zuwanderung von Fachkräften und höhere Erwerbsquote durch ausreichend Kinderbetreuung. Höhere Produktivität bringen bessere Ausbildung, neue Technologien und Investitionen in Maschinen und Anlagen. Da die demografische Entwicklung das Arbeitsangebot in vielen Industrieländern bremst, gewinnt die Produktivitätssteigerung als Wachstumsquelle laufend an Bedeutung.`, teilerklaerungen: [] },
  { id: '1c752298-46cb-424c-997c-fb9c97779253', fachbereich: 'VWL', musterlosung: `In der Schweiz lassen sich Parteien grob den drei Gerechtigkeitstheorien zuordnen, wobei die Zuordnung idealtypisch und vereinfacht ist. Die Junge SVP steht den Libertarians nahe und fordert Eigenverantwortung statt Sozialstaat. Die Jungfreisinnigen vertreten die liberale Position mit gezielten Interventionen bei Marktversagen. Die Junge SP entspricht den Collectivists mit Ausbau des Sozialstaats und mehr Umverteilung. Wettbewerbsorientierung gehört zur libertären, Verstaatlichung zur kollektivistischen Position.`, teilerklaerungen: [] },
  { id: '1e0e0c3c-60b6-4a86-a9f4-bc2fba1ad7ef', fachbereich: 'VWL', musterlosung: `Geld erfüllt drei klassische Funktionen. Als Zahlungsmittel dient es zum Bezahlen von Gütern, sei es bar an der Kasse oder per Online-Überweisung. Als Rechnungseinheit ermöglicht es den Vergleich von Preisen — Handys, Autos und Dienstleistungen lassen sich in Franken bewerten und gegenüberstellen. Als Wertaufbewahrungsmittel erlaubt Geld das Sparen und das Verschieben von Konsum auf später, etwa für Ferien oder die Altersvorsorge.`, teilerklaerungen: [] },
  { id: '2cd14b61-6a46-4904-a963-bea2ae37cd0b', fachbereich: 'VWL', musterlosung: `Staatsversagen hat verschiedene Ursachen. Veränderte Leistungsanreize (Moral Hazard) entstehen, wenn Sozialleistungen die Eigenanstrengung dämpfen — grosszügige ALV oder Sozialhilfe verlängern die Stellensuche. Eigendynamik und Überangebot beschreiben das Phänomen, dass einmal eingeführte Subventionen kaum abschaffbar sind und Sozialausgaben schneller wachsen als das BIP. Unbeabsichtigte Nebenwirkungen treten auf, wenn gut gemeinte Regulierungen wie Kündigungsschutz oder Mietpreisbremse gegenteilige Effekte erzeugen.`, teilerklaerungen: [] },
  { id: '3205c0fc-71ac-4b16-9188-908b120cd53c', fachbereich: 'VWL', musterlosung: `Der Staat greift auf vier Arten in die Wirtschaft ein. Mit Regulierung setzt er Verhaltensregeln, etwa obligatorische Sozialversicherungsbeiträge oder Mindestlöhne. Über Finanzierung lenkt er via Steuern und Subventionen Geldströme — Einkommenssteuer auf der Einnahmeseite, Krankenkassenverbilligung auf der Ausgabenseite. Über Produktion stellt er Güter direkt bereit, etwa staatliche Schulen mit Lehrpersonen. Mit Transfers schliesslich leistet er direkte Zahlungen an Bedürftige wie Sozialhilfe und Mietbeiträge.`, teilerklaerungen: [] },
  { id: '36f46235-1e55-4095-b59a-893c2f6ad800', fachbereich: 'VWL', musterlosung: `Umverteilung erfolgt über zwei Seiten des Staatsbudgets. Auf der Einnahmenseite nimmt der Staat — über die progressive Einkommenssteuer, Lohnprozente von Arbeitgebenden und Arbeitnehmenden sowie die Mehrwertsteuer. Auf der Ausgabenseite gibt er — über AHV-Renten, Prämienverbilligungen der Krankenkasse und Subventionen für Kinderkrippen. Beide Seiten zusammen verändern die primäre Markteinkommensverteilung in Richtung einer gleichmässigeren sekundären Verteilung. Der Umverteilungseffekt summiert sich aus Einnahmen- und Ausgabenwirkung.`, teilerklaerungen: [] },
  { id: '3d5ec9ca-502e-41aa-8582-9be7f16a497e', fachbereich: 'VWL', musterlosung: `Negative externe Effekte verursachen Kosten für unbeteiligte Dritte, ohne dass der Verursacher dafür aufkommt — Flussverschmutzung, Fluglärm und Abgase im Stadtverkehr sind klassische Beispiele. Positive externe Effekte stiften Nutzen für Dritte, ohne dass dieser eingepreist wird — Bestäubung durch Imkerbienen, Herdenimmunität durch Impfung und gesellschaftliche Erträge aus Forschung. Beide Phänomene führen zu Marktversagen: zu viel negative, zu wenig positive Externalitäten.`, teilerklaerungen: [] },
  { id: '404e1c00-be3f-400d-b4e5-a8f0c434a404', fachbereich: 'VWL', musterlosung: `Produktinnovationen schaffen neue oder deutlich verbesserte Güter — das Smartphone, ein neues Medikament oder das Elektroauto sind klassische Beispiele. Prozessinnovationen verändern Herstellungsverfahren und steigern damit die Produktivität — Fliessbandarbeit, Automatisierung durch Roboter und 3D-Druck als neue Produktionstechnologie. Beide Innovationsformen treiben das Wirtschaftswachstum, wirken aber unterschiedlich: Produktinnovationen erweitern das Angebot, Prozessinnovationen senken Kosten und Preise.`, teilerklaerungen: [] },
  { id: '41c43add-44e6-4d76-b3c3-9c6019a8d300', fachbereich: 'VWL', musterlosung: `Die vier Güterarten unterscheiden sich nach Rivalität und Ausschliessbarkeit im Konsum. Private Güter wie Auto und Kleider sind rival und ausschliessbar; der Markt versorgt effizient. Klubgüter wie Pay-TV sind nicht-rival, aber ausschliessbar — Anbieter können den Zugang kontrollieren. Allmendegüter wie Fischbestände sind rival, aber nicht-ausschliessbar und benötigen Regulierung gegen Übernutzung. Öffentliche Güter wie Landesverteidigung und saubere Luft sind nicht-rival und nicht-ausschliessbar; der Staat muss sie bereitstellen.`, teilerklaerungen: [] },
  { id: '41ce0d29-9fd7-4cf4-929f-d4780d8a14ca', fachbereich: 'VWL', musterlosung: `Die Maslow'sche Bedürfnispyramide ordnet menschliche Bedürfnisse fünfstufig. Körperliche Grundbedürfnisse umfassen Essen, Trinken und ein Dach über dem Kopf. Sicherheitsbedürfnisse zeigen sich in Krankenversicherung und stabilem Arbeitsplatz. Soziale Bedürfnisse betreffen Freundschaften und die Zugehörigkeit zu einer Gruppe. Selbstverwirklichung manifestiert sich in kreativem Tun oder dem Schreiben eines Buches. In der Praxis können mehrere Stufen gleichzeitig aktiv sein.`, teilerklaerungen: [] },
  { id: '455187e4-02de-4bb0-83f9-2765f8a7204d', fachbereich: 'VWL', musterlosung: `Lohnrigiditäten haben drei zentrale Erklärungen. Institutionelle Faktoren wie Mindestlöhne, Kündigungsschutz und Gesamtarbeitsverträge schützen bestehende Löhne vor Anpassungen nach unten. Das Insider-Outsider-Modell betont die Verhandlungsmacht der Beschäftigten gegenüber Arbeitssuchenden: Insider verlangen höhere Löhne, weil Neueinstellungen Transaktionskosten verursachen. Die Effizienzlohntheorie erklärt, dass Unternehmen freiwillig über dem Marktlohn zahlen, um Motivation und Loyalität zu erhöhen sowie die Fluktuation zu senken.`, teilerklaerungen: [] },
  { id: '4fbbba8c-05f0-41bd-93d7-79013d276a92', fachbereich: 'VWL', musterlosung: `Eine Mengensteuer hat vier Wohlfahrtseffekte. Die Konsumentenrente sinkt wegen des höheren Konsumentenpreises, die Produzentenrente sinkt wegen des tieferen Erlöses je verkaufter Einheit. Der Staat erhält Steuereinnahmen — das Rechteck zwischen altem und neuem Preis multipliziert mit der neuen Menge. Ein Teil der verlorenen Renten geht jedoch unwiderruflich verloren: das Deadweight-Loss-Dreieck der durch die Steuer verhinderten Transaktionen. Die Steuereinnahmen sind nicht der Wohlfahrtsverlust.`, teilerklaerungen: [] },
  { id: '5bffa9a7-f31c-4d72-bb60-879fdafd311e', fachbereich: 'VWL', musterlosung: `Marktformen unterscheiden sich nach Wettbewerbsintensität und damit nach Wohlfahrtsverlust. Vollkommene Konkurrenz erzeugt keinen Wohlfahrtsverlust, weil Preis gleich Grenzkosten ist. Monopolistische Konkurrenz produziert mittlere Verluste durch Produktdifferenzierung und beschränkte Marktmacht der einzelnen Anbieter. Monopol ohne Preisdifferenzierung führt zu hohem Verlust durch Mengenbeschränkung und überhöhte Preise. Oligopolistische Kartellabsprachen bewirken ähnlich grosse Verluste wie reine Monopole.`, teilerklaerungen: [] },
  { id: '5daf945d-e899-483a-b7b6-21adfd767461', fachbereich: 'VWL', musterlosung: `Die Drei-Sektoren-Hypothese unterscheidet drei Wirtschaftsbereiche. Der primäre Sektor umfasst die Urproduktion und Rohstoffgewinnung — Landwirtschaft (Bauer), Forstwirtschaft (Förster) und Fischerei (Fischer). Der sekundäre Sektor steht für Verarbeitung und Industrie, etwa Automechaniker in Fabriken oder Uhrmacher. Der tertiäre Sektor bündelt sämtliche Dienstleistungen wie Bankberatung, Bildung und Gesundheitsversorgung. In der Schweiz arbeiten heute über 75 Prozent der Erwerbstätigen im tertiären Sektor.`, teilerklaerungen: [] },
  { id: '5df97a4f-374b-4ae9-9323-db9f7ce68aeb', fachbereich: 'VWL', musterlosung: `Konjunkturelle Defizite entstehen rezessionsbedingt durch tiefere Steuereinnahmen und höhere Sozialausgaben. Sie wirken als automatische Stabilisatoren und verschwinden im Aufschwung von selbst. Strukturelle Defizite hingegen sind dauerhaft nicht finanzierte Ausgaben und werden auch in Aufschwungphasen nicht abgebaut. Sie können nur durch aktive Massnahmen beseitigt werden — Ausgabenkürzungen oder Steuererhöhungen. Die Schweizer Schuldenbremse zielt auf den Ausgleich des strukturellen Saldos und lässt konjunkturelle Defizite zu.`, teilerklaerungen: [] },
  { id: '5fabc10a-aa1a-4693-b861-ec768cb2220d', fachbereich: 'VWL', musterlosung: `Die Schweizer Altersvorsorge ruht auf drei Säulen. Die 1. Säule (AHV) deckt das Existenzminimum, ist seit 1948 obligatorisch und wird im Umlageverfahren finanziert. Die 2. Säule (BV) sichert die Fortführung der gewohnten Lebenshaltung, ist seit 1985 obligatorisch und im Kapitaldeckungsverfahren organisiert. Die 3. Säule der individuellen Vorsorge ist freiwillig und steuerlich begünstigt. Zusammen sollen die drei Säulen rund 60 bis 80 Prozent des letzten Einkommens ersetzen.`, teilerklaerungen: [] },
  { id: '5ff8edbb-1f13-4ac8-8e2b-78da948ade83', fachbereich: 'VWL', musterlosung: `Sozialversicherungsreformen wirken entweder auf der Leistungs- oder auf der Finanzierungsseite. Leistungsreformen verändern, was und wie viel ausbezahlt wird — Heraufsetzung des Rentenalters, Einheitsrente oder Privatisierung der ALV ändern die Ausgaben. Finanzierungsreformen verändern die Einnahmequellen, etwa die Umstellung auf Kapitaldeckung, Finanzierung über Mehrwertsteuer statt Lohnprozente oder über Ökosteuern. Wirksame Reformen kombinieren oft beide Ansätze, denn nachhaltige Lösungen brauchen Anpassungen auf beiden Seiten.`, teilerklaerungen: [] },
]

async function main() {
  const stateRaw = await fs.readFile(STATE, 'utf8')
  const state = JSON.parse(stateRaw)

  const outLines = []
  let done = 0
  const now = new Date().toISOString()

  for (const u of updates) {
    const existing = state.fragen[u.id]
    if (existing && existing.status === 'done') {
      console.warn(`skip already done: ${u.id}`)
      continue
    }
    outLines.push(JSON.stringify(u))
    state.fragen[u.id] = {
      status: 'done',
      zeitpunkt: now,
      teile: u.teilerklaerungen.length,
    }
    done++
  }

  state.verarbeitet = (state.verarbeitet || 0) + done
  state.letzteSession = now

  await fs.appendFile(OUT, outLines.join('\n') + (outLines.length ? '\n' : ''), 'utf8')
  await fs.writeFile(STATE, JSON.stringify(state, null, 2), 'utf8')

  console.log(`Session 24: ${done} verarbeitet, total ${state.verarbeitet}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
