#!/usr/bin/env node
/**
 * Session 8: 100 Recht/richtigfalsch-Fragen.
 * aussagen ohne IDs → teilerklaerungen = [] (Spec-Konvention).
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'fragen-updates.jsonl')
const STATE = path.join(__dirname, 'state.json')

const updates = [
  { id: '12a4f135-8c28-4973-aa54-1b3e8822857c', fachbereich: 'Recht', musterlosung: 'Falsch. Art. 3 ZGB ist kein allgemeiner Grundsatz mit umfassendem Geltungsbereich. Die Norm greift nur dort, wo das Gesetz eine Rechtsfolge ausdrücklich an den guten oder bösen Glauben knüpft (z.B. Art. 933, 936 ZGB). Ein umfassender Gutglaubensschutz besteht im schweizerischen Recht nicht — der Gutglaubensschutz ist stets punktuell.', teilerklaerungen: [] },
  { id: '13574949-cfc8-4abf-9bd4-496ab2ca729a', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 266a Abs. 1 OR können die Parteien längere, nicht aber kürzere Kündigungsfristen als die gesetzlichen vereinbaren. Diese einseitig zwingende Regelung schützt insbesondere den Mieter vor übereilten Wohnungsverlusten. Wird dennoch eine kürzere Frist vereinbart, gilt die gesetzliche Frist.', teilerklaerungen: [] },
  { id: '1403657b-f869-4da6-9906-e59dced6a5de', fachbereich: 'Recht', musterlosung: 'Falsch. Obligationen können aus drei Entstehungsgründen hervorgehen: aus Vertrag (OR 1 ff.), aus unerlaubter Handlung (OR 41 ff.) oder aus ungerechtfertigter Bereicherung (OR 62 ff.). Der Vertrag ist zwar der häufigste Entstehungsgrund, aber keineswegs der einzige — gesetzliche Tatbestände wie Deliktshaftung oder Rückforderung einer Nichtschuld erzeugen Obligationen ohne Vertragsschluss.', teilerklaerungen: [] },
  { id: '18e39d5e-2b8d-4b28-9085-44bc1e26680b', fachbereich: 'Recht', musterlosung: 'Falsch. Gesetze werden vom Parlament verabschiedet und treten grundsätzlich ohne Volksabstimmung in Kraft. Das Volk kann mit dem fakultativen Referendum (50\'000 Unterschriften) zwar eine Abstimmung verlangen, muss dies aber nicht tun. Ohne Referendumsbegehren wird das Gesetz nach Ablauf der Referendumsfrist rechtskräftig.', teilerklaerungen: [] },
  { id: '1a195f1e-c935-41a5-8279-5ea8a26df80f', fachbereich: 'Recht', musterlosung: 'Richtig. Wer eine Sache mit Aufgabewillen verlässt (Dereliktion), verliert nach dem Sachenrecht das Eigentum daran. Die Sache wird herrenlos und kann von jedermann originär zu Eigentum erworben werden. Der Zettel «zum Mitnehmen» bringt den Aufgabewillen klar zum Ausdruck und erfüllt damit den Tatbestand der Besitzesaufgabe.', teilerklaerungen: [] },
  { id: '1d761022-41f2-428c-b25e-5d18734d0ef9', fachbereich: 'Recht', musterlosung: 'Richtig. Art. 36 Abs. 4 BV bestimmt: «Der Kerngehalt der Grundrechte ist unantastbar.» Der Kerngehalt bezeichnet jenen Bereich eines Grundrechts, der unter keinen Umständen eingeschränkt werden darf — auch nicht bei überwiegendem öffentlichem Interesse. Beispiel: Das Folterverbot gehört zum unantastbaren Kerngehalt der persönlichen Freiheit.', teilerklaerungen: [] },
  { id: '1e5831a9-3d49-4edc-88e4-17a2366be701', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 63 Abs. 1 kann die Rückforderung einer freiwillig bezahlten Nichtschuld nur verlangt werden, wenn der Leistende beweist, dass er sich über die Schuldpflicht im Irrtum befand. Ohne Irrtum gilt die Zahlung als bewusste Leistung und ist nicht rückforderbar. Die Beweislast liegt beim Rückforderer.', teilerklaerungen: [] },
  { id: '1e6aba6f-e62a-4acf-907c-5882d41d2660', fachbereich: 'Recht', musterlosung: 'Richtig. Ein Rechtsmissbrauch nach Art. 2 Abs. 2 ZGB liegt insbesondere bei nutzloser Rechtsausübung vor — also wenn ein Recht aus Rache, Schikane oder Schadenfreude ausgeübt wird. In solchen Fällen wird das Recht zweckwidrig eingesetzt, ohne schutzwürdiges eigenes Interesse. Der offenbare Missbrauch findet keinen Rechtsschutz.', teilerklaerungen: [] },
  { id: '1ec5bd84-4557-41d4-a836-253f4b737379', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 15 StGB darf ein rechtswidriger oder unmittelbar bevorstehender Angriff in einer den Umständen angemessenen Weise abgewehrt werden. Entscheidend ist die Verhältnismässigkeit: Die Abwehr muss erforderlich und angemessen sein. Liegt berechtigte Notwehr vor, entfällt die Rechtswidrigkeit — die Handlung bleibt straffrei.', teilerklaerungen: [] },
  { id: '1f57dbd4-40f2-45ea-a25e-66dc34919fe8', fachbereich: 'Recht', musterlosung: 'Richtig. Unproblematische Kleintiere wie Meerschweinchen, Hamster, Wellensittiche oder Kanarienvögel dürfen grundsätzlich auch ohne ausdrückliche Einwilligung des Vermieters gehalten werden — sofern weder übermässige Anzahl noch Lärm oder Schmutz eine Beeinträchtigung verursachen. Selbst ein generelles Tierhaltungsverbot im Mietvertrag gilt für solche Kleintiere in der Regel als unzulässig.', teilerklaerungen: [] },
  { id: '21199a6c-55c7-467f-ac72-a7c63083e49e', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 322 ff. ist die Lohnzahlung die zentrale Gegenleistung des Arbeitgebers für die vom Arbeitnehmer erbrachte Arbeit. Sie bildet neben der Fürsorgepflicht (OR 328) die Hauptpflicht des Arbeitgebers im Arbeitsvertrag. Ohne vereinbarten Lohnbestandteil liegt kein Arbeitsvertrag, sondern ein anderer Vertragstyp vor.', teilerklaerungen: [] },
  { id: '2473f346-8df4-4f92-9f64-726ad0588005', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 259 OR hat der Mieter den gewöhnlichen Unterhalt der Mietsache selbst zu besorgen. Darunter fallen kleine Arbeiten, die ohne Fachmann erledigt werden können — etwa Glühbirnen wechseln oder einen verstopften Abfluss reinigen. Sobald ein Handwerker nötig wird, handelt es sich nicht mehr um gewöhnlichen Unterhalt, sondern um eine Reparatur des Vermieters.', teilerklaerungen: [] },
  { id: '2619d274-1c25-43b2-8505-18efa0a5df3c', fachbereich: 'Recht', musterlosung: 'Falsch. Die freiwillige Einwilligung des Betroffenen ist ein Rechtfertigungsgrund nach Art. 28 Abs. 2 ZGB. Wer in Kenntnis der Sachlage einer Veröffentlichung zustimmt, kann nachträglich keine Persönlichkeitsverletzung geltend machen, solange sich die Verwendung im Rahmen der Einwilligung bewegt. Anderes gilt bei Erweiterung oder Missbrauch der Einwilligung.', teilerklaerungen: [] },
  { id: '2660bc8a-b1c3-49bb-8322-3f69cd713757', fachbereich: 'Recht', musterlosung: 'Falsch. Ein blosser Motivirrtum — der Irrtum über den Beweggrund des Vertragsschlusses — berechtigt nicht zur Anfechtung. Anfechtbar sind nur die im Gesetz genannten wesentlichen Irrtümer: der Erklärungsirrtum (OR 23/24) und der qualifizierte Grundlagenirrtum. Der Beweggrund gehört zur Risikosphäre des Irrenden und fällt nicht darunter.', teilerklaerungen: [] },
  { id: '283dae37-6f27-4ae4-b2d5-d3e5eef9fb3e', fachbereich: 'Recht', musterlosung: 'Richtig. Ein Auto ist eine Sache und damit ein Rechtsobjekt. Rechtsobjekte sind Gegenstände, über die Rechtssubjekte (natürliche und juristische Personen) verfügen können. Typischerweise streiten Rechtssubjekte um Rechtsobjekte — z.B. wem ein bestimmtes Auto gehört oder wer es verwenden darf.', teilerklaerungen: [] },
  { id: '2985d830-2039-4fd8-b717-19d4bb5940a4', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 19 Abs. 2 StGB mildert das Gericht die Strafe, wenn der Täter nur vermindert schuldfähig war. Vollständige Straffreiheit tritt ausschliesslich bei vollständiger Schuldunfähigkeit nach Art. 19 Abs. 1 StGB ein. Bei verminderter Schuldfähigkeit bleibt ein Teil des Unrechts zurechenbar — eine Bestrafung findet statt, aber in reduziertem Umfang.', teilerklaerungen: [] },
  { id: '2a99b673-408c-4383-b282-7bdd6205c108', fachbereich: 'Recht', musterlosung: 'Falsch. Bei einer Speziesschuld ist die individuell bestimmte Sache geschuldet — der Schuldner kann nicht einseitig eine gleichwertige Ersatzsache liefern. Wird die Sache ohne Verschulden zerstört, erlischt die Obligation nach OR 119. Bei Verschulden schuldet der Schuldner Schadenersatz nach OR 97 statt Ersatzleistung.', teilerklaerungen: [] },
  { id: '2ad18cac-1b1a-4602-a036-7aa1703aec9b', fachbereich: 'Recht', musterlosung: 'Falsch. Überzeit ist nach Art. 12 und 13 ArG auf höchstens 170 Stunden pro Jahr begrenzt und muss grundsätzlich durch gleichwertige Freizeit oder einen Lohnzuschlag von mindestens 25% kompensiert werden. Die Berufung auf «Notwendigkeit» ändert diese zwingende Kompensationspflicht nicht. 15 Stunden pro Woche ohne Ausgleich sind unzulässig.', teilerklaerungen: [] },
  { id: '2bf2f87e-22ed-450a-b5e9-fc15488a5d12', fachbereich: 'Recht', musterlosung: 'Falsch. Im Zivilprozess gilt die Beweislastregel nach Art. 8 ZGB: Wer aus einer Tatsache Rechte ableitet, trägt die Beweislast — in der Regel also der Kläger. Der Beklagte muss nur dann Tatsachen beweisen, wenn er selbst daraus Rechte ableitet, etwa bei einer Einrede wie Verjährung oder Zahlung. Eine generelle Unschuldsbeweispflicht besteht nicht.', teilerklaerungen: [] },
  { id: '2d8ca1b9-32bd-458f-a6f1-97fcd2a74b52', fachbereich: 'Recht', musterlosung: 'Richtig. Im Berner Wegweisungsfall hatte eine 13-köpfige Gruppe im Bahnhof Bern erheblich Alkohol konsumiert, Lärm verursacht und Passanten belästigt. Die Polizei verbot den Beteiligten daraufhin für drei Monate den Aufenthalt in alkoholkonsumierenden Personenansammlungen im Bahnhofsbereich. Der Fall führte zum bundesgerichtlichen Leiturteil zur Verhältnismässigkeit polizeilicher Wegweisungen.', teilerklaerungen: [] },
  { id: '2e988a17-06b1-49d1-bd10-67ba5a4259a3', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 336 ff. OR kann eine missbräuchliche Kündigung dem Arbeitnehmer eine Entschädigung von bis zu sechs Monatslöhnen einbringen (Art. 336a OR). Zuständig ist das Arbeitsgericht. Das Arbeitsverhältnis als solches wird jedoch trotz Missbrauch beendet — Wiedereinstellung wird nur ausnahmsweise ausgesprochen.', teilerklaerungen: [] },
  { id: '30ce4677-c12d-4cb0-9a59-7db9ffd4bc16', fachbereich: 'Recht', musterlosung: 'Richtig. Sitte bezeichnet ein gesellschaftlich erwartetes äusseres Verhalten — etwa sich beim neuen Nachbarn vorzustellen oder Höflichkeitsregeln einzuhalten. Die Einhaltung wird nicht staatlich durchgesetzt, die Missachtung kann aber gesellschaftliche Folgen wie Ablehnung oder Ächtung nach sich ziehen. Sitte unterscheidet sich damit vom rechtlich erzwingbaren Verhalten.', teilerklaerungen: [] },
  { id: '313b04c1-b6d5-4dd1-8861-acf1fb026ce1', fachbereich: 'Recht', musterlosung: 'Richtig. Die clausula rebus sic stantibus ist eine gewohnheitsrechtliche Ausnahme vom Grundsatz pacta sunt servanda. Gestützt auf Art. 2 Abs. 1 ZGB kann bei grundlegend und unvorhersehbar veränderten Umständen eine Vertragsanpassung oder ein teilweiser Leistungsverzicht verlangt werden. Voraussetzung sind Zumutbarkeits- und Verhältnismässigkeitserwägungen — das Festhalten am Vertrag müsste für eine Partei treuwidrig sein.', teilerklaerungen: [] },
  { id: '33bc3081-7009-40c2-9498-3423ea7a3262', fachbereich: 'Recht', musterlosung: 'Falsch. Recht haben und Recht bekommen ist nicht dasselbe. Im Prozess unterliegt eine Partei nicht selten nicht deshalb, weil sie materiell im Unrecht wäre, sondern weil sie die erforderlichen Beweise nicht erbringen kann. Die Beweislast nach Art. 8 ZGB entscheidet, wer die Folgen der Beweislosigkeit trägt.', teilerklaerungen: [] },
  { id: '345af82b-f6a8-42a7-b8ac-74af8e366958', fachbereich: 'Recht', musterlosung: 'Richtig. Bei der Verschuldenshaftung nach OR 41 muss der Geschädigte alle vier Haftungsvoraussetzungen beweisen: Schaden, adäquater Kausalzusammenhang, Widerrechtlichkeit und Verschulden. Fehlt einer der Punkte, entfällt die Haftung. Die Beweislast kann im Einzelfall durch Beweislastumkehr oder Gefahrensatz-Rechtsprechung erleichtert werden.', teilerklaerungen: [] },
  { id: '358d95cc-3884-451f-8659-19cf7e102cd3', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 262 Abs. 1 OR darf der Mieter die Mietsache nur mit Zustimmung des Vermieters ganz oder teilweise untervermieten. Der Vermieter darf die Zustimmung nur aus wichtigen Gründen verweigern (Art. 262 Abs. 2 OR). Ohne Zustimmung liegt eine Vertragsverletzung vor, die den Vermieter zur ausserordentlichen Kündigung berechtigen kann.', teilerklaerungen: [] },
  { id: '36eb7b92-7489-4694-b8d2-e557f24ed7c8', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 8 Abs. 3 BV und dem Gleichstellungsgesetz (GlG) gilt das Diskriminierungsverbot zwischen Frau und Mann zwingend. Ein GAV, der Frauen systematisch geringer entlöhnt als Männer für gleichwertige Arbeit, verstösst gegen GlG Art. 3. Das individuelle Recht auf gleichen Lohn setzt sich gegen widersprechende Kollektivverträge durch.', teilerklaerungen: [] },
  { id: '374925f8-52d9-44b7-be73-f758000c9d3f', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 29 liegt Furchterregung vor, wenn eine Partei durch die Drohung mit einem nicht geringen Übel zum Vertragsschluss bewegt wird. Die Drohung muss kausal und rechtswidrig sein. Der Bedrohte kann den Vertrag innerhalb eines Jahres anfechten (OR 31) und Schadenersatz fordern.', teilerklaerungen: [] },
  { id: '37b5f50c-fc54-46f6-b06a-5d3a2b163fb4', fachbereich: 'Recht', musterlosung: 'Falsch. Eine Dauerschuld ist eine fortgesetzte Leistungspflicht, die sich über einen Zeitraum erstreckt — typische Beispiele sind Miete, Arbeitsvertrag oder Abonnement. Sie unterscheidet sich strukturell von einer einmaligen Leistungspflicht, auch wenn diese in Raten erfüllt wird (z.B. Kaufpreiszahlung in Teilen). Bei der Dauerschuld ist Zeit ein konstitutives Element.', teilerklaerungen: [] },
  { id: '3b4b30f6-ec04-491a-9020-67de544fe635', fachbereich: 'Recht', musterlosung: 'Richtig. Weigert sich der Vermieter, Mängel ins Antrittsprotokoll aufzunehmen, sollte der Mieter eine eigene vollständige Mängelliste erstellen und per Einschreiben zustellen. So ist die Mängelmeldung beweiskräftig dokumentiert. Die Frist für nachträgliche Mängelrügen beträgt je nach Kanton in der Regel 10 bis 30 Tage nach Einzug.', teilerklaerungen: [] },
  { id: '3b624d34-1370-4191-95bf-c1265572d003', fachbereich: 'Recht', musterlosung: 'Falsch. Die Rechtsanwendung folgt einer festen Reihenfolge: Zuerst wird der Sachverhalt festgestellt (was ist geschehen?), dann die passende Rechtsnorm gesucht, danach die Subsumtion durchgeführt (stimmen Tatbestandsmerkmale überein?), und erst am Schluss die Rechtsfolge bestimmt. Die Rechtsfolge vor der Sachverhaltsprüfung zu setzen, würde den Prozess umkehren.', teilerklaerungen: [] },
  { id: '3c8814c3-3202-4b02-977c-ef756b4c4dc7', fachbereich: 'Recht', musterlosung: 'Falsch. Bei Offizialdelikten (z.B. Raub, schwere Körperverletzung) verfolgt die Staatsanwaltschaft die Tat von Amtes wegen, unabhängig vom Willen des Opfers. Nur bei Antragsdelikten (z.B. einfacher Diebstahl unter Angehörigen, Ehrverletzung) kann das Opfer durch Rückzug des Strafantrags das Verfahren beenden. Die blosse Anzeigenzurücknahme genügt bei Offizialdelikten nicht.', teilerklaerungen: [] },
  { id: '3d789caf-482c-4748-9a20-7c4411047ffa', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 71 hat der Schuldner bei einer Gattungsschuld grundsätzlich die Auswahl, welche Sache er aus der geschuldeten Gattung liefert — sofern nichts anderes vereinbart wurde. Er muss jedoch mindestens mittlere Qualität leisten. Wurde die Auswahl vertraglich dem Gläubiger zugewiesen, gilt dessen Wahlrecht.', teilerklaerungen: [] },
  { id: '3dd6c423-a894-4f43-8486-e317ad04a5bb', fachbereich: 'Recht', musterlosung: 'Falsch. Konkurrenzverbote nach Beendigung des Arbeitsverhältnisses unterliegen nach OR 340 ff. strengen Voraussetzungen: Sie müssen zeitlich, örtlich und sachlich angemessen begrenzt sein und dürfen das wirtschaftliche Fortkommen der Arbeitnehmerin nicht unbillig erschweren. Unangemessene Klauseln können vom Richter gekürzt oder für unverbindlich erklärt werden (OR 340a Abs. 2).', teilerklaerungen: [] },
  { id: '3f491b5c-2c4c-4de3-a60f-cd0d11581159', fachbereich: 'Recht', musterlosung: 'Falsch. Der Mietvertrag ist grundsätzlich formfrei. Er kann mündlich, schriftlich oder sogar stillschweigend (konkludent) abgeschlossen werden — das Gesetz schreibt keine besondere Form vor. Schriftlichkeit ist zwar aus Beweisgründen empfohlen und in der Praxis üblich, aber keine Gültigkeitsvoraussetzung.', teilerklaerungen: [] },
  { id: '40974c2d-eb4f-4f94-9068-f87ddc764531', fachbereich: 'Recht', musterlosung: 'Falsch. Das Rechtsmissbrauchsverbot nach Art. 2 Abs. 2 ZGB schützt gerade nicht denjenigen, der ein Recht zweckwidrig ausübt. Vielmehr weist die Norm den Richter an, den offenbaren Missbrauch eines Rechts nicht zu schützen. Wer ein Recht missbräuchlich geltend macht, verliert insoweit den Rechtsschutz.', teilerklaerungen: [] },
  { id: '4136a8ea-0335-466c-bc6c-38ca28a24c49', fachbereich: 'Recht', musterlosung: 'Richtig. Der Grundsatz von Treu und Glauben nach Art. 2 Abs. 1 ZGB schützt das berechtigte Vertrauen in die Anständigkeit anderer — meistens des Vertragspartners. Wer gestützt auf ein solches Vertrauen gehandelt hat, soll nicht nachträglich im Stich gelassen werden. Der Grundsatz ist einer der zentralen Generalklauseln des schweizerischen Privatrechts.', teilerklaerungen: [] },
  { id: '420d56b1-8a45-4327-ba48-1b018216e2ec', fachbereich: 'Recht', musterlosung: 'Falsch. Der Grundsatz gilt nicht ausnahmslos. Nach Art. 21 StGB bleibt der Täter straffrei, wenn er bei der Tat aus zureichenden Gründen annehmen konnte, er handle rechtmässig (unvermeidbarer Rechtsirrtum). Bei vermeidbarem Irrtum kann die Strafe gemildert werden. Die volle Bestrafung ist also nicht in jedem Fall zwingend.', teilerklaerungen: [] },
  { id: '44a2320c-1269-4986-856b-912cb802ede9', fachbereich: 'Recht', musterlosung: 'Richtig. Die Rechtsfähigkeit der natürlichen Person endet mit dem Tod — ab diesem Zeitpunkt kann die verstorbene Person keine Rechte und Pflichten mehr tragen. Bestehende Rechtsverhältnisse gehen grundsätzlich im Wege der Universalsukzession auf die Erben über (Art. 560 ZGB). Höchstpersönliche Rechte erlöschen hingegen mit dem Tod.', teilerklaerungen: [] },
  { id: '47b535e0-69fd-4bfc-adc3-b37b661010b1', fachbereich: 'Recht', musterlosung: 'Falsch. Die Allgemeine Erklärung der Menschenrechte (AEMR) von 1948 ist eine Deklaration der UNO-Generalversammlung — kein völkerrechtlicher Vertrag. Sie entfaltet keine direkte rechtliche Bindungswirkung, hat aber grosse moralische und politische Autorität. Rechtlich verbindlich sind erst die darauf aufbauenden Menschenrechtspakte (UNO-Pakt I und II).', teilerklaerungen: [] },
  { id: '492bfb13-cb2c-435b-a2c9-72894d4139ec', fachbereich: 'Recht', musterlosung: 'Richtig. Art. 930 ZGB enthält die Vermutung, dass der Besitzer einer beweglichen Sache auch deren Eigentümer ist. Die Norm schützt das Vertrauen in den Rechtsschein und erleichtert den Geschäftsverkehr. Die Vermutung ist widerlegbar — wer bessere Rechte geltend macht, muss diese beweisen.', teilerklaerungen: [] },
  { id: '4a070db3-b1f7-4445-a7f5-54c36d45af57', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 31 Abs. 1 ZGB beginnt die Rechtsfähigkeit (Rechtspersönlichkeit) mit der vollendeten Geburt. Vor der Geburt ist das Kind unter der Bedingung der Lebendgeburt bereits rechtsfähig — man spricht von der bedingten Rechtsfähigkeit des Nasciturus. Damit können z.B. Erbansprüche des ungeborenen Kindes geschützt werden.', teilerklaerungen: [] },
  { id: '4af32b58-dc82-4f20-be1d-29918aced93a', fachbereich: 'Recht', musterlosung: 'Falsch. Ein Hund ist kein Rechtssubjekt, sondern Rechtsobjekt. Rechtssubjekte sind ausschliesslich natürliche Personen (Menschen) und juristische Personen (AG, GmbH, Verein etc.). Tiere werden rechtlich wie Sachen behandelt, auch wenn Art. 641a ZGB ausdrücklich festhält, dass sie keine Sachen im herkömmlichen Sinn sind.', teilerklaerungen: [] },
  { id: '4c356d00-795a-4c67-9425-7a8012d1f302', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 24 StGB wird der Anstifter nach derselben Strafandrohung bestraft wie der Haupttäter. Das heisst: Der Strafrahmen ist identisch. Die konkrete Strafzumessung erfolgt jedoch individuell (Art. 47 StGB), weshalb Anstifter und Täter im Einzelfall unterschiedliche Strafen erhalten können — etwa wegen unterschiedlichen Tatbeiträgen oder persönlichen Verhältnissen.', teilerklaerungen: [] },
  { id: '4dc8da88-113e-4790-9e2f-0dc88ad6b4bc', fachbereich: 'Recht', musterlosung: 'Richtig. Die Veröffentlichung des Namens eines verurteilten Straftäters kann durch ein überwiegendes öffentliches Interesse gerechtfertigt sein — ein anerkannter Rechtfertigungsgrund nach Art. 28 Abs. 2 ZGB. Voraussetzung ist eine sorgfältige Interessenabwägung: Bei leichteren Delikten, Jugendlichen oder schon länger zurückliegenden Taten kann das Persönlichkeitsrecht überwiegen.', teilerklaerungen: [] },
  { id: '4e95f6c0-6bb1-4a35-a47e-f8faa6666b13', fachbereich: 'Recht', musterlosung: 'Richtig. In der Frühzeit waren Recht, Sitte und Religion eng miteinander verknüpft — rechtliche Gebote galten als heilig, von Gott oder Göttern gewollt. Die Zehn Gebote sind ein klassisches Beispiel solchen göttlichen Rechts. Erst mit fortschreitender Zivilisation wurden die drei Sphären voneinander getrennt und das Recht als weltliche Ordnung verstanden.', teilerklaerungen: [] },
  { id: '4eef9ea3-40b6-49e3-8fe7-b1a64ccfce4f', fachbereich: 'Recht', musterlosung: 'Richtig. Ein Koppelungsgeschäft nach Art. 254 OR ist nichtig. Der Tatbestand ist erfüllt, wenn der Vermieter den Abschluss oder die Fortsetzung eines Mietvertrags davon abhängig macht, dass der Mieter einen weiteren Vertrag ohne sachlichen Zusammenhang zur Miete abschliesst. Der ungewollte Parkplatz ist ein klassisches Lehrbuchbeispiel für diese Nichtigkeitsfolge.', teilerklaerungen: [] },
  { id: '4fbb518d-f0bd-4132-91aa-7839a83f9192', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 92 kann der Schuldner beim Gläubigerverzug die Sachleistung auf Gefahr und Kosten des Gläubigers hinterlegen und sich damit von seiner Schuld befreien. Voraussetzung ist, dass der Gläubiger die ordnungsgemäss angebotene Leistung zu Unrecht verweigert hat. Die Hinterlegung ist ein Schutzinstrument für den leistungsbereiten Schuldner.', teilerklaerungen: [] },
  { id: '50c857ce-234b-4ccd-8bd1-9f3f7310c313', fachbereich: 'Recht', musterlosung: 'Falsch. Der Eigentumsvorbehalt nach Art. 715 f. ZGB wirkt gegenüber gutgläubigen Dritten nur, wenn er im Eigentumsvorbehaltsregister am Wohnort des Erwerbers eingetragen ist. Ohne Eintrag besteht der Vorbehalt nur zwischen den Parteien (inter partes). Gutgläubige Dritte erwerben ohne Eintrag nach Art. 933 ZGB originäres Eigentum.', teilerklaerungen: [] },
  { id: '5108a3d7-4c43-4acb-b040-1cde2c140c0d', fachbereich: 'Recht', musterlosung: 'Richtig. Die Grundrechte sind in den Art. 7–36 BV verankert. Dazu gehören etwa Menschenwürde, Rechtsgleichheit, Willkürverbot, persönliche Freiheit, Meinungsfreiheit, Versammlungsfreiheit und die Eigentumsgarantie. Sie begrenzen die Macht des Staates und schützen die individuelle Freiheit gegenüber staatlichem Handeln.', teilerklaerungen: [] },
  { id: '5123de10-a86d-48e6-be46-37444cefaaef', fachbereich: 'Recht', musterlosung: 'Falsch. Im Gegensatz zu Freiheitsstrafen orientiert sich die Dauer von Massnahmen nicht am Verschulden, sondern am Gesundheitszustand des Täters und am Sicherheitsbedürfnis der Allgemeinheit (Art. 59 Abs. 4 / Art. 60 Abs. 4 StGB). Eine Massnahme kann daher länger dauern als die vergleichbare Freiheitsstrafe — sie endet, wenn der Zweck erreicht ist.', teilerklaerungen: [] },
  { id: '53ac7531-c24c-4a6c-9ae9-025de7ccc616', fachbereich: 'Recht', musterlosung: 'Falsch. Besitz und Eigentum fallen nicht zwingend zusammen. Ein Besitzer kann ein blosses Benützungsrecht haben (Mieter, Leasingnehmer, Entlehner) oder die Sache zur Aufbewahrung übernommen haben (Hinterlegung). Beispiel: Der Mieter einer Wohnung ist deren Besitzer, aber nicht Eigentümer. Die Vermutung von Art. 930 ZGB ist widerlegbar.', teilerklaerungen: [] },
  { id: '5647ebbb-8bb4-48ad-aab5-ede11c77f235', fachbereich: 'Recht', musterlosung: 'Richtig. Rechtsfähigkeit und Handlungsfähigkeit sind strikt zu unterscheiden. Nach Art. 11 ZGB ist jeder Mensch rechtsfähig — unabhängig von Alter, Gesundheitszustand oder Urteilsfähigkeit. Wer unter umfassender Beistandschaft steht, verliert zwar die Handlungsfähigkeit (er kann nicht selbst Rechte begründen), bleibt aber Trägerin von Rechten und Pflichten. Er kann z.B. Eigentümer oder Erbe sein.', teilerklaerungen: [] },
  { id: '56dda355-55e2-40e1-b79a-b71a5e4a949a', fachbereich: 'Recht', musterlosung: 'Falsch. Gehilfen nach Art. 25 StGB werden milder bestraft als der Haupttäter — die Strafe wird obligatorisch gemildert. Das Gesetz berücksichtigt, dass Gehilfen lediglich fördernde Beiträge leisten, die Tat aber nicht selbst ausführen. Die individuelle Strafzumessung berücksichtigt zusätzlich Tatbeitrag und persönliche Verhältnisse.', teilerklaerungen: [] },
  { id: '59c70c65-14d6-4524-9b9f-5735b2e9471a', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 19 Abs. 3 ZGB werden urteilsfähige Unmündige durch unerlaubte Handlungen (Delikte) schadenersatzpflichtig — dies bezeichnet man als Deliktsfähigkeit. Ein 16-Jähriger kann also nicht alle Verträge allein schliessen, haftet aber persönlich, wenn er jemandem durch unerlaubte Handlung Schaden zufügt. Voraussetzung ist die Urteilsfähigkeit im Moment der Handlung.', teilerklaerungen: [] },
  { id: '5be78eed-495e-4fec-8302-77b525d06537', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 197 ZPO muss in der Schweiz vor Einreichung einer Zivilklage grundsätzlich ein Schlichtungsverfahren durchgeführt werden. Die Schlichtungsbehörde versucht, eine gütliche Einigung herbeizuführen. Scheitert dies, wird die Klagebewilligung ausgestellt. Ausnahmen bestehen für dringliche Massnahmen und bestimmte Streitigkeiten (Art. 198 ZPO).', teilerklaerungen: [] },
  { id: '5cc105aa-9cca-42ec-805c-334110e6a51f', fachbereich: 'Recht', musterlosung: 'Falsch. Das vereinfachte Verfahren gilt nach Art. 243 ZPO nur bei einem Streitwert bis CHF 30\'000. Bei CHF 50\'000 kommt das ordentliche Verfahren zur Anwendung — es ist formeller, sieht Schriftenwechsel vor und wird je nach Kanton vom Kollegialgericht beurteilt. Der Streitwert ist die zentrale Weichenstellung für die Verfahrensart.', teilerklaerungen: [] },
  { id: '5e1b85f6-5f92-441e-8231-3d88f71b0702', fachbereich: 'Recht', musterlosung: 'Falsch. Das Arbeitsgesetz ist relativ zwingendes Recht — zulasten der Arbeitnehmenden sind Abweichungen ungültig, zugunsten der Arbeitnehmenden sind bessere Regelungen jedoch erlaubt. Ein GAV darf also höhere Zuschläge, längere Ferien oder kürzere Arbeitszeiten vorsehen. Nur für Arbeitnehmende nachteilige Klauseln sind unwirksam.', teilerklaerungen: [] },
  { id: '5fab4350-dc2f-4fb8-8442-745f6a7e7f9a', fachbereich: 'Recht', musterlosung: 'Falsch. Im Zivilprozess stehen sich zwei private Parteien gegenüber: der Kläger, der seine Rechte geltend macht, und der Beklagte, gegen den die Klage gerichtet ist. Der Staat greift nicht als Partei ein. Erst im Strafprozess tritt der Staat — vertreten durch die Staatsanwaltschaft — gegen eine beschuldigte Person an.', teilerklaerungen: [] },
  { id: '6041e340-165f-4287-9cdc-acf9d30b62f7', fachbereich: 'Recht', musterlosung: 'Falsch. Nach Art. 366 StGB werden grundsätzlich alle Verurteilungen wegen Verbrechen und Vergehen ins Strafregister eingetragen — nicht aber alle Übertretungen. Nur durch Verordnung des Bundesrates bezeichnete Übertretungen erscheinen im Register. Ordnungsbussen und viele leichte Übertretungen werden daher nicht erfasst.', teilerklaerungen: [] },
  { id: '60559138-9df6-454e-9df0-26b0e98ee269', fachbereich: 'Recht', musterlosung: 'Falsch. Nach OR 336a besteht zwar kein Anspruch auf Wiedereinstellung nach missbräuchlicher Kündigung — der Arbeitgeber kann die Kündigung durchsetzen. Der Arbeitnehmer erhält aber eine Entschädigung von bis zu sechs Monatslöhnen. Eine unabdingbare Pflicht zur Entschädigung besteht; die Wahl zwischen Weiterarbeit und Entschädigung steht hingegen nicht grundsätzlich offen.', teilerklaerungen: [] },
  { id: '61c429ad-28bd-4f41-9e99-ae3220c9a2bf', fachbereich: 'Recht', musterlosung: 'Falsch. Nach OR 337b und 337c hat der Arbeitnehmer bei unrechtmässiger fristloser Kündigung Anspruch auf Ersatz dessen, was er bei Einhaltung der Kündigungsfrist verdient hätte — inklusive Lohn. Darüber hinaus kann eine zusätzliche Entschädigung bis zu sechs Monatslöhnen zugesprochen werden. Lohnfortzahlung und Schadenersatz sind also nicht einander ausschliessend.', teilerklaerungen: [] },
  { id: '61cbd486-a2a8-4922-8362-92f7f0801db9', fachbereich: 'Recht', musterlosung: 'Richtig. Eine Mietkautionsversicherung übernimmt das Mietzinsdepot gegen eine jährliche Prämie und ist eine legale Alternative für Mieter ohne ausreichende Liquidität. Zu beachten: Die Versicherung wirkt nicht wie eine Haftpflichtversicherung — übernommene Ausstände werden inklusive Gebühren und Verzugszinsen vom Mieter zurückgefordert. Sie verschiebt also die Zahlungspflicht, ohne sie aufzulösen.', teilerklaerungen: [] },
  { id: '651b67b9-cf6f-42db-9bb7-d7f33acfba87', fachbereich: 'Recht', musterlosung: 'Falsch. Grundrechte gehören zum öffentlichen Recht und sind zwingender Natur. Auf sie kann nicht durch Privatvereinbarung oder individuelle Erklärung verzichtet werden. Sie gelten für alle Personen im Geltungsbereich der BV unabhängig davon, ob sie dies wünschen. Einzelne Grundrechtsausübungen sind hingegen dispositiv (z.B. Verzicht auf Wahlbeteiligung).', teilerklaerungen: [] },
  { id: '65d6b1f8-8dd8-47a8-bcb0-a01a6dc127de', fachbereich: 'Recht', musterlosung: 'Falsch. Nach OR 160 Abs. 1 kann der Gläubiger bei der Konventionalstrafe entweder die Erfüllung der Obligation oder die Konventionalstrafe verlangen — nicht beides gleichzeitig. Er muss sich entscheiden. Eine Ausnahme gilt, wenn die Konventionalstrafe als blosse Reugeld-Ersatzleistung konzipiert ist oder der Vertrag eine kumulative Geltendmachung ausdrücklich vorsieht.', teilerklaerungen: [] },
  { id: '65eb12d7-b9ef-42b2-a5c4-80fef7539797', fachbereich: 'Recht', musterlosung: 'Falsch. Menschenrechte stehen jedem Menschen zu — unabhängig von Staatsangehörigkeit, Herkunft, Geschlecht oder Religion. Dies ergibt sich bereits aus Art. 2 AEMR sowie aus dem Universalitätsgrundsatz der Menschenrechte. Sie sind angeboren und unveräusserlich. Vom Bürgerstatus abhängig sind nur die politischen Rechte (z.B. Stimmrecht).', teilerklaerungen: [] },
  { id: '6e31f20f-12bc-4688-b513-6c6010411c81', fachbereich: 'Recht', musterlosung: 'Richtig. Verordnungen werden in der Regel von der Regierung (Exekutive) erlassen — auf Bundesebene vom Bundesrat, auf Kantonsebene vom Regierungsrat. Sie konkretisieren Gesetze und können jederzeit ohne Mitwirkung des Parlaments oder des Volkes erlassen, geändert oder aufgehoben werden. Die Verordnungsebene schafft Flexibilität unterhalb des Gesetzes.', teilerklaerungen: [] },
  { id: '6e7766b5-2e56-47b6-b9cc-e539f58bf351', fachbereich: 'Recht', musterlosung: 'Richtig. Da die Dauer einer Massnahme nicht am Verschulden, sondern am Gesundheitszustand des Täters und am Sicherheitsbedürfnis der Allgemeinheit orientiert ist (Art. 59 Abs. 4 / Art. 60 Abs. 4 StGB), kann sie länger dauern als die vergleichbare Freiheitsstrafe. Die Massnahme dauert in der Regel bis zu fünf Jahre, kann aber verlängert werden, solange die Voraussetzungen bestehen.', teilerklaerungen: [] },
  { id: '6e9732d8-a895-4a4f-a99b-d402ea0ba897', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Abschluss der Untersuchung entscheidet die Staatsanwaltschaft, ob sie Anklage erhebt oder das Verfahren einstellt. Bei Anklageerhebung übergibt sie den Fall dem Gericht zur Hauptverhandlung. Die Staatsanwaltschaft vertritt die Anklage und tritt vor Gericht als Gegenseite der beschuldigten Person auf — vergleichbar einer «Klägerin» des Staates.', teilerklaerungen: [] },
  { id: '70e6b237-db19-4f0f-a717-f83a6fc972e6', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 89 Abs. 1 StGB wird die bedingt entlassene Person, die während der Probezeit ein Verbrechen oder Vergehen begeht, in den Strafvollzug zurückgebracht und muss die restliche Strafe verbüssen. Die bedingte Entlassung steht also unter der Bedingung der Bewährung. Bewährt sich die Person, gilt sie endgültig entlassen (Art. 88 StGB).', teilerklaerungen: [] },
  { id: '71aca87e-4bc3-497b-a33c-a5695a056854', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 3 Abs. 1 ZGB wird der gute Glaube vermutet, wo das Gesetz eine Rechtswirkung an ihn knüpft. Jede Person gilt also kraft Gesetzes als gutgläubig, bis das Gegenteil bewiesen ist. Die Beweislast liegt bei demjenigen, der Bösgläubigkeit behauptet. Die Vermutung erleichtert den Rechtsverkehr erheblich.', teilerklaerungen: [] },
  { id: '71c671fc-7990-4ef0-ab85-742dfde1c149', fachbereich: 'Recht', musterlosung: 'Falsch. Das Arbeitsgesetz (ArG) kennt wichtige Ausnahmen: Es gilt etwa nicht für leitende Angestellte, für öffentliche Verwaltungen, landwirtschaftliche Betriebe oder wissenschaftlich-künstlerische Tätigkeiten. Kleinbetriebe haben teilweise erleichterte Anforderungen. Leitende Angestellte und Kleinstbetriebe werden also gerade nicht wie Normalbetriebe behandelt.', teilerklaerungen: [] },
  { id: '723ef4a7-4e72-4a81-959a-eb08863c5efd', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 257a OR sind Nebenkosten nur dann separat geschuldet, wenn sie im Mietvertrag ausdrücklich und einzeln aufgeführt sind. Fehlt eine solche Vereinbarung, gelten alle Nebenkosten als im Mietzins inbegriffen. Dies dient dem Transparenzgebot und schützt Mieter vor unerwarteten Zusatzkosten.', teilerklaerungen: [] },
  { id: '72b4f896-1c0b-490f-899e-eb31f6859880', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 936 ZGB kann der Eigentümer vom bösgläubigen Besitzer die Sache jederzeit — auch nach mehr als fünf Jahren — herausverlangen. Der bösgläubige Erwerber geniesst keinen Eigentumsschutz. Bösgläubig ist, wer beim Erwerb wusste oder nach den Umständen hätte wissen müssen, dass es sich um gestohlene oder verlorene Sachen handelt.', teilerklaerungen: [] },
  { id: '74662535-7a07-4de1-91fa-4eef25f8a1e3', fachbereich: 'Recht', musterlosung: 'Richtig. Das Folterverbot nach Art. 5 AEMR (bzw. Art. 3 EMRK) gehört zu den notstandsfesten Menschenrechten und gilt absolut. Es darf auch in Krisen, bei Terrorismusbekämpfung oder zur Abwehr einer nationalen Bedrohung nicht eingeschränkt werden. In der BV entspricht dies dem Kerngehalt der persönlichen Freiheit (Art. 10 Abs. 3 BV), der nach Art. 36 Abs. 4 BV unantastbar bleibt.', teilerklaerungen: [] },
  { id: '74d0b4d6-0c7f-4560-9aa0-cf1acc3243c6', fachbereich: 'Recht', musterlosung: 'Falsch. Vertragliche Schäden werden nach OR 97 abgegolten (vertragliche Haftung). OR 41 ff. regeln hingegen die ausservertragliche Haftung aus unerlaubter Handlung. Die Unterscheidung ist fundamental: Bei vertraglicher Haftung wird Verschulden vermutet, bei OR 41 muss es vom Geschädigten bewiesen werden.', teilerklaerungen: [] },
  { id: '7630189a-30ab-4b6b-9774-319b14f7d2be', fachbereich: 'Recht', musterlosung: 'Richtig. Art. 2 Abs. 1 ZGB verlangt, dass sich die Rechtssubjekte nach Treu und Glauben verhalten — also anständig und korrekt. Auf diesem Weg finden allgemeine Werte der Sittlichkeit und Moral über die Generalklausel Eingang ins Recht. Die Bestimmung ist eine der zentralen Auslegungsmaximen des schweizerischen Privatrechts.', teilerklaerungen: [] },
  { id: '7632e046-16bb-42d8-bc8e-f406f278b7a0', fachbereich: 'Recht', musterlosung: 'Falsch. Bei der Kausalhaftung entfällt gerade das Verschulden als Haftungsvoraussetzung. Die Haftung knüpft stattdessen an die Verantwortlichkeit für eine bestimmte Gefahr, Person oder Sache an — etwa Werkeigentümerhaftung (OR 58) oder Halterhaftung. Der Geschädigte muss nur Schaden, Kausalzusammenhang und Widerrechtlichkeit beweisen, kein Verschulden.', teilerklaerungen: [] },
  { id: '76c4a315-b69a-46f0-b9ff-06b05f8a00ed', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 255 OR kann die Miete auf bestimmte oder unbestimmte Zeit eingegangen werden. Befristete Mietverträge enden automatisch mit Ablauf der vereinbarten Dauer (Art. 266 OR) — ohne Kündigung. Unbefristete Mietverträge enden durch ordentliche Kündigung unter Einhaltung von Frist und Termin.', teilerklaerungen: [] },
  { id: '77fae288-f22c-42ac-a917-e6d1bab611b6', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 19 Abs. 1 ZGB bedürfen urteilsfähige Unmündige der Zustimmung ihres gesetzlichen Vertreters (z.B. der Eltern), um Rechte und Pflichten zu begründen. Es gibt Ausnahmen: geringfügige Angelegenheiten des täglichen Lebens (Art. 19 Abs. 2 ZGB), höchstpersönliche Rechte (Art. 19c ZGB) und Verfügung über selbst erworbenen Lohn (Art. 323 ZGB).', teilerklaerungen: [] },
  { id: '7954d841-6c05-4032-bdff-55a1cf2f2780', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 320 Abs. 2 kann ein Arbeitsvertrag auch konkludent entstehen. Wenn ein Arbeitnehmer mit Zustimmung des Arbeitgebers die Arbeit aufnimmt, ohne dass eine ausdrückliche Einigung getroffen wurde, liegt darin ein stillschweigend geschlossener Arbeitsvertrag. Die Konkludenz-Regel schützt Arbeitnehmer vor schwach dokumentierten Arbeitsverhältnissen.', teilerklaerungen: [] },
  { id: '7a2c086e-4825-45bc-9284-38c0c406984b', fachbereich: 'Recht', musterlosung: 'Falsch. Der Führerausweisentzug ist eine verwaltungsrechtliche Administrativmassnahme, nicht eine Strafe im strafrechtlichen Sinne. Angeordnet wird er vom Strassenverkehrsamt, nicht vom Strafgericht. Für Betroffene fühlt er sich zwar oft wie eine Strafe an; rechtlich und verfahrensmässig unterscheidet er sich jedoch klar vom Strafrecht.', teilerklaerungen: [] },
  { id: '7e50bf42-a485-4f67-afa8-e2c70289d797', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 102 Abs. 1 muss der Gläubiger den Schuldner grundsätzlich durch Mahnung in Verzug setzen. Ausnahmen: Verfalltagsgeschäft (OR 102 Abs. 2) und Fixgeschäft (OR 108) — in beiden Fällen tritt der Verzug ohne Mahnung ein. Auch bei ausdrücklichem vertraglichem Ausschluss kann auf die Mahnung verzichtet werden.', teilerklaerungen: [] },
  { id: '7f06c26f-c6b2-41b9-b50a-f85a685cb382', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 259b lit. b OR kann der Mieter bei einem vom Vermieter trotz Fristsetzung nicht behobenen Mangel die Beseitigung selbst vornehmen lassen und die Kosten dem Vermieter in Rechnung stellen (Ersatzvornahme). Voraussetzung ist die vorherige Anzeige und Fristsetzung. Die Kosten müssen angemessen und erforderlich sein.', teilerklaerungen: [] },
  { id: '834bdb2d-d648-42e1-9904-1ce4c39c12d2', fachbereich: 'Recht', musterlosung: 'Richtig. Nach Art. 10 Abs. 3 StGB sind Vergehen Taten, die mit Freiheitsstrafe bis zu drei Jahren oder mit Geldstrafe bedroht sind. Die Sachbeschädigung (Art. 144 StGB) sieht eine Freiheitsstrafe bis zu drei Jahren vor und fällt damit in die Kategorie der Vergehen. Verbrechen wären Taten mit mehr als drei Jahren Freiheitsstrafe.', teilerklaerungen: [] },
  { id: '866ae0a2-c44d-45b1-b4eb-c7d19ad12371', fachbereich: 'Recht', musterlosung: 'Richtig. Bei Offizialdelikten leitet die Strafverfolgungsbehörde das Verfahren von Amtes wegen ein, auch ohne Strafanzeige — der Grundsatz «Wo kein Kläger, da kein Richter» gilt hier nicht. Bei Antragsdelikten hingegen dürfen die Behörden erst einschreiten, wenn ein gültiger Strafantrag des Opfers vorliegt. Die Einteilung bestimmt Art. 30 StGB.', teilerklaerungen: [] },
  { id: '87564994-2ade-4924-8a8c-8cb8a997ef30', fachbereich: 'Recht', musterlosung: 'Falsch. Zwischen Vermieter und Untermieter besteht keine direkte Rechtsbeziehung. Der Hauptmieter bleibt alleiniger Vertragspartner des Vermieters und haftet ihm für Mietzins und Sorgfalt. Der Untermieter ist nur mit dem Hauptmieter vertraglich verbunden. Der Vermieter kann vom Untermieter daher nicht direkt Miete verlangen.', teilerklaerungen: [] },
  { id: '87b1602a-d845-4085-ba07-793b85074ba9', fachbereich: 'Recht', musterlosung: 'Richtig. Der Referenzzinssatz basiert auf dem volumengewichteten Durchschnitt der inländischen Hypothekarforderungen und wird vierteljährlich vom Bundesamt für Wohnungswesen publiziert. Er dient als Grundlage für Mietzinsanpassungen: Sinkt er, können Mieter eine Reduktion verlangen; steigt er, kann der Vermieter eine Erhöhung durchsetzen.', teilerklaerungen: [] },
  { id: '8b99f861-6266-4690-90fe-de713b2b2d32', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 74 Abs. 2 Ziff. 1 sind Geldschulden Bringschulden — der Schuldner muss die Zahlung am Wohnsitz des Gläubigers leisten. Er trägt daher auch das Transportrisiko und die Übermittlungskosten. Banküberweisungen sind dem Gläubiger gutzuschreiben, damit die Leistung als erbracht gilt.', teilerklaerungen: [] },
  { id: '8cef589b-f4c7-4997-a332-81e14cf84983', fachbereich: 'Recht', musterlosung: 'Richtig. Die BV unterscheidet zwischen Menschenrechten, die allen Menschen zustehen (z.B. Menschenwürde, Meinungsfreiheit, Glaubensfreiheit), und Bürgerrechten, die nur Schweizer Staatsangehörigen zukommen (z.B. Niederlassungsfreiheit Art. 24 BV, politische Rechte Art. 34 BV). Der 2. Titel der BV heisst daher «Grundrechte, Bürgerrechte und Sozialziele».', teilerklaerungen: [] },
  { id: '8f08fef1-1cf3-4a02-a8f0-ff0261f1da62', fachbereich: 'Recht', musterlosung: 'Falsch. Der Instanzenzug muss grundsätzlich eingehalten werden: Zuerst ist das Urteil bei der zweiten kantonalen Instanz (Obergericht) anzufechten. Erst gegen dessen Urteil kann Beschwerde ans Bundesgericht erhoben werden. Eine Sprungbeschwerde direkt ans Bundesgericht ist nur ausnahmsweise und bei Zustimmung der Gegenpartei zulässig (Art. 75 Abs. 2 BGG).', teilerklaerungen: [] },
  { id: '96869b38-0c05-49d4-aa34-a65cf4fceb53', fachbereich: 'Recht', musterlosung: 'Falsch. Grundrechte können unter den Voraussetzungen von Art. 36 BV eingeschränkt werden. Erforderlich sind eine gesetzliche Grundlage, ein öffentliches Interesse oder der Schutz von Grundrechten Dritter, die Verhältnismässigkeit der Massnahme und die Wahrung des unantastbaren Kerngehalts. Absolut unantastbar ist nur der Kerngehalt, nicht das gesamte Grundrecht.', teilerklaerungen: [] },
  { id: '9690a73f-8a52-4ced-a3e3-1b4b3cc0c25c', fachbereich: 'Recht', musterlosung: 'Falsch. Wer in berechtigter Notwehr handelt, muss dem Angreifer den dabei zugefügten Schaden nicht ersetzen. Notwehr ist ein Rechtfertigungsgrund, der die Widerrechtlichkeit ausschliesst — eine Haftungsvoraussetzung nach OR 41 fehlt somit. Voraussetzung ist, dass die Abwehr angemessen und erforderlich war (Art. 15 StGB, sinngemäss OR).', teilerklaerungen: [] },
  { id: '970cf9cf-9b92-4adb-8978-28f4bcbe5e07', fachbereich: 'Recht', musterlosung: 'Richtig. Die Staatsanwaltschaft ist zur Objektivität verpflichtet: Sie muss belastende und entlastende Umstände gleichermassen ermitteln und bei der Anklageerhebung berücksichtigen. Sie ist nicht einseitige Parteivertreterin, sondern sucht den wahren Sachverhalt. Diese Objektivitätspflicht ist ein Grundpfeiler des rechtsstaatlichen Strafverfahrens.', teilerklaerungen: [] },
  { id: '983c6dbc-6068-4446-89fd-96652f3437ef', fachbereich: 'Recht', musterlosung: 'Falsch. Beim Stockwerkeigentum werden Mehrheiten grundsätzlich aufgrund aller stimmberechtigten Miteigentümer berechnet — nicht nur der anwesenden. Die Versammlung ist beschlussfähig, wenn mindestens die Hälfte aller Stockwerkeigentümer mit mindestens der Hälfte der Wertquoten anwesend oder vertreten ist (Art. 712p ZGB). Dies schützt abwesende Eigentümer vor Überstimmung.', teilerklaerungen: [] },
  { id: '9a39c4bd-5d14-4aa8-a86a-6ec9e6e299b8', fachbereich: 'Recht', musterlosung: 'Falsch. Nach OR 321e haftet der Arbeitnehmer für Schäden, die er durch unsorgfältige oder untreue Arbeitsausführung verursacht. Die Haftung wird allerdings reduziert oder ausgeschlossen, wenn nur leichte Fahrlässigkeit vorliegt — das Betriebsrisiko trägt insoweit der Arbeitgeber. Bei mittlerer oder grober Fahrlässigkeit kann die volle Haftung greifen.', teilerklaerungen: [] },
  { id: '9e96555c-39c5-4985-b9c5-11e6e65c7d84', fachbereich: 'Recht', musterlosung: 'Richtig. Das Bundesgericht beurteilte den Berner Wegweisungsartikel grundsätzlich als verfassungskonform. Alle fünf Richter hielten die Norm für zulässig; der dissentierende Richter Fonjallaz sah lediglich in der konkreten Anwendung auf die 13 Beschwerdeführer Probleme, nicht in der Norm als solcher. Der Entscheid ist ein Leiturteil zur polizeilichen Wegweisung.', teilerklaerungen: [] },
  { id: 'a26b404e-4668-4fa4-99fe-5f83f8c0e7dc', fachbereich: 'Recht', musterlosung: 'Richtig. Nach OR 324a muss der Arbeitgeber bei unverschuldeter Verhinderung des Arbeitnehmers (Krankheit, Unfall, gesetzliche Pflichten) den Lohn für eine begrenzte Zeit weiter zahlen. Die Dauer ist nach Dienstjahren gestaffelt — gemäss Berner Skala 3 Wochen im ersten Dienstjahr bis 26 Wochen ab 20+ Dienstjahren. Kollektivversicherungen können die Pflicht ablösen.', teilerklaerungen: [] },
  { id: 'a3e950bb-a8db-44ca-9933-174260c25eeb', fachbereich: 'Recht', musterlosung: 'Richtig. Art. 47 StGB regelt die allgemeinen Strafzumessungsfaktoren: Verschulden des Täters, Beweggründe, Vorleben, persönliche Verhältnisse und Wirkung der Strafe. Art. 48 StGB führt weitere strafmindernde Gründe auf — etwa schwere Bedrängnis, Gehorsam, heftige Gemütsbewegung oder aufrichtige Reue. Zusammen bilden beide Artikel den Kern der Strafzumessung.', teilerklaerungen: [] },
  { id: 'a49eff76-a50a-47a1-b0ef-7e4be6d98a65', fachbereich: 'Recht', musterlosung: 'Falsch. Nach OR 335 ist eine Kündigung zwar grundsätzlich formfrei gültig; viele GAV und Einzelverträge sehen jedoch Schriftform vor. Dann genügt die Unterzeichnung durch die kündigende Partei — eine Gegenunterschrift ist nicht erforderlich. Entscheidend ist der Zugang beim anderen Vertragspartner, damit die Kündigung wirksam wird.', teilerklaerungen: [] },
]

// Duplikate filtern (defensiv)
const seen = new Set()
const filtered = updates.filter((u) => {
  if (seen.has(u.id)) return false
  seen.add(u.id)
  return true
})

const lines = filtered.map((u) => JSON.stringify(u)).join('\n') + '\n'
await fs.appendFile(OUT, lines)

const state = JSON.parse(await fs.readFile(STATE, 'utf8'))
state.letzteSession = new Date().toISOString()
state.verarbeitet = (state.verarbeitet || 0) + filtered.length
state.fragen = state.fragen || {}
for (const u of filtered) {
  state.fragen[u.id] = { status: 'done', zeitpunkt: state.letzteSession, teile: u.teilerklaerungen.length }
}
await fs.writeFile(STATE, JSON.stringify(state, null, 2))
console.log(`[s8] ${filtered.length} Updates | total ${state.verarbeitet}/${state.totalFragen}`)
