#!/usr/bin/env node
/**
 * Session 11a: 50 VWL-Fragen (erste Hälfte des Session-11-Batches)
 * Verteilung: 33 freitext + 6 hotspot + 11 lueckentext
 *
 * Teilerklärungen für hotspot (bereiche) + lueckentext (luecken).
 * freitext: keine Sub-Struktur → [].
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(__dirname, 'fragen-updates.jsonl')
const STATE = path.join(__dirname, 'state.json')

const updates = [
  // ========== VWL / freitext (33) — keine Sub-Struktur ==========
  { id: 'b0d36023-cb78-4e03-9b34-709e17c35e44', fachbereich: 'VWL', musterlosung: 'Zwischen Wirtschaftswachstum und Umweltqualität besteht traditionell ein Zielkonflikt: Mehr Produktion bedeutet oft mehr Ressourcenverbrauch und Emissionen. Qualitatives Wachstum (Dienstleistungen, Kreislaufwirtschaft, saubere Technologien) entkoppelt Wertschöpfung teilweise vom Umweltverbrauch. Kurzfristig dominiert die Konkurrenz, langfristig ist partielle Harmonie durch Innovation möglich. Eine differenzierte Beurteilung unterscheidet zwischen quantitativem Output und qualitativem Fortschritt.', teilerklaerungen: [] },
  { id: 'bab882e7-963d-44ef-8efa-00572ab277a0', fachbereich: 'VWL', musterlosung: 'Trinkwasser ist ökonomisch knapp — Aufbereitung und Verteilung kosten. Ein Preis verhindert Übernutzung (Tragik der Allmende) und signalisiert Knappheit. Gleichzeitig ist Wasser ein Grundbedürfnis, das niemand entbehren kann. Die Schweizer Lösung kombiniert beides: Moderate Gebühren decken Kosten, Sozialtarife oder Transferleistungen sichern den Grundzugang. Preis ja, aber nicht nach reiner Marktlogik — ein klassischer Mischansatz.', teilerklaerungen: [] },
  { id: 'bb9348be-a349-44b5-97b9-342049d648bd', fachbereich: 'VWL', musterlosung: 'Der Schneeballeffekt beschreibt die Eigendynamik der Staatsverschuldung: Wer mehr Schulden hat, zahlt mehr Zinsen, was das Defizit vergrössert und neue Kredite nötig macht. Investoren verlangen bei steigender Schuldenlast höhere Risikoprämien, was die Zinslast zusätzlich erhöht. Dieser Teufelskreis kann im Staatsbankrott enden, wie Beispiele Griechenlands oder Argentiniens zeigen.', teilerklaerungen: [] },
  { id: 'bc1cc2de-fe7a-4430-b708-82bd0f2cf828', fachbereich: 'VWL', musterlosung: 'Wirtschaftswachstum verlangt meist mehr Energie und Rohstoffe — das erzeugt Emissionen und Naturverbrauch. Decoupling (Entkopplung) meint die Trennung von Wachstum und Ressourcenverbrauch: relativ (Verbrauch wächst langsamer als BIP) oder absolut (Verbrauch sinkt bei steigendem BIP). Nur absolutes Decoupling löst den Zielkonflikt nachhaltig. Empirisch gelingt dies bislang selten — der technische Fortschritt muss massiv beschleunigt werden.', teilerklaerungen: [] },
  { id: 'bd186cc1-dda3-469c-968d-ff9bba0e4071', fachbereich: 'VWL', musterlosung: 'Im klassischen Modell sind Löhne flexibel: Arbeitslosigkeit entsteht nur bei Lohnrigidität (zu hohe Löhne, Mindestlohn). Lösung: Löhne senken. Im keynesianischen Modell ist die gesamtwirtschaftliche Nachfrage entscheidend: Sinken Löhne, sinkt die Konsumnachfrage, die Krise verschärft sich. Lösung: Staat stützt Nachfrage durch Ausgaben. Beide Modelle spiegeln unterschiedliche Diagnosen derselben Symptome — die Antwort bestimmt die wirtschaftspolitische Reaktion.', teilerklaerungen: [] },
  { id: 'bf15e7cd-0bf1-45b4-9c0f-c7230c88abe8', fachbereich: 'VWL', musterlosung: 'Das Notensystem schafft Anreize, bei jeder Prüfung ausreichend zu lernen — 4.0 als Bestehensschwelle. Unerwünschte Nebeneffekte: Teaching to the Test (nur prüfungsrelevanter Stoff), strategisches Risiko (knapp bestehen statt Exzellenz anstreben), Abschreiben, Stress. Der Homo oeconomicus reagiert rational auf die Anreize, nicht auf Bildungsziele. Das illustriert den Kobraeffekt: Anreizsysteme wirken oft anders als beabsichtigt.', teilerklaerungen: [] },
  { id: 'bff3a000-433f-485e-b680-d8deb9418298', fachbereich: 'VWL', musterlosung: 'Die Aussage stimmt unter idealen Bedingungen: vollkommener Wettbewerb, vollständige Information, keine externen Effekte. In der Realität ist keines dieser Idealbedingungen erfüllt — es gibt Marktmacht, Informationsasymmetrien und öffentliche Güter. Deshalb braucht es staatliche Eingriffe bei Marktversagen. Die Pauschalaussage ist irreführend: Märkte sind effizient, aber nicht allmächtig. Der Staat muss als Ergänzung, nicht als Ersatz, wirken.', teilerklaerungen: [] },
  { id: 'c129a186-02d8-4099-80a4-9149a8e875c7', fachbereich: 'VWL', musterlosung: 'Die tiefe Schweizer Primär-Gini (0.38) spricht beide Seiten an. Contra Ausbau: Marktlöhne sind bereits relativ gleichmässig, weitere Umverteilung könnte Leistungsanreize schwächen. Pro Ausbau: Die sekundäre Verteilung (nach Steuern) soll weiter ausgleichen, wenn Chancengleichheit das Ziel ist. Die Entscheidung hängt von der Gerechtigkeitsvorstellung ab — Effizienz-Gerechtigkeits-Trade-off bleibt bestehen.', teilerklaerungen: [] },
  { id: 'c73974b8-a7e5-4595-a4a5-752f36ab3ccd', fachbereich: 'VWL', musterlosung: 'Die Einheitsprämie unabhängig vom Gesundheitszustand führt zu adverser Selektion: Gesunde steigen aus, nur Kranke bleiben, die Prämie steigt, die Spirale dreht sich. Das Obligatorium durchbricht diesen Mechanismus — alle müssen dabei sein. Zusätzlich verwirklicht es das Solidaritätsprinzip: Gesunde subventionieren Kranke. Ohne Obligatorium wäre der Schweizer Grundversicherungsmarkt nicht überlebensfähig.', teilerklaerungen: [] },
  { id: 'c7af049c-d1c6-443f-b46f-37e69cb653b8', fachbereich: 'VWL', musterlosung: 'Vorteile: Disziplinierung des Staates, Effizienzanreize, Wahlfreiheit der Steuerzahlenden, tiefere Gesamtsteuerlast. Nachteile: Race to the Bottom, Ungleichheit zwischen Kantonen, Unterfinanzierung öffentlicher Güter. Der Nationale Finanzausgleich (NFA) gleicht die gröbsten Unterschiede aus, schafft aber eigene Fehlanreize. In der Summe überwiegen die Vorteile, sofern der Ausgleichsmechanismus funktioniert — das ist die Schweizer Position.', teilerklaerungen: [] },
  { id: 'c93740e4-b4b7-4c26-a435-76c3e3154822', fachbereich: 'VWL', musterlosung: 'Beispiel steigende Mieten: (1) Beschreiben — Mietpreisindex misst die Entwicklung. (2) Erklären — Angebot (Bauzahlen) und Nachfrage (Zuwanderung, Einkommen) analysieren. (3) Prognostizieren — bei gleichbleibender Knappheit weiterer Anstieg absehbar. (4) Beeinflussen — Massnahmen wie Verdichtung, Mietpreisbremse oder Wohnbauförderung prüfen. Die vier Schritte ergeben ein systematisches Vorgehen von Beobachtung zur Politik.', teilerklaerungen: [] },
  { id: 'cc41adba-6c02-4543-b757-fc4bec825a55', fachbereich: 'VWL', musterlosung: 'Pro Geldleistungen: Autonomie der Empfänger, individuelle Bedürfnisbefriedigung, weniger Bürokratie. Pro Sachleistungen: Sicherstellung der zweckgerechten Verwendung, paternalistischer Schutz vor Fehlkonsum, politisch besser durchsetzbar. Die Schweiz kombiniert beides: Sozialhilfe und AHV als Geldleistung, Prämienverbilligungen und subventionierte Kitas als zweckgebunden. Der richtige Mix hängt vom Kontext ab — pauschale Regel wäre zu einseitig.', teilerklaerungen: [] },
  { id: 'd3b97f90-4826-422e-a207-045bf2eb359f', fachbereich: 'VWL', musterlosung: 'Beispiele Sachgüter (materiell, lagerfähig, übertragbar): Brot, Kleidungsstück. Beispiele Dienstleistungen (immateriell, nicht lagerfähig): Zugfahrt, Schulunterricht. Zentraler Unterschied: Bei Sachgütern wird Eigentum an einer Ware übertragen, bei Dienstleistungen wird eine Tätigkeit erbracht. Uno-actu-Prinzip: Produktion und Konsum fallen bei Dienstleistungen zeitlich zusammen.', teilerklaerungen: [] },
  { id: 'd4087035-61ae-4225-a469-d84fdad81e38', fachbereich: 'VWL', musterlosung: 'Die Franchise reduziert Moral Hazard, weil Versicherte bei kleinen Rechnungen selbst zahlen — das senkt unnötige Arztbesuche. Negative Effekte: Personen mit chronischen Krankheiten erreichen die Franchise ohnehin, der Lenkungseffekt fehlt. Geringverdienende wählen aus Risikoscheu hohe Franchisen, die bei Krankheit finanziell belasten. Die Bandbreite CHF 300–2\'500 versucht Effizienz und Gerechtigkeit auszubalancieren — perfekt ist der Kompromiss nicht.', teilerklaerungen: [] },
  { id: 'd9fce8d7-ba7a-4df0-8dd0-915962ab90f7', fachbereich: 'VWL', musterlosung: 'Beispiel: Eine Freistunde kann zum Lernen oder zum Austausch mit Freunden genutzt werden. Trade-off: mehr Lernzeit = bessere Noten, weniger Erholung. Opportunitätskosten einer Lernstunde = der Nutzen der entgangenen Alternative (Freunde, Sport, Schlaf). Auch Fach-Entscheidungen (SF vs. Ergänzungsfach) bedeuten Opportunitätskosten. Ökonomisches Denken macht diese unsichtbaren Kosten bewusst.', teilerklaerungen: [] },
  { id: 'dfb8d91d-2337-4c03-99cb-b9d9e87b4d75', fachbereich: 'VWL', musterlosung: 'Der Bundeshaushalt wird als Transferhaushalt bezeichnet, weil rund 45% der Ausgaben als Transfers zu anderen Akteuren (Kantone, Sozialwerke, Haushalte) fliessen. Der Bund produziert wenig selbst, sondern verteilt um. Problematik: Die hohe Fixbindung reduziert den Handlungsspielraum für Zukunftsinvestitionen (Bildung, Forschung, Infrastruktur). Strukturelle Reformen werden politisch schwierig, weil jede Kürzung Betroffene hat.', teilerklaerungen: [] },
  { id: 'e028c4d4-5f57-47fd-bc3a-82479f21c2de', fachbereich: 'VWL', musterlosung: 'Der Homo oeconomicus ist ein Modell, keine Beschreibung realer Menschen. Modelle sind bewusst vereinfachte Arbeitshypothesen — wie eine Karikatur, die wesentliche Züge hervorhebt. Trotz Abweichungen prognostiziert das Modell Durchschnittsverhalten oft erstaunlich gut (Preisreaktionen, Arbeitsangebot). Die Verhaltensökonomie (Kahneman, Thaler) ergänzt das Modell um psychologische Realitäten — sie ersetzt es aber nicht. Unrealistisch, nicht nutzlos.', teilerklaerungen: [] },
  { id: 'e4d0f37d-838d-4dd4-b3fe-9fd17443a135', fachbereich: 'VWL', musterlosung: 'Staatseingriffe in die soziale Wohlfahrt können Fehlanreize schaffen: Arbeitslosenunterstützung verlängert Suchphasen, hoher Kündigungsschutz erschwert Neueinstellungen (Insider-Outsider-Problem), Sozialhilfe reduziert den Anreiz zur Aufnahme schlecht bezahlter Arbeit. Zusätzlich entstehen Stigmatisierung und hohe Bürokratiekosten. Grundsatz: Schutz gegen Fehlanreize abwägen. Gute Sozialpolitik aktiviert, statt nur zu versorgen.', teilerklaerungen: [] },
  { id: 'ee00a438-7a92-40e3-9e40-2492b4290277', fachbereich: 'VWL', musterlosung: 'Die Waschmaschine steigert die Produktivität der Hausarbeit drastisch — eine Stunde Wäsche statt eines halben Tages. Sinkende Opportunitätskosten für Bildung und Erwerbsarbeit ermöglichen Frauen Studium, Beruf und politische Teilhabe. Rosling zeigt: Die Waschmaschine ist ein Symbol für befreite Zeit — technische Innovation wirkt über Produktivitätssteigerung hinaus auf Gesellschaft und Geschlechterverhältnisse.', teilerklaerungen: [] },
  { id: 'ee5e6107-82a6-4033-b469-fa115bae6222', fachbereich: 'VWL', musterlosung: 'Ein höherer Lohn kann die Produktivität erhöhen: Mitarbeitende sind motivierter, bleiben länger (weniger Fluktuationskosten), identifizieren sich mit dem Unternehmen und arbeiten effizienter. Gleichzeitig attrahiert er bessere Bewerbungen. Der Effizienzlohn liegt dort, wo der Produktivitätsgewinn die Mehrkosten gerade übersteigt. Im Modell erklärt das Lohnrigidität nach unten und unfreiwillige Arbeitslosigkeit.', teilerklaerungen: [] },
  { id: 'ef6d4e7b-a78c-4ece-baa0-7519d659c795', fachbereich: 'VWL', musterlosung: 'Der Ressourcenfluch: Rohstoffreichtum führt oft zu wirtschaftlichen Problemen. Ursachen: (1) Dutch Disease (Währungsaufwertung schadet anderen Exportsektoren), (2) schwache Institutionen durch leichtes Einkommen, (3) Korruption und Renten-Suche, (4) fehlende Diversifikation. Gegenbeispiele wie Norwegen (Staatsfonds, transparente Institutionen) zeigen: Entscheidend sind nicht die Ressourcen, sondern die Institutionen, die deren Erträge verwalten.', teilerklaerungen: [] },
  { id: 'ef9135f3-8c36-4930-af65-983e13097ff4', fachbereich: 'VWL', musterlosung: 'Die Aussage ist empirisch falsch. Länder mit moderater Ungleichheit (Skandinavien) wachsen zuverlässig, extreme Ungleichheit (Lateinamerika) dämpft Wachstum durch geringe Bildungsinvestitionen und soziale Instabilität. Milanovic unterscheidet «gute» (leistungsbasierte) und «schlechte» (vererbte) Ungleichheit. Moderate Gleichheit kann Wachstum sogar fördern — der Zusammenhang ist nicht linear, sondern U-förmig.', teilerklaerungen: [] },
  { id: 'einr-ft-formatierung', fachbereich: 'VWL', musterlosung: 'Ein beispielhaft korrekter Satz wäre: «Ich teste gerade die **Prüfungsplattform** und finde sie *spannend*.» Dabei ist «Prüfungsplattform» fett und «spannend» kursiv formatiert. Die Aufgabe prüft die Anwendung der Formatierungsleiste oder der Tastenkürzel Ctrl+B und Ctrl+I. Ein Wort fett, ein Wort kursiv genügen — der Inhalt ist frei wählbar.', teilerklaerungen: [] },
  { id: 'f604a105-1607-4991-8dcf-28e045df0e56', fachbereich: 'VWL', musterlosung: 'Die Laffer-Kurve illustriert anschaulich: Bei 0% und 100% Steuersatz erzielt der Staat keine Einnahmen, dazwischen existiert ein Maximum. Grenzen: Der optimale Satz ist empirisch kaum bestimmbar und variiert je nach Steuerart. Das Modell blendet Wohlfahrtsaspekte (Verteilung, öffentliche Güter) aus. Politisch wird die Kurve oft missbraucht, um Steuersenkungen zu rechtfertigen. Nützlich als Denkhilfe, untauglich als präzises Politikinstrument.', teilerklaerungen: [] },
  { id: 'f7915117-1c25-46bb-b288-dbf6f26fc4ea', fachbereich: 'VWL', musterlosung: 'Der Zoll verschiebt die Angebotskurve für importierte Elektronik nach oben (um 10%). Gleichgewichtspreis steigt, Gleichgewichtsmenge sinkt. Konsumenten zahlen mehr und konsumieren weniger — Konsumentenrente sinkt. US-Hersteller profitieren teilweise (Substitution), der Staat erzielt Zolleinnahmen. Netto entsteht ein Wohlfahrtsverlust durch die geringere Handelsmenge. Langfristig drohen Vergeltungszölle.', teilerklaerungen: [] },
  { id: 'f83de7f3-9c4d-4484-b4b3-27bbe43de96d', fachbereich: 'VWL', musterlosung: 'Fiskalzweck: Einnahmebeschaffung für den Staatshaushalt, zum Beispiel die direkte Bundessteuer auf Einkommen oder die Mehrwertsteuer. Lenkungszweck: Verhaltenssteuerung, zum Beispiel die Tabaksteuer zur Reduktion des Rauchens oder die CO₂-Abgabe zur Senkung von Emissionen. In der Praxis überlagern sich die Zwecke meist — auch Fiskalsteuern lenken Verhalten, auch Lenkungssteuern bringen Einnahmen.', teilerklaerungen: [] },
  { id: 'f8ffa251-05b1-4f32-951d-e4d021628101', fachbereich: 'VWL', musterlosung: 'Produktivitätsgewinne in der Landwirtschaft setzen Arbeitskräfte frei — weniger Menschen ernähren mehr Menschen. Diese wandern in Industrie und später in Dienstleistungen ab, wo die Nachfrage wegen steigendem Einkommen wächst (Engelsches Gesetz). Arbeitsteilung und Spezialisierung erhöhen die Effizienz in allen Sektoren. Der Strukturwandel ist kein Verlust, sondern Folge des Wohlstandswachstums — in der Schweiz arbeiten heute rund 75% im tertiären Sektor.', teilerklaerungen: [] },
  { id: 'f941c497-4ebf-4c30-8997-c9f50f1f863d', fachbereich: 'VWL', musterlosung: 'Entstehungsseite: Summe der Wertschöpfung aller Unternehmen. Verteilungsseite: Summe aller Einkommen (Löhne, Zinsen, Gewinne). Verwendungsseite: Summe aller Ausgaben für Endprodukte (C+I+G+NX). Alle drei messen denselben ökonomischen Vorgang aus verschiedenen Perspektiven: Was produziert wird, muss verteilt werden, und was verteilt wird, wird verwendet. Kreislaufgedanke — das ist die Identität der Volkswirtschaftlichen Gesamtrechnung.', teilerklaerungen: [] },
  { id: 'fc64c71a-111b-459a-bd41-ca3e9815230b', fachbereich: 'VWL', musterlosung: 'Grossbanken wie UBS oder Credit Suisse sind systemrelevant — ihr Ausfall würde die Volkswirtschaft gefährden. Die implizite Staatsgarantie senkt ihre Finanzierungskosten und schafft Anreize zu riskanteren Geschäften: Gewinne bleiben privat, Verluste trägt der Steuerzahler (Moral Hazard). Beispiel Credit Suisse 2023: UBS-Übernahme mit Bundesgarantien. Lösungsansätze: höhere Eigenkapitalquoten, geordnete Abwicklungsverfahren (Bail-in).', teilerklaerungen: [] },
  { id: 'fe06a7cc-aae4-49fc-a331-067257658465', fachbereich: 'VWL', musterlosung: 'Zu grosszügig: Sozialhilfe reduziert den Anreiz zur Arbeitsaufnahme (Schwelleneffekt), belastet Steuerzahlende, schafft Abhängigkeiten. Unzureichend: Ansätze liegen oft unter der Armutsgrenze nach SKOS, Bezügerinnen leiden unter Stigma und hoher Nichtbezugsquote (25%). Beide Kritiken treffen Teilaspekte. Eine differenzierte Beurteilung fordert aktivierende Massnahmen (Qualifizierung, Kinderbetreuung) statt pauschaler Erhöhung oder Kürzung.', teilerklaerungen: [] },
  { id: 'ff1fa57b-e613-4970-98a4-33141ee264a8', fachbereich: 'VWL', musterlosung: 'Die westliche untere Mittelschicht (80. Perzentil) stagnierte, weil sie der Konkurrenz des Faktors Kapital ausgesetzt ist: Automatisierung ersetzt Routinejobs, Globalisierung verlagert Produktion in Niedriglohnländer. Gleichzeitig profitieren das globale Top-1% (Kapital) und die asiatische Mittelschicht (neue Arbeitsplätze). Der Lohndruck auf westliche Geringqualifizierte ist strukturell — sie verlieren, während andere Gruppen gewinnen.', teilerklaerungen: [] },
  { id: 'ff251348-d99e-41e0-83a4-d0c8701f7265', fachbereich: 'VWL', musterlosung: 'Güterkreislauf: Frau Studers Arbeitsleistung fliesst zum Globus, die Bluse vom Globus zurück zu ihr. Geldkreislauf (entgegengesetzt): CHF 2\'800 Lohn vom Globus an Frau Studer, CHF 70 von Frau Studer an den Globus. Faktormarkt: Arbeit gegen Lohn. Gütermarkt: Bluse gegen Kaufpreis. Das Beispiel illustriert den einfachen Wirtschaftskreislauf zwischen Unternehmen und Haushalten — Geldströme spiegeln Güterströme.', teilerklaerungen: [] },
  { id: 'ueb-ft-formatierung', fachbereich: 'VWL', musterlosung: 'Ein beispielhaft korrekter Satz wäre: «Die **Schweiz** bietet eine *vielfältige* Landschaft.» Dabei ist «Schweiz» fett und «vielfältige» kursiv formatiert. Die Aufgabe prüft die Anwendung der Formatierungsleiste oder der Tastenkürzel Ctrl+B und Ctrl+I. Ein Wort fett, ein Wort kursiv genügen — der Inhalt ist frei wählbar.', teilerklaerungen: [] },

  // ========== VWL / hotspot (6) — Teilerklärungen pro bereich (ausser ueb-hs-europa) ==========
  { id: '03cbf96e-559b-4ed5-b821-0e7240463fb0', fachbereich: 'VWL', musterlosung: 'Das Geldmarktgleichgewicht liegt im Schnittpunkt zwischen Geldangebot (vertikal, von der SNB fixiert) und Geldnachfrage (fallend im Zinssatz). Punkt A markiert genau diesen Schnitt. Links davon (tiefer Zins) entsteht Nachfrageüberschuss, rechts (hoher Zins) Angebotsüberschuss. Im Gleichgewicht wollen die Wirtschaftssubjekte genau die vorhandene Geldmenge halten.', teilerklaerungen: [
    { feld: 'bereiche', id: 'b_x8t6pjdv', text: 'A ist der Schnittpunkt von Angebot und Nachfrage — das Geldmarktgleichgewicht mit räumendem Zinssatz.' },
    { feld: 'bereiche', id: 'b_p3ayjuzl', text: 'B liegt bei zu hohem Zins: Geldangebot übersteigt Geldnachfrage, der Zins muss sinken.' },
    { feld: 'bereiche', id: 'b_25nkrv0c', text: 'C liegt bei zu tiefem Zins: Die Geldnachfrage ist höher als das Angebot — Geldknappheit, der Zins müsste steigen.' },
    { feld: 'bereiche', id: 'b_ul2ejef8', text: 'D liegt ausserhalb der Kurven — kein gleichzeitiges Treffen von Angebot und Nachfrage.' },
  ] },
  { id: '06a92c58-5214-4c0a-9da0-c67fafb6e82c', fachbereich: 'VWL', musterlosung: 'Die Beveridge-Kurve zeigt den inversen Zusammenhang zwischen Arbeitslosenquote und offenen Stellen. In einer Rezession bewegt sich die Wirtschaft entlang der Kurve nach rechts unten: Arbeitslosigkeit hoch, Stellen tief. Punkt B entspricht dieser Konstellation. Im Boom gilt das Gegenteil (links oben), strukturelle Arbeitslosigkeit zeigt sich als Verschiebung der ganzen Kurve nach aussen.', teilerklaerungen: [
    { feld: 'bereiche', id: 'b_xvnamjxz', text: 'A zeigt den Boom: tiefe Arbeitslosigkeit, viele offene Stellen — links oben auf der Kurve.' },
    { feld: 'bereiche', id: 'b_alpw8itk', text: 'B zeigt die Rezession: hohe Arbeitslosigkeit, wenige offene Stellen — rechts unten auf der Kurve.' },
    { feld: 'bereiche', id: 'b_k43uadpp', text: 'C zeigt strukturelle Arbeitslosigkeit — das äussert sich in einer Verschiebung der gesamten Kurve, nicht in einem einzelnen Punkt.' },
    { feld: 'bereiche', id: 'b_lpsynqgl', text: 'D liegt ausserhalb der Kurve und hat keine ökonomische Bedeutung in diesem Modell.' },
  ] },
  { id: '0b53285b-b86f-4c5a-8eb5-3c9980fb0987', fachbereich: 'VWL', musterlosung: 'Die Maslowsche Bedürfnispyramide ordnet Bedürfnisse hierarchisch. Die dritte Stufe — soziale Bedürfnisse — umfasst Zugehörigkeit, Freundschaft, Partnerschaft und Gemeinschaft. Sie wird relevant, sobald Grund- und Sicherheitsbedürfnisse befriedigt sind. Punkt C markiert diese Ebene. Darunter liegen physiologische und Sicherheitsbedürfnisse, darüber Wertschätzung und Selbstverwirklichung.', teilerklaerungen: [
    { feld: 'bereiche', id: 'b_tm7m2fw3', text: 'A sind die Grundbedürfnisse (Nahrung, Wasser, Schlaf) — die unterste Stufe der Pyramide.' },
    { feld: 'bereiche', id: 'b_uarnbx88', text: 'B sind die Sicherheitsbedürfnisse (Wohnung, Arbeit, Gesundheit) — zweite Stufe.' },
    { feld: 'bereiche', id: 'b_bhtxkpbf', text: 'C sind die sozialen Bedürfnisse: Freundschaft, Zugehörigkeit, Partnerschaft — genau diese Stufe ist gesucht.' },
    { feld: 'bereiche', id: 'b_3pnkaels', text: 'D ist Wertschätzung (Status, Anerkennung) — vierte Stufe, über den sozialen Bedürfnissen.' },
    { feld: 'bereiche', id: 'b_jgsxjakq', text: 'E ist Selbstverwirklichung (Potenzialentfaltung) — die Spitze der Pyramide.' },
  ] },
  { id: '35d573ff-4d30-4040-a27b-df96a201c293', fachbereich: 'VWL', musterlosung: 'Das Marktgleichgewicht liegt im Schnittpunkt von Angebotskurve (steigend) und Nachfragekurve (fallend). Punkt A markiert genau dort, wo angebotene und nachgefragte Menge beim Gleichgewichtspreis übereinstimmen. Der Markt räumt sich — es gibt weder Angebotsüberschuss noch Nachfrageüberschuss. Preisdruck nach oben oder unten entsteht nur, wenn die Kurven sich verschieben.', teilerklaerungen: [
    { feld: 'bereiche', id: 'b_ouo8fcar', text: 'A ist der Schnittpunkt von Angebot und Nachfrage — das Marktgleichgewicht mit räumendem Preis.' },
    { feld: 'bereiche', id: 'b_8gwwc8l0', text: 'B liegt rechts oben: Der Preis ist zu hoch, das Angebot übersteigt die Nachfrage — Angebotsüberschuss.' },
    { feld: 'bereiche', id: 'b_so54d866', text: 'C liegt links unten: Der Preis ist zu tief, die Nachfrage übersteigt das Angebot — Nachfrageüberschuss.' },
    { feld: 'bereiche', id: 'b_7t0sxffs', text: 'D liegt ausserhalb der Kurven und markiert keinen realisierten Marktzustand.' },
  ] },
  { id: '3aa709ec-16bd-478b-acb8-1ec939f16c64', fachbereich: 'VWL', musterlosung: 'Der Konjunkturzyklus durchläuft vier Phasen: Aufschwung, Boom, Abschwung, Talsohle. Die Arbeitslosigkeit ist an der Talsohle (Punkt A) am höchsten. Weil der Arbeitsmarkt ein Spätindikator ist, erreicht die Arbeitslosigkeit ihr Maximum erst dann, wenn das BIP bereits am Tiefpunkt angekommen ist — Entlassungen aus der Rezessionsphase wirken verzögert nach.', teilerklaerungen: [
    { feld: 'bereiche', id: 'b_kik613ju', text: 'A ist die Talsohle: tiefster BIP-Punkt, Arbeitslosigkeit am höchsten — Spätindikator.' },
    { feld: 'bereiche', id: 'b_nqda13iu', text: 'B ist der Boom: höchster BIP-Punkt, Arbeitslosigkeit niedrig, Inflationsdruck steigt.' },
    { feld: 'bereiche', id: 'b_9r6b7xdw', text: 'C ist der Abschwung: BIP fällt, Entlassungen beginnen, Arbeitslosigkeit steigt.' },
    { feld: 'bereiche', id: 'b_qlaajz73', text: 'D ist der Aufschwung: BIP steigt, Arbeitsmarkt erholt sich verzögert.' },
  ] },
  { id: 'ueb-hs-europa', fachbereich: 'VWL', musterlosung: 'Die Schweiz liegt zentral in Europa, eingebettet zwischen Frankreich, Deutschland, Österreich, Liechtenstein und Italien. Auf einer Europakarte befindet sie sich etwa in der Mitte, knapp links. Ein Klick auf diese Region markiert das Land. Diese Übungsaufgabe prüft die Orientierung auf einer geografischen Karte — eine Grundkompetenz, die im Wirtschaftsunterricht bei internationalen Vergleichen vorausgesetzt wird.', teilerklaerungen: [] },

  // ========== VWL / lueckentext (11 erste) — Teilerklärungen pro luecke ==========
  { id: '00ce7db4-7d7f-4715-b8b8-7b165b74dc04', fachbereich: 'VWL', musterlosung: 'Konsumgüter dienen der direkten Bedürfnisbefriedigung (Brot, Kleidung). Investitionsgüter werden zur Herstellung anderer Güter gebraucht (Maschinen, Fabrikgebäude). Dienstleistungen sind immaterielle Leistungen (Zugfahrt, Beratung, Unterricht). Die Unterscheidung ist nicht starr — Güter können je nach Verwendung beide Kategorien erfüllen (z.B. PC privat oder im Büro).', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Konsumgüter sind für die direkte Bedürfnisbefriedigung bestimmt — sie werden vom Endverbraucher konsumiert.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Investitionsgüter (auch Produktionsgüter) dienen der Herstellung anderer Güter, etwa Maschinen oder Fabriken.' },
    { feld: 'luecken', id: 'luecke-2', text: 'Bei einer Dienstleistung zählt nicht der Warenwert, sondern der Wert der erbrachten Leistung — immateriell und nicht lagerfähig.' },
  ] },
  { id: '01dd3622-b2b5-4427-93f8-afa31909d39a', fachbereich: 'VWL', musterlosung: 'Negative externe Effekte belasten Dritte (Umweltverschmutzung, Lärm), positive nutzen ihnen (Impfungen, Bildung, gepflegte Gärten). Der Marktpreis bildet beide nicht ab — Märkte versagen. Der Staat korrigiert: Steuern und Verbote bei negativen Externalitäten, Subventionen und Gebote bei positiven. Internalisierung macht die verursachten Kosten oder Nutzen im Preis sichtbar.', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Negative Externalitäten verursachen Kosten für Dritte, die im Marktpreis fehlen — z.B. Abgase oder Lärm.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Positive Externalitäten stiften Nutzen für Dritte, z.B. Impfungen oder Bildung, und werden privatwirtschaftlich unterversorgt.' },
  ] },
  { id: '03e41cd8-a723-4df7-a047-ba7ba3498fb2', fachbereich: 'VWL', musterlosung: 'Nach dem Sayschen Theorem schafft sich jedes Angebot seine eigene Nachfrage: Produktion erzeugt Einkommen, das wiederum zur Nachfrage nach anderen Gütern wird. Die Klassiker folgerten, dass es keine dauerhafte Überproduktion geben könne. Keynes widerlegte diese Sicht in den 1930er-Jahren mit dem Hinweis, dass Einkommen auch gespart statt ausgegeben werden können — was zu Nachfragelücken führt.', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Jedes Angebot — also jede Produktion — schafft gemäss Say das Einkommen, das die Nachfrage trägt.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Jedes Angebot schafft seine eigene Nachfrage: Klassische Grundüberzeugung, die Überproduktion als dauerhaftes Phänomen ausschliesst.' },
  ] },
  { id: '07066581-224e-4b2e-92e6-b5b094511bc3', fachbereich: 'VWL', musterlosung: 'Geld erfüllt drei zentrale Funktionen: Als Tauschmittel vermittelt es Kauf und Verkauf und vermeidet Naturaltausch. Als Wertmassstab (Recheneinheit) erlaubt es, Preise verschiedener Güter in einer Einheit zu vergleichen. Als Wertaufbewahrungsmittel speichert es Kaufkraft über die Zeit. Alle drei Funktionen senken Transaktionskosten und sind Voraussetzung moderner arbeitsteiliger Wirtschaft.', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Als Tauschmittel vermittelt Geld Kauf und Verkauf — es ersetzt den ineffizienten Naturaltausch.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Als Wertmassstab ermöglicht Geld Preisvergleiche: Alle Güter werden in einer Einheit (z.B. CHF) ausgedrückt.' },
    { feld: 'luecken', id: 'luecke-2', text: 'Als Wertaufbewahrung speichert Geld Kaufkraft zeitversetzt — man kann heute sparen und später kaufen.' },
  ] },
  { id: '0a1a6362-8d41-4b42-923b-2bbd02667477', fachbereich: 'VWL', musterlosung: 'Im Nationalen Finanzausgleich leisten ressourcenstarke Kantone (Zug, Schwyz, Zürich) Ausgleichszahlungen an ressourcenschwache (Uri, Jura, Wallis). Ziel ist eine minimale finanzielle Grundausstattung aller Kantone — damit jeder Kanton seine öffentlichen Aufgaben erfüllen kann. Der NFA ist ein zentrales Element der schweizerischen Solidarität zwischen den Gliedstaaten.', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Ressourcenstarke Kantone (hohe Steuerbasis) sind Geberkantone — sie finanzieren den Ausgleich.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Ressourcenschwache Kantone erhalten Ausgleichszahlungen, um Grundaufgaben finanzieren zu können.' },
  ] },
  { id: '0eb829fa-25f8-4098-8956-a8974716e10d', fachbereich: 'VWL', musterlosung: 'Im erweiterten Wirtschaftskreislauf finanziert sich der Staat über Steuereinnahmen der Haushalte und Unternehmen. Er verwendet diese Mittel für den Kauf von Gütern und Dienstleistungen (Beschaffung für die Verwaltung) sowie für Transferzahlungen an die Haushalte (AHV-Renten, Sozialhilfe — Leistungen ohne direkte Gegenleistung).', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Steuereinnahmen sind die Haupteinnahmequelle des Staates — Pflichtabgaben ohne direkte Gegenleistung.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Der Staat kauft Güter und Dienstleistungen für Verwaltung, Bildung, Infrastruktur und Sicherheit.' },
    { feld: 'luecken', id: 'luecke-2', text: 'Transferzahlungen sind Leistungen ohne Gegenleistung an Haushalte — z.B. AHV-Renten oder Sozialhilfe.' },
  ] },
  { id: '12390cba-9f7d-4dd1-a736-6f7c588fa09d', fachbereich: 'VWL', musterlosung: 'Die keynesianische Konzeption ist nachfrageorientiert: In Krisen muss der Staat die ausfallende private Nachfrage durch eigene Ausgaben ersetzen. Die angebotsorientierte neoklassische Konzeption betont dagegen Rahmenbedingungen: Tiefe Steuern, wenig Regulierung und flexible Märkte schaffen Investitionsanreize für langfristiges Wachstum. Beide Ansätze lösen unterschiedliche Probleme.', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Nachfrageorientiert: Keynes sieht in Krisen die Gesamtnachfrage als Engpass — der Staat muss aktiv stützen.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Angebotsorientiert: Die Neoklassik betont gute Rahmenbedingungen (Steuern, Regulierung) für Investitionen und Wachstum.' },
  ] },
  { id: '13cc3f28-05db-4ba9-bfee-72a415c1bcec', fachbereich: 'VWL', musterlosung: 'Die Maslowsche Pyramide ordnet Bedürfnisse hierarchisch: Zuunterst die physiologischen Grundbedürfnisse (Nahrung, Schlaf, Wärme), darüber Sicherheit (Wohnung, Arbeit, Gesundheit), dann soziale Bedürfnisse (Zugehörigkeit, Freundschaft), an der Spitze Selbstverwirklichung. Erst wenn tiefere Stufen befriedigt sind, werden höhere aktiv. Eisenhut nennt zusätzlich Wertschätzung als fünfte Stufe.', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Grundbedürfnisse sind physiologisch — Nahrung, Wasser, Schlaf, Wärme als biologische Basis.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Sicherheitsbedürfnisse umfassen Schutz vor Gefahren: Wohnung, Arbeit, Gesundheit.' },
    { feld: 'luecken', id: 'luecke-2', text: 'Soziale Bedürfnisse betreffen Zugehörigkeit: Freundschaft, Partnerschaft, Gemeinschaft.' },
    { feld: 'luecken', id: 'luecke-3', text: 'Selbstverwirklichung ist die Spitze: persönliches Wachstum, Kreativität, Potenzialentfaltung.' },
  ] },
  { id: '14197d12-f97f-4aca-a752-348addd27b8e', fachbereich: 'VWL', musterlosung: 'Nachhaltige Entwicklung nach der Brundtland-Definition (1987) befriedigt die Bedürfnisse der heutigen Generation, ohne zu riskieren, dass zukünftige Generationen ihre Bedürfnisse nicht befriedigen können. Das Konzept betont intergenerationelle Gerechtigkeit: Wachstum heute darf nicht auf Kosten morgen gehen. Drei Dimensionen: ökologisch, ökonomisch, sozial.', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Die heutige Generation soll ihre Bedürfnisse befriedigen können — das ist die Ausgangslage der Definition.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Zukünftige (kommende, nachfolgende) Generationen dürfen durch heutiges Handeln nicht benachteiligt werden.' },
    { feld: 'luecken', id: 'luecke-2', text: 'Der Brundtland-Bericht (1987) der Weltkommission für Umwelt und Entwicklung prägte diese Definition.' },
  ] },
  { id: '19393443-c099-43c9-962d-e784854b72c4', fachbereich: 'VWL', musterlosung: 'Gebühren sind Zahlungen für konkrete Gegenleistungen des Staates und werden nur geschuldet, wenn die Leistung auch tatsächlich beansprucht wird. Im Gegensatz dazu sind Steuern unabhängig vom Leistungsbezug. Beispiele für Gebühren: Passgebühr, Gerichtskosten, Kehrichtentsorgung. Wer die Leistung nicht bezieht, muss auch nicht zahlen — klassisches Äquivalenzprinzip.', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Gegenleistungen (Dienstleistungen) des Staates sind konkret und werden individuell zurechenbar erbracht.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Beansprucht (genutzt, in Anspruch genommen): Nur wer die Leistung tatsächlich bezieht, schuldet die Gebühr.' },
  ] },
  { id: '19ca46f1-8a7d-4b13-b25b-ab7373e45d71', fachbereich: 'VWL', musterlosung: 'Die AHV wurde 1948 eingeführt und bildet die erste Säule der Schweizer Altersvorsorge. Ihr Zweck ist die Deckung des Existenzminimums der nicht mehr im Berufsleben stehenden Personen: Rentnerinnen und Rentner, Witwen, Witwer und Waisen. Finanziert wird sie im Umlageverfahren — laufende Beiträge finanzieren laufende Renten.', teilerklaerungen: [
    { feld: 'luecken', id: 'luecke-0', text: 'Die AHV wurde 1948 nach einer Volksabstimmung eingeführt und ist seither die Basis der 1. Säule.' },
    { feld: 'luecken', id: 'luecke-1', text: 'Die AHV gehört zur 1. Säule — der staatlichen Existenzsicherung im Umlageverfahren.' },
    { feld: 'luecken', id: 'luecke-2', text: 'Das Existenzminimum soll gedeckt werden — kein gewohnter Lebensstandard, dafür sorgt erst die 2. Säule.' },
  ] },
]

// === Runner ===
async function main() {
  const lines = updates.map(u => JSON.stringify(u)).join('\n') + '\n'
  await fs.appendFile(OUT, lines)

  const state = JSON.parse(await fs.readFile(STATE, 'utf8'))
  const now = new Date().toISOString()
  for (const u of updates) {
    state.fragen[u.id] = { status: 'done', zeitpunkt: now, teile: u.teilerklaerungen.length }
  }
  state.verarbeitet += updates.length
  state.letzteSession = now
  await fs.writeFile(STATE, JSON.stringify(state, null, 2))

  const withTeile = updates.filter(u => u.teilerklaerungen.length > 0).length
  console.log(`Session 11a: ${updates.length} Fragen appended (${withTeile} mit Teilerklärungen, ${updates.length - withTeile} ohne).`)
  console.log(`Total verarbeitet: ${state.verarbeitet} / ${state.totalFragen}`)
}

main().catch(err => { console.error(err); process.exit(1) })
